### ISSUE TITLE
With AP, Hubzilla post arrives twice.

### ISSUE THREAD

**Issue by clacke** [friendica/friendica#6068] opened 2018-11-03 12:10 UTC
### Expected behavior

 - Hubzilla user posts.
 - I see the post once -- regardless which protocol arrives first, Friendica is able to determine that it's the same post and eliminate any duplicates.

### Actual behavior

 - Hubzilla user posts.
 - I see the post as a Hubzilla post.
 - I see the post as a Hubzilla (AP) post.

```
This is Friendica, version 2018.12-dev that is running at the web location https://libranet.de. The database version is 1289, the post update version is 1281.
```

**Comment by MrPetovan** [comment] 2018-11-03 12:52
I can't reproduce this, but I've receive the same Hubzilla post twice, once public, once private, and both links to the original page on Hubzilla say "Permission denied".

**Comment by annando** [comment] 2018-11-03 12:58
Hubzilla can use ActivityPub and the Diaspora protocol to post to Friendica. With Diaspora, the post is identified with the GUID, with ActivityPub it is identified with the URL. The Diaspora post doesn't transmit the URL, the ActivityPub post doesn't transmit the GUID. This means that we don't have a way to determine that it is a duplicated post. Friendica does transmit the GUID via AP in some non standard field. Until Hubzilla hadn't done something similar, we can't prevent duplicates.

**Comment by clacke** [comment] 2018-11-04 14:31
Created https://framagit.org/hubzilla/core/issues/1290

**Comment by tobiasd** [comment] 2021-10-01 15:56
As the Hubzilla issue has been closed, I think we can close this issue.

**Closed by tobiasd** 2021-10-01 15:56 UTC
Labels: Federation, Sup­port Request
