### ISSUE TITLE
Twitter-Plugin: Retweets are displayed unpleasant 

### ISSUE THREAD

**Issue by PolynomialDivision** [friendica/friendica#8827] opened 2020-06-29 08:23 UTC
Currently, if a retweet on twitter is published to friendica, they always have `[bookmark=` in it. Further, it seems that the author of the post is wrong.

Here is an example: 
- [Friendica](https://friendica.astatu.berlin/display/96794102-945e-f705-ec43-a62349883341)
- [Twitter](https://twitter.com/astaup/status/1276789514414022659)

**Comment by tobiasd** [comment] 2020-06-29 12:31
What version of Friendica are you using?

**Comment by annando** [comment] 2020-06-29 13:30
See https://friendica.astatu.berlin/friendica  - it is 2020.03. AFAIK we solved this in the RC.

**Comment by MrPetovan** [comment] 2020-06-29 13:37
Thank you for your report, this issue is a duplicate of #8722 fixed by #8725

**Closed by MrPetovan** 2020-06-29 13:37 UTC
Labels: Addons, Bug
