### ISSUE TITLE
Trouble when trying to drop contact

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#10729] opened 2021-09-19 07:05 UTC
### Bug Description

Error messages, faulty UI and action never proceeding when trying to drop contact.

### Steps to Reproduce

1.  Open contacts list
2.  Tick checkbox in bottom right of contact in the list
3.  Click `Drop Contact` icon

Actual Result:

Error message shows multiple times: "The form security token was not correct. This probably happened because the form has been opened for too long (>3 hours) before submitting it."

Friendica UI shows second friendica overlay over existing UI.

Expected Result:

Contact should be dropped.

### Screenshots
<img width="263" alt="error" src="https://user-images.githubusercontent.com/5708172/133918708-97c0065f-7bc6-47f1-8090-14ed8452d2e1.png">
<img width="1035" alt="double UI" src="https://user-images.githubusercontent.com/5708172/133918701-4e56d5ce-84df-408f-b3a1-8495bd11eef2.png">

### Platform Info

Friendica Version:

This is Friendica, version 2021.09-rc that is running at the web location https://pirati.ca. The database version is 1435/1435, the post update version is 1427/1427.

**Comment by MrPetovan** [comment] 2021-09-19 08:28
Thank you for the report, this looks like an exact duplicate of #10698 that was fixed in #10713, hopefully pirati.ca hasn't been updated to the latest RC by @annando .

**Comment by ghost** [comment] 2021-09-19 08:42
> Thank you for the report, this looks like an exact duplicate of #10698 that was fixed in #10713, hopefully pirati.ca hasn't been updated to the latest RC by @annando .

Etiqueti.de is up to date with the latest RC but I still have the problem.

**Comment by MrPetovan** [comment] 2021-09-19 09:22
Ok, I'll look into it again.

**Comment by MrPetovan** [comment] 2021-09-19 17:19
I wasn't able to reproduce this issue with an RSS contact, trying a Twitter contact now.

**Comment by MrPetovan** [comment] 2021-09-19 17:21
I was able to correctly drop a Twitter contact even if it makes no sense since Twitter contacts are managed by the addon.

I'm this close to removing the feature for users to manually drop contacts instead of just unfollowing.

**Comment by foss-** [comment] 2021-09-19 21:53
Feature request to implement Unfollow option for Twitter contacts: https://github.com/friendica/friendica/issues/10734

**Comment by MrPetovan** [comment] 2021-09-20 00:22
@annando Is there a good reason to keep the "Drop Contact" feature beyond exposing a technical capability with no actual use-case?

**Comment by annando** [comment] 2021-09-20 03:54
Unfollow removes the contact as well when the contact isn't a follower. But possibly we want to remove that person as a follower as well? This is an use case I could see here.

**Comment by MrPetovan** [comment] 2021-09-20 04:35
I haven't seen any obvious indication that we are removing a contact as a follower when we drop it, do we just stop sending posts to them without transmitting the relationship change? I've seen the various protocol-based unfollow calls when a contact is dropped, but not the other way around.

**Comment by annando** [comment] 2021-09-20 04:59
See here: https://github.com/friendica/friendica/blob/2021.09-rc/src/Protocol/ActivityPub/Transmitter.php#L2053

It is called here: https://github.com/friendica/friendica/blob/2021.09-rc/src/Model/Contact.php#L846

And the `dissolve` parameter is set when a contact is dropped: https://github.com/friendica/friendica/blob/2021.09-rc/src/Module/Contact.php#L251

**Comment by foss-** [comment] 2021-09-20 05:24
> Unfollow removes the contact as well when the contact isn't a follower. But possibly we want to remove that person as a follower as well? This is an use case I could see here.

Coming from Twitter I was unaware of this concept as I thought I had no control over having a contact following me to make them unfollow me from my side, other then maybe blocking them. Is this feasible on Twitter?

**Comment by annando** [comment] 2021-09-20 06:14
Possibly with a protected Twitter account this is possible, but I don't know.

**Comment by MrPetovan** [comment] 2021-09-20 10:52
> See here: https://github.com/friendica/friendica/blob/2021.09-rc/src/Protocol/ActivityPub/Transmitter.php#L2053
> 
> It is called here: https://github.com/friendica/friendica/blob/2021.09-rc/src/Model/Contact.php#L846
> 
> And the `dissolve` parameter is set when a contact is dropped: https://github.com/friendica/friendica/blob/2021.09-rc/src/Module/Contact.php#L251

Thanks, I was confused by the name of the message. it seemed to me like rejecting a contact request. This same `terminateFriendship` call  should be added to the block feature and the drop feature won't be necessary anymore.

**Comment by MrPetovan** [comment] 2021-09-20 10:53
Blocking is the only current way on Twitter to make someone stop following you or to leave a custom account list someone else put you on. Making your account protected keeps your current following.

**Closed as completed** 2021-10-02 20:12 UTC
Labels: Bug
