### ISSUE TITLE
Auto-linking in a post can't handle parentheses

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#6095] opened 2018-11-07 19:24 UTC
### Expected behavior
Posting a URL such as https://en.wikipedia.org/wiki/Solid_(web_decentralization_project) should link to the whole text.

### Actual behavior
Link stops at the first parenthesis - ie, the link becomes: 
https://en.wikipedia.org/wiki/Solid_

### Steps to reproduce the problem
Copy such a link to your post, even preview mode will display the problem.
Reference that made me check up on this: 
https://social.isurf.ca/display/ec054ce7-825b-dd58-c974-351350086299

### Friendica version you encountered the problem
2018-09 stable

### Friendica source (git, zip)
git

### PHP version
7.2.9

### SQL version
10.1.35

**Comment by AlfredSK** [comment] 2018-11-07 19:55
Happens on 2018.12-dev too. Possible workaround: BBCode tags.
`[url]https://en.wikipedia.org/wiki/Solid_(web_decentralization_project)[/url]`

**Comment by MrPetovan** [comment] 2018-11-08 01:07
Duplicate of #2487 as it's about the autolinker regular expression.

**Closed by MrPetovan** 2018-11-08 01:07 UTC

**Comment by nupplaphil** [comment] 2019-03-09 13:23
fixed by #6835
