### ISSUE TITLE
Follow Hubzilla accounts sometime gives errors

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#2626] opened 2016-06-20 19:26 UTC
Sometime it won work to follow a Hubzilla account, in the example I tried to follow @piratenpartijdenhaag＠piratenpartij.org, but it did not work. The fault was "Das angefragte Profil ist nicht vorhanden.", which means something like the profile does not exist. Which was not true. 

Webfinger and probe were done and can be found [here](https://social.yl.ms/display/e18176ef135766ad1754c0e603443620). 

Mike MacGirvin explains this as following:

> Friendica changes the network type to NETWORK_PHANTOM if the feed doesn't contain any items and then fails to connect with it. Hubzilla version 1.2.3 from last February is what that site is running. That version only provides feeds going back a month, and the most recent public item on that channel is about 3 months old. I'm cautiously calling this a Friendica bug (since hubzilla feeds can in fact be empty or be permission denied). We've since changed the lower limit on feeds so it isn't time dependent; but in any event the pirate party should upgrade. We just released 1.8 about an hour ago. About 70% of the codebase has been re-written since February. And Friendica shouldn't change the network type away from Diaspora if the feed comes up empty.

Also the details can be found [here](https://social.yl.ms/display/e18176ef135766ad1754c0e603443620) as written above.

**Comment by annando** [comment] 2018-08-06 19:06
I cannot reproduce this. The feed is only checked during the test for a feed or for OStatus.

**Comment by AlfredSK** [comment] 2018-08-25 18:28
Then I did two tests with my own Hubzilla instance. I did probe tests from mordor.social (Friendica 2018.08-dev).
An inactive channel gives an empty probe result while an active one gives a perfectly fine probe result.

**Comment by AlfredSK** [comment] 2018-08-25 21:28
Oh! Yes, that's possible. In Hubzilla the Diaspora protocol is a server **and** a user (channel) setting.

**Comment by annando** [comment] 2018-08-25 22:01
So I guess we can close this issue?

**Comment by annando** [comment] 2018-08-26 10:31
If no one disagrees, then I would like to close this issue now.

**Comment by MrPetovan** [comment] 2018-08-26 12:33
Closed as invalid.

**Closed by MrPetovan** 2018-08-26 12:33 UTC
Labels: Federation, Sup­port Request
