### ISSUE TITLE
Users profile still available to view for up to 2 days after deleting

### ISSUE THREAD

**Issue by mark4409** [friendica/friendica#5010] opened 2018-05-09 16:01 UTC
After a user chooses to delete their account, the status in the admin console sits at Pending deletion for a couple of days. During this time, the users profile is still visible. This is in contrast with the documentation that states that the users account is removed in 'moments'. I have experienced this both on my own mass-trespass.uk server and also the libranet.de server. Both were running the latest dev.

My own server is running PHP 7.2 fpm, but I'm not sure about Libranet.

**Comment by tobiasd** [comment] 2018-05-09 16:45
> The question is, is it a documentation issue (intended behavior) or a
> bug?

It is a bug.

The deletion should take place immediately and the profile should not be accessible after the deletion was requested by the user as documented.

To reduce the server load the actual deletion process of postings is done by the background worker in chunks (IIRC). Also there is a grace period (the pending time) in which connected nodes are informed about the deletion of the account.

**Comment by tobiasd** [comment] 2018-05-24 06:32
The fix seems to restore the intended behavior in my testing, so I'm closing the issue.

**Closed by tobiasd** 2018-05-24 06:32 UTC
Labels: Bug
