### ISSUE TITLE
Drag and drop upload for photos

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#10710] opened 2021-09-14 19:20 UTC
When composing a new post/comment it would be great to be able to add photos to the post/comment by dragging them into the text box. 

This would be a great feature to speedup sharing photos and photos are a big part of the social media and the Fediverse in special.

**Comment by AlfredSK** [comment] 2021-09-14 19:35
I'm pretty sure there's already an issue for that (dragging/pasting images into the editor).

**Comment by utzer** [comment] 2021-09-14 19:57
> I'm pretty sure there's already an issue for that (dragging/pasting images into the editor).

You're right... sorry. There is #8848 which asks for this feature too.

**Comment by MrPetovan** [comment] 2021-09-14 20:44
Closed as duplicate of #8848

**Closed as completed by MrPetovan** 2021-09-14 20:44 UTC
Labels: New Feature
