### ISSUE TITLE
2019.09 PHP Notices

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#7681] opened 2019-09-29 16:24 UTC
PHP Notice: Undefined index: id in /src/Worker/Delivery.php on line 245
PHP Notice: Undefined index: id in /src/Worker/Delivery.php on line 273
PHP Notice: Undefined index: id in /src/Worker/Delivery.php on line 354
PHP Notice: Undefined index: id in /src/Worker/Delivery.php on line 367
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 399
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 458

**Comment by nupplaphil** [comment] 2019-09-29 20:44
Duplicate of https://github.com/friendica/friendica/issues/7677#issuecomment-536270441

**Closed by nupplaphil** 2019-09-29 20:44 UTC
