### ISSUE TITLE
Image blurred

### ISSUE THREAD

**Issue by RealVegOs** [friendica/friendica#13534] opened 2023-10-12 23:37 UTC
I uploaded my lastest montage. It looked like this in the composing preview:

![grafik](https://github.com/friendica/friendica/assets/7726676/8bfee739-df15-4846-82f2-14ebe784da83)

As you see, the width of the preview is 430 pixels, that is the same size like in my gallery. 

The montage was displayed like this:

![grafik](https://github.com/friendica/friendica/assets/7726676/60074ce1-cbef-48df-9d65-39cc2152d233)

It looks rather blurry so I think, the 430 pixel preview was upscaled by the browser to 630 pixels. This behavior is new. I uploaded some montages before without any issues. I deleted the post instantly, because I'm a wanabe photographer with sensitive eyes.

Mr @Raroun the admin of the instance I use runs the latest dev versions of Friendica.

**Comment by MrPetovan** [comment] 2023-10-13 00:52
This looks like a duplicate of #13506 that should have been solved by #13517. @Raroun how recently did you pull the `2023.09-rc` branch?

**Comment by RealVegOs** [comment] 2023-10-13 10:17
I checked that myself:
> This is Friendica, version 2023.09-rc that is running at the web location https://friendica.opensocial.space.

**Comment by MrPetovan** [comment] 2023-10-13 11:18
Thanks, unfortunately this isn't enough to figure out if this node has updated to https://github.com/friendica/friendica/pull/13517.

**Comment by Raroun** [comment] 2023-10-14 07:52
@MrPetovan 
I like to live dangerously, so I do a pull everyday :)

**Comment by MrPetovan** [comment] 2023-10-14 16:57
@RealVegOs Can you please share a link to the post with the blurred image?

**Comment by RealVegOs** [comment] 2023-10-14 17:00
I deleated it, but you have unscaled screenshots in original resolution above. I may do a new post, if you want.

**Comment by RealVegOs** [comment] 2023-10-14 17:12
See here: https://friendica.opensocial.space/display/8ffdf77c-8565-2acb-b105-06c622221360

Looks like, the preview is embedded in the psot instead the original size. First click shows 530px width, next click original (1000px). Preview is 430px.

**Comment by MrPetovan** [comment] 2023-10-14 18:12
Thanks, I'm really confused about the numbers I'm seeing in the code:
```html
<div style="max-width: 692px;">
    <figure class="img-allocated-height" style="width: auto; padding-bottom: 147.9%">
        <a data-fancybox="uri-id-28207804" href="https://friendica.opensocial.space/photo/media/11847243">
            <img src="https://friendica.opensocial.space/photo/preview/1024/11847243" alt="For Mr. Petovan Hypolite ©Zacke" title="For Mr. Petovan Hypolite ©Zacke" loading="lazy">
        </a>
    </figure>
</div>
```
The original image size is 1000px wide, the preview image is 432px wide, so I'm not sure where the 692px value in the wrapper `div` is coming from. 🤔

@Raroun Can you please paste the result of this SQL query:
```sql
SELECT * FROM `post-media` WHERE `id` = 11847243\G
```
The `\G` suffix is intended to switch the result display from a table to a list.

**Comment by Raroun** [comment] 2023-10-14 18:31
```
id: 11847243
uri-id: 28207804
url: https://friendica.opensocial.space/photo/6260255081652ac9ddb9cc5228801817-0.png
type: 1
mimetype: image/png
height: 1479
width: 1000
size: 2584239
preview: https://friendica.opensocial.space/photo/6260255081652ac9ddb9cc5228801817-1.png
preview-height: 640
preview-width: 432
description: For Mr. Petovan Hypolite ©Zacke
name: NULL
author-url: NULL
author-name: NULL
author-image: NULL
publisher-url: NULL
publisher-name: NULL
publisher-image: NULL
media-uri-id: NULL
blurhash: |DFr;Q%MoNM_M{%MxuxuRjxafit7IUR*-;xuxuV@?bofaKIUWBt6aybHRj9ZxuxuM{a#xujsayRjD$M{ogs:t7j[kBRiRj~XjXt7t7ozozWCazM{Rjt8WCWVt7oet6oft7%Ns:IUM{j]WCWBbHWBNGRkofM{f6xuoeofV[

```

**Comment by MrPetovan** [comment] 2023-10-14 19:04
Thanks, I found the culprit: https://github.com/friendica/friendica/blob/ec61cdac83b5e3beed68d2b371ecf4b96f7984a0/src/Model/Item.php#L3430-L3439

For some reason even if a media has a preview image, we override it with a larger size for portrait images. This behavior already existed before the image allocation feature, but it wasn't showing.

Also during image upload we scale down images to fit inside a 640px square, but the Proxy medium size is 600px, which can also create slightly blurry downscaled pictures, although it's less noticeable than with upscaling.

**Comment by MrPetovan** [comment] 2023-10-14 19:32
I went ahead and aligned the proxy sizes to preview sizes, so there shouldn't be any significant downscaling anymore.

**Comment by RealVegOs** [comment] 2023-10-14 20:03
THX to G'MIC which made a landscape montage... sorry portrait!

**Comment by MrPetovan** [comment] 2023-10-15 13:26
@RealVegOs It's been 15 hours, hopefully @Raroun pulled the RC branch, please let me know if the fix worked.

**Comment by RealVegOs** [comment] 2023-10-15 13:30
Yes it is fixed. I uploaded again, but the old test post above is OK too!
https://friendica.opensocial.space/display/8ffdf77c-1565-2bbd-4f94-2d2304551365

**Comment by MrPetovan** [comment] 2023-10-15 14:05
Yay! Closed by https://github.com/friendica/friendica/pull/13541

**Closed as completed by MrPetovan** 2023-10-15 14:05 UTC
Labels: Bug

**Comment by RealVegOs** [comment] 2023-10-16 14:14
A funny little addendum:
https://friendica.opensocial.space/feed/vegos_f06/
The pic now is present twice in atom feed. Sorrrry for that! 🙄
Checked with Liferea and my Blog thing.

**Comment by MrPetovan** [comment] 2023-10-16 14:20
You can delete the second upload now if you'd like!

**Comment by RealVegOs** [comment] 2023-10-16 14:28
There is only one upload in my gallery. I always deleted the previous one. I just checked for that.

**Comment by MrPetovan** [comment] 2023-10-16 14:44
Your gallery and your timeline are independent of each other. Meaning when you delete a picture from your gallery, the posts in which it has been embedded aren't deleted automatically. This means you should delete this post manually: https://friendica.opensocial.space/display/8ffdf77c-8565-2acb-b105-06c622221360

**Comment by RealVegOs** [comment] 2023-10-16 14:55
Done, but it will take a time, to refetch already sent posts from feed. Since several weeks I use not actively to upload images. I paste them from clipboard, but they too go to the gallery.

**Comment by MrPetovan** [comment] 2023-10-16 14:56
Feed is already updated, and all the images you upload in your posts go to your gallery where you can reuse them without having to re-upload them.

**Comment by RealVegOs** [comment] 2023-10-16 15:00
That was quick, it is even updated in my blog now. The script there has its own interval.

**Comment by tio-trom** [comment] 2024-03-19 22:44
While this was a good solution for the blurred images, it introduces a CSS conundrum. All images inside a post are inside a div with a max-width, and since this div has no class then you end up with images that cannot be centered. As such:

![2024-03-19_23-40](https://github.com/friendica/friendica/assets/38043315/7acfa2fe-7ec0-4539-9982-6345cdadb0ad)

And in my view that looks weird. I'd like to at least make this div centered and if it had a class I could do it. Like this post https://social.trom.tf/display/dbc8dc44-3865-f85e-5e18-ef0121773041 to me it looks a bit off with all the images tucked to the left, and some being as wide as the post body, some not. I wish I can make the div that contains the images in a post as wide as the post body itself, regardless if they will be a little bit blurry.

Anyway, at the end of the day if that div containing the images in a post had a class it would solve all issues with say custom themes.

**Comment by MrPetovan** [comment] 2024-03-20 00:25
I see what you mean, you don't necessarily want us to make the image centered but you'd like the ability to do it yourself. Please open a new issue for this, it definitely is a junior job.

**Comment by Quix0r** [comment] 2025-07-08 21:39
Sorry for digging up an old issue but it happened again:
```
SELECT * FROM `post-media` WHERE `id` = 8891093\G
*************************** 1. row ***************************
             id: 8891093
         uri-id: 10649326
            url: https://www.bostonherald.com/2025/06/07/harvard-gets-other-universities-backing-in-trump-funding-fight/
           type: 17
       mimetype: text/html; charset=UTF-8
         height: NULL
          width: NULL
           size: NULL
        preview: https://www.bostonherald.com/wp-content/uploads/2023/10/harvardnl006.jpg?w=1600&resize=1600,900
 preview-height: 900
  preview-width: 1600
    description: A group of 18 leading research universities including Princeton and MIT asked a federal judge for permission to file legal arguments in support of Harvard in its showdown with the Trump administrat…
           name: Harvard gets other universities’ backing in Trump funding fight
     author-url: NULL
    author-name: Bloomberg News
   author-image: NULL
  publisher-url: NULL
 publisher-name: Boston Herald
publisher-image: NULL
   media-uri-id: NULL
       blurhash: |9CZY4W=4.-:9Ft7WUobRj_NxvahRQIURkRkNGofM|%MxuM{xtfkj=j[oc?HRkM{ofM|bIoft7Rk4.oJWAM{WBt7RjWDxuD%ofxut6xuWBaxt7oeaKRjRjf9RjRjj]aza$M{adoykCjYt6oyaeoLRPRjt7t7ogM|azoMWX
      attach-id: NULL
       language: NULL
      published: NULL
       modified: NULL
```
Results in a blurry image at https://f.haeder.net/photo/preview/640/8891093

**Comment by Quix0r** [comment] 2025-07-08 21:46
Other one to not give the impression that maybe the image's URL is the cause:
```
SELECT * FROM `post-media` WHERE `id` = 8956412\G
*************************** 1. row ***************************
             id: 8956412
         uri-id: 10799689
            url: https://www.thegatewaypundit.com/2025/07/former-cia-officer-says-deep-state-probably-destroyed/
           type: 17
       mimetype: text/html; charset=UTF-8
         height: NULL
          width: NULL
           size: 374999
        preview: https://www.thegatewaypundit.com/wp-content/uploads/2025/07/img_7211.jpg
 preview-height: 637
  preview-width: 1169
    description:           A former CIA officer told Fox News host Jesse Watters on Monday evening that the Deep State “probably destroyed” the Epstein files long ago.
           name: HERE IT IS: Former CIA Officer Says Deep State "Probably Destroyed" Epstein Files Long Ago (VIDEO) | The Gateway Pundit | by Cristina Laila
     author-url: https://www.thegatewaypundit.com/author/cristina/
    author-name: Cristina Laila
   author-image: https://www.thegatewaypundit.com/wp-content/uploads/cropped-cropped-IMG_9442-1-96x96.jpg
  publisher-url: https://www.thegatewaypundit.com/
 publisher-name: Where Hope Finally Made a Comeback
publisher-image: https://www.thegatewaypundit.com/wp-content/uploads/tgp-icon-512x512-2.png
   media-uri-id: NULL
       blurhash: |LEVv#D%xwbJNEWBE+RikEn3IU-os,n#oetSRkkD?wRkbdxaM|tRxbkDNH9Et7ems,f5oIngoKkBS~slbcayt7a{V?s.kCxsV?s+WCt6ofjFs,WBIUV?x]Rlt6s:bbxZWD-:n,WAWBj]jZRkoKWBE1s:ozaextaxfiWVoe
      attach-id: NULL
       language: en
      published: 2025-07-08 02:00:35
       modified: NULL
```
