### ISSUE TITLE
Delegation function deletes the wrong account

### ISSUE THREAD

**Issue by Tuxi2020** [friendica/friendica#13311] opened 2023-07-26 11:33 UTC
### Bug Description

It was changed to a group account via "User accounts" (/delegation).  This group account should be deleted via the settings. Unfortunately, not this group account was deleted, but the actual main account.
Details see here: https://loma.ml/display/373ebf56-1364-c0f1-16c0-383020562910

It should not be possible to delete the main account via the /delegation function.

### Steps to Reproduce
1.  /settings
2.  /removeme
3.  Password confirmed

Actual Result:
It was not the used group account that was deleted, but the actual main account.

Expected Result:
The account used via /delegation must be deleted and never another (main) account.

**Comment by Ravenbird** [comment] 2023-07-26 17:25
The whole thing happened to me. I wanted to delete a group that was connected to one of my two main accounts, because I had learned that there is already a similar group. So I switched from the main account via user change to the group and wanted to delete the group account there in the settings. You can imagine how shocked I was when I noticed that not the group account but my main account with numerous partly quite detailed posts and post discussions and still unanswered comments had been deleted. Not nice at all.

**Comment by MrPetovan** [comment] 2023-07-26 19:18
Sorry about it 😞

**Comment by MrPetovan** [comment] 2023-07-26 19:59
I just tried the steps to reproduce but it has only removed the delegated group account as expected. 😕

**Comment by annando** [comment] 2023-07-27 05:33
I'm slight confused by this line: https://github.com/friendica/friendica/blob/develop/src/Module/Settings/RemoveMe.php#L81

Apparently we are fetching the user id with this function, although we are already providing it. This could be the source of the problem. If there is a mismatch, we shouldn't proceed. Also in the interface we should clarify the account's name on that page, so that it is really clear which account is about to be deleted. Also we shouldn't allow deleting an account that has got delegations.

**Comment by MrPetovan** [comment] 2023-07-27 10:29
The authentication line is the way we authenticate users. The provided local user id has been enough in my case to pick only the delegated account.

Your suggestions are welcome.

**Comment by annando** [comment] 2023-10-16 21:17
We are now having a mechanism that should prevent an accidental deletion. Can we close the issue?

**Comment by MrPetovan** [comment] 2023-10-17 00:09
Closed by https://github.com/friendica/friendica/pull/13314

**Closed as completed by MrPetovan** 2023-10-17 00:09 UTC
Labels: Bug, UX
