### ISSUE TITLE
instance with no public signup should not show "Register" button on login page

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#7385] opened 2019-07-15 08:16 UTC
### Expected behavior

If an instance does not support public signup aka new registrations, the Registration button should not be shown.

Ideally, instances with no public sign up should direct interested users to the public server list: https://dir.friendica.social/servers

The Register button could be replaced with a  "Join public server" button, although that may be too technical for new users. Less technical wording may be preferred.

### Actual behavior

Currently the green registration button is shown. Clicking it will take users to https://squeet.me/register with an info bubble saying "Permission denied." For interested new users, this is a raod block. They don't understand what's going on and may already give up on joining friendica.

![Active Registration button](https://user-images.githubusercontent.com/5708172/61202786-cc329000-a6e8-11e9-8140-5bbed755696c.png)

### Steps to reproduce the problem

An example instance where this can easily be reproduced is https://squeet.me/

**Comment by MrPetovan** [comment] 2019-07-15 12:09
Is this only a frio theme issue?

**Comment by AlfredSK** [comment] 2019-07-15 12:41
Duplicate of #7293

**Closed** 2019-07-15 12:43 UTC
Labels: Bug, UI/Theme, UX
