### ISSUE TITLE
Private messages sent to unrelated servers

### ISSUE THREAD

**Issue by grishka** [friendica/friendica#13263] opened 2023-07-09 00:58 UTC
- [x] I have searched open and closed issues for duplicates

### Bug Description

I just received a private message sent between two Friendica servers.

### Steps to Reproduce

1. Run a well-federated ActivityPub server I guess?

Actual Result:

Private messages are sent to servers that aren't supposed to receive them.

Expected Result:

Private messages should only be sent to servers where their recipients' accounts are.

### Screenshots

![image](https://github.com/friendica/friendica/assets/1478258/75461881-d449-4b33-86a7-f80b7814469e)

As you can see, the `to` field contains only one actor and `cc` is empty, making this a private message. Yet somehow I received it on my server, `friends.grishka.me`.

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2023.09-dev-1522

**Comment by MrPetovan** [comment] 2023-07-09 12:24
Uuuuuh @annando ?

Thank you for the report!

**Comment by annando** [comment] 2023-07-09 15:15
First question of course is: How have you discovered that post? Because even when it was delivered to you, the receiver shouldn't display it to you. Also the question is: Do you know the sender?

**Comment by grishka** [comment] 2023-07-09 15:22
> First question of course is: How have you discovered that post?

I did a serious refactor in Smithereen and I was looking through the server log to see if anything was broken (some things indeed were). I currently don't support any form of privacy anyway and reject any non-public posts but that will change soon.

> Also the question is: Do you know the sender?

No and neither the sender nor receiver follow or are followed by any accounts on my server.

**Comment by annando** [comment] 2023-07-09 16:14
What I meant was: Do you know the system that send this? It could of course be the actor - but it would also possible that it was the receiver.

I'm slightly confused since we create the list of target inboxes out of the values for to/cc/bcc.

**Comment by grishka** [comment] 2023-07-09 16:16
>  Do you know the system that send this? It could of course be the actor - but it would also possible that it was the receiver.

No, I don't log the IP addresses. The object did contain a valid LD signature though, so it indeed may be the receiver forwarding it.

**Comment by shiribailem** [comment] 2023-07-11 12:47
Have you reached out to either of the two users? wthinker@libranet.de and iron_bug@friendica.ironbug.org (which I would guess is the admin of that instance)

It should either be you, or someone with a more official status with Friendica making the contact (because otherwise we risk them getting spammed by people with good intentions)

Depending on which sent this, it could also be already resolved. Ironbug is running Friendica **2020-12-dev**

**Comment by annando** [comment] 2023-10-31 13:31
I'm still asking myself, if that was just some one time hiccup or if this could caused by that really old Friendica server. Having worked at the message distribution recently, I don't see any clues in the current code that could cause this. But possibly there had been an issue in that really old version on the receiver side that then distributed the comment.

**Comment by grishka** [comment] 2023-10-31 13:46
It is probably that old version friendica.ironbug.org is running. I also receive these (note the empty `to` and `cc`):
![image](https://github.com/friendica/friendica/assets/1478258/5a6d6d01-8fd8-4a9c-8af9-911929e80766)
Combined with an invalid LD-signature, it makes my server very angry:
![image](https://github.com/friendica/friendica/assets/1478258/a4f9f2fa-9dac-42f1-a526-1419837ed710)

**Comment by foss-** [comment] 2023-11-27 13:05
All this sounds like this is not actionable. https://friendica.ironbug.org/friendica is running 2020.12-dev. If the issue persists after updating it, this can be investigated. Otherwise this feels a lot like a wontfix item.

**Closed as not planned** 2023-11-27 17:28 UTC
Labels: Bug, Privacy
