### ISSUE TITLE
'greater than' becomes closing bracket.

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#3482] opened 2017-05-22 07:38 UTC
A few days ago I submitted a comment on posting published by somebody else. 
I've put a literal 'greater than' ( > ) in my comment. Directly after submitting everythig was fine, but after a few minutes the greater than became a closing bracket.

If you take a look at the posting on the server, where the posting got published, everything is ok : https://horche.demkontinuum.de/display/2196d4ee45591cc141a2a4c473106802 ,
but if you view this posting from another server you will see, that only the 'greater thans'
put by the author of the top level posting are not modified - only those by commenters from other servers.

**Comment by annando** [comment] 2017-08-15 19:53
I try to reproduce it, but it works for me. I tried it with ```> -> :coffee <- <``` which had made problems in that thread. I tested it between three different servers.

**Comment by rebeka-catalina** [comment] 2017-08-15 20:03
On 2017.08.15, Michael Vogel wrote:
> I try to reproduce it, but it works for me. I tried it with ```> -> :coffee <- <``` which had made problems in that thread. I tested it between three different servers.
> 

Try it on a posting from horche.demkontinuum.de - there you've had the
same issue that time.

**Comment by annando** [comment] 2017-08-18 06:07
Based upon my tests it seems as if an addon is causing this. I have the "retriever" addon in mind.

**Comment by annando** [comment] 2017-08-18 07:37
It is now checked, the origin of the problem is the "retriever" addon.

**Comment by annando** [comment] 2017-08-18 07:53
I have deactivated the addon: https://github.com/friendica/friendica-addons/pull/419

**Comment by annando** [comment] 2017-08-19 10:20
I guess we can now close the issue?

**Closed** 2017-08-19 10:22 UTC
Labels: Addons, Bug
