### ISSUE TITLE
Forbidden error (access permission denied)

### ISSUE THREAD

**Issue by bbadiddou** [friendica/friendica#1533] opened 2015-04-24 19:40 UTC
I updated my server Friendica to version 3.4, everything worked well, but after some days I get the error 403 and 443 with SSL, can someone help me please?

**Comment by tobiasd** [comment] 2015-04-24 20:39
I find a "bba diddou" in the directory, is this you? Following to the linked profile I get a GNUsocial instance.

**Comment by bbadiddou** [comment] 2015-04-24 21:01
My server is tawassol.org and i'm the admin , with the address : bba@tawassol.org

**Comment by tobiasd** [comment] 2015-04-25 05:32
Have you also updated your servers software? Apache 2.4 has some new syntax for allow,deny stuff. Is the directory you have installed friendica into accessible for the server?

**Comment by bbadiddou** [comment] 2015-04-25 10:16
I don't update my software server manually, it is a distant server , my apache version is 2.2.29 . My Friendica instance is not accessible for directory server, i update it by replacing folders using ftp.

**Comment by annando** [comment] 2015-04-25 11:41
Please have a look at your apache log files. There is something wrong that has nothing to do with friendica but with the system.

**Comment by bbadiddou** [comment] 2015-04-25 12:02
But my three other WordPress websites in the same server are working correctly.

**Comment by annando** [comment] 2015-04-25 16:39
You **really** have to look at your apache log file. The problem is maybe in the file permissions. Or it's a problem with the .htaccess. Or maybe in the server's configuration for this hostname. Or somewhere else.

Only the logfile can help.

**Comment by bbadiddou** [comment] 2015-04-25 18:47
Indeed, the problem is in .htaccess, the log file indicates the error: " .htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable". If you can help me to fix the problem I will be very grateful

**Comment by bbadiddou** [comment] 2015-04-26 19:50
I have fixed the problem now, many thanks for your help.

**Comment by annando** [comment] 2015-04-26 20:20
Great! I'm closing this issue.

**Closed by annando** 2015-04-26 20:20 UTC
