### ISSUE TITLE
Drag&Drop of images in Composer

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#7937] opened 2019-12-12 11:47 UTC
In order to standardize the functions and to offer a better user experience, the existing Drag&Drop function for uploading images should also be offered in Composer. It would be optimal to copy the content directly into the composer and output it.
![Drag_and_Drop_Compose](https://user-images.githubusercontent.com/44441246/70709542-653bf600-1cdd-11ea-9c88-45b663d424f8.png)

**Comment by AlfredSK** [comment] 2019-12-12 16:13
Also great but duplicate of #6249 .

**Comment by MrPetovan** [comment] 2019-12-12 16:38
Duplicate of #6249

**Closed by MrPetovan** 2019-12-12 16:38 UTC
Labels: Enhancement, UI
