### ISSUE TITLE
Private mail displays incorrect conversation participant information

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#5503] opened 2018-07-25 20:54 UTC
### Expected behavior
Private messages I receive should, in the private message listing, show the other party's name "and You".  ie: if I was having a conversation with "Jim Smith", the listing on that message thread should be "Jim Smith and You"

### Actual behavior
On message threads that I was not the originator of, the message says my full name "and You", rather than the other party.  I have numerous private message threads that have the remote user's avatar shown but they say "Adam Clark and You".

For threads that I have initiated, the order is changed to "You and " the remote user full name, and these display the correct information.

### Friendica version you encountered the problem
2018.05

### Friendica source (git, zip)
git

### PHP version
7.2.4

### SQL version
mariadb 10.1.29

**Comment by tobiasd** [comment] 2018-07-26 07:02
Duplicate of your #4738 closing this one

**Closed by tobiasd** 2018-07-26 07:02 UTC
Labels: Bug, UX

**Comment by realkinetix** [comment] 2018-07-26 16:45
*facepalm*  Sorry about that.
