### ISSUE TITLE
Problem Following GoToSocial Accounts

### ISSUE THREAD

**Issue by jlamothe** [friendica/friendica#12419] opened 2022-12-14 23:02 UTC
There seems to be an issue preventing Friendica from following GoToSocial accounts.  When either a GoToSocial account's handle or profile URL is put into the search bar, no results are returned.  See [this thread](https://social.jlamothe.net/display/c35d279b-1163-9a02-0a7d-dc0409902631) for additional details.

**Comment by ghost** [comment] 2022-12-19 08:38
I'm able to reproduce this behavior from Friendica 2022.10 with GoToSocial 0.5.2 git-c31f219. Is this related to #10740 ?

Probe request on `@nyanotech@catgirl.download` returns the following:
```
Array
(
    [name] => nyanotech@catgirl.download
    [nick] => nyanotech@catgirl.download
    [guid] => 
    [url] => nyanotech@catgirl.download
    [addr] => 
    [alias] => 
    [photo] => https://social.lkw.tf/images/person-300.jpg
    [header] => 
    [account-type] => 
    [community] => 
    [keywords] => 
    [location] => 
    [about] => 
    [xmpp] => 
    [matrix] => 
    [hide] => 
    [batch] => 
    [notify] => 
    [poll] => 
    [request] => 
    [confirm] => 
    [subscribe] => 
    [poco] => 
    [following] => 
    [followers] => 
    [inbox] => 
    [outbox] => 
    [sharedinbox] => 
    [priority] => 0
    [network] => unkn
    [pubkey] => 
    [manually-approve] => 
    [baseurl] => http://catgirl.download
    [gsid] => 1802
)
```

**Comment by MrPetovan** [comment] 2022-12-19 13:51
Most probably, thank you for the additional info!

**Comment by ghost** [comment] 2022-12-19 17:21
> Most probably, thank you for the additional info!

My pleasure. Please get in touch with me if you need to run additional tests.

**Comment by annando** [comment] 2022-12-19 20:54
Problem is that the returned data doesn't validate. I yet have to find out where the problem lies, but currently I assume that GoToSocial doesn't completely follow the JsonLD standard.
```
{
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        "http://joinmastodon.org/ns",
        "https://w3id.org/security/v1"
    ],
    "discoverable": false,
    "featured": "https://catgirl.download/users/nyanotech/collections/featured",
    "followers": "https://catgirl.download/users/nyanotech/followers",
    "following": "https://catgirl.download/users/nyanotech/following",
    "icon": {
        "mediaType": "image/png",
        "type": "Image",
        "url": "https://catgirl.download/fileserver/01EB04EEJK195GDTXJXEQJKXW9/attachment/original/01JE47D615B75EJR8P6ZNGXYE9.png"
    },
    "id": "https://catgirl.download/users/nyanotech",
    "inbox": "https://catgirl.download/users/nyanotech/inbox",
    "manuallyApprovesFollowers": false,
    "name": "meowy catgirl",
    "outbox": "https://catgirl.download/users/nyanotech/outbox",
    "preferredUsername": "nyanotech",
    "publicKey": {
        "id": "https://catgirl.download/users/nyanotech/main-key",
        "owner": "https://catgirl.download/users/nyanotech",
        "publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvjaR/nPgZAT/QzIH8GbP\n/Iw7Xzw5FqtS85ItjdLcBxOr54GVMYyD9XDypPPhz/1uteXeOOXODOZieRv21fGd\nhW4rsN81jFNMToHUaVUWIqIcSMQmiIwVDy4//oTSTx8/mifgkwMH7QHIToEPBTX9\nsvofwf4Cpl1ow6UMVTk910BHHddL3KSoqBtKzZneOGwuIAC1uWSzDbeSee7EwWsV\nH+Js7ywkGBdU3roLqcbPh6xFRLlBXtT3wTUoeSbfTbY2M4T8IQfcaHJKgxPn29/1\nBu0NElwlr/YwvM5ui1yIw/yOlNGf/1+K+uEi0nuyHuNJhb/AenSBWx4IVhCoZ8gh\nIwIDAQAB\n-----END PUBLIC KEY-----\n"
    },
    "summary": "<p>nyaaa~ | it/its | 25 | meows at computers | headpats/hugs/etc ok | 🔞</p>",
    "tag": [],
    "type": "Person",
    "url": "https://catgirl.download/@nyanotech"
}
```

**Comment by MrPetovan** [comment] 2022-12-19 21:08
This is an issue we should bring to them, is there a third-party validator we can recommend them?

**Comment by annando** [comment] 2022-12-19 21:19
The problem was the context. You mustn't add ` "http://joinmastodon.org/ns"` that way. 

It has to look that way:
```
"@context": [
        "https://www.w3.org/ns/activitystreams",
        {
            "toot": "http://joinmastodon.org/ns#"
        },
        "https://w3id.org/security/v1"
    ],
```
The order of the elements doesn't matter. But the Mastodon namespace must be assigned to a namespace.

**Closed as completed** 2022-12-19 21:24 UTC
Labels: Bug, Federation

**Comment by jlamothe** [comment] 2022-12-19 21:29
I've also had issues following Owncast accounts.  I don't know if this fix would address that.  Can anone tell if this fix would address that as well?  An account you can try is `@stream@live.jlamothe.net`

If not, I can always open another issue.

**Comment by annando** [comment] 2022-12-19 21:33
Indeed. They made the same mistake.

**Comment by jlamothe** [comment] 2022-12-19 21:35
Awesome!  Thanks so much for all that you do.

**Comment by MrPetovan** [comment] 2022-12-19 21:38
There already is an issue for this over there: https://github.com/superseriousbusiness/gotosocial/issues/240

But the repository is read-only until January 2023 per description.
