### ISSUE TITLE
Use original Mastodon App with Friedica.

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11432] opened 2022-04-21 11:37 UTC
The original app for Mastodon is now also available for Android. here
https://play.google.com/store/apps/details?id=org.joinmastodon.android
Would it be possible to make Friedica usable for this app as well?
At the moment there is still an error message when logging in.

**Comment by tobiasd** [comment] 2022-04-21 12:04
Which error message is reported?

**Comment by ghost** [comment] 2022-04-21 12:06
> Which error message is reported?

After entering the domain, the message "Missing parameters" appears

**Comment by tobiasd** [comment] 2022-05-08 06:09
Duplicate of #11415, closing this.

**Closed as completed by tobiasd** 2022-05-08 06:09 UTC
Labels: New Feature
