### ISSUE TITLE
[kaiteki] Notifications data structure different to Mastodon?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13673] opened 2023-11-27 06:27 UTC
Relating to https://github.com/Kaiteki-Fedi/Kaiteki/issues/475 : Using Kaiteki with Friendica, notification's don't display with an error suggesting that some API call returns a wrong datatype - List where a Map would be expected?

**Comment by HankG** [comment] 2023-11-27 12:21
I think the problem is that if markers aren't set that the empty result string returned by PHP is `[]` rather than `{}` which Dart is interpreting as a list which is the wrong type. Because the distinction between maps and lists is more ambiguous in PHP I'm not sure if there is an easy way to fix that but one of the PHP savvy people may be able to. Apparently there is a way to override serializers but I'm not sure how that all is wired up in Friendica: https://stackoverflow.com/questions/41588574/how-to-serialize-empty-array-to-json-object-curly-braces-with-jms-serializer-i

**Comment by MrPetovan** [comment] 2023-11-27 17:27
This particular question was asked in the context of the third-party library JMS serializer which we don't use. And as I said [here](https://github.com/Kaiteki-Fedi/Kaiteki/issues/475#issuecomment-1828298592), we'd need to see the JSON that triggered the error to be able to do something about it.

**Comment by kr428** [comment] 2023-11-27 19:07
> This particular question was asked in the context of the third-party library JMS serializer which we don't use. And as I said [here](https://github.com/Kaiteki-Fedi/Kaiteki/issues/475#issuecomment-1828298592), we'd need to see the JSON that triggered the error to be able to do something about it.

Ok, thanks, I'll see what I can do here. General question, then: Kaiteki is quite an interesting and promising client for Mastodon API servers. The devs themselves have stated that they don't want to officially support Friendica. Still, it's an interesting option to have so I wonder where to file issues like these at all - should it be all about Kaiteki fixing their client implementation, or should it be Friendica getting closer to Mastodons understanding of Mastodon API? The latter might be a better approach as it could help also seamlessly using other Mastodon API clients with Friendica but I'm unsure whether this is desired...

**Comment by MrPetovan** [comment] 2023-11-27 19:19
No, we should fix our serialization, but I'd still need the failing JSON document as a starting point.

**Comment by kr428** [comment] 2023-11-27 20:21
Diving through the code, problem seems different: Apparently, Kaiteki tries a call to /api/v1/markers (which I am unsure what it actually does) that, though it doesn't fail, returns just "[ ]" as JSON and subsequently fails without even loading notifications. The API call for markers is here - https://github.com/Kaiteki-Fedi/Kaiteki/blob/fa5b769b6ab15af7fa4ee39b027db44b58c95f02/src/kaiteki_core/lib/src/social/backends/mastodon/client.dart#L378 , the "troublesome" code in Kaiteki apparently here: https://github.com/Kaiteki-Fedi/Kaiteki/blob/fa5b769b6ab15af7fa4ee39b027db44b58c95f02/src/kaiteki_core/lib/src/social/backends/mastodon/shared_adapter.dart#L396 -- if I remove this "if" condition and just force markers to be null, notifications do load as expected...

**Comment by MrPetovan** [comment] 2023-11-27 21:07
Thanks, I have a fix for this.

**Closed as completed** 2023-11-28 01:10 UTC
Labels: Bug, API

**Comment by kr428** [comment] 2023-11-28 06:37
Tested, works. Thanks loads! :+1:
