### ISSUE TITLE
The administrator should be able to private message anybody on the node

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#5504] opened 2018-07-25 21:02 UTC
### Expected behavior
The system administrator should be able to send any user a private message.

### Actual behavior
Same access level as anyone else, and if a user blocks private messages from non-friends, then the sysadmin would have to resort to looking up & emailing a user if they had to contact them.

### Steps to reproduce the problem
Try sending a message to any user that has default settings on.

### Friendica version you encountered the problem
2018.05 

### Friendica source (git, zip)
git

### PHP version
7.2.4

### SQL version
mariadb 10.1.29

**Comment by tobiasd** [comment] 2018-07-26 06:58
Duplicate of the 2nd part from #773 so I'll close this one.

**Closed by tobiasd** 2018-07-26 06:58 UTC
Labels: Enhancement, UX

**Comment by MrPetovan** [comment] 2018-07-26 11:34
More like point 1, still a duplicate though.
