### ISSUE TITLE
Notification with another user with same nickname (on ostatus)

### ISSUE THREAD

**Issue by Shnoulle** [friendica/friendica#3535] opened 2017-06-09 21:05 UTC
Hi all,

I have this issue : web show notification for another user on ostatus network. 
![capture du 2017-06-09 22-29-00](https://user-images.githubusercontent.com/1439428/26993501-9eef3232-4d63-11e7-9da7-33b5041f078e.png)

All this notification are for `shnoulle@ostatus.shnoulle.net` and not for `shnoulle@social.shnoulle.net` (see for example : `https://social.shnoulle.net/display/52acf9cdb1328f62b3c57e6139d60086a2b6f5b1` .

Way to (maybe) reproduce :

1. Create an account on a public server (start with gnusocial) (gnusocial only ? ostatus only ? friendica ? diaspora ?)
2. Connect with this account on you friendica
3. Ask to another user to mention your gnusocial account
4. See what happen.

Currently : i didn't think it can happen a lot, but if fediverse become really big, it can happen more :).

My log (normal)
```
2017-06-08 21:25:53@log5939c0e175f0d9.74058052	[NORMAL]:api.php:374:api_call	API call not implemented: api/v1/timelines/public?limit=40
2017-06-08 21:26:26@log5939c102863e69.85058163	[NORMAL]:dfrn_notify.php:237:dfrn_notify_content	dfrn_notify: new notification dfrn_id=1:b8f1c412c8626a3f53253af09f00c823ab479a4b27aec4eb0b905a1090340f78
2017-06-08 21:26:27@log5939c102e7d008.76963391	[NORMAL]:dfrn_notify.php:126:dfrn_notify_post	dfrn_notify: received notify from Hypolite Petovan for Shnoulle (F)
2017-06-08 21:26:27@log5939c102e7d008.76963391	[NORMAL]:dfrn_notify.php:157:dfrn_notify_post	rino: md5 raw key: d72873fc5f0e91fd2e404e21bea2758d
2017-06-08 21:26:27@log5939c102e7d008.76963391	[NORMAL]:dfrn.php:2294:process_entry	Processing entries
2017-06-08 21:26:27@log5939c102e7d008.76963391	[NORMAL]:dfrn.php:2294:process_entry	Processing entries
2017-06-08 21:26:27@log5939c102e7d008.76963391	[NORMAL]:items.php:1036:item_store	item_store: created item 21275
```
(set it to debug now).

A line of notify DB
```
INSERT INTO `notify` (`id`, `hash`, `type`, `name`, `url`, `photo`, `date`, `msg`, `uid`, `link`, `iid`, `parent`, `seen`, `verb`, `otype`, `name_cache`, `msg_cache`) VALUES
(1537, '7407686b451013ab40ea95fda6875f7afc2f2ea62676b9b3921b0c58b59fe710', 128, 'Arnaud J.', 'https://framapiaf.org/@arnaudj', 'https://framapiaf.org/system/accounts/avatars/000/005/700/original/a59b3cc9b223adfd.jpg?1492208599', '2017-06-09 21:22:25', '[url=https://framapiaf.org/@arnaudj]Arnaud J.[/url] [url=https://social.shnoulle.net/display/22b2c6df4bb96d472eddcff64ebc52b20b18b334]vous a étiqueté[/url].', 1, 'https://social.shnoulle.net/display/22b2c6df4bb96d472eddcff64ebc52b20b18b334', 21797, 21355, 1, 'http://activitystrea.ms/schema/1.0/tag', 'item', 'Arnaud J.', '{0} vous a &eacute;tiquet&eacute;.');

```

**Comment by Shnoulle** [comment] 2017-06-20 11:26
@Hypolite Can you tell me where the Notification test is done ? Maybe i can take a look :)

**Comment by Hypolite** [comment] 2017-06-21 01:27
What do you mean by Notification test? Friendica has no unit tests at all at the moment.

**Comment by Shnoulle** [comment] 2017-06-21 07:39
No :) where a “notice” is tested and send in notify table. 

M%aybe i found it : NotificationsManager->_personal_sql_extra if i don't make error.

**Comment by annando** [comment] 2017-08-20 20:57
@Shnoulle I guess you added your OStatus account to Friendica? In that case it is not a bug but a feature.

**Comment by Shnoulle** [comment] 2017-08-21 06:10
Hi,

Not exactly, i add my OStatus account as mirror in Friendica at start but remove it after. Today : `shnoulle@ostatus.shnoulle.net` are a friend of `shnoulle@social.shnoulle.net`. 
But you're right : maybe there are some glitch with the old mirroring.

**Comment by annando** [comment] 2017-09-12 17:59
@Shnoulle can we close it?

**Comment by Shnoulle** [comment] 2017-09-12 18:46
Sorry, didn't update and make good testing … in my todo list for tomorrow …

**Comment by Shnoulle** [comment] 2017-09-13 08:31
@annando current situation : 

1. I use during some time GNU Social Import/Export/Mirror with my Ostatus account
2. I disable GNU Social Import/Export/Mirror via admin
3. Still receive the notification

This is a bug no ?
![capture du 2017-09-13 10-30-20](https://user-images.githubusercontent.com/1439428/30367471-9aad9f00-986e-11e7-8f90-8e00fd6349e9.png)

**Closed** 2018-08-10 04:33 UTC
Labels: Bug
