### ISSUE TITLE
frio: side effect of new theming

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9042] opened 2020-08-20 16:08 UTC
### Expected behavior
Checkboxes shouldn't use the custom background color. They should use the same color as before (like the text input fields look like - probably white).

### Actual behavior
I'm using a custom color scheme. The (wonderful) new theme settings seem to have the side effect that makes the checkboxes use the custom background color.

I noticed that when using Friendica on my phone (Chrome web app on Android 10). Will check on desktop as soon as I am home.

### Steps to reproduce the problem
Activate a custom color scheme. Set the background to a color other than white. Could be some other dark color but it looks exactly like my bg color.

![Screenshot_20200820-175454](https://user-images.githubusercontent.com/3656054/90796393-8db9cc80-e30f-11ea-9814-1ca98cbd29d9.jpg)

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment] 2020-08-20 16:10
Yep. It's the background color. When I change it to red the boxes are red too.

**Comment by MrPetovan** [comment] 2020-08-20 16:10
It looks like you also set a custom background image, I'd suggest you change the custom background color to a lighter one to match the brightness of the background image.

**Comment by AlfredSK** [comment] 2020-08-20 17:05
> It looks like you also set a custom background image, I'd suggest you change the custom background color to a lighter one to match the brightness of the background image.

Yep. I can do that. But what if a user doesn't use a bg image? Does it look right then?

**Comment by AlfredSK** [comment] 2020-08-20 18:08
Found another glitch. When I reshare a post the reshared content protrudes* over the edge of the modal background in the preview. The submit button is then floating outside the modal.

I guess that's another issue. Or should we use this one to collect the rough edges?

*) never heard of that word before but DeepL thinks it's great :-)

**Comment by MrPetovan** [comment] 2020-08-20 18:13
Please collect the problems you find in another issue.

> Yep. I can do that. But what if a user doesn't use a bg image? Does it look right then?

We're talking about the "Custom" scheme so the background color can be adjusted freely. Checkbox display has been checked in fixed background color schemes.

**Comment by MrPetovan** [comment] 2020-08-24 11:07
Can we close this?

**Comment by AlfredSK** [comment] 2020-08-24 15:09
No. I don't think so. I still think it is a bug that the background color is used in checkboxes and radio buttons. It looks weird and is - from my point of view - unexpected.

**Comment by foss-** [comment] 2020-08-29 10:21
So far you have not mentioned expected behaviour. You filled the field, but only wrote down what you do not expect.
Background colours work nicely on the new frio themes:
![Bildschirmfoto 2020-08-29 um 12 19 41](https://user-images.githubusercontent.com/5708172/91634633-04cb2100-e9f2-11ea-8b45-8ebf750c3df4.png)

So wondering if making the fields transparent would work for both new frio themes and custom themes with image as background?

**Comment by vinzv** [comment] 2020-10-12 21:24
I'm trying to dig into this issue right now. So far I can reproduce the behaviour observerd by @AlfredSK. It looks like it got lost in this thread so I'll rewrite it here:

1. Set Frio color scheme to "custom"
2. Set "background color" to something different than white

Result:
![image](https://user-images.githubusercontent.com/74432/95789327-9e6a3b80-0cdd-11eb-9ecc-18e8c1596a31.png)

Expected result:
![image](https://user-images.githubusercontent.com/74432/95789557-0882e080-0cde-11eb-9fc3-131805610e68.png)

The reason for this behavior roots from here: 
https://github.com/friendica/friendica/blob/1b273e25b546e09426cb223ce7c534b5b66c9995/view/theme/frio/css/style.css#L2045-L2048

**Comment by MrPetovan** [comment] 2020-10-13 00:56
Yes, as you can see, it was intended (by me). The problen I ran into is that I didn't want the checkboxes/form controls to hurt people's eyes by having a bright background color on dark/black themes. So this seemed to me like a good solution: by using the chose background color, it would always be in the correct brightness.

Unfortunately, because of this, checkboxes became counter-intuitive. The original issue still stands. Can only checkboxes have a white background while other form fields have a background color of the ambiant brightness? Should they just have a black background on dark/black theme, and if yes, should there be an arbitrary cutoff between white and black for the custom scheme where the background-color can be set freely?

**Closed** 2020-10-13 00:58 UTC
Labels: Sup­port Request
