### ISSUE TITLE
Friendica Incorrectly Calculates my Age

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9879] opened 2021-01-29 22:32 UTC
- [x] I have searched open and closed issues for duplicates

### Bug Description

My Birthdate is 11/4/1958, Friendica incorrectly calculates my age as 61, I am 62.
### Steps to Reproduce

1.  step one
2.  step two
3.  step three

Create your profile with your birthdate.
Actual Result:

Calculated Age is wrong.
Expected Result:

Should show my age as 62.

### Platform Info

Friendica Version:

    Friendica 'Red Hot Poker' 2021.03-dev - 1385
Friendica Source: 
Github
PHP version:
PHP 7.4.14
SQL version:
mysql  Ver 15.1 Distrib 10.5.8-MariaDB

**Comment by MrPetovan** [comment] 2021-01-30 10:01
Thank you for the report, this isn't a bug, it's a flattering feature! 😄

**Comment by 4nanook** [comment] 2021-01-30 10:08
:smile_cat:

**Comment by tobiasd** [comment] 2021-01-30 11:13
I'd like to have the feature as well (IOW Friendica calculated my age correctly)

**Comment by MrPetovan** [comment] 2021-01-31 00:43
I'm not able to reproduce this using your birth date and your specific timezone, can you please verify you set your birth year correctly in your profile?

**Comment by 4nanook** [comment] 2021-01-31 01:06
![profile](https://user-images.githubusercontent.com/3466797/106371788-6edb4f80-631d-11eb-8644-119964a79985.png)
![profile2](https://user-images.githubusercontent.com/3466797/106371791-71d64000-631d-11eb-88e3-02b25ce7f529.png)

**Comment by MrPetovan** [comment] 2021-01-31 02:50
Thank you for the elaboration!

**Comment by MrPetovan** [comment] 2021-01-31 03:30
I found the issue. On the one hand, on your profile there is an automatic profile field named "Age" that currently doesn't display anything for American English users because of a bug in the localization code. When a translation is missing, we normally use the source string, but for plurals, we don't do this correctly.

On the other hand, last year, before your birthday, you created a custom profile field with your age at the time. You also titled this field "Age", probably because your age wasn't showing normally. This custom field will not update automatically because it is just a number you set yourself. For now, you can update it manually, but I will fix the localization bug which will restore the automatic display of your age based on your birthdate.

**Comment by 4nanook** [comment] 2021-01-31 04:12
I sure did not intentionally create any custom field.  Hmm.  This is
getting more bizzare by the moment.  I also saw a comment today with my name
that I didn't make, perhaps time to change password.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by MrPetovan** [comment] 2021-02-27 23:43
I consider this resolved, closing the issue for bookkeeping.

**Closed as completed by MrPetovan** 2021-02-27 23:43 UTC
Labels: Bug
