### ISSUE TITLE
support for AndStatus mobile client

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#1427] opened 2015-03-10 12:47 UTC
I enjoy using AndStatus Android app all along with friendica but as far as I can tell, there are a bunch of minor and less minor (https://github.com/andstatus/andstatus/issues/241) issues in this combination. Since AndStatus seems more promising and in some ways better maintained than other options (speaking Twidere or the Friendica app found in f-droid), I think pushing friendica to a point at which it works well out of the box with AndStatus would be very helpful. I would volunteer for testing and debugging, but I'm not deep enough into either Friendica or AndStatus to provide meaningful commits...

**Comment by annando** [comment] 2015-03-22 01:03
Could you make tests about the issues? In my tests I had no problems, only some unsupported functions.

**Comment by strk** [comment] 2015-05-31 12:21
I had (can reproduce) this problem with friendica 3.4.0 and AndStatus 17.1: https://github.com/andstatus/andstatus/issues/241

**Comment by annando** [comment] 2015-05-31 20:15
I'm using 17.1 as well - and the developer branch of friendica. I had the problem in the past but cannot reproduce the behaviour anymore. In the current branch we increased the speed of some API calls. Maybe that solved the issue.

**Comment by fabrixxm** [comment] 2015-12-21 13:20
is this issue fixed by #2024 ?

**Comment by annando** [comment] 2015-12-21 13:21
@fabrixxm Yeah, see here: https://github.com/friendica/friendica/pull/2024

**Closed** 2015-12-21 13:49 UTC
Labels: Mobile
