### ISSUE TITLE
posting by cc: email errore.

### ISSUE THREAD

**Issue by bbadiddou** [friendica/friendica#1475] opened 2015-04-04 17:50 UTC
in the friendica 3.3.2 and 3.3.3 posting to cc : email doesn't work  and i get blanc page when i try t
![capture du 2015-04-04 19 45 55](https://cloud.githubusercontent.com/assets/11799395/6993870/dd5df10e-db03-11e4-8989-f04281f83ebf.png)
his .

**Comment by fabrixxm** [comment] 2015-04-04 21:26
Duplicate of issue #1437. Fixed in release/3.4

**Closed** 2015-04-04 21:26 UTC
