### ISSUE TITLE
API: return info of newly uploaded images

### ISSUE THREAD

**Issue by Extarys** [friendica/friendica#9824] opened 2021-01-19 17:02 UTC
### Is the feature request related to a problem? Please describe.

lack of info returned by `http://friendica.local/wall_upload/testadmin?response=json&album=` when uploading an image with `ajaxupload.js`

### Describe the feature you'd like
Currently when uploading a file, the endpoint returns
```
{
    ok: true
}
```
Which isn't that much useful.

When sending a file to `http://friendica.local/wall_upload/testadmin?response=json&album=`, the API should return the path to the newly uploaded image.
Something like:
```
{
    ok: true
    img: /photo/7275381691600709c97f04a795410284-1.png 
    link: /photos/testadmin/image/7275381691600709c97f04a795410284
}
```

### Additional context

I'm working to implement `Drag and drop/paste photos to share (post, comments, private messages)` from #9787. The client needs to know what is the path created by the server. Currently the user need to go to the image tab and click on the newly uploaded images to insert the image path.

I'm not sure if there is another api endpoint that also process uploaded images.

**Comment by MrPetovan** [comment] 2021-01-19 17:30
What does it return at the moment?

**Comment by Extarys** [comment] 2021-01-19 17:40
```
{
    ok: true
}
```

![image](https://user-images.githubusercontent.com/11581433/105072187-8ed45e80-5a53-11eb-9afe-efdd1e19f486.png)

**Comment by Extarys** [comment] 2021-01-19 18:45
Is the [API documentation](https://github.com/friendica/friendica/blob/develop/doc/API-Friendica.md#post-apifriendicaphotoupdate) for `POST api/friendica/photo/update` up to date? If so, wall_upload and that should return a JSON object based on that IMO. (We wouldn't need the base64 value of the image obviously, but the internal should be based on the api - eventually :smile:

**Comment by MrPetovan** [comment] 2021-01-19 19:17
I cannot vouch for the accuracy of the API documentation, but the `wall_upload` response could really be improved.

**Comment by MrPetovan** [comment] 2021-01-21 04:35
Alright, I started to look into it, and oh boy.

The `/wall_upload` module is a legacy part of Friendica built between 2010 and left alone since 2015, so even before I joined the project in 2016. The module itself isn't used as is, meaning that no part of the project calls the `/wall_upload` endpoint.

BUT.

The API itself makes heavy use of the module function itself, in `/api/statuses/mediap`, `/api/statuses/update` (and `/api/statuses/update_with_media` since they are aliases) and `/api/media/upload`.

The module function accounts for at least four different way of using it, between the `$desktopmode` boolean flag and the `response=json` GET parameter check.

The `$desktopmode` flag is set when the module is accessed directly via `/wall_upload`, which we don't do (anymore?). Your manual use of the endpoint probably echoes back to a long-forgotten use and the terse response is an artifact of that period.

The `response=json` GET parameter isn't set in Friendica anymore either, not even in the API, so again this is a code path overrun with vegetation.

Here's a handy chart explaining the issue you faced:

|                                        | response != json  | response == json |
| -------------------------- | ------------------- | ------------------- |
| $desktopmode == false | Current API use   | 🐉 Dragons 🐉   | 
| $desktopmode == true  | 🐉 Dragons 🐉  |  You are here 🔴  | 

However, I have good news. It seems you can use the `/api/media/upload` API endpoint with the same payload and it should give you a more detailed response than `/wall_upload`. And if the preview URL isn't enough, there are a couple more returned by `wall_upload_post()` that we can expose in the API response.

**Comment by annando** [comment] 2021-01-21 06:33
I guess we should replace `wall_upload` then with the upload functionality that is still used and remove the module then?

**Comment by Extarys** [comment] 2021-01-21 11:59
Gonna tag #9813 here for future reference.
I'm glad the backend uses the `/api` path though.

>  this is a code path overrun with vegetation

The image is strong. :laughing: Gonna try to make some uploads with the endpoints you provided. IMO the JSON response should be the default one when calling a REST API. I do know we need to be careful as some instances runs older version and it's federated so, it adds to the complexity of, everything.

**Comment by Extarys** [comment] 2021-01-21 12:02
Does PHP support Swagger or some OpenAPI implementation that could generate the doc for the APIs?

Something similar to this [Swagger demo](https://petstore.swagger.io/)? If so, we can document the endpoints quite easily and generate a documentation, even if it's just for us for the moment.

**Comment by MrPetovan** [comment] 2021-01-21 15:41
The API used to be PHP global functions hastily cobbled together, we've only started to move them to a more proper class hierarchy, we aren't at the self-documentation stage at all!

> I guess we should replace `wall_upload` then with the upload functionality that is still used and remove the module then?

Absolutely.

**Comment by Extarys** [comment] 2021-01-21 16:05
@MrPetovan I was suggesting that as classes are created for endpoints and all, we could make it so an OpenAPI app could at least show that route in some form of documentation. Once this is implemented, even rudimentary, it's a matter of looking for that route in the code and add more information as we go along - makes small easy PRs too for beginners.

But I do understand too if even that is too soon.

**Comment by MrPetovan** [comment] 2021-01-21 16:35
I didn't know about OpenAPI and Swagger so it definitely wasn't on my mind, I'll see if it's affordable to us.

**Comment by annando** [comment] 2021-05-24 18:21
@Extarys with the upcoming version we now support the Mastodon API. This does contain a functionality to upload pictures.

**Comment by Extarys** [comment] 2021-05-26 23:25
Thanks! I've been so busy, I should have time to continue playing with you folks soon TM

<3

Should we close this issue if it's in an upcoming release?

**Comment by annando** [comment] 2021-05-27 03:55
I guess the best would be that you close it by yourself when you tested it. So we can be sure that it meats your demand.

**Comment by MrPetovan** [comment] 2021-05-27 15:43
> [...] So we can be sure that it meats your demand.

My t-shirt saying "Friendica isn't a cannibal cult" has folks asking me a lot of questions already answered by the t-shirt.

**Comment by tobiasd** [comment] 2021-07-03 17:44
What is the state of the issue?

**Comment by MrPetovan** [comment] 2021-09-04 06:02
No answer from OP, no work has been done, removing from milestone.

**Comment by annando** [comment] 2023-02-11 08:57
From my perspective the issue is solved. We have introduced new endpoints and they return usable data as well.

**Closed as completed** 2023-02-11 13:37 UTC
Labels: New Feature, API
