### ISSUE TITLE
Posting a new message without reloading

### ISSUE THREAD

**Issue by valvin1** [friendica/friendica#7081] opened 2019-05-04 06:10 UTC
### Expected behavior

I'm reading my timeline and I wish posting a new message. On Frio theme I can do it without leaving my timeline. I compose it and click on publish. I would like that message is sent asynchronously without lost where my timeline was. It is the same when I reshare a post as it composes a new message.

This is already implemented when I post a comment on an existing post or like a message.

### Actual behavior

When I send my message it reloads the whole page and the timeline. If I'm using infinite scrolling I go back to newer post. If I'm using pagination I go to the top of the page I was.

### Friendica version you encountered the problem

2019.03

**Comment by MrPetovan** [comment] 2019-05-04 12:10
Duplicate of #4599

**Closed by MrPetovan** 2019-05-04 12:10 UTC
