### ISSUE TITLE
[2023.05] PHP Warnings

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#13025] opened 2023-04-23 14:30 UTC
Please report here any PHP Warning message obtained running the 2023.04 stable or 2023.05-dev/rc versions.

Replaces https://github.com/friendica/friendica/issues/12488

**Comment by ghost** [comment] 2023-04-23 19:23
Still relevant in the last develop

`PHP Warning:  sem_acquire(): Failed to acquire key 0x66031b0c: Identifier removed in /src/Core/Lock/Type/SemaphoreLock.php on line 65
`

**Comment by annando** [comment] 2023-04-23 21:06
@copiis This semaphore thing is related to your installation. It is not caused by the system.

**Comment by ghost** [comment] 2023-04-26 08:59
`PHP Warning: Trying to access array offset on value of type bool in /vendor/michelf/php-markdown/Michelf/MarkdownExtra.php on line 525'`

**Comment by MrPetovan** [comment] 2023-04-28 03:13
I would need to know the input Markdown text that triggered this warning :/

**Comment by ghost** [comment] 2023-05-05 15:39
`PHP Warning:  Undefined array key "subscribe" in /src/Model/GServer.php on line 872`

Addressed in https://github.com/friendica/friendica/pull/13099

**Comment by ghost** [comment] 2023-05-05 15:41
> I would need to know the input Markdown text that triggered this warning :/

If that would have been easy to find out, you would have shown me a way, right?

**Comment by MrPetovan** [comment] 2023-05-05 15:46
Absolutely, however warnings are soft errors that don't generate a complete trace so they can be slippery when they depend on the actual content.

**Comment by ghost** [comment] 2023-05-06 13:33
`PHP Warning: Undefined array key "t" in /home/users/meld/www/meld/src/Module/Hashtag.php on line 38'`

Addressed in https://github.com/friendica/friendica/pull/13099

**Comment by ghost** [comment] 2023-05-06 15:12
`PHP Warning:  DOMXPath::query(): Invalid expression in /src/Protocol/Feed.php on line 481`

Addressed in https://github.com/friendica/friendica/pull/13099

**Comment by nupplaphil** [comment] 2023-05-09 19:31
hmmm I'm not sure if this is a config error or a code error, but:
```console
2023-05-09T21:26:18+02:00	{"source": "nginx", "time": 1683660378.563, "resp_body_size": 583, "host": "friendica.philipp.info", "request_length": 1803, "method": "POST", "uri": "/inbox", "status": 200,  "user_agent": "http.rb/4.4.1 (Mastodon/3.3.3; +https://pawoo.net/)", "resp_time": 3.000, "upstream_addr": "172.31.0.6:9000", "request_id": "44ae2aa3b29f3268c6d10392aeb66878"}

2023-05-09T21:26:18+02:00	Friendica[8947]: index [WARNING]: E_WARNING: Cannot modify header information - headers already sent {"code":2,"message":"Cannot modify header information - headers already sent","file":"/var/www/html/src/App/Page.php","line":423} - {"file":null,"line":null,"function":"header","request-id":"44ae2aa3b29f3268c6d10392aeb66878","uid":"f2e2f0"}

2023-05-09T21:26:18+02:00	Friendica[8947]: index [WARNING]: E_WARNING: Cannot modify header information - headers already sent {"code":2,"message":"Cannot modify header information - headers already sent","file":"/var/www/html/src/App/Page.php","line":410} - {"file":null,"line":null,"function":"header","request-id":"44ae2aa3b29f3268c6d10392aeb66878","uid":"f2e2f0"}

2023-05-09T21:26:15+02:00	Friendica[8947]: index [WARNING]: E_WARNING: Cannot modify header information - headers already sent {"code":2,"message":"Cannot modify header information - headers already sent","file":"/var/www/html/src/App.php","line":633} - {"file":null,"line":null,"function":"header","request-id":"44ae2aa3b29f3268c6d10392aeb66878","uid":"f2e2f0"}
```

No further errors in the log so far .. and the response code is 200 as well ..

[Edit] Nevermind, seems like a timeout, as I recently set the timeout config

**Comment by nupplaphil** [comment] 2023-05-11 04:56
Friendica[445131]: worker [WARNING]: E_WARNING: DOMXPath::query(): Invalid expression {"code":2,"message":"DOMXPath::query(): Invalid expression","file":"/var/www/html/src/Protocol/Feed.php","line":481} - {"file":null,"line":null,"function":"query","request-id":"645c3fb510b3c","uid":"330f90"}

Addressed in https://github.com/friendica/friendica/pull/13116

**Comment by MrPetovan** [comment] 2023-05-11 09:02
It should have been addressed by https://github.com/friendica/friendica/pull/13099, can you make sure your node was up-to-date when you received the message?

**Comment by ghost** [comment] 2023-05-12 04:03
> `PHP Warning: DOMXPath::query(): Invalid expression in /src/Protocol/Feed.php on line 481`
> 
> Addressed in #13099

Still getting a lot of these.

Addressed in https://github.com/friendica/friendica/pull/13116

**Comment by AlfredSK** [comment] 2023-05-19 12:26
2023.05-rc, PHP 8.1

`Undefined array key "tags" in .../src/Core/Search.php on line 90`

Addressed in https://github.com/friendica/friendica/pull/13145

**Comment by Quix0r** [comment] 2023-05-21 07:24
Reported by `@tino@fri.dxz.ch`:
`PHP Warning: Undefined array key "subscribe" in /var/www/virtual/../friendica/src/Model/GServer.php on line 872`
Original: https://fri.dxz.ch/display/e309fc6b-4064-69b5-4396-d2f275069901
Version: `2023.04-1`

Addressed in https://github.com/friendica/friendica/pull/13099

**Closed as completed** 2023-05-23 21:53 UTC
Labels: Bug
