### ISSUE TITLE
stable version to developer version:  Parameter must be an array or an object that implements Countable in dba.php on line 969

### ISSUE THREAD

**Issue by gurussia** [friendica/friendica#4482] opened 2018-02-21 03:18 UTC
php scripts/worker.php 
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/etc/friendica/include/dba.php on line 969

/var/etc/html/friendica# PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/etc/friendica/include/dba.php on line 969

**Comment by MrPetovan** [comment] 2018-02-21 04:15
Duplicate of #4478, please keep commenting in the original issue.

**Closed by MrPetovan** 2018-02-21 04:15 UTC
Labels: Sup­port Request
