### ISSUE TITLE
Confusing padlock in post editor for public posts.

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1689] opened 2015-06-24 22:36 UTC
The post editor in "quattro" theme always shows a padlock, which makes you think the post is private even when it is instead public.

**Comment by fabrixxm** [comment] 2015-06-25 08:25
Padlock icon is open when post is public, and closed when private
![padlock1](https://cloud.githubusercontent.com/assets/309361/8350294/6efbbe6a-1b24-11e5-9b79-2c40de2a7729.jpg)

maybe could be more evident, like this?
![padlock2](https://cloud.githubusercontent.com/assets/309361/8350301/7f00e150-1b24-11e5-9e14-383f2bf4e48c.jpg)

**Comment by strk** [comment] 2015-06-25 08:48
The one I see is the closed one. I just double checked.

**Comment by fabrixxm** [comment] 2015-06-25 08:58
that could be because you have some default privacy settings?

**Comment by strk** [comment] 2015-06-25 09:05
I've set a default to only show items to a group, recently. I'm not sure if this specific post was posted before or after the change. But when I look at the post from my status page there's no padlock there, and I do can see that post from an anonymous window, so it's clearly public.

See also #1656 which is related (not enough info given about posts privacy)

**Comment by vinzv** [comment] 2019-08-19 23:33
Is this still relevant? Or can we close the issue?

**Comment by annando** [comment] 2019-08-20 03:57
The system still behaves identically, so the issue isn't solved. Possibly @fabrixxm can decide whether to close this, since this is his theme.

P.S: Thanks for working through the old issues!

**Comment by fabrixxm** [comment] 2019-08-20 08:47
I quick tested it on `2019.09-rc` and it works correctly.
But I would  say that quattro it's quite unsupported  (by me, at least)

**Comment by MrPetovan** [comment] 2019-08-20 09:18
Clo-sing.

**Closed by MrPetovan** 2019-08-20 09:18 UTC
