### ISSUE TITLE
[frio] Permissions missing for mobile photo upload

### ISSUE THREAD

**Issue by danielbierstedt** [friendica/friendica#6458] opened 2019-01-17 12:04 UTC
### Expected behavior
Upload photo into folder, select to share with text

### Actual behavior
- When uploaded, a photo is marked as "private message". The post is being shared, but the image is missing to the public. I need to go back to the image and change access permissions from "nothing" (?) to "public"
- Image with meta data description cannot be selected. When clicking on the image, the description pops up. Another click hides the description. That way, its impossible to select that image for sharing.

### Friendica version you encountered the problem
2018.09

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
zip

### PHP version
7.0

**Comment by danielbierstedt** [comment] 2019-01-17 12:19
Ok, I see its most likely an issue of theme "Frio"

**Comment by danielbierstedt** [comment] 2019-01-19 11:03
I'm sorry, but this is not about missing permissions.

The issue is: due to the layover of embedded description, I am not able to select the image. The layover takes the whole window (if there is enough text).

**Comment by AlfredSK** [comment] 2019-01-19 12:43
By "layover" do you mean the name of the image file that is shown as some dark overlay? If so, that is fixed in the current release candidate. You can click through that overlay now to select the image for sharing.

**Comment by MrPetovan** [comment] 2019-01-19 13:07
Duplicate of #5968, closing.

**Closed by MrPetovan** 2019-01-19 13:07 UTC
Labels: UI/Theme, UX
