### ISSUE TITLE
Auto-Search is broken

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7406] opened 2019-07-18 16:24 UTC
Searching without pressing <enter>  in your contacts does deliver not all possibilities. If you press <enter> you will get the contact you search.

If you try to write a restricted post at the moment, you are lost,, because pressing <enter>  sends the post. And you have no possibility to set the right permission if the search doesn't find your contact.

This is tested on Frio and Vier

### Friendica version you encountered the problem
GIT/Develop/MariaDB/PHP7.2

**Comment by MrPetovan** [comment] 2019-07-18 16:35
This isn't new, @rabuzarus said it was because we don't cache all contacts for auto-search. I suggested we remove the feature entirely because it is confusing but he insisted on keeping it. See https://github.com/friendica/friendica/pull/5201

**Comment by AlfredSK** [comment] 2019-07-18 16:42
I would help a lot when pressing Enter in the ACL search field of the compose-post-modal would NOT send the post but trigger a search.

**Comment by MrPetovan** [comment] 2019-07-18 16:46
We're talking about the contact page search field, not the compose modal. At least the ACL search field returns all the expected results.

**Comment by AlfredSK** [comment] 2019-07-18 16:48
Yes, maybe... but:

> If you try to write a restricted post at the moment, you are lost,, because pressing sends the post. 

Sounds like @hoergen is talking about writing a post.

**Comment by MrPetovan** [comment] 2019-07-18 16:55
Fair enough, maybe both searches are broken.

**Comment by rebeka-catalina** [comment] 2019-07-18 17:00
I have also problems when I want to set permissions of a post. Not all my contacts are listed in the permission dialog. This isn't really new... already since a year or longer from time to time contacts used to be inaccessible in this dialog, but they reappear after a few hours. Today I miss a lot of my contacts the whole day and I as far as I see constantly the same contacts are missing.

**Comment by MrPetovan** [comment] 2019-08-24 16:32
What I propose we do:
- Remove contact auto-completion
- Actively prevent Enter from submitting the post with either the modal or the Compose page (the issue is similar)

**Comment by MrPetovan** [comment] 2019-08-26 10:39
Both parts have been addressed, closing.

**Closed by MrPetovan** 2019-08-26 10:39 UTC
Labels: Bug, UX

**Comment by rabuzarus** [comment] 2021-01-16 02:13
> This isn't new, @rabuzarus said it was because we don't cache all contacts for auto-search.

This isn't correct.
For autosearch in the contact page there were three limitations.
1.) There were some problems if the contact did contain (or begin - I didn't remember) Emojis
2.) The user needs to type at least 3 letters before the search starts (this was done to improve the speed through limiting the database results)
3.) The search was limited through the queries in this function https://github.com/friendica/friendica/blob/develop/view/theme/frio/theme.php#L254

If the `function frio_acl_lookup()` outputs results the contact filtering should work

**Comment by rabuzarus** [comment] 2021-01-16 02:16
BTW: the global contacts search (if you search for a contact in the navbar) does have a `cache` issue. Because global contact could contain hundred thousands of contacts we limit the number of results in the database query
