### ISSUE TITLE
Notification URLs/redirection broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8173] opened 2020-01-26 11:16 UTC
### Expected behavior
When I go to .../notifications/system or .../notifications/home or .../notifications/network and I click on one of listed notifications the page should open in the same browser window/tab and show the related content.  

### Actual behavior
When I go to .../notifications/system or .../notifications/home or .../notifications/network and I click on one of listed notifications the page opens in a new/second browser window/tab.
This behavior is especially bad when you use Friendica as webapp on mobile devices.

### Steps to reproduce the problem
Go to e.g. .../notifications/network and click on one of the links.

### Friendica version you encountered the problem
2020.03-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by nupplaphil** [comment] 2020-01-26 11:49
Surely caused by #8155

**Comment by nupplaphil** [comment] 2020-01-26 13:10
Should be fixed with #8174

**Closed** 2020-01-26 13:47 UTC
Labels: Bug
