### ISSUE TITLE
Error 404 in frontend after git pull

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#5432] opened 2018-07-21 04:26 UTC
### Expected behavior
The page should be loaded
### Actual behavior
The requested URL /network was not found on this server.
### Steps to reproduce the problem
after git pull 2018.07.21 4AM
### Friendica version you encountered the problem
2018-8
### Friendica source (git, zip)
git
### PHP version
7.2.7-0ubuntu0.18.04.2
### SQL version
5.5.5-10.1.29-MariaDB-6

**Comment by tobiasd** [comment] 2018-07-21 05:06
can you have a look into the log files (Friendica and PHP log) to see if something is mentioned in there.

Do other URLs (e.g. `/admin`, `/settings` or `/friendica`) work?

**Comment by annando** [comment] 2018-07-21 05:46
This is the cause of PR https://github.com/friendica/friendica/pull/5428

Please copy the .htaccess from the default file. Or wait until the PR https://github.com/friendica/friendica/pull/5435 is merged and pull again.

**Comment by MrPetovan** [comment] 2018-07-21 11:34
Closed via #5435

**Closed by MrPetovan** 2018-07-21 11:34 UTC
Labels: Bug
