### ISSUE TITLE
Page not found - Contact Groups: Everybody

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6243] opened 2018-12-08 18:19 UTC
### Expected behavior
When I go to 'Contacts' -> 'Groups' there is a box on the left side to select a group.
Clicking on 'Everybody' should show all contacts.

### Actual behavior
I get a page not found error.

### Friendica version you encountered the problem
2018.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by MrPetovan** [comment] 2018-12-09 06:03
Caused by #5891

Fixed by the pending commit https://github.com/friendica/friendica/pull/6238/commits/9820d1308c9a821bca211425f2f9d871ce60046e

**Closed by MrPetovan** 2018-12-09 06:03 UTC
Labels: Bug, UX
