### ISSUE TITLE
Memcache is failing

### ISSUE THREAD

**Issue by ingoj** [friendica/friendica#4543] opened 2018-03-04 12:38 UTC
In friendica 3.5.4 I used the following setup for memcache: 

// for memcache
$a->config['system']['memcache'] = true;
$a->config['system']['memcache_host'] = "127.0.0.1";
$a->config['system']['memcache_port'] = 11211;

This is now failing in 3.6-rc with this error: 

2018-03-04T12:36:02Z@v59q8reejadgjr7nrnpjm8cot3 [TRACE]:MemcacheSessionHandler.php:50:read      no data for session v59q8reejadgjr7nrnpjm8cot3
2018-03-04T12:36:05Z@08c4n1btvsl3u1g323av80sgd2 [TRACE]:MemcacheSessionHandler.php:50:read      no data for session 08c4n1btvsl3u1g323av80sgd2
2018-03-04T12:36:07Z@rl227khjrmv74lik70n271er15 [TRACE]:MemcacheSessionHandler.php:50:read      no data for session rl227khjrmv74lik70n271er15

This results in being unable to login. When already logged in, you'll be prompted with the login page as well.

**Comment by MrPetovan** [comment] 2018-03-04 13:15
Thanks for the report, I’ve similar issues but I was chalking them to a flaky memcache install. At least now I know that it may have something wrong with our code.

**Comment by ingoj** [comment] 2018-03-04 13:38
I've tested it with two memcached instances. Both were not working. I think it's normal that you need to login again after enabling memcache or changing memcache servers, but when login after a forced page reload with saved login credentials from password manager is not working, then something is broken... ;-)

**Comment by MrPetovan** [comment] 2018-03-04 13:56
Indeed, thanks for testing further.

**Comment by annando** [comment] 2018-03-04 15:17
I had problems as well, but I thought it was related to my Debian update.

**Comment by MrPetovan** [comment] 2018-03-04 18:01
I've been testing for about 30 minutes without issues so far, I thought it could have been a problem with the expiration, but it doesn't seem to be the problem.

**Comment by ingoj** [comment] 2018-03-04 18:34
Are you using php-fpm (I do)? Just a guess...

**Comment by MrPetovan** [comment] 2018-03-04 18:41
No, I'm using the Apache 2 SAPI, but I used to have persistence issues as well. Of course, now that I am intensely scrutinizing the process it works flawlessly, otherwise it wouldn't be fun I suppose.

**Comment by ingoj** [comment] 2018-03-04 18:50
On Debian with php-fpm there is /etc/php/7.0/fpm/pool.d/www.conf and in there the pool is defined within the pool definition: 

; Start a new pool named 'www'.
; the variable $pool can be used in any directive and will be replaced by the
; pool name ('www' here)
[www]

So, when there's something with the pool wrong, then this might get triggered by 3.6-rc, but this is just a wild guess...

**Comment by MrPetovan** [comment] 2018-03-04 18:53
I'm not familiar enough with php-fpm to formulate any solid hypothesis. My first thought would be that it shouldn't matter whether the session is managed by PHP or Memcache as we are using the built-in session handler interface. If you didn't have trouble with php-fpm and native sessions, you shouldn't have trouble with Memcache either. Conversely, if you had problems with native sessions, then using Memcache won't improve things.

**Comment by ingoj** [comment] 2018-03-04 19:02
I'm using php-fpm and memcache with Wordpress and Drupal as well, which is still working. And it was working before the upgrade from 3.5.4 to 3.6-rc. 
Maybe someone else has more experience with php-fpm and memcache and has some ideas....

**Comment by MrPetovan** [comment] 2018-03-04 19:13
I definitely changed something between 3.5.4 and 3.6-rc, we moved from the global functions session handler to the class-based approach, and it's been working for the database handler. I agree something is up with the Memcache handler, but I'm still waiting for an error on my server.

**Comment by MrPetovan** [comment] 2018-03-04 20:34
More than 3 hours ago, I've had no forceful session logout. On Debian I did:
````
$> apt install php-memcache
$> /etc/init.d/memcached start
$> /etc/init.d/apache2 reload
````
Can you try to restart the `memcached` and `php-fpm` services just to be on the safe side?

**Comment by ingoj** [comment] 2018-03-04 20:54
Does a full server reboot qualify as well? (there was a kernel update pending today, so I rebooted everything) 

But still no login possible: 

vserv1# apt install php-memcache
Reading package lists... Done
Building dependency tree
Reading state information... Done
php-memcache is already the newest version (3.0.9~20160311.4991c2f-5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
vserv1# /etc/init.d/memcached restart
Restarting memcached: memcached.
vserv1# /etc/init.d/apache2 reload
[ ok ] Reloading Apache httpd web server: apache2.
vserv1#

I even tested in a different browser (Safari instead of FF). No change.

**Comment by MrPetovan** [comment] 2018-03-04 21:51
Wait, if you are using php-fpm you probably need to restart it as well, I believe it would be
```
$> /etc/init.d/php-fpm reload
```
Or something close (restart instead of reload maybe).

A full server reboot isn't really indicative if memcached isn't started on boot for example.

Does the database session handler works? Do you have SSL enabled for your domain? Is it enabled as well in the admin settings? The session cookie wouldn't be set if you had the SSL setting enabled but your domain wasn't SSL-enabled.

**Comment by MrPetovan** [comment] 2018-03-04 22:14
Just set `$a->config['system']['memcache'] = false;`

**Comment by MrPetovan** [comment] 2018-03-05 00:40
About 7 hours later, still no sign of failure, I'm about to say the dreaded "It works on my machine". If someone else can test Memcache on Debian and report on it I'd be grateful.

**Comment by ingoj** [comment] 2018-03-05 17:29
Ok, now it becomes strange... 

When I was trying to login from work I was unable to do so, despite whether or not memcache was set to true or false: I was unable to login from FF nor Safari nor Chrome. I even tested from X2go session on my server with FF. No luck. 

When I reset my password I was able to login from work. I then changed the password back to the previous one and activated memcache and it worked as well. 
Now I'm back home and tried again with my logged-in session from this morning before I went to work and I was prompted for login. No surprise here, but when I entered my credentials, I was able to login here as well. 

For me everything seems to work. But it is still unclear what happened. 
Best guess so far is a confused memcache, which expired my old session credentials somewhen when I was at work.  No idea if this is a valid guess... 
I'd recommend to close this bug report after 48 hrs when no other update stating that it's not working again. ;)

**Comment by MrPetovan** [comment] 2018-03-05 19:29
You can close this issue yourself, and reopen it if it fails again.

**Comment by tobiasd** [comment] 2018-03-06 17:09
Mmh, the issue is for the 3.6 milestone, but the PRs have gone into develop to fix the issue, do I see that correct?

**Comment by MrPetovan** [comment] 2018-03-06 18:27
No, there's a small but subtle difference between fixing a Memcache_ issue and adding support for Memcache**d**.

**Comment by tobiasd** [comment] 2018-03-07 05:42
Ok, if you say so :-)

**Comment by MrPetovan** [comment] 2018-03-07 17:48
Closing for now.

**Closed by MrPetovan** 2018-03-07 17:48 UTC
Labels: Bug, Performance
