### ISSUE TITLE
frio: hover windows don't vanish as expected

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7131] opened 2019-05-11 14:39 UTC
### Expected behavior
When you hover over a contact avatar a small popup windows shows up. When you leave the hover zone or click/tap somewhere else that popup should vanish instantly.

### Actual behavior
The hover popup doesn't vanish. Even when you click/tap somewhere else it stays open. It's difficult to make it go away again. That's annoying.

### Steps to reproduce the problem
Hover with your mouse over a contact avatar. Try to get rid of the popup.
That behavior started some time ago. It happens with Firefox and Chrome/Chromium on Linux and Android.

Discussion:
https://forum.friendi.ca/display/0b6b25a8-125c-d6b3-1da2-c6b355848187

### Friendica version you encountered the problem
2019.06-dev

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

**Comment by AlfredSK** [comment] 2019-05-11 22:04
Btw. you can hover over the avatars here on GitHub to see how it should work. :-)

**Comment by AlfredSK** [comment] 2019-05-12 19:52
I just noticed it works flawlessly in master.

**Comment by MrPetovan** [comment] 2019-05-21 13:44
From my personal experience, the secret to get rid of hovercards is to first hover the card itself and then to move your mouse out of it. No click necessary. The trick is that the hovercard appears above the profile name/picture where the mouse is, so until the mouse actually goes on the hovercard first, it will stay displayed.

Still needs to be polished probably, still hope it helps.

**Comment by AlfredSK** [comment] 2019-05-21 15:33
> From my personal experience, the secret to get rid of hovercards is to first hover the card itself and then to move your mouse out of it.

Yep. That works. But it is not intuitive. There are ~~a lot~~ some complaints about the current behavior in develop/rc because that behavior is unexpected.

The behavior here on Github and **on current master (!)** is much better. Hover in and out and the window appears and disappears.
On touch devices it's even worse. There you have to tap inside the hovercard and then outside the hovercard to make it disappear.

**Comment by MrPetovan** [comment] 2019-05-21 15:36
I'm sad and puzzled because I don't recall we willfully changed anything to the hovercard behavior since master. So it has to be a regression and it is never fun.

**Comment by AlfredSK** [comment] 2019-05-21 15:47
Could that be related to the changes that have been done concerning the Chrome onclick issue with the main (fake) comment box? I think the hover behavior changed around that time.

**Comment by MrPetovan** [comment] 2019-05-21 15:48
It's possible. No one on the team is either skilled or enjoy working on frontend Javascript, so this is going to be a big doozy.

**Comment by AlfredSK** [comment] 2019-05-21 15:49
I'm sorry. :-)

**Comment by nupplaphil** [comment] 2019-05-26 19:55
Should be fixed with #7194

**Comment by MrPetovan** [comment] 2019-05-27 11:53
Verified.

**Closed by MrPetovan** 2019-05-27 11:53 UTC
Labels: Bug, UI/Theme
