### ISSUE TITLE
RSS/Atom feed: Error fetching image: 403

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#8360] opened 2020-03-03 09:31 UTC
### Expected behavior
Adding https://www.heise.de/rss/heise-atom.xml as a contact should correctly show images in the retrieved posts.

### Actual behavior
Images are not shown, only placeholder string "Image/photo". Directly opening the image in another tab shows:

```
Interner Serverfehler

Eine unerwartete Situation ist eingetreten, zu der keine detailliertere Nachricht vorliegt.
#0 /var/www/friendica/src/Module/Proxy.php(113): Friendica\Module\Proxy::responseError()
#1 [internal function]: Friendica\Module\Proxy::init(Array)
#2 /var/www/friendica/src/App/Module.php(271): call_user_func(Array, Array)
#3 /var/www/friendica/src/App.php(571): Friendica\App\Module->run(Object(Friendica\Core\L10n), Object(Friendica\App\BaseURL), Object(Friendica\Util\Logger\VoidLogger), Array, Array)
#4 /var/www/friendica/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\App\Authentication), Object(Friendica\App\Page))
#5 {main}
```

Opening the source image (as found in the debug.log) directly works.

### Steps to reproduce the problem
1. Add https://www.heise.de/rss/heise-atom.xml as contact
2. "update now" contact to retrieve posts
3. inspect posts

### Friendica version you encountered the problem
develop branch pulled yesterday.

### Friendica source (git, zip)
git; on branch develop

### PHP version
PHP 7.3.11-0ubuntu0.19.10.3 (cli) (built: Feb 12 2020 15:22:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-0ubuntu0.19.10.3, Copyright (c) 1999-2018, by Zend Technologies

### SQL version
mysqld  Ver 5.7.29 for Linux on x86_64 (MySQL Community Server (GPL))

### debug.log excerpt
```
2020-03-03T09:09:44Z index [WARNING]: error: https://heise.cloudimg.io/width/450/tjpeg.q80.webp-lossy-80.foil1/_www-heise-de_/imgs/18/2/8/5/4/3/9/0/ss_fcc7a64234b8b26cac3d69dfc4779dd438582f15-f47e540b893035fc.jpeg: 403 -  [] - {"file":"CurlResult.php","line":169,"function":"checkSuccess","uid":"09c6e0","process_id":3451}
2020-03-03T09:09:44Z index [INFO]: Fetched for user 1 from https://www.heise.de/scale/geometry/450/q80//imgs/18/2/8/5/4/3/9/0/ss_fcc7a64234b8b26cac3d69dfc4779dd438582f15-f47e540b893035fc.jpeg returned 403 [] - {"file":"HTTPSignature.php","line":469,"function":"fetchRaw","uid":"09c6e0","process_id":3451}
2020-03-03T09:09:44Z index [INFO]: Error fetching image {"image":"https:\/\/www.heise.de\/scale\/geometry\/450\/q80\/\/imgs\/18\/2\/8\/5\/4\/3\/9\/0\/ss_fcc7a64234b8b26cac3d69dfc4779dd438582f15-f47e540b893035fc.jpeg","return":403,"empty":false} - {"file":"Proxy.php","line":112,"function":"init","uid":"09c6e0","process_id":3451}
2020-03-03T09:09:44Z index [INFO]: http_status_exit 500 [] - {"file":"System.php","line":116,"function":"httpExit","uid":"09c6e0","process_id":3451}
```

**Comment by wiwie** [comment] 2020-03-18 18:41
The problem only occurs with chromium on Android.

Firefox and Firefox preview work fine.

So I guess the issue can be closed?

**Comment by wiwie** [comment] 2020-03-18 18:58
This is a weird issue: if I browse the affected posts the first time with chromium or Firefox in Android the images are broken. As soon as I open the posts with Firefox preview on Android the images show, and even do they show then in all tested browsers.

**Comment by wiwie** [comment] 2020-03-19 21:43
Further investigation reveals, that the images that were not working are a redirect to cloudfront, which is then returning 403:

```
2020-03-19T21:21:35Z index [DEBUG]: https://heise.cloudimg.io/width/450/tjpeg.q80.webp-lossy-80.foil1/_www-heise-de_/imgs/02/2/8/6/0/3/1/9/image-1575550227322832-f39116029907b064.jpeg: 403 HTTP/2 403 
server: CloudFront
date: Thu, 19 Mar 2020 21:21:35 GMT
content-type: text/html
content-length: 915
x-cache: Error from cloudfront
via: 1.1 36977a8510529cb59322504bc8295469.cloudfront.net (CloudFront)
x-amz-cf-pop: CPH50-C1
x-amz-cf-id: utqJFrDw70CPOzFqlgWBLnbSoIuxPD3rdNgGcYmqE9KCO1ZsM7EUjA==

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: utqJFrDw70CPOzFqlgWBLnbSoIuxPD3rdNgGcYmqE9KCO1ZsM7EUjA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML> [] - {"file":"CurlResult.php","line":133,"function":"__construct","uid":"ff983c","process_id":14085}
```

Some digging in the friendica code led me to the following snippet in Util/Network.php:

```
                // These settings aren't needed. We're following the location already.
                //      @curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
                //      @curl_setopt($ch, CURLOPT_MAXREDIRS, 5);
```

Uncommenting the line that sets CURLOPT_FOLLOWLOCATION to true fixes the issue for me. So the comment above the statement does not seem to be true entirely?

Also, I don't understand why it did work in some browsers on Android but not others.

**Comment by MrPetovan** [comment] 2020-03-19 22:47
I believe we're following the location manually, meaning that we're calling the Network::fetch method recursively if we get a redirection location?

**Comment by wiwie** [comment] 2020-03-20 19:08
Hm okay. Well i could see in the debug output that one redirect is being followed and the second request then goes to cloudfront where the 403 error occurs.

Maybe in your Manuel redirect handling something is not handled or forwarded correctly? I'm no expert in this area, so I'm not sure how redirects are supposed to be handled...

Also, I can't exclude the possibility that it has something to do with my nginx config for friendica, so maybe it could help if someone else tried to add said RSS feed to their instance as well.

Is there any debug info that I didn't paste in here yet that could help shed more light on this issue?

**Comment by hoergen** [comment] 2021-03-09 08:29
Is this still an issue? I tested some RSS feeds for showing the images and it worked. Can this issue be closed?

**Comment by wiwie** [comment] 2021-03-09 08:37
I'm no longer subscribing to feeds on friendica, so can't comment on whether it works now.

**Comment by hoergen** [comment] 2021-03-09 08:59
Since i can't reproduce this, are you ok, that we close it?

**Comment by wiwie** [comment] 2021-03-09 09:10
Yes

**Comment by hoergen** [comment] 2021-03-09 11:55
Thank you very much :+1:

**Closed by hoergen** 2021-03-09 11:55 UTC
