### ISSUE TITLE
[frio][mobile] Increase size of common controls on mobile devices 

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#12582] opened 2022-12-31 11:46 UTC
Using Friendica with Mastodon client apps works well for basic use cases but misses some functionality that's Friendica specific and available in the Web client. This, too, mostly works well on mobile devices but some of the core controls ("like", "comment", "share", "bookmark" are quite small on these screens and aren't really suitable for touch-driven operation. Increasing size of these controls really would ease using Friendica in auch environments and reduce the need or desire to use mobile apps instead.

**Comment by MrPetovan** [comment] 2022-12-31 15:18
Can you please provide screenshots of the small controls?

**Comment by kr428** [comment] 2022-12-31 15:24
Sure, see attached. Maybe just doubling this size would make it better...? Not sure whether that's easily doable. 

![Screenshot_20221231-162239_Brave](https://user-images.githubusercontent.com/685879/210141552-8c048701-442b-4612-95d3-f2a8492ce0a2.jpg)

**Comment by kr428** [comment] 2022-12-31 15:31
In comparison, similar controls in pixelfed which feel "safer" to use, maybe that would be an option too?

![Screenshot_20221231-162948_Brave](https://user-images.githubusercontent.com/685879/210143577-e8af26c7-f49b-4d40-87d8-4336d96242e7.jpg)

**Comment by MrPetovan** [comment] 2022-12-31 15:56
It is easy to double, but the issue is that it would be hard to keep all the buttons on the same line in threaded conversations (notice the narrower screen of my phone as well):
![DBF23CB5-1D0D-4587-8E3A-F9C1B510EEA6](https://user-images.githubusercontent.com/925415/210148882-9c584777-5614-47d2-a827-495a8d157b7f.jpeg)
Imagine the optional “Dislike” button and we can’t double the size even at the first reply level.

**Comment by kr428** [comment] 2022-12-31 16:03
Maybe then it would already help to make the "button" style more visible at least on dark themes? Comparing the screenshots, yours already looks more accessible for finger-pointed input than mine... 🙂

**Comment by MrPetovan** [comment] 2022-12-31 16:12
Of course, not sure what I should change, mock-ups would help.

**Comment by foss-** [comment] 2023-01-01 23:24
Dupe of https://github.com/friendica/friendica/issues/9201?

**Comment by MrPetovan** [comment] 2023-01-02 00:00
Not sure, it's related but yours was about the desktop display, this is about the mobile display.

**Comment by foss-** [comment] 2023-01-02 00:36
Hmm, I think the four suggestions about interaction icons apply to both desktop and mobile.

**Comment by MrPetovan** [comment] 2023-01-02 00:37
They need different mock-ups and changes in different places so it's enough to keep them separate.

**Comment by kr428** [comment] 2023-01-02 06:17
I'll try to come up with some mockups then, not sure I'm really good at this tough. Suggestion, in "words", would be to make these interaction fields in mobile look more like "buttons" than like simple icons. In example take the pixelfed screenshot above (visible border and background around the "fave" / "comment" icon) whereas in both my and your Friendica screenshot, there's no border at all and contrast between "button" background and "page" background seems fairly unnoticeable at least on mobile.

**Comment by damianwajer** [comment] 2023-01-20 17:32
+1
I've made the clickable area of these icons a little larger in https://github.com/friendica/friendica/pull/12699 but not yet enough IMO (to avoid the issue with breaking them into two lines in threaded conversations).

One solution could be to move additional icons to the "more" dropdown. Maybe just the "share via" icon to make enough space to increase the size of the rest. If it will be only "share via", it makes sense to put it in the dropdown where other share actions are (with "Reshare" and "Quote share").

**Comment by foss-** [comment] 2023-01-20 18:36
@damianwajer can you share a screenshot of what the icons look like after your patch?

Cross-linking my update: https://github.com/friendica/friendica/issues/9201#issuecomment-1398784211

**Comment by damianwajer** [comment] 2023-01-20 18:56
@foss- Sure:

![social icons](https://user-images.githubusercontent.com/8630866/213544934-432c65fb-c205-43ec-b29b-61eb77faa959.png)

(Screens with my changes are also in the PR: https://github.com/friendica/friendica/pull/12699)

Please note that this is just the first post, not a threaded comment, which has less space. There can also be a "spinner" icon, which shows up only for a moment and has almost the same size as a social icon.

**Comment by MrPetovan** [comment] 2023-01-20 19:20
My desire to remove the dislike feature intensifies.

**Comment by foss-** [comment] 2023-03-26 20:12
Icon placement has been changed so they are evenly spread on the available width and size has been increased. I think this can be closed.

See also:
https://github.com/friendica/friendica/issues/12835
https://github.com/friendica/friendica/issues/9201

**Comment by MrPetovan** [comment] 2023-03-26 20:14
Closed by #12836

**Closed as completed by MrPetovan** 2023-03-26 20:14 UTC
Labels: Theme-specific, Mobile, Enhancement, UI
