### ISSUE TITLE
addon: js_upload sets wrong permission on uploaded images

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7888] opened 2019-12-01 19:57 UTC
### Expected behavior
When default permission is set to public and permission in upload dialogue is set to public a uploaded photo should also have permission set to public.

### Actual behavior
When default permission is set to public and permission in upload dialogue is set to public a uploaded photo has permission set to 'limited/followers' after the upload.
That only happens with 'js_upload'. Without the add-on it works as expected.

### Steps to reproduce the problem
Enable 'js_upload'.
Set your default permission to 'public'.
Go to .../photos/$user/upload.
Check permission by clicking on the permissions button. It is set to 'public'. Great.
Now upload an image.
After the upload check the permissions of the uploaded image (frio: you will see a lock!)
The permission is set to 'limited/followers'.

### Friendica version you encountered the problem
2019.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment] 2019-12-01 20:04
Just to make it clear - when you upload an image while composing a post everything works. Also w/o 'js_upload' everything works as expected. The issue only exists when the upload is processed by the add-on.

**Comment by MrPetovan** [comment] 2019-12-01 20:27
Oooh, right, I know why it’s doing this.

**Comment by MrPetovan** [comment] 2019-12-01 21:36
Fixed by https://github.com/friendica/friendica-addons/pull/915

**Closed** 2019-12-02 04:53 UTC
Labels: Addons, Bug, UX

**Comment by MrPetovan** [comment] 2019-12-02 09:38
Caused by #914
