### ISSUE TITLE
Sticky/pinned post for timeline and forums

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5026] opened 2018-05-11 06:27 UTC
I would love to have a sticky/pin feature for posts for every profile and forums that can be set by the profile or the forum owner. It should have  a symbol,background color, or something that you immediately recognize, that this is a sticky/pinned post.

On a profile this can be used to point out some information you want to focus a visitor on your profile.

On a forum it can be used to post important information about the forum, like actions members have to do, link to the code of conduct, Forum rules, etc.

**Comment by wiwie** [comment] 2020-03-26 22:58
I think this issue and #4828 are partly describing the same things. Should they be consolidated?

Apart from that, I'm also missing said features. I would really like to have the option to pin some posts to my profile page instead of or additionally to the box with all the non-federated user information. I looked into where this could maybe be done and discovered the profile_advanced hook. Could this one be used to attach posts to the profile?

**Comment by annando** [comment] 2020-03-26 23:10
On the profile page you can already pin posts.

**Comment by wiwie** [comment] 2020-03-26 23:24
Really, how? I can't find it. I'm using the Frio theme.

**Comment by wiwie** [comment] 2020-03-26 23:29
Ok I think you mean under the profile status? I didn't mean the posts there. But rather directly on the profile. Together with all the information that describes who the person is, like nationality, age, and so on.

**Comment by MrPetovan** [comment] 2020-03-27 05:33
In Friendica you do not need to pin statuses to your profile for information complements since last release. The new custom profile fields are unlimited in size and accept BBCodes, so anything you'd like to put in one or more "pinned profile posts" like in Mastodon can be put in one or more custom profile fields.

**Comment by AlfredSK** [comment] 2020-03-27 06:05
> Really, how? I can't find it. I'm using the Frio theme.

RC: ···More menu -> Pin post
Master: Action menu (top-right corner) -> Pin post

**Comment by wiwie** [comment] 2020-03-27 09:08
@MrPetovan okay. But why not just allowing posts there instead? Then one could pin posts of other people as well and could show comments also.

**Comment by MrPetovan** [comment] 2020-03-27 12:01
Because it wouldn't make sense. You're essentially asking to replicate a behavior that exists on Mastodon because it doesn't have a dedicated profile page and posts limited to 500 characters by default. None of these apply to Friendica so there's no reason for us to go out of our way to implement what is a workaround on Mastodon even though we have different constraints.

**Comment by wiwie** [comment] 2020-03-27 15:49
I don't see what Mastodon has to do with my question. I'm asking to extend friendicas feature set, as the two things I talked about are not possible with friendicas custom profile fields. Such fields can't be discussed with or commented on by others, or can they? and can I pin posts of others, such as one of my organisations or such, to my profile? This would be cool in my eyes, can make sense and has nothing to do with how Mastodon does it. 

Apart from that splitting profile fields and pinned posts/status up into two different tabs doesn't really allow to send one link around that gives the whole picture and people I sent the link to have to click around to find stuff themselves. I don't think that corresponds very well to the term of a  profile page.

**Comment by annando** [comment] 2020-03-27 16:51
Since this discussion leads away from the topic (pinning of posts in the timeline and for forum posts), I suggest creating a new issue for this.

**Comment by tobiasd** [comment] 2020-03-27 21:37
With the upcoming 2020.03 release, you will only have custom profile fields basically (some fields are still fixed).

**Comment by MrPetovan** [comment] 2020-03-28 03:57
Duplicate of #4077
Closed by #7823

@wiwie Please open separate issues for pinning posts on the profile page and for pinning posts by someone else.

**Closed by MrPetovan** 2020-03-28 03:57 UTC
Labels: Enhancement, New Feature, UX
