### ISSUE TITLE
How far Community view goes back?

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#10358] opened 2021-06-01 23:10 UTC
There are times when I can scroll back two weeks and times much shorter.  Today I can go back only two hours.  My machine isn't anywhere near out of space either in the data base or any of the file systems.  Is there a way I can allow friendica to store and show more messages?

**Comment by MrPetovan** [comment] 2021-06-09 00:00
From #10382
> Can someone elaborate as to friendica's message and image retention policy? Sometimes I can go back 4 hours, sometimes a month, I can't figure out what the cause of this variability. Is there any way to make the retention period longer so I can scroll back further?

**Comment by MrPetovan** [comment] 2021-06-12 10:58
Closed as duplicate of #10382 since conversation is taking place over there.

**Closed as completed by MrPetovan** 2021-06-12 10:58 UTC
