### ISSUE TITLE
Multiple admin notification mails

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6788] opened 2019-03-01 21:44 UTC
### Expected behavior
When a notification mail is sent to the mail address of the admin it should be one mail.

### Actual behavior
When a notification mail is sent that mail is sent two, four, six, eight or 244 times.

### Steps to reproduce the problem
I have two admin accounts with two different mail addresses. So, I understand that each mail is sent twice. But when a user deletes his/her account I often get 4 ,6 or 8 mails about it.
Today the database structure was updated to version 1304 and I got **244** admin notification mails about the update.

This behavior has been confirmed by another node admin in our XMPP chat room. He got 50+ mails about the DB update.

### Friendica version you encountered the problem
2019.03-rc

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

**Comment by MrPetovan** [comment] 2019-03-01 21:55
Confirmed, I got only 4 emails about it.

**Comment by nupplaphil** [comment] 2019-03-01 23:11
Possibly a side effect of #6773 that the mail sending for updates are generally fixed again.

**Comment by MrPetovan** [comment] 2019-03-02 04:49
Ive only been notified once about the update from database version 1303 to 1304.

**Comment by AlfredSK** [comment] 2019-03-02 09:32
Yeah. For the DB update on the forum node I got only one mail, too. The forum node has only one admin account. Maybe that's part of the general problem. Or it has something to do with the time the updates takes. I don't know.

Forum node: 1 admin account, DB update took 10 seconds -> 1 notification mail
Libranet node: 2 admin accounts, DB update took 25 minutes -> 244 notification mails

Both nodes are running on the same server. So, I would rule out a mail config problem.

**Comment by annando** [comment] 2019-03-02 12:35
This line is responsible: https://github.com/friendica/friendica/blob/develop/src/Core/Update.php#L209

This will send out a mail to every user account with the mail address of an administrator - which will include all subpages.

**Comment by nupplaphil** [comment] 2019-03-02 12:39
But I already replaced it in 2019.03-RC with: https://github.com/friendica/friendica/blob/2019.03-RC/src/Core/Update.php#L212

**Comment by annando** [comment] 2019-03-02 12:40
The problem is the same.

**Comment by MrPetovan** [comment] 2019-03-02 14:02
This isn't consistent though, I received four emails from my test install where I have only one user account at all.

**Comment by MrPetovan** [comment] 2019-03-02 14:36
Closed by #6790

**Comment by MrPetovan** [comment] 2019-03-03 13:56
I just got six emails for the update from database version 1303 to 1304 after having pulled the RC branch.

**Comment by realkinetix** [comment] 2019-03-04 16:19
I received 4 copies of the email notification for the DB update from 1303 to 1304 when I pulled yesterday, but hadn't updated the RC branch in about 4 days.

**Comment by nupplaphil** [comment] 2019-03-04 17:27
I think that's a Update check issue.

**Comment by MrPetovan** [comment] 2019-03-09 21:00
Hopefully fixed with #6842

**Comment by MrPetovan** [comment] 2019-03-09 23:30
No dice: After pulling #6842, I've been constantly receiving successful update emails for an update that was already done. Received 35 emails and counting in about 4 minutes. How do I stop the madness?

**Comment by AlfredSK** [comment] 2019-03-09 23:36
apt remove postfix ;-)

service postfix stop
postsuper -D ALL

**Comment by MrPetovan** [comment] 2019-03-09 23:36
Ha ha! It won't prevent Friendica from trying to send more emails though.

**Comment by nupplaphil** [comment] 2019-03-10 22:58
At least I now know what happened.. The git pull on my node of the failed/catastrophic PR wasn't pulled because of a missing escape of the branch, so I tested it with the last 2019.03-RC branch..

**Comment by nupplaphil** [comment] 2019-03-11 20:17
Let's have a look at #6858 ...

**Comment by nupplaphil** [comment] 2019-03-12 06:41
@AlfredSK and @MrPetovan .. Plz have a look again ..

**Comment by AlfredSK** [comment] 2019-03-12 09:57
I'd like to have a look again. But how? I cannot update the node again.

**Comment by nupplaphil** [comment] 2019-03-12 12:09
I tried it with:
```SQL
UPDATE config set v = '1301' WHERE v = '1304';
```

**Comment by MrPetovan** [comment] 2019-03-12 13:17
I pulled the RC branch, crossing fingers.

**Comment by AlfredSK** [comment] 2019-03-12 13:24
@nupplaphil I did what you did. :-) After that I manually ran dbstructure update. The values are back to 1304. DB update successful.

````
MariaDB [mordor]> select k,v from config where v = 1301;
+------------------------+------+
| k                      | v    |
+------------------------+------+
| build                  | 1301 |
| last_successful_update | 1301 |
+------------------------+------+
2 rows in set, 139 warnings (0.00 sec)

MariaDB [mordor]> select k,v from config where v = 1301;
Empty set, 139 warnings (0.00 sec)

MariaDB [mordor]> select k,v from config where v = 1304;
+------------------------+------+
| k                      | v    |
+------------------------+------+
| build                  | 1304 |
| last_successful_update | 1304 |
+------------------------+------+
2 rows in set, 139 warnings (0.00 sec)
````

But I got 0 (zero) mails. :-)

**Comment by MrPetovan** [comment] 2019-03-12 13:34
No email so far.

**Comment by MrPetovan** [comment] 2019-03-12 13:34
Closed via #6858

**Closed by MrPetovan** 2019-03-12 13:34 UTC
Labels: Bug

**Comment by AlfredSK** [comment] 2019-03-12 13:36
I thought it was intended to get _one_ mail about the successful update.

**Comment by MrPetovan** [comment] 2019-03-12 13:46
I'd rather get no emails than 350 emails, so this is progress!

**Comment by nupplaphil** [comment] 2019-03-12 14:04
hm .. retry it with loglevel `info` again.
I had an "email sent" log entry after each successful update...

At least I don't flood your postbox anymore :-/ ..

**Comment by AlfredSK** [comment] 2019-03-12 14:24
Well, yes. Zero is better than a mail firehose. :-)

I don't see a "email sent" entry in my log. I was on log level 'info' during the update.
I deleted all the lines about the individual table updates...

````
2019-03-12 13:21:35 console [INFO]: Update starting. {"from":1301,"to":1304} {"file":"Update.php","line":86,"function":"run","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:35 console [INFO]: Update function start. {"function":"pre_update_1302"} {"file":"Update.php","line":160,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:35 console [INFO]: Update function skipped. {"function":"pre_update_1302"} {"file":"Update.php","line":198,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:35 console [INFO]: Update function start. {"function":"pre_update_1303"} {"file":"Update.php","line":160,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:35 console [INFO]: Update function skipped. {"function":"pre_update_1303"} {"file":"Update.php","line":198,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:35 console [INFO]: Update function start. {"function":"pre_update_1304"} {"file":"Update.php","line":160,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:35 console [INFO]: Update function skipped. {"function":"pre_update_1304"} {"file":"Update.php","line":198,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:36 console [INFO]: Update finished. {"from":1301,"to":1304} {"file":"Update.php","line":123,"function":"run","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:36 console [INFO]: Update function start. {"function":"update_1302"} {"file":"Update.php","line":160,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:36 console [INFO]: Update function skipped. {"function":"update_1302"} {"file":"Update.php","line":198,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:36 console [INFO]: Update function start. {"function":"update_1303"} {"file":"Update.php","line":160,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:36 console [INFO]: Update function skipped. {"function":"update_1303"} {"file":"Update.php","line":198,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:36 console [INFO]: Update function start. {"function":"update_1304"} {"file":"Update.php","line":160,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:36 console [INFO]: Update function skipped. {"function":"update_1304"} {"file":"Update.php","line":198,"function":"runUpdateFunction","uid":"fcd81a9","process_id":21926}
2019-03-12 13:21:36 console [NOTICE]: Update success. {"from":1301,"to":1304} {"file":"Update.php","line":134,"function":"run","uid":"fcd81a9","process_id":21926}
````
