### ISSUE TITLE
Avatar not updated everywhere

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#3309] opened 2017-04-08 21:42 UTC
Hello,

I updated my avatar yesterday. It is correctly displayed on my profile but I still see the default avatar on my posts: https://social.rudloff.pro/profile/rudloff
(Also note that other instances do see the correct avatar.)

**Comment by AlfredSK** [comment] 2017-04-08 23:58
Confirmed.

**Comment by Hypolite** [comment] 2017-04-09 05:06
Hi @Rudloff and welcome on Friendica! Thanks for opening an issue about a recurring issue we have been having.

Technical notes: The problem I've experienced is a picture discrepancy between the public contact (uid=0) and the personal contact (uid=1). Since either are displayed in different parts of Friendica (for very good reasons), different avatars can show up.

A new example in two parts, Thomas Willingham changed his profile picture this morning, and even on his instance the picture of his public profile isn't updated, while the profile picture of his local account is.

![screen shot 2017-03-28 at 10 09 08 am](https://cloud.githubusercontent.com/assets/925415/24409702/fa1e531c-139e-11e7-87a3-adf472e7cb42.png)

A view from my instance:

![screen shot 2017-03-28 at 10 21 16 am](https://cloud.githubusercontent.com/assets/925415/24410155/5328da80-13a0-11e7-924e-2c041638e8ac.png)

**Comment by ben-utzer** [comment] 2017-04-09 12:42
My profile picture also show up with the placeholder on my local server in some places, this is since a few weeks. But I thought it might be linked to the PHP picture upload problem I have added as an [issue](https://github.com/friendica/friendica/issues/3291).

**Comment by Hypolite** [comment] 2017-04-09 13:25
@ben-utzer I've noticed as weel, and I don't think it's related since your uploaded avatar shows up in some places. I think it's the same issue as reported here.

**Comment by annando** [comment] 2017-06-03 13:15
Can someone test it again? I guess that the changes in pull request https://github.com/friendica/friendica/issues/3471 had solved this.

**Comment by annando** [comment] 2017-06-06 20:17
I now will close this. Hopefully this was fixed.

**Comment by rebeka-catalina** [comment] 2017-06-14 10:05
Please, reopen the issue. I'm exactly in this situation now - develop branch and actual code.

**Comment by ben-utzer** [comment] 2017-06-14 10:34
> Please, reopen the issue. I'm exactly in this situation now - develop branch and actual code.

What I tried was to select a new picture as avatar pictures, I selected the same one as before, but I think after this the problem seems to be solved. 

On joindiaspora.com nothing is updated, but that might be a problem of Diaspora, on squeet.me it looks fine.

**Comment by rebeka-catalina** [comment] 2017-06-18 07:52
On 2017.06.14, ben-utzer wrote:
> > Please, reopen the issue. I'm exactly in this situation now - develop branch and actual code.
> 
> What I tried was to select a new picture as avatar pictures, I selected the same one as before, but I think after this the problem seems to be solved. 

Strange - I didn't change any setting, but now it got updated in the
stream as well.

**Comment by annando** [comment] 2017-08-20 21:05
Sometimes it can be related to browser cache issues. Can someone confirm if this is still an issue?

**Comment by annando** [comment] 2017-08-31 08:29
Since no one complained again, I will close it now - again :-)

**Comment by MrPetovan** [comment] 2018-02-26 21:03
This happened again with my latest avatar see https://friendica.mrpetovan.com/display/ec054ce7195a9475b2a55be479550644

**Comment by ben-utzer** [comment] 2018-02-26 22:54
I hope this does not reopen the issue... It seems to work now, I can now after months see a correct profile picture of utzer@social.yl.ms on https://joindiaspora.com/people/409b3d8b46f6331b

Thanks @annando!

**Comment by MrPetovan** [comment] 2018-02-27 00:42
Pulled the latest `develop`  version, uploaded the same avatar, but the old one still isn't replaced in conversations: 
![double_avatar](https://user-images.githubusercontent.com/925415/36704182-2d678428-1b2d-11e8-8768-0829831aaeae.png)

**Comment by MrPetovan** [comment] 2018-02-27 01:32
It's getting better:
![double_avatar2](https://user-images.githubusercontent.com/925415/36705621-2186de5e-1b34-11e8-8d7b-14bba80fff5d.png)

**Comment by valvin1** [comment] 2019-02-24 10:25
i don't know if the same issue but users on mastodon (framapiaf) don't see my new avatar althought on friendica side it looks ok. is there a workaround to update it ?

**Comment by annando** [comment] 2019-02-24 11:05
We currently don't know why Mastodon is refusing these updates, since other AP systems like Pleroma don't have any problem.

**Comment by valvin1** [comment] 2019-02-24 15:51
It looks like the exchange in this [friendica's post](https://fed.sonnenmulde.at/display/b42a482c-185c-6c83-e656-653441786915) and the [Issue on mastodon](https://github.com/tootsuite/mastodon/issues/1303) are linked.

If the picture url is the same, mastodon doesn't update the picture. 

And if I refer on the [exchange about my profile](https://social.tcit.fr/@tcit/101646693904650207) it looks like we have only one url and with a strange formatting.

**Comment by annando** [comment] 2019-02-24 17:49
Normally the URL should be different after each change.

**Comment by lapo-luchini** [comment] 2019-03-27 18:12
I've checked my URL changes each time I change picture, but Mastodon is still using the old (default) one. :-/

**Comment by valvin1** [comment] 2019-03-27 18:56
Definitively it looks like this issue is on mastodon side. My avatar had to be updtaded manually by administrator on the instance where i did test before adding an avatar.

**Comment by lapo-luchini** [comment] 2019-06-21 07:45
Switching from stable to latest rc (cb5a30218d497f3adf678605cec17e8ed5c18ee5) seems to have fixed this for me.

(Maybe related to #6477?)

**Comment by MrPetovan** [comment] 2019-06-21 12:18
I'll close for now, thanks for the follow-up!

**Closed by MrPetovan** 2019-06-21 12:18 UTC
Labels: Bug

**Comment by annando** [comment] 2019-06-21 17:08
@lapo-luchini this should had been fixed since - at least - somewhere last year. Since that time we fetch the contact url from the public contact.

**Comment by lapo-luchini** [comment] 2019-06-22 14:49
@annando I'm not sure about that: I can confirm I changed avatar (with the same image, but re-uploads) a few times in the last month using 2019.04 and it never changed on Mastodon, as soon as I upgraded to latest rc and changed avatar again, it was immediately visible on a Mastodon instance that had my previous "default avatar" cached.

**Comment by annando** [comment] 2019-06-23 09:44
@lapo-luchini we are speaking of different issues. I referred to the original issue which was only some local issue on the same machine.
