### ISSUE TITLE
remote subscribe to GNUSocial account fails

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1665] opened 2015-06-13 09:00 UTC
I"ve been trying with no luck to remote subscribe to a GNUSocial account from a Friendica node I installed from master (beb4980f020e09625357114159a860f64f030004)

According to @mmn, the problem lies in friendica's webfinger not including in the XRD something like this:
```
<Link rel="http://ostatus.org/schema/1.0/subscribe" 
               template="https://social.umeahackerspace.se/main/ostatussub?profile={uri}"/>
```

**Comment by mmn** [comment] 2015-06-13 09:03
Hello.

I assume the relevant portion for Friendica are the purl.org schema links with 'dfrn' and 'dfrn_poll', but since we currently do not implement DFRN in GNU social it'd probably be better to have the ostatus schema thing published.

Just to mention, GNU social also supports a non-template version of that (using a direct href instead).

**Comment by strk** [comment] 2015-06-13 09:09
I filed a ticket on GNUSocial tracker to implement DFRN: https://git.gnu.io/gnu/gnu-social/issues/51
But I seem to understand that's a technology being abandoned ?

**Comment by annando** [comment] 2015-06-13 09:24
We improved the OStatus protocol part in Friendica very much. This will be part of the next release. Could you tell me the GS account you want to subscribe? Then I would check with my installation.

**Comment by abjectio** [comment] 2015-06-13 10:28
@annando you could try to subscribe to this account - @abjectio@gnusocial.no - https://gnusocial.no/abjectio

**Comment by tobiasd** [comment] 2015-06-13 10:46
On Sat, 13 Jun 2015 03:28:40 -0700
abjectio <notifications@github.com> wrote:

> 
> @annando you could try to subscribe to this account -
> @abjectio@gnusocial.no - https://gnusocial.no/abjectio

Subscription works for me (with current develop branch code)

**Comment by strk** [comment] 2015-06-13 10:48
I just tried to switch to the "develop" branch but things did not
change. Is there an upgrade procedure I need to run after switching ?

**Comment by abjectio** [comment] 2015-06-13 10:49
@tobiasd - confirmed - I'm able to see a successful subscription from you.

**Comment by mmn** [comment] 2015-06-13 10:58
@tobiasd I think the problem is explicitly when someone fills in the WebFinger/acct URI on a "remote follow" form on a GNU social profile page. Not just subscription in general.

That is, on each profile page for GNU social we have a form that goes to - or just proxies via - the profile-hosting site's /main/ostatus - like https://quitter.no/main/ostatus

That form takes the "User nickname" (like 'abjectio' on quitter.no) as the person you are interested in - and then uses the "Profile account" (your URL or WebFinger/acct URI) to lookup your home node.

When filling in, say, mmn@social.umeahackerspace.se as the WebFinger URI it does a RFC7033 lookup (and if that fails, a RFC6415 for arbitrary XRD endpoints, like with Friendica). This lookup must have an endpoint for the interested party (in my case mmn@social.umeahackerspace.se) to initiate the subscription procedure. In OStatus, that is an endpoint which has rel="http://ostatus.org/schema/1.0/subscribe".

So if the XRD found on lookup does not provide a suitable endpoint for OStatus subscription, we cannot complete the request. But subscriptions work the other way (i.e. you provide the remote party's address directly on your local node).

GNU social's OStatus subscription endpoint is generally /main/ostatussub which requires a logged in state and then presents the user (on their local node) with an confirmation form that the profile is really the one they wish to initiate a subscription for.

**Comment by strk** [comment] 2015-06-13 11:05
I confirm I used the "remote follow" button, hadn't tried with sending the request from my node (will look it up and let you know how it goes)

**Comment by strk** [comment] 2015-06-13 11:08
Connecting from the "Add new contact" form in my own node indeed works fine. Should the issue title be changed ?

**Comment by mmn** [comment] 2015-06-13 11:09
@strk Yes, I think so. :)

**Comment by strk** [comment] 2015-06-13 11:15
What would a good name be ? It's getting too technical for my level of knowledge in this domain :)

**Comment by strk** [comment] 2015-06-13 11:15
^name^title

**Comment by annando** [comment] 2015-06-13 17:57
I just tested and now did a pull request. Thanks to the information from @mmn this was a really easy task.

**Comment by strk** [comment] 2015-06-13 21:05
and the pull request is ? how to test ?
I hope there can be more than this cross-technology synergy here :)

**Comment by strk** [comment] 2015-06-13 21:11
Figured (#1667) -- tested successfully here. Thanks for the quick fix ! Looking forward to next release !
(better only close this once that PR is merged)

**Comment by annando** [comment] 2015-06-24 12:31
It is merged with the developer branch and will be part of the upcoming release. So I close this issue.

**Closed by annando** 2015-06-24 12:31 UTC
