### ISSUE TITLE
Feature: Play Animated GIFs onClick

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4963] opened 2018-05-01 06:26 UTC
I would like to propose to implement loading and playing animated GIFs on click.
Animated GIFs can be quite large. I've seen some in my stream bigger than 10MB. If there is such a big one in your stream or several smaller ones it takes a lot of time to load the network stream. Also, it's annoying sometimes. :-)

I like how Google+ is doing this. You only see a preview of the first frame with a play button. Just like we do it with YouTube videos. I like that.

As I found out this could be done very easily. There is a jquery plugin called **gifplayer** that does exactly that.
website: http://rubentd.com/gifplayer/
github: https://github.com/rubentd/gifplayer

I don't know how this would inter-operate with our proxy cache. Would be great to have PlayOnClick for uploaded GIFs and for shared remote GIFs (shared via 'img' tags) as well.

Thank you!

**Comment by tobiasd** [comment] 2018-05-01 06:31
This is a duplicate of #2033 I think

**Comment by AlfredSK** [comment] 2018-05-01 06:34
Oh! You're right. I always :-) search for open issues before I create one. But This time I was lazy. Sorry.

**Closed** 2018-05-01 08:46 UTC
