### ISSUE TITLE
Twitter plugin is shortening incorrect

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4144] opened 2017-12-29 11:08 UTC
If you post a longer article in friendica with another link to a third website, the post is shortend and on Twitter there is only the link to the third website, but not the link to the original post. Priority should be, that there is the link to friendica with the whole post. 

Example:
Twitter : https://twitter.com/hoergen/status/946350852327071744
Friendica : https://horche.demkontinuum.de/display/2196d4ee215a44dd8586637408661289

![00_temp](https://user-images.githubusercontent.com/24474762/34435828-b9688aba-ec90-11e7-9839-5264a5cf3a5c.png)
![01_temp](https://user-images.githubusercontent.com/24474762/34435857-ebde1e6a-ec90-11e7-9d6a-489f3326507f.png)

**Comment by hoergen** [comment] 2017-12-29 11:11
And between title and content (friendica to twitter) a blank is lacking. See Twitter post.

**Comment by annando** [comment] 2017-12-29 13:01
This is not a bug, but a feature. When you use the ```[attachment]``` BBCode, the link inside the attachment has priority.

**Comment by annando** [comment] 2017-12-29 13:04
But: The missing space indeed is a bug.

**Comment by hoergen** [comment] 2017-12-29 13:52
Hmm from my point of view it is a anti-feature aka wrong logic. Because when I'm writing some longer posts, it isn't linked so that someone on an other network has the possibility to read it. Even to know where it comes from. Friendica should be the central of all my posts, not just a distributer. I want to hold the discussion mostly on my posts. And if people are interested in what I'm posting, they should be able to see what I'm writing. At the moment, they can't.

**Comment by MrPetovan** [comment] 2017-12-29 16:12
I believe this issue is related or maybe a duplicate of #4014

**Comment by annando** [comment] 2017-12-29 16:40
When you want to write longer articles, don't use ```[attachment]``` but ```[url]```. This is some philosophical thing.

**Comment by hoergen** [comment] 2017-12-29 21:56
hmm weird philosophy.

**Comment by hoergen** [comment] 2017-12-30 23:55
I'm not sure, if this is the same.1st it is the direction of Friendica to Twitter and not the other way like you described in your case and 2nd it prioritizes attachment tags over other text parts like @annando described. 3rd (what is a bit part of 2nd) it uses the wrong url (if there is an attachement), when not the whole text can be posted on Twitter.

**Comment by annando** [comment] 2017-12-31 15:01
The philosophy behind that is that when "attachment" is used, the attached link is important. Then the text is the description of the link. Since you can crosspost to networks with and without length restrictions you then can write a text where - for example - the first paragraph is a summary that is then used for Twitter, while the whole text (after the paragraph) is used for Friendica and commercial networks without length limitations like Facebook or Google+.

**Comment by hoergen** [comment] 2018-01-02 12:49
I understand the logic. But when I post something in a network with commenting it, you rip away my personal view of that topic with ignoring to link it to networks with limited post length. I as an author want to tell "the limited world" as well something, but that world isn't able to read it, because there is no source link. 
So if I start an ironic post and linking an article with attachement it could reverse my intention completely. In the worst case it looks like I'm pro something where I'm absolutely against it.
And you have to teach _every_ new user that logic, instead of letting the software do what is common sense. 

Don't get me wrong I'm really fully for new concepts, but in this case omitting the source of a post that want to tell you something with links (attaches) to another (third) source can't be  the correct way.

**Comment by annando** [comment] 2018-01-02 13:38
It's complicated and should possibly be configurable.

**Comment by hoergen** [comment] 2018-01-02 13:42
From my point of view it would be perfect to cut down the text lenght to the limit of that network, setting "my" source link and using (if there is an attachment) the attachments image.

**Comment by annando** [comment] 2018-01-02 13:58
I just realized that the switch already is present: "Disable intelligent shortening" in the user settings under "Social Networks".

**Comment by hoergen** [comment] 2018-01-02 14:04
Oh nice! Thanks. Do you know if it is configurable that I can set this systemwide? Can't find something like that in the adminstration/plugin settings.

**Comment by annando** [comment] 2018-01-02 14:18
No, it is a user setting.

**Comment by tobiasd** [comment] 2018-01-03 10:46
Can we close the issue then?

**Comment by hoergen** [comment] 2018-01-03 16:04
I think yes. Thanks for asking.

**Comment by MrPetovan** [comment] 2018-01-03 16:08
I can't find the "Disable intelligent shortening" settings in "Social Networks" ?

**Comment by tobiasd** [comment] 2018-01-03 16:23
> I can't find the "Disable intelligent shortening" settings in "Social
> Networks" ?

User Settings -> Social Networks -> General Settings -> 1st option

(that's roughly translated from German)

**Comment by MrPetovan** [comment] 2018-01-03 16:27
Thanks, on frio it doesn't look like an accordion so I never clicked on the settings group header. However, when I click on the checkboxes or the label in this group, nothing happens, and the input element isn't explicitly disabled 😬

**Comment by hoergen** [comment] 2018-01-03 16:29
It happened to me too ;) Never realized that this is an additional section where I can configure something ;)

**Comment by annando** [comment] 2018-01-03 16:47
Yeah, from a design standpoint we should make this more clearer.

**Comment by MrPetovan** [comment] 2018-01-05 05:49
Duplicate of #4144, closing the old one.

**Closed** 2018-01-22 12:40 UTC
Labels: Addons
