### ISSUE TITLE
Support for nomadic identity?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13030] opened 2023-04-24 08:36 UTC
Arising from a lengthy discussion on Hubzilla - https://zotum.net/display/b64.aHR0cHM6Ly9sb21hLm1sL29iamVjdHMvMzczZWJmNTYtMTY2NC00NjMyLWY2N2MtNGYzMzEwNzUxODYy : Would it be possible to support (Hubzillas understanding of) nomadic identity on Friendica?

**Comment by tobiasd** [comment] 2023-04-25 04:56
This is actually a duplicate of #1164 from 2014 xD from my POV yes, please add support of Zot

**Closed as completed by tobiasd** 2023-04-25 04:56 UTC
Labels: New Feature, Federation

**Comment by kr428** [comment] 2023-04-25 05:49
@tobiasd Not sure whether this really is a duplicate but still added some thoughts to #1164 ... 🙂️
