### ISSUE TITLE
Unable to add Mastodon contacts : 'The network type couldn't be detected. Contact can't be added.'

### ISSUE THREAD

**Issue by tomchiverton** [friendica/friendica#12185] opened 2022-11-15 21:10 UTC
I've tried to follow several Mastadon accounts via "add new contact" at `/contact` and pressing "connect", such as '@Landwomble@mastodon.cloud'

This always leads to a page with a black and white toaster saying "The network type couldn't be detected. Contact can't be added." as well as body content : 

```
Connect/Follow

Profile URL
    [Landwomble@mastodon.cloud](https://WWWWW.XXXXX.YYYY/Landwomble@mastodon.cloud)

Your Identity Address: https://social.rachaelandtom.info/profile/tom

[ Cancel]
```

There's no further information I can see anywhere in the admin or server logs as to what might be wrong.

Fresh install today of the latest release, PHP8.0 on Amazon Linux.

**Comment by MrPetovan** [comment] 2022-11-16 00:27
Hi, I'm able to probe this address from my node, are you administrator of your own by any chance?

**Comment by tomchiverton** [comment] 2022-11-16 08:24
Yup, happy to look at any thing to debug this 
-- 
†øღ

**Comment by MrPetovan** [comment] 2022-11-16 12:06
Excellent, can you please enter the account's Webfinger address `Landwomble@mastodon.cloud` in the Admin -> probe address page (Path `/probe` on your own domain)?

**Comment by tomchiverton** [comment] 2022-11-16 20:19
Seems to be OK? 

```
Array
(
    [name] => Landwomble@mastodon.cloud
    [nick] => landwomble@mastodon.cloud
    [guid] => 
    [url] => Landwomble@mastodon.cloud
    [addr] => 
    [alias] => 
    [photo] => https://social.rachaelandtom.info/images/person-300.jpg
    [header] => 
    [account-type] => 
    [community] => 
    [keywords] => 
    [location] => 
    [about] => 
    [xmpp] => 
    [matrix] => 
    [hide] => 
    [batch] => 
    [notify] => 
    [poll] => 
    [request] => 
    [confirm] => 
    [subscribe] => https://mastodon.cloud/authorize_interaction?uri={uri}
    [poco] => 
    [following] => 
    [followers] => 
    [inbox] => 
    [outbox] => 
    [sharedinbox] => 
    [priority] => 0
    [network] => unkn
    [pubkey] => 
    [manually-approve] => 
    [baseurl] => http://mastodon.cloud
    [gsid] => 4
)
```

**Comment by AlfredSK** [comment] 2022-11-16 20:36
Nope. Should look like this...

```
Array
(
    [name] => Landwomble
    [nick] => Landwomble
    [guid] => 
    [url] => https://mastodon.cloud/users/Landwomble
    [addr] => Landwomble@mastodon.cloud
    [alias] => https://mastodon.cloud/@Landwomble
    [photo] => https://media.mastodon.cloud/accounts/avatars/109/293/773/858/774/011/original/0d75c98d660500c6.jpg
    [header] => https://media.mastodon.cloud/accounts/headers/109/293/773/858/774/011/original/12c95c0eeef65f02.jpg
    [account-type] => 0
    [community] => 
    [keywords] => 
    [location] => 
    [about] => Photographer, tinkerer, voider of warranties. Enthusiastic gig goer, occasional track day enthusiast. Double spaces after a full stop is the hill I'll die on. Works for Microsoft as a PM in Azure. Views not necessarily those of my employer, YMMV etc. Don't vote Tory. He/Him
    [xmpp] => 
    [matrix] => 
    [hide] => 0
    [batch] => https://mastodon.cloud/inbox
    [notify] => https://mastodon.cloud/users/Landwomble/inbox
    [poll] => https://mastodon.cloud/users/Landwomble/outbox
    [request] => 
    [confirm] => 
    [subscribe] => https://mastodon.cloud/authorize_interaction?uri={uri}
    [poco] => 
    [following] => https://mastodon.cloud/users/Landwomble/following
    [followers] => https://mastodon.cloud/users/Landwomble/followers
    [inbox] => https://mastodon.cloud/users/Landwomble/inbox
    [outbox] => https://mastodon.cloud/users/Landwomble/outbox
    [sharedinbox] => https://mastodon.cloud/inbox
    [priority] => 0
    [network] => apub
    [pubkey] => -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv5WKpL8IHHy/GttrgDpK
dpBCy+CPryrUhSe0e36CKhNVm4oWLq2yhEIL1jOLY/FdxB8dQAvO5zIKfGyCZWGY
XCWbd5XPpe5C7LIgyXEne33r+FMiKhxcmH3N2msZN3Mp8ThT1KwnKVidoxcH4qny
q9hhjSkP1JGJLe5QIKb74D9ACh61R+p/qaaCyOeLks5i/1Hp6VrT3HhmDyi8j6cr
OCeT9NnVWSOrLvd0Y3qdCrXTLsYpyfKJvAzInuYRKpBbKVN5ct8f2r9IBChOw3YE
01sjUf53t3P4Aw9pqYFdsfhhRy2Yl8ceaHpaF8xjU23bJFj1qWXWfeZEGqUsVROq
eQIDAQAB
-----END PUBLIC KEY-----
    [manually-approve] => 0
    [baseurl] => https://mastodon.cloud
    [gsid] => 2746
)
```

**Comment by MrPetovan** [comment] 2022-11-16 21:16
I have the same output as @AlfredSK. It's possible that `mastodon.cloud` has blocked your particular domain, which would prevent you to probe or friend accounts on their server. I've looked for a public server block list but they don't seem to be exposing it.

**Comment by tomchiverton** [comment] 2022-11-17 21:33
This is a brand new domain and install. I've allowed time for DNS propagation.

**Comment by MrPetovan** [comment] 2022-11-17 22:46
Can you please increase your Friendica log level to Info, try the same probe, and look for the remote account address in your log? There might be a clue.

**Comment by efelon** [comment] 2022-11-18 10:33
I have the same behaviour (same probe and same error) with `https://fosstodon.org/@homeassistant`. Here the logs with "Info":

```
2022-11-18T10:26:38Z index [NOTICE]: Multiple requests for the address {"url":"https://fosstodon.org/@homeassistant","update":true,"callstack":"ActivityPub::probeProfile, Probe::uri, Probe::content, BaseModule::run, App::runFrontend","result":"ActivityPub::probeProfile, Probe::uri, Probe::content, BaseModule::run, App::runFrontend"} - {"file":"APContact.php","line":178,"function":"getByURL","uid":"699c4f","process_id":2142194}
2022-11-18T10:26:43Z index [NOTICE]: Deleted duplicated contact {"ret":true,"account-user":{"id":135},"cid":135,"uid":0,"uri-id":200599,"url":"https://fd.winklerfamilie.eu/friendica"} - {"file":"Contact.php","line":192,"function":"insert","uid":"699c4f","process_id":2142194}
2022-11-18T10:26:43Z index [INFO]: Probing start {"uri":"https://fosstodon.org/@homeassistant"} - {"file":"Probe.php","line":672,"function":"detect","uid":"699c4f","process_id":2142194}
2022-11-18T10:26:43Z index [INFO]: Test Atom/RSS feed [] - {"file":"Feed.php","line":69,"function":"import","uid":"699c4f","process_id":2142194}
2022-11-18T10:26:43Z index [INFO]: There are no entries in this feed. [] - {"file":"Feed.php","line":271,"function":"import","uid":"699c4f","process_id":2142194}
2022-11-18T10:26:43Z index [INFO]: Probing done {"uri":"https://fosstodon.org/@homeassistant","network":"unkn"} - {"file":"Probe.php","line":742,"function":"detect","uid":"699c4f","process_id":2142194}
2022-11-18T10:26:44Z index [NOTICE]: Deleted duplicated contact {"ret":true,"account-user":{"id":135},"cid":135,"uid":0,"uri-id":200599,"url":"https://fd.winklerfamilie.eu/friendica"} - {"file":"Contact.php","line":192,"function":"insert","uid":"53d603","process_id":2142596}
```
And the log when probing `@homeassistant@fosstodon.org`:
```
2022-11-18T10:46:28Z index [NOTICE]: Multiple requests for the address {"url":"https://fosstodon.org/users/homeassistant","update":true,"callstack":"ActivityPub::probeProfile, Probe::uri, Probe::content, BaseModule::run, App::runFrontend","result":"ActivityPub::probeProfile, Probe::uri, Probe::content, BaseModule::run, App::runFrontend"} - {"file":"APContact.php","line":178,"function":"getByURL","uid":"06988e","process_id":2142208}
2022-11-18T10:46:30Z index [NOTICE]: Deleted duplicated contact {"ret":true,"account-user":{"id":135},"cid":135,"uid":0,"uri-id":200599,"url":"https://fd.winklerfamilie.eu/friendica"} - {"file":"Contact.php","line":192,"function":"insert","uid":"2a885f","process_id":2142202}
2022-11-18T10:46:30Z index [NOTICE]: Unable to retrieve AP contact for actor - message is discarded {"actor":"https://ioc.exchange/users/NotAlpharius"} - {"file":"Receiver.php","line":107,"function":"processInbox","uid":"2a885f","process_id":2142202}
2022-11-18T10:46:31Z index [INFO]: Thread is ignored {"parent-uri-id":565373,"type":16} - {"file":"Notification.php","line":147,"function":"getMessageFromNotification","uid":"04f5f9","process_id":2142196}
2022-11-18T10:46:31Z index [INFO]: Thread is ignored {"parent-uri-id":562510,"type":16} - {"file":"Notification.php","line":147,"function":"getMessageFromNotification","uid":"04f5f9","process_id":2142196}
2022-11-18T10:46:31Z index [INFO]: Thread is ignored {"parent-uri-id":545925,"type":32} - {"file":"Notification.php","line":147,"function":"getMessageFromNotification","uid":"04f5f9","process_id":2142196}
2022-11-18T10:46:31Z index [INFO]: Local link {"url":"https://fd.winklerfamilie.eu/images/person-300.jpg","callstack":"HttpClient::head, ParseUrl::getContentType, Photo::getPhotoById, Photo::rawContent, BaseModule::run, App::runFrontend"} - {"file":"HttpClient.php","line":79,"function":"request","uid":"728b9f","process_id":2143641}
2022-11-18T10:46:32Z index [NOTICE]: Deleted duplicated contact {"ret":true,"account-user":{"id":135},"cid":135,"uid":0,"uri-id":200599,"url":"https://fd.winklerfamilie.eu/friendica"} - {"file":"Contact.php","line":192,"function":"insert","uid":"06988e","process_id":2142208}
2022-11-18T10:46:32Z index [INFO]: Probing start {"uri":"homeassistant@fosstodon.org"} - {"file":"Probe.php","line":672,"function":"detect","uid":"06988e","process_id":2142208}
2022-11-18T10:46:32Z index [INFO]: Test Atom/RSS feed [] - {"file":"Feed.php","line":69,"function":"import","uid":"06988e","process_id":2142208}
2022-11-18T10:46:32Z index [INFO]: XML is empty. [] - {"file":"Feed.php","line":77,"function":"import","uid":"06988e","process_id":2142208}
2022-11-18T10:46:32Z index [INFO]: Probing done {"uri":"homeassistant@fosstodon.org","network":"unkn"} - {"file":"Probe.php","line":742,"function":"detect","uid":"06988e","process_id":2142208}
2022-11-18T10:46:35Z index [NOTICE]: Deleted duplicated contact {"ret":true,"account-user":{"id":135},"cid":135,"uid":0,"uri-id":200599,"url":"https://fd.winklerfamilie.eu/friendica"} - {"file":"Contact.php","line":192,"function":"insert","uid":"728b9f","process_id":2143641}
2022-11-18T10:46:35Z index [ERROR]: Uncaught Exception Error: "Call to a member function isSuccess() on null" at /var/www/friendica/src/Core/Storage/Type/ExternalResource.php line 62 {"exception":"Error: Call to a member function isSuccess() on null in /var/www/friendica/src/Core/Storage/Type/ExternalResource.php:62\nStack trace:\n#0 /var/www/friendica/src/Model/Photo.php(207): Friendica\\Core\\Storage\\Type\\ExternalResource->get()\n#1 /var/www/friendica/src/Module/Photo.php(155): Friendica\\Model\\Photo::getImageDataForPhoto()\n#2 /var/www/friendica/src/BaseModule.php(238): Friendica\\Module\\Photo->rawContent()\n#3 /var/www/friendica/src/App.php(719): Friendica\\BaseModule->run()\n#4 /var/www/friendica/index.php(44): Friendica\\App->runFrontend()\n#5 {main}"} - {"file":null,"line":null,"function":null,"uid":"728b9f","process_id":2143641}
```

I have added contacts from `fosstodon.org` successfully before. This is my first attempt to add users since the update to `Friendica 'Giant Rhubarb' 2022.10 - 1484`.

Contact ' 135' is:
```
Kontakt: relay

Status
    Netzwerktyp: friendica (AP)
```

**Comment by MrPetovan** [comment] 2022-11-18 15:37
Please limit your logs to the same `process_id`, `2142194` in the first block, `2142208` in the second, it will help separating the probe from unrelated requests.

Then can you please rerun the probe after temporarily increasing your log level to `Debug` ?

**Comment by jakedfw** [comment] 2022-11-18 19:28
I'm hitting this as well with mastadon.world. Will watch others troubleshoot first for once. ;)

**Comment by efelon** [comment] 2022-11-19 01:23
@MrPetovan, I "greped" for the process ID with `Debug`:

```
2022-11-19T01:18:31Z index [DEBUG]: No HTTP_SIGNATURE header [] - {"file":"HTTPSignature.php","line":525,"function":"getSigner","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: Got ID for URL {"id":1,"url":"https://fd.winklerfamilie.eu","callstack":"User::createSystemAccount, User::getSystemAccount, HTTPSignature::fetchRaw, APContact::getByURL, ActivityPub::probeProfile, Probe::uri, Probe::content, BaseModule::run, App::runFrontend"} - {"file":"GServer.php","line":126,"function":"getID","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: Delete contact {"id":872355} - {"file":"Contact.php","line":213,"function":"deleteById","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: DELETE FROM `account-user`  WHERE (`id` = 872355) {"callstack":"Contact::insert, User::createSystemAccount, User::getSystemAccount, HTTPSignature::fetchRaw, APContact::getByURL, ActivityPub::probeProfile"} - {"file":"Database.php","line":1282,"function":"delete","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: DELETE FROM `contact`  WHERE (`id` = 872355) {"callstack":"Contact::insert, User::createSystemAccount, User::getSystemAccount, HTTPSignature::fetchRaw, APContact::getByURL, ActivityPub::probeProfile"} - {"file":"Database.php","line":1282,"function":"delete","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [NOTICE]: Deleted duplicated contact {"ret":true,"account-user":{"id":135},"cid":135,"uid":0,"uri-id":200599,"url":"https://fd.winklerfamilie.eu/friendica"} - {"file":"Contact.php","line":192,"function":"insert","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [INFO]: Probing start {"uri":"https://fosstodon.org/@homeassistant"} - {"file":"Probe.php","line":672,"function":"detect","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: Request start. {"url":"https://fosstodon.org/.well-known/webfinger?resource=acct%3Ahomeassistant%40fosstodon.org","method":"get"} - {"file":"HttpClient.php","line":69,"function":"request","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: http request config. {"url":"https://fosstodon.org/.well-known/webfinger?resource=acct%3Ahomeassistant%40fosstodon.org","method":"get","options":{"headers":{"User-Agent":"Friendica 'Giant Rhubarb' 2022.10-1484; https://fd.winklerfamilie.eu","Accept":"application/jrd+json,application/json;q=0.9"},"timeout":20,"on_headers":{},"sink":"/tmp/fd.winklerfamilie.eu/http-KCUK9y"}} - {"file":"HttpClient.php","line":162,"function":"request","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: Request stop. {"url":"https://fosstodon.org/.well-known/webfinger?resource=acct%3Ahomeassistant%40fosstodon.org","method":"get"} - {"file":"HttpClient.php","line":178,"function":"request","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: Request start. {"url":"https://fosstodon.org/@homeassistant","method":"get"} - {"file":"HttpClient.php","line":69,"function":"request","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: http request config. {"url":"https://fosstodon.org/@homeassistant","method":"get","options":{"headers":{"User-Agent":"Friendica 'Giant Rhubarb' 2022.10-1484; https://fd.winklerfamilie.eu","Accept":"application/atom+xml,application/rss+xml;q=0.9,application/rdf+xml;q=0.8,text/xml;q=0.7,*/*;q=0.6"},"on_headers":{},"sink":"/tmp/fd.winklerfamilie.eu/http-2DjFAC"}} - {"file":"HttpClient.php","line":162,"function":"request","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: Request stop. {"url":"https://fosstodon.org/@homeassistant","method":"get"} - {"file":"HttpClient.php","line":178,"function":"request","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [INFO]: Test Atom/RSS feed [] - {"file":"Feed.php","line":69,"function":"import","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [INFO]: There are no entries in this feed. [] - {"file":"Feed.php","line":271,"function":"import","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [INFO]: Probing done {"uri":"https://fosstodon.org/@homeassistant","network":"unkn"} - {"file":"Probe.php","line":742,"function":"detect","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: Got ID for URL {"id":576,"url":"https://fosstodon.org","callstack":"Probe::uri, Probe::content, BaseModule::run, App::runFrontend"} - {"file":"GServer.php","line":126,"function":"getID","uid":"a5c688","process_id":2304856}
2022-11-19T01:18:33Z index [DEBUG]: Runtime {"method":"GET","module":"probe","runtime":"1.977","load":"2.77","origin":"runFrontend","signature":false,"request":"/probe?addr=https%3A%2F%2Ffosstodon.org%2F%40homeassistant"} - {"file":"Page.php","line":114,"function":"logRuntime","uid":"a5c688","process_id":2304856}
```
`homeassistant@fosstodon.org`
```
2022-11-19T01:12:41Z index [DEBUG]: No HTTP_SIGNATURE header [] - {"file":"HTTPSignature.php","line":525,"function":"getSigner","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:41Z index [DEBUG]: Request start. {"url":"https://fosstodon.org/.well-known/webfinger?resource=acct:homeassistant%40fosstodon.org","method":"get"} - {"file":"HttpClient.php","line":69,"function":"request","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:41Z index [DEBUG]: http request config. {"url":"https://fosstodon.org/.well-known/webfinger?resource=acct:homeassistant%40fosstodon.org","method":"get","options":{"headers":{"User-Agent":"Friendica 'Giant Rhubarb' 2022.10-1484; https://fd.winklerfamilie.eu","Accept":"application/jrd+json,application/json;q=0.9"},"timeout":20,"on_headers":{},"sink":"/tmp/fd.winklerfamilie.eu/http-AEiNrl"}} - {"file":"HttpClient.php","line":162,"function":"request","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:42Z index [DEBUG]: Request stop. {"url":"https://fosstodon.org/.well-known/webfinger?resource=acct:homeassistant%40fosstodon.org","method":"get"} - {"file":"HttpClient.php","line":178,"function":"request","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:42Z index [NOTICE]: Multiple requests for the address {"url":"https://fosstodon.org/users/homeassistant","update":true,"callstack":"ActivityPub::probeProfile, Probe::uri, Probe::content, BaseModule::run, App::runFrontend","result":"ActivityPub::probeProfile, Probe::uri, Probe::content, BaseModule::run, App::runFrontend"} - {"file":"APContact.php","line":178,"function":"getByURL","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: Got ID for URL {"id":1,"url":"https://fd.winklerfamilie.eu","callstack":"User::createSystemAccount, User::getSystemAccount, HTTPSignature::fetchRaw, APContact::getByURL, ActivityPub::probeProfile, Probe::uri, Probe::content, BaseModule::run, App::runFrontend"} - {"file":"GServer.php","line":126,"function":"getID","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: Delete contact {"id":872213} - {"file":"Contact.php","line":213,"function":"deleteById","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: DELETE FROM `account-user`  WHERE (`id` = 872213) {"callstack":"Contact::insert, User::createSystemAccount, User::getSystemAccount, HTTPSignature::fetchRaw, APContact::getByURL, ActivityPub::probeProfile"} - {"file":"Database.php","line":1282,"function":"delete","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: DELETE FROM `contact`  WHERE (`id` = 872213) {"callstack":"Contact::insert, User::createSystemAccount, User::getSystemAccount, HTTPSignature::fetchRaw, APContact::getByURL, ActivityPub::probeProfile"} - {"file":"Database.php","line":1282,"function":"delete","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [NOTICE]: Deleted duplicated contact {"ret":true,"account-user":{"id":135},"cid":135,"uid":0,"uri-id":200599,"url":"https://fd.winklerfamilie.eu/friendica"} - {"file":"Contact.php","line":192,"function":"insert","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [INFO]: Probing start {"uri":"homeassistant@fosstodon.org"} - {"file":"Probe.php","line":672,"function":"detect","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: Request start. {"url":"https://fosstodon.org/.well-known/webfinger?resource=acct%3Ahomeassistant%40fosstodon.org","method":"get"} - {"file":"HttpClient.php","line":69,"function":"request","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: http request config. {"url":"https://fosstodon.org/.well-known/webfinger?resource=acct%3Ahomeassistant%40fosstodon.org","method":"get","options":{"headers":{"User-Agent":"Friendica 'Giant Rhubarb' 2022.10-1484; https://fd.winklerfamilie.eu","Accept":"application/jrd+json,application/json;q=0.9"},"timeout":20,"on_headers":{},"sink":"/tmp/fd.winklerfamilie.eu/http-rZTHVn"}} - {"file":"HttpClient.php","line":162,"function":"request","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: Request stop. {"url":"https://fosstodon.org/.well-known/webfinger?resource=acct%3Ahomeassistant%40fosstodon.org","method":"get"} - {"file":"HttpClient.php","line":178,"function":"request","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: Request start. {"url":"homeassistant@fosstodon.org","method":"get"} - {"file":"HttpClient.php","line":69,"function":"request","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: URL cannot be resolved. {"url":"homeassistant@fosstodon.org","callstack":"HttpClient::get, Probe::feed, Probe::detect, Probe::uri, Probe::content, BaseModule::run, App::runFrontend"} - {"file":"HttpClient.php","line":73,"function":"request","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: construct {"url":"homeassistant@fosstodon.org","returncode":0,"result":""} - {"file":"CurlResult.php","line":135,"function":"__construct","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: debug {"info":{"http_code":0}} - {"file":"CurlResult.php","line":175,"function":"checkSuccess","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [INFO]: Test Atom/RSS feed [] - {"file":"Feed.php","line":69,"function":"import","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [INFO]: XML is empty. [] - {"file":"Feed.php","line":77,"function":"import","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [INFO]: Probing done {"uri":"homeassistant@fosstodon.org","network":"unkn"} - {"file":"Probe.php","line":742,"function":"detect","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: Got ID for URL {"id":576,"url":"http://fosstodon.org","callstack":"Probe::uri, Probe::content, BaseModule::run, App::runFrontend"} - {"file":"GServer.php","line":126,"function":"getID","uid":"34b09f","process_id":2304866}
2022-11-19T01:12:45Z index [DEBUG]: Runtime {"method":"GET","module":"probe","runtime":"3.955","load":"2.01","origin":"runFrontend","signature":false,"request":"/probe?addr=homeassistant%40fosstodon.org"} - {"file":"Page.php","line":114,"function":"logRuntime","uid":"34b09f","process_id":2304866}
```

**Comment by MrPetovan** [comment] 2022-11-19 02:00
So, a glaring issue: Your system is constantly trying to retrieve the system user account, failing to do so, creating a new one, and then immediately deleting the new one because it is a duplicate of a contact with the same URL.

What gives ``SELECT `id`, `nick`, `name`, `uri-id`, `url` FROM `contact` WHERE `uid` = 0 AND `self` `` on your database?

And what gives ``SELECT `id`, `uid`, `nick`, `name`, `self` FROM `contact` WHERE `uri-id` = 200599``

**Comment by efelon** [comment] 2022-11-19 07:30
One short sleep later...
```
MariaDB [friendica_db]> SELECT `id`, `nick`, `name`, `uri-id`, `url` FROM `contact` WHERE `uid` = 0 AND `self`;
Empty set (0.001 sec)
```

```
MariaDB [friendica_db]> SELECT `id`, `uid`, `nick`, `name`, `self` FROM `contact` WHERE `uri-id` = 200599;
+-----+-----+-------+-------+------+
| id  | uid | nick  | name  | self |
+-----+-----+-------+-------+------+
| 135 |   0 | relay | relay |    0 |
+-----+-----+-------+-------+------+
1 row in set (0.001 sec)
```

**Comment by MrPetovan** [comment] 2022-11-19 12:46
Please delete this row, I'll have a fix soon for this case not to happen again. I'm not sure it will fix the original probe issue but at least your log will be sane again.

**Comment by efelon** [comment] 2022-11-19 16:34
Thanks @MrPetovan, I can probe again normally.
After the deletion, the select statement outputs:
```
MariaDB [friendica_db]> SELECT `id`, `uid`, `nick`, `name`, `self` FROM `contact` WHERE `uri-id` = 200599;
+--------+-----+-----------+----------------+------+
| id     | uid | nick      | name           | self |
+--------+-----+-----------+----------------+------+
| 892471 |   0 | friendica | System Account |    1 |
+--------+-----+-----------+----------------+------+
```
<details><summary>And the Probe:</summary>

```
Array
(
    [name] => Home Assistant
    [nick] => homeassistant
    [guid] => 
    [url] => https://fosstodon.org/users/homeassistant
    [addr] => homeassistant@fosstodon.org
    [alias] => https://fosstodon.org/@homeassistant
    [photo] => https://cdn.fosstodon.org/accounts/avatars/109/305/287/743/222/285/original/26d2c191f965a5a6.jpg
    [header] => https://cdn.fosstodon.org/accounts/headers/109/305/287/743/222/285/original/26696fb0d111383d.jpeg
    [account-type] => 0
    [community] => 
    [keywords] => 
    [location] => 
    [about] => Open source home automation that puts local control & privacy first. Powered by a worldwide community of tinkerers & DIY enthusiasts.
    [xmpp] => 
    [matrix] => 
    [hide] => 0
    [batch] => https://fosstodon.org/inbox
    [notify] => https://fosstodon.org/users/homeassistant/inbox
    [poll] => https://fosstodon.org/users/homeassistant/outbox
    [request] => 
    [confirm] => 
    [subscribe] => https://fosstodon.org/authorize_interaction?uri={uri}
    [poco] => 
    [following] => https://fosstodon.org/users/homeassistant/following
    [followers] => https://fosstodon.org/users/homeassistant/followers
    [inbox] => https://fosstodon.org/users/homeassistant/inbox
    [outbox] => https://fosstodon.org/users/homeassistant/outbox
    [sharedinbox] => https://fosstodon.org/inbox
    [priority] => 0
    [network] => apub
    [pubkey] => -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv8ACv2AhYI7X9HGl2twO
n5EAEQ8FItSV1yoJGdcXSS2nANTTFsrZCybuWa3ub1bhtRRsOB5XFbRdEBc6qKLm
OnkY9jOJaTTZzto74KE4fJeberJXYoVUiblVuuvKzo6xan4BRm+XH1+BvUqSVMF+
H6wp+ml6TQvIA1ZET+ZOkx3myjzfLjUbgOMPIX3Vo5sWGlWTyt97MDrrLCai1vp4
vBBsPEqZtahUOfqucPxLMhUCVzOeYjjYJ8UhUhSbvRCyh8ViJ8B9N9x5nreFdwyW
u3TZcUNR7hRE+bbNrvvnvOzxEuouKjNKvCSmxW/6Z30uPUgMyfCp9bvsLt7UXE3h
KQIDAQAB
-----END PUBLIC KEY-----
    [manually-approve] => 0
    [baseurl] => https://fosstodon.org
    [gsid] => 576
)
```

</details>

**Comment by MrPetovan** [comment] 2022-11-19 17:00
Oooh, so it was related! My fix may also resolve @tomchiverton 's issue.

**Closed as completed** 2022-12-19 00:32 UTC
Labels: Bug
