### ISSUE TITLE
Ability to ignore birthday and events notifications

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#10735] opened 2021-09-20 01:52 UTC
Maybe is a good idea to have an option somewhere in the settings to be able to ignore birthday notifications and event notifications, maybe separately. They can be quite intrusive. One sits at the top of your entire news feed, and one on your homepage. Cheers! :) And no rush :)

**Comment by MrPetovan** [comment] 2021-09-20 02:59
There's a system-wide config to hide them that can easily be transformed into a user-specific setting.

**Comment by foss-** [comment] 2021-09-20 06:48
Dupe of https://github.com/friendica/friendica/issues/8542

**Comment by MrPetovan** [comment] 2021-09-20 10:54
Nice catch!

**Comment by MrPetovan** [comment] 2021-09-20 10:54
Closed as duplicate of #8542

**Closed as completed by MrPetovan** 2021-09-20 10:54 UTC
Labels: New Feature
