### ISSUE TITLE
Compose - Send a new message without refreshing wall 

### ISSUE THREAD

**Issue by valvin1** [friendica/friendica#8127] opened 2020-01-18 09:17 UTC
I think there is already an issue about it but I've not found it back.

If there is a feature I would love having on Friendica it is the possibility to send / repost a message without loosing the position of my timeline.

I know there is a workaround by limiting the number of message displayed in one page but it is not what I'd like.

It looks like things happen in Compose items. If I've well understood there is `compose.tpl` which interacts with `compose.js` from theme. And finally `Compose.post()`.

What are the other object to check before trying to implement this kind of feature?

**Comment by MrPetovan** [comment] 2020-01-18 13:20
Actually, the best way to achieve this goal is to make the JOT modal on frio not refresh the page. The compose page is a separate page, so it would be challenging to keep your position in the timeline, especially with infinite scroll. This is already described in #4599

**Comment by valvin1** [comment] 2020-01-19 09:36
I remember comment this issue but wasn't able to find it back :)

Thank you for explanation so the challenge is more : Remove the form in `jot.tpl` file [here](https://github.com/friendica/friendica/blob/fd7c47ed55b9ee2895647c7a3583b169d8f6e74e/view/templates/jot.tpl#L8) and replacing it with an asynchronous call.

**Comment by MrPetovan** [comment] 2020-01-19 13:28
The form can stay, but it would be better handled with Javascript (with [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) for example)

**Comment by annando** [comment] 2020-01-19 13:30
Whatever we do, we should keep the accessibility in mind.

**Comment by MrPetovan** [comment] 2020-01-19 13:31
Not sure about it since we're already using a modal but it is a good reminder nonetheless.

**Comment by MrPetovan** [comment] 2020-01-30 04:20
Duplicate of #4599

**Closed by MrPetovan** 2020-01-30 04:20 UTC
Labels: Enhancement, UX

**Comment by hoergen** [comment] 2020-02-03 12:55
So great improvement! I always opened a new tab in firefox to write a post to not lose the position ;) Thanks a lot 🎉👍🌻

**Comment by MrPetovan** [comment] 2020-02-03 13:29
I know, it’s so much more comfortable!
