### ISSUE TITLE
If XMPP plugin is activated posts or comments can't be edited

### ISSUE THREAD

**Issue by sesom42** [friendica/friendica#3717] opened 2017-09-19 18:02 UTC
With frio the following error message is displayed:
![bildschirmfoto vom 2017-09-19 19-36-37](https://user-images.githubusercontent.com/8649051/30606886-7a93a44e-9d73-11e7-9184-b97442506c55.png)

With vier, an incomplete edit window is displayed first and when you click on it, the window changes to an empty edit window.

After switching off the XMPP plugin everything works normally again. (Current develop branch)

**Comment by annando** [comment] 2017-09-20 07:41
Yeah, this is some JS problem. Are we having an expert here?

**Comment by foss-** [comment] 2019-01-30 14:59
Related behavior: Connect/Follow dialog "Does contact_name know you?" button is unresponsive. reported in #6547 which I closed as dupe as I think the root of the issue is the same.

Another user is reporting this here: https://squeet.me/display/962c3e10-615c-5068-ec8e-745300213133 in that case navigation elements were missing and no new posts showed up.

**Comment by poVoq** [comment] 2019-03-14 18:39
Probably the previously mentioned Bootstrap3 bug with the frio theme. Recently ConverseJS updated to Bootstrap 4, and I guess if frio was also updated it might work again.

Another option would be to explore using JSXC https://github.com/jsxc/jsxc which is not bootstrap based I think. The recently released beta 4.0 looks also really cool and the Nexcloud integration could be a cool template for a modern user integration https://github.com/nextcloud/jsxc.nextcloud

**Comment by MrPetovan** [comment] 2019-05-31 19:46
Should we just mark the addon as unsupported until someone™ picks it up?

**Comment by annando** [comment] 2019-06-01 07:52
I guess so.

**Comment by MrPetovan** [comment] 2019-06-03 20:47
The addon has been marked as unsupported.

**Closed** 2019-06-03 20:47 UTC
Labels: Addons, Bug, Won't Fix
