### ISSUE TITLE
Automatically add NSFW hashtag to (mirrored) posts

### ISSUE THREAD

**Issue by produnis** [friendica/friendica#3401] opened 2017-04-27 17:50 UTC
Hi there,
I would like to automatically set a (list of) specific #hashtag to every post that gets out from my account, including those I mirror from contacts.

Greetings
Joe

**Comment by Hypolite** [comment] 2017-04-27 18:05
Hi,

may I ask why you don't want put those hashtags yourself, whether in you main account or your mirrored ones?

It would help me understand this feature request that is very specific and probably could end up being a simple addon.

**Comment by produnis** [comment] 2017-04-27 19:15
I run a nsfw account.  
This account mirrors several rss feeds. Some mirrored posts don't have the  #nsfw hashtag, so these posts are not collapsed in my stream. 

So, while being loged in with my main account, there might show up some boobies...

**Comment by Hypolite** [comment] 2017-04-27 19:19
Oh, this sounds like it could rather easily be solved with a "NSFW account" flag on the mirrored contacts that would automatically append `#nsfw` to mirrored posts content.

Am I missing something? Where else did you want to automatically add the hashtag?

**Comment by produnis** [comment] 2017-04-27 19:29
where would I find this nsfw-flag for contacts?

**Comment by fabrixxm** [comment] 2017-04-27 19:59
I have the skeleton of a plugin that should add a per-contact configurable list of tags to incoming posts.
But I never finished it.......

**Comment by Hypolite** [comment] 2017-04-27 20:20
@produnis I'm sorry if I wasn't clear, this flag doesn't exist yet, but is easier to add to Friendica than an arbitrary hashtag appenderr.

**Comment by fabrixxm** [comment] 2017-04-27 20:24
my last step is to find how inject tags in incoming posts...

**Comment by annando** [comment] 2017-04-27 20:50
There is a "nsfw" functionality in Diaspora. So we should build some functionality that can be made compatible with this.

**Comment by tobiasd** [comment] 2017-04-28 07:53
There is #1404 to include NSFW tags into the profile

**Comment by Hypolite** [comment] 2017-04-28 16:31
Closing as duplicate of #1404.

**Closed by Hypolite** 2017-04-28 16:31 UTC
Labels: Feature Request, Junior Jobs, UX
