### ISSUE TITLE
Deprecation warning in page

### ISSUE THREAD

**Issue by shiribailem** [friendica/friendica#13159] opened 2023-05-24 01:01 UTC
Not able to replicate this, but I got this on a couple of pages, I was fiddling to track it down and it disappeared. I was seeing this on the Social Networks and Addons (user side) pages in the lists of items. *Just* updated to 2023.5.

Especially since it's a deprecation message I figured it best to share it.

`Deprecated: Using php-function "is_string" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier. in /var/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php on line 114`

**Comment by MrPetovan** [comment] 2023-05-24 01:42
Thank you, we've been collecting PHP 8.1+ deprecation notices in this issue: https://github.com/friendica/friendica/issues/12011

**Comment by MrPetovan** [comment] 2023-05-24 01:57
Duplicate of https://github.com/friendica/friendica/issues/12011#issuecomment-1523913027

**Closed as not planned by MrPetovan** 2023-05-24 01:57 UTC
Labels: Bug
