### ISSUE TITLE
Calendar settings are applied incorrectly

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12580] opened 2022-12-31 06:39 UTC
- [x] I have searched open and closed issues for duplicates

### Bug Description

The calendar setting "Week start:" and "Default calendar view:" are not or only incompletely applied since 2022.12.

The change Week start in the settings from Sunday to Monday jumps back to Sunday after saving.
The calendar setting Day and List is without function.

"Week start - Monday" is displayed on the calendar view. However, the default Sunday - Saturday is displayed in the event start and end picker. This is irritating and leads to incorrect entries. 

### Screenshots

Before Save
![grafik](https://user-images.githubusercontent.com/44441246/210127710-9e025ced-390e-4dfc-afaf-0a0483dbf233.png)
After Save
![grafik](https://user-images.githubusercontent.com/44441246/210127720-a2be0347-f6d2-43c8-b87f-12e4f3980bae.png)
Save as list
![grafik](https://user-images.githubusercontent.com/44441246/210127741-d938bacf-60d6-4098-8459-07f67821699d.png)
"Week start:" Monday
![grafik](https://user-images.githubusercontent.com/44441246/210127771-18ed72f9-8dcf-4106-9e88-61df80416e3c.png)

### Platform Info

Friendica Version: 2022.12

Friendica Source: git

PHP version: 7.4

SQL version: 10.4

**Comment by MrPetovan** [comment] 2022-12-31 06:44
Thank you for the report, this issue has been identified and patched 5 days ago on the `develop` branch: https://github.com/friendica/friendica/pull/12528

Duplicate of #12524

**Closed as not planned by MrPetovan** 2022-12-31 06:44 UTC
Labels: Bug
