### ISSUE TITLE
config/addon.config.php not used for ldapauth

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#10379] opened 2021-06-08 00:48 UTC
- [X] I have searched open and closed issues for duplicates

### Bug Description

put ldapauth config from addons/ldapauth/config/ldapauth.config.php into config/addon.config.php brings up error "ldapauth not configured or php-ldap not installed"

i've installed php-ldap, but the "server"-variable is shown as empty.

filled in the values in addons/ldapauth/config/ldapauth.config.php, a login is possible to ldap. 
So it seems, the addon-config-file config/addon.config.php is not used for ldapauth.

### Platform Info

Friendica Version:

2021.04

**Comment by MrPetovan** [comment] 2021-06-08 03:57
What does your `config/addon.config.php` file look like?

**Comment by xundeenergie** [comment] 2021-06-08 06:10
This is my config/addon.config.php

example.com and password is surely replaced with correct values.

```
<?php

return [
        'ldapauth' => [
                // ldap_server (String)
                // ldap hostname server - required
                // Example: ldap_server = host.example.com
                'ldap_server' => 'ldaps://ldap.example.com',

                // ldap_binddn (String)
                // admin dn - optional - only if ldap server dont have anonymous access
                // Example: ldap_binddn = cn=admin,dc=example,dc=com
                'ldap_binddn' => 'cn=service_id,ou=friendica,ou=apps,ou=services,dc=example,dc=com',

                // ldap_bindpw (String)
                // admin password - optional - only if ldap server dont have anonymous access
                'ldap_bindpw' => 'vEryS3cretPasswo4d',

                // ldap_searchdn (String)
                // dn to search users - required
                // Example: ldap_searchdn = ou=users,dc=example,dc=com
                'ldap_searchdn' => 'ou=users,dc=example,dc=com',

                // ldap_userattr (String)
                // attribute to find username - required
                // Example: ldap_userattr = uid
                'ldap_userattr' => 'name',

                // ldap_group (String)
                // DN of the group whose member can auth on Friendica - optional
                'ldap_group' => '',

                // ldap_autocreateaccount (Boolean)
                // To create Friendica account if user exists in ldap
                // Requires an email and a simple (beautiful) nickname on user ldap object
                // active account creation - optional - default true
                'ldap_autocreateaccount' => true,

                // ldap_autocreateaccount_emailattribute (String)
                // attribute to get email - optional - default : 'mail'
                'ldap_autocreateaccount_emailattribute' => 'mail',

                // ldap_autocreateaccount_nameattribute (String)
                // attribute to get nickname - optional - default : 'givenName'
                'ldap_autocreateaccount_nameattribute' => 'name',
        ],
];
```

**Comment by xundeenergie** [comment] 2021-06-08 06:13
when i write this to addons/ldapauth/config/ldapauth.config.php, the login is possible.
my ldap-server is tls-secured, so i have to add the ldaps:// in front of the ldap_server. (this info schould be added in the readme and comment)

**Comment by xundeenergie** [comment] 2021-06-08 07:57
So i set it back.

set ldap-settings only in config/addon.config.php to the values above, and checked out the original addon/ldapauth/config/ldapauth.config.php (with empy ldap_server) to get the original error-message:

this is, what log/friendica.log says in debug-mode on login 
```
2021-06-07T22:58:57Z index [ERROR]: Addon not configured or missing php-ldap extension {"extension_loaded":true,"server":""} - {"file":"ldapauth.php","line":97,"function":"ldapauth_authenticate","uid":"0a3267","process_id":794421}
2021-06-07T22:58:57Z index [WARNING]: authenticate: failed login attempt {"action":"login","username":"jakob","ip":"192.168.178.162"} - {"file":"Authentication.php","line":271,"function":"withPassword","uid":"0a3267","process_id":794421}
```

it seems, the config-file is ignored.

**Comment by xundeenergie** [comment] 2021-06-08 08:50
Ok... i found something strange out...

if there are the variables-names in config/addon.config.php with underscores, they are not recognized.
if i remove the underscores (and change also addon/ldapauth/ldapauth.php to use the names without unterscores), then i get a result ... 

strange... the variables in addon/ldapauth/config/ldapauth.config.php are taken with underscores...

**Comment by MrPetovan** [comment] 2021-06-08 11:31
Thank you for the additional information. Your `config/addon.local.php` file looks good, and your successful test without underscores is concerning.

**Comment by xundeenergie** [comment] 2021-06-09 13:10
I looked at the code a little... and i did not find a part, where the mistake happens... its only sourcing... i think, what i've found.

**Comment by xundeenergie** [comment] 2021-06-09 13:15
There are some more open issues for ldap... but i will open them, when this is fixed.

the code which checks the ldap_group does also not work. what i've seen is the call wrong. wrong parameter-ordering but then it even does not find the group on ldap.

and i thought, if a group-membership is not found, the login must be denied. even if the account exists locally... so how it works acually, i do not need ldap... only for using the same passwort on more services...

It would be also great, if i can define a group for users, and one for admins. If my user is in admin-group, it's admin on friendica. and ir a user is whether in admin or user-group, no login is possible.

i don't know, how to set a second user as admin... but if i find this out, i will make fix/enhancement and a pull-request.

**Comment by xundeenergie** [comment] 2021-06-11 21:01
I made now a few tests. It is really strange... 

only if the section in addon.config.php is named "ldapauth", the variable is ignored, if a underscore is in it.

my config/addon.config.php looks for testing purpose like this:

```
<?php

// Addon configuration

// Copy this configuration file to addon.config.php and edit it if you want to configure addons, see below example for the twitter addon                                                                          

return [
        'ldapauth' => [
            'ldapserver' => 'https://ldap.example.net',
            'ldap_server' => 'https://ldap.example.com',
        ],
        'foobar' => [
            'ldapserver' => 'https://ldap.example.net',
            'ldap_server' => 'https://ldap.example.com',
        ],
        'twitter' => [
                'consumerkey' => '1234567890',
                'consumersecret' => 'ABCDEFGHIJKLMONPQRSTUVWXYZ',
                'consumer_secret' => 'ABCDEFGHIJKLMONPQRSTUVWXYZ',
        ],
];
```

then i added a few lines in ldapauth.php
```
function ldapauth_authenticate($username, $password)
  {
+         $ldap_serve3   = DI::config()->get('foobar', 'ldapserver');
+         $ldap_serve2   = DI::config()->get('foobar', 'ldap_server');
+         $ldap_serve1   = DI::config()->get('ldapauth', 'ldapserver');
          $ldap_server   = DI::config()->get('ldapauth', 'ldap_server');
          $ldap_binddn   = DI::config()->get('ldapauth', 'ldap_binddn');
          $ldap_bindpw   = DI::config()->get('ldapauth', 'ldap_bindpw');
          $ldap_searchdn = DI::config()->get('ldapauth', 'ldap_searchdn');
          $ldap_userattr = DI::config()->get('ldapauth', 'ldap_userattr');
          $ldap_group    = DI::config()->get('ldapauth', 'ldap_group');
          $ldap_autocreateaccount = DI::config()->get('ldapauth', 'ldap_autocreateaccount');
          $ldap_autocreateaccount_emailattribute = DI::config()->get('ldapauth', 'ldap_autocreateaccount_emailattribute');                                                                                        
          $ldap_autocreateaccount_nameattribute  = DI::config()->get('ldapauth', 'ldap_autocreateaccount_nameattribute');                                                                                         
+         $twitter_consumer = DI::config()->get('twitter', 'consumer_secret');
+         $twitter_consumer_orig = DI::config()->get('twitter', 'consumersecret');
+ 
+         Logger::error('Twitter', ['consumer' => $twitter_consumer, 'consumer_orig' => $twitter_consumer_orig]);                                                                                                 
+         Logger::error('LDAP', ['server' => $ldap_server, 'server_1' => $ldap_serve1]);
+         Logger::error('FOOBAR', ['server' => $ldap_serve2, 'server_1' => $ldap_serve3]);
  
          if (!extension_loaded('ldap') || !strlen($ldap_server)) {
                  Logger::error('Addon not configured or missing php-ldap extension', ['extension_loaded' => extension_loaded('ldap'), 'server' => $ldap_server]);                                                
                  return false;
          }
```

The output on a loginattempt with an unregistered user (which should fail) looks like this (DEBUG is Loglevel)

```
2021-06-11T20:58:06Z index [INFO]: No HTTP_SIGNATURE header [] - {"file":"HTTPSignature.php","line":476,"function":"getSigner","uid":"e6e969","process_id":515663}
2021-06-11T20:58:06Z index [ERROR]: Twitter {"consumer":"ABCDEFGHIJKLMONPQRSTUVWXYZ","consumer_orig":"ABCDEFGHIJKLMONPQRSTUVWXYZ"} - {"file":"ldapauth.php","line":101,"function":"ldapauth_authenticate","uid":"e6e969","process_id":515663}
2021-06-11T20:58:06Z index [ERROR]: LDAP {"server":"","server_1":"https:\/\/ldap.example.net"} - {"file":"ldapauth.php","line":102,"function":"ldapauth_authenticate","uid":"e6e969","process_id":515663}
2021-06-11T20:58:06Z index [ERROR]: FOOBAR {"server":"https:\/\/ldap.example.com","server_1":"https:\/\/ldap.example.net"} - {"file":"ldapauth.php","line":103,"function":"ldapauth_authenticate","uid":"e6e969","process_id":515663}
2021-06-11T20:58:06Z index [ERROR]: Addon not configured or missing php-ldap extension {"extension_loaded":true,"server":""} - {"file":"ldapauth.php","line":106,"function":"ldapauth_authenticate","uid":"e6e969","process_id":515663}
2021-06-11T20:58:06Z index [WARNING]: authenticate: failed login attempt {"action":"login","username":"adminfoobar","ip":"10.0.100.10"} - {"file":"Authentication.php","line":250,"function":"withPassword","uid":"e6e969","process_id":515663}
2021-06-11T20:58:06Z index [INFO]: No HTTP_SIGNATURE header [] - {"file":"HTTPSignature.php","line":476,"function":"getSigner","uid":"70523e","process_id":515139}
2021-06-11T20:58:07Z index [INFO]: No HTTP_SIGNATURE header [] - {"file":"HTTPSignature.php","line":476,"function":"getSigner","uid":"7d934b","process_id":515970}
2021-06-11T20:58:07Z index [INFO]: No HTTP_SIGNATURE header [] - {"file":"HTTPSignature.php","line":476,"function":"getSigner","uid":"9ecbf5","process_id":515663}
```

Here you can explicitely see, that variables with underscore are accepted (twitter and foobar) but not when the config-section is called "ldapauth"
I gave you 6 examples with and without underscore including the logging-lines. 

and if the variable is set in addon/ldapauth/config/ldapauth.config.php, underscores are taken in variable-names... for the same variable.

**Comment by xundeenergie** [comment] 2021-06-11 21:04
And when i login with credentials of an existing user with the SAME configuration as above, i get this and can login:

```
2021-06-11T21:02:35Z index [INFO]: No HTTP_SIGNATURE header [] - {"file":"HTTPSignature.php","line":476,"function":"getSigner","uid":"fc309c","process_id":515663}                                                
2021-06-11T21:02:35Z index [DEBUG]: Contact found {"url":"https:\/\/friendica.schuerz.at\/profile\/jakob","uid":0,"update":false,"cid":6} - {"file":"Contact.php","line":1076,"function":"getIdForURL","uid":"fc309c","process_id":515663}
2021-06-11T21:02:35Z index [INFO]: auth_identities: Array
(
    [0] => Array
        (
            [uid] => 3
            [username] => Mee and Bobby Mc Gee
            [nickname] => meeee
        )

    [1] => Array
        (
            [uid] => 5
            [username] => First Forum
            [nickname] => bla
        )

    [2] => Array
        (
            [uid] => 6
            [username] => Second forum
            [nickname] => foo
        )

)
 [] - {"file":"Authentication.php","line":325,"function":"setForUser","uid":"fc309c","process_id":515663}
2021-06-11T21:02:35Z index [INFO]: No HTTP_SIGNATURE header [] - {"file":"HTTPSignature.php","line":476,"function":"getSigner","uid":"f8f584","process_id":515139}                                                
2021-06-11T21:02:35Z index [DEBUG]: Contact found {"url":"https:\/\/friendica.schuerz.at\/profile\/jakob","uid":0,"update":false,"cid":6} - {"file":"Contact.php","line":1076,"function":"getIdForURL","uid":"f8f584","process_id":515139}
```

**Comment by xundeenergie** [comment] 2021-06-11 21:43
So found out something else...
I played around with the section-name 'ldapauth' in config/addon.config.php. And for sure, i adapted the function in ldapauth.php too

if the config-section is called
'dapauth', the values for server and server1 are "null"
if the config-section is called
'ldapaut', the values are taken for ldap_server and ldapserver... 
if the config-section is called
'authbla', the values are taken for ldap_server and ldapserver.

'ldaauth' works
'dauth' works

Obviously it hangs on the "auth" at the end in section-name. But not in all cases... 

It is really strange. Maybe there is in DI.php a function called "auth"... but I'm not really sure.

**Comment by MrPetovan** [comment] 2022-11-20 15:38
Duplicate of #10188

**Closed as not planned by MrPetovan** 2022-11-20 15:38 UTC
Labels: Bug
