### ISSUE TITLE
Twitter Plugin is forgetting links #import

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4304] opened 2018-01-22 07:40 UTC
On Twitter I retweeted a post and commented it with an additional link. Wenn I get this Tweet in friendica my additional link is lost

Twitter Post (contains 2 Links) https://twitter.com/hoergen/status/955339767314616320
![01_temp](https://user-images.githubusercontent.com/24474762/35209741-b333ad4c-ff4f-11e7-96bd-56b43f160dcb.png)

Friendica import (contains only 1 Link) https://horche.demkontinuum.de/display/2196d4ee165a659303639b7066684603
![00_temp](https://user-images.githubusercontent.com/24474762/35209749-bddd4032-ff4f-11e7-99ca-a9f6bc701bd4.png)

**Comment by MrPetovan** [comment] 2018-01-22 12:38
Exact duplicate of #4014

**Closed by MrPetovan** 2018-01-22 12:38 UTC
Labels: Addons, Bug
