### ISSUE TITLE
[frio] Clicking "Preview" on a comment actually submits it

### ISSUE THREAD

**Issue by clacke** [friendica/friendica#7498] opened 2019-08-11 02:33 UTC
### Expected behavior

"Preview" on a comment renders it for me, and doesn't submit it as a comment.

### Actual behavior

It doesn't render. It submits.

### Steps to reproduce the problem

Write a comment, click Preview.

### Friendica version you encountered the problem

`This is Friendica, version 2019.09-dev that is running at the web location https://libranet.de. The database version is 1320, the post update version is 1297.`

**Comment by MrPetovan** [comment] 2019-08-11 03:23
Which theme are you using?

**Comment by tobiasd** [comment] 2019-08-11 05:47
Title of the issue says "Frio"

**Comment by MrPetovan** [comment] 2019-08-11 06:14
Doh!

**Comment by AlfredSK** [comment] 2019-08-11 06:49
Hmm. I tested it right now and I cannot confirm the issue.
I tried it with Chromium on desktop. I have the new compose page enabled for my user only, if that is important.

**Comment by AlfredSK** [comment] 2019-08-11 06:55
Ah! OK. Now I can confirm! :-) When the window is narrow enough to jump to mobile view, the preview button indeed seems to do nothing. When you then refresh the page the comment has been posted instead.
Tested with Firefox.

**Comment by AlfredSK** [comment] 2019-08-11 06:58
OK. That happens ONLY with Firefox NOT with Chromium (no matter what view, desktop or mobile view). Weird.

**Comment by AlfredSK** [comment] 2019-08-11 07:03
OK. This could be an issue with adblocking. When I disable uBlock origin for the domain in Firefox everything works as expected.

**Comment by AlfredSK** [comment] 2019-08-11 07:07
I give up. Now it works in every browser again no matter if adblocking is enabled or not. I need coffee.

**Comment by AlfredSK** [comment] 2019-08-11 07:40
A user from squeet.me has confirmed the issue. Seems to be a bug then...

**Comment by annando** [comment] 2019-08-11 09:45
squeet.me is on a very current develop branch, I just updated it this week.

**Comment by MrPetovan** [comment] 2019-08-17 04:05
I can confirm this on the `develop` branch.

**Comment by MrPetovan** [comment] 2019-08-18 12:40
This is a Javascript cache issue, the expected `preview` query parameter controlling sending/previewing has been moved from the HTML form to the Javascript action. Unfortunately, the HTML change is immediate while the Javascript change requires a cache clear. In the meantime, the preview feature is unavailable.

**Comment by AlfredSK** [comment] 2019-08-18 12:42
Yeah. I thought so, too. Because after some tests (see above) I couldn't reproduce it anymore.

**Comment by MrPetovan** [comment] 2019-08-18 12:58
I would like to go one step further and differentiate the post/preview endpoints but it's going to require a Javascript change again 🤷‍♂️

**Comment by MrPetovan** [comment] 2019-08-18 13:12
Closing as it can't be fixed from the code, but it needs to be addressed in the Release Notes.

**Closed by MrPetovan** 2019-08-18 13:12 UTC
Labels: Bug, UX
