### ISSUE TITLE
frio: after failed login, login layout displaced

### ISSUE THREAD

**Issue by PolynomialDivision** [friendica/friendica#5814] opened 2018-10-03 08:07 UTC
### Expected behavior
Layout of Login Page should stay the same.

### Actual behavior
Text fields are shifted to the top corner of the site.
![friendica_normal](https://user-images.githubusercontent.com/10708466/46397916-de13eb00-c6f3-11e8-80b8-5ecd87530db6.png)
![friendica_failed_login](https://user-images.githubusercontent.com/10708466/46397927-e2400880-c6f3-11e8-88a2-3b9ab5edb931.png)

### Steps to reproduce the problem
Do a wrong login try.
OR Just try to open login page with /login ...
https://friendica.astatu.berlin/login

### Friendica version you encountered the problem
2018.09

### Friendica source (git, zip)
git

**Comment by JonnyTischbein** [comment] 2018-10-03 10:51
I guess the problem is that the `/src/Module/Login.php` redirects to `/login` even if authentification failed.
When I get it right is the home template including the login template.

    141		} catch (Exception $e) {
    142			logger('authenticate: failed login attempt: ' . notags($username) . ' from IP ' . $_SERVER['REMOTE_ADDR']);
    143			notice($e->getMessage() . EOL);
    144			goaway(self::getApp()->get_baseurl() . '/login');
    145		}

The problem accurse on small screens.

Also I noticed that the function `notice` doesn't appear. My suggestion:

    143    info("Login failed: " . notice($e->getMessage() . EOL);
    144    goaway('/'); // OR goaway();

In a short test it worked.

**Comment by MrPetovan** [comment] 2018-10-04 19:52
Closed via #5816

**Closed by MrPetovan** 2018-10-04 19:52 UTC
Labels: Bug, UI/Theme, UX
