### ISSUE TITLE
/network endless scrolling problem

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#9432] opened 2020-10-17 07:54 UTC
- [X] I have searched open and closed issues for duplicates

### Bug Description
The endless scrolling will load endlessly. 

### Steps to Reproduce

1. Got to /network, switch to "Latest posts" in the top. 
2. Go to /network by the link in the top menu of Frio. 
3. Scroll down all the way to the bottom, " Loading more entries... " will be shown forever. 
4. Scroll up, switch from "Latest posts" to "Latest activity" (does not matter, other work too).
5. Scroll down to the bottom, new posts should load. 
6. Switch to "Latest posts" again, scroll down, new posts should load. 
7. Click on the /network link again in the top of the Frio theme. 
8. Scroll down to the bottom, load will take forever.

**It seems it is also working, when you're in /network and then change the selection to the same selection again, ie. you're in "Latest posts" and click on "Latest posts" again. This will change the URL from "/network" to "/network?order=received".** 

Actual Result:
Loading takes forever. 

Expected Result:
Loads new posts in less than 1 sec. 

### Screenshots
Not needed. 

### Platform Info

Friendica Version:
Latest development, "git pull" said "Already up to date."

Friendica Source: git

PHP version: PHP 7.4.11

SQL version: mariadb  Ver 15.1 Distrib 10.5.6-MariaDB

**Comment by annando** [comment] 2020-10-17 08:20
Could be fixed by https://github.com/friendica/friendica/pull/9431

**Comment by utzer** [comment] 2020-10-20 04:35
Currently not fixed for me. I should be on the develop branch from yesterday evening. I will check details some time today to make sure.

**Comment by utzer** [comment] 2020-10-20 17:47
Latest dev

This has endless scrolling:
https://social.yl.ms/network?order=commented

Here it doesn't work:
https://social.yl.ms/network

**Comment by MrPetovan** [comment] 2020-10-20 17:54
I've removed the need for the `order` GET parameter to be provided and this might be the consequence.

**Comment by AlfredSK** [comment] 2020-10-20 17:55
I tried to reproduce this but couldn't. Followed the steps. Infinite scrolling worked here.
Tested with Chrome/Android and Chromium/Linux.

**Comment by annando** [comment] 2020-10-20 18:28
@MrPetovan but I introduced some fix for this.

**Comment by MrPetovan** [comment] 2020-10-20 18:56
And maybe it wasn't enough? If @ben-utzer still experience the same issue without the GET parameter?

**Comment by utzer** [comment] 2020-10-20 19:01
Maybe I need to clean the cache? Hmm will do it.

**Comment by utzer** [comment] 2020-10-20 19:44
That didn't help. Anyone want to have anything from the logs?

**Comment by MrPetovan** [comment] 2020-11-01 04:24
What about now on the `develop` branch?

**Comment by utzer** [comment] 2020-11-01 13:23
> What about now on the `develop` branch?

No, still doesn't work, I did just pull now but still the infinite scroll (that is what the setting is called) does not work in /network, but only in /network?order=received (didn't try the other registers).

**Comment by annando** [comment] 2020-11-01 16:39
Since it does seem to work for everyone else, I slowly come to the conclusion that it is a local problem. Probably this is a browser issue or some plugin that disrupts the communication. Part of the whole construct are session variables. And they are a likely target for some privacy plugins. So possibly you could try with a different browser with no plugins installed?

**Comment by utzer** [comment] 2020-11-02 14:38
> Since it does seem to work for everyone else, I slowly come to the conclusion that it is a local problem. Probably this is a browser issue or some plugin that disrupts the communication. Part of the whole construct are session variables. And they are a likely target for some privacy plugins. So possibly you could try with a different browser with no plugins installed?

I recall there was at least one other person with the issue. I would have to search for the post. 

But however, clean install of Chromium has the same problem. No addons, settings out of the box.

**Comment by AlfredSK** [comment] 2020-11-02 19:20
Anything in browser console?

**Comment by utzer** [comment] 2020-11-02 20:14
Yes, I think that will help. 
Some 404:
![image](https://user-images.githubusercontent.com/8361662/97914473-3cd34500-1d50-11eb-9a6e-1af150a4b404.png)

The given URL leads to the "Not found" page of Friendica, which gives:
```
#0 [internal function]: Friendica\Module\HTTPException\PageNotFound::content()
#1 /srv/http/src/App/Page.php(331): call_user_func()
#2 /srv/http/src/App/Page.php(387): Friendica\App\Page->initContent()
#3 /srv/http/src/App.php(559): Friendica\App\Page->run()
#4 /srv/http/index.php(42): Friendica\App->runFrontend()
#5 {main}
```

Any tips on this?

**Comment by MrPetovan** [comment] 2020-11-02 20:58
It's indeed missing a `?` instead of the first `&` before `mode=raw` in the faulty URL.

**Comment by utzer** [comment] 2020-11-02 22:12
> It's indeed missing a `?` instead of the first `&` before `mode=raw` in the faulty URL.

Let me know if I can help with any further information. Let me know if this problem is caused on my end, assuming not. 


I sometimes don't follow up well and might also forget, but I am always happy to helpout with more information.

**Comment by MrPetovan** [comment] 2020-11-03 01:10
Based on your error message, I was able to devise a fix for it. Now the interesting thing is that my install also had these wrong URLs, but it was correctly interpreted anyway. Between the URL rewriting and the Router, we apparently have a self-correcting system but it isn't 100% reliable.

My fix straightens out the infinite content scroll Ajax URL query string parameters, which shouldn't rely on the multiple elements of the chain to come out right.

**Closed as completed** 2020-11-03 18:47 UTC
Labels: Bug

**Comment by utzer** [comment] 2020-11-03 21:35
> Based on your error message, I was able to devise a fix for it. Now the interesting thing is that my install also had these wrong URLs, but it was correctly interpreted anyway.

Yes, that was very strange. I seems to depend on the/my host, at least I tried different clients/browsers. Thanks for following up on it, I appreciate it alot. Thanks @annando and @MrPetovan
