### ISSUE TITLE
Queue fix

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#12253] opened 2022-11-24 01:02 UTC
Image > https://reisub.nsupdate.info/filehost/files/53u.jpg

Log https://friendicarg.nsupdate.info/log/friendica.log

**Comment by bkil** [comment] 2022-11-24 01:05
I believe this is a duplicate of #12111 #12113. After you have confirmed this, you can close this issue and remove the shared log file.

**Comment by bkil** [comment] 2022-11-25 22:12
How many rows do you have in the workerqueue table where command is ForkHook with payload mentioning mailstream_send_hook?

I think what might be happening is that despite the fact that you have deactivated the faulty mailstream addon, its hook got queued for workers. Then they will happily attempt to invoke that function from that PHP file.

What I have recommended weeks ago is that you should activate mailstream and copy & paste the new version of this file instead
- https://github.com/friendica/friendica-addons/blob/f2ff1053b096977cf31cca5559a0f7ef6f91e21b/mailstream/mailstream.php

**Comment by mama21mama** [comment] 2022-12-01 19:40
Solved

**Closed as completed** 2022-12-01 19:57 UTC
Labels: Sup­port Request
