### ISSUE TITLE
frio: login design: replace icon with Login button

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#3671] opened 2017-08-30 13:09 UTC
Current design for users not logged in

![frio theme no logged in users](https://user-images.githubusercontent.com/5708172/29873540-ef84a662-8d93-11e7-87a6-bd0b1f1a9a58.jpg)

**Current Problems**

- the buttons are confusing as to what kind of action they trigger, the login icon actually looks like the icon often used to logout / leave a service
- tooltip helps, but login / register should be usable even without tooltips required
- login / register both trigger an overlay where login / signup is done

**Proposed improvements**

- [x] replace icons with buttons "Register" and "Login" (buttons have text, thus tooltip no longer required and to be removed)
- [x] optionally text fields for username / email and password could be displayed (that would allow immediate login without requiring any overlay or view switching)
- [ ] optionally even the sign up form could be displayed on the startpage of a friendica instance (since the user is not logged in, either 1. they want to login or 2. are not users yet, so immediate and easy signup should call for action and be easily available on the default landing page of an instance)

Details of this proposal sure subject to debate and a few ideas are drawn from facebook. We don't have to, nor do we want to copy facebook and yet, there seems to be good reasoning behind their design decisions for the default landing page. See screenshot (sorry it's in german):

![facebook](https://user-images.githubusercontent.com/5708172/29873852-296c5496-8d95-11e7-8363-776ef74f1b0d.jpg)

**Comment by AlfredSK** [comment] 2017-08-30 18:54
The look in the picture of squeet.me is caused by the community home plugin. Without this plugin the visitor has a login form and a login button (also a register link and a password recovery link).
But I agree in general. The home/login and register pages need more love (a better look).

**Comment by rabuzarus** [comment] 2018-02-08 15:31
Since we restyled the frio login page this issue is fixes. So I close it.

**Comment by foss-** [comment] 2018-02-08 17:12
Remaining:

*  replace icons with buttons "Register" and "Login" (buttons have text, thus tooltip no longer required and to be removed) - on pirati.ca I still see the door button which opens a login overlay over the existing login form. I'd still propose to remove the top icons from the login page. It is still unclear what the door icon does. Usually it is used to logout. But here it's actually login. Also opening a secondary login form over the existing login form is quite confusing.
![login1](https://user-images.githubusercontent.com/5708172/35987011-e750089c-0cfa-11e8-9b8a-d655a754fd69.png)
*  optionally even the sign up form could be displayed on the startpage of a friendica instance (since the user is not logged in, either 1. they want to login or 2. are not users yet, so immediate and easy signup should call for action and be easily available on the default landing page of an instance) - this is also still missing. there's a register button, which takes the user to the register page. I can live with that. but there's room for improvement. If others think that's fine as is, let's ignore this one and focus on the remaining icon issue.

@rabuzarus re-open until the icon thing is solved as well?

**Comment by foss-** [comment] 2018-02-08 17:49
icons are addressed with https://github.com/friendica/friendica/pull/4421

Let's close this one as fixed and whenever someone feels like wanting to invest time into improving the register process have a separate ticket for that then.

**Closed** 2018-02-08 17:54 UTC
Labels: UI/Theme
