### ISSUE TITLE
Diaspora and RSS seems to be broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11751] opened 2022-07-19 19:13 UTC
- [X ] I have searched open and closed issues for duplicates

### Bug Description
I don't receive any posts from Diaspora since 2 days. 
Also, I just noticed that I don't get any RSS posts anymore. The RSS contacts are gone.

Just a quick emergency report w/o details. I can provide them if needed.
 
### Platform Info

Friendica Version:
2022.09-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

**Comment by AlfredSK** [comment] 2022-07-19 19:43
Diaspora: Looks like all incoming Diaspora posts are invalid.

```
Invalid posting [] - {"file":"Diaspora.php","line":478,"function":"dispatchPublic","uid":"9fc3df","process_id":4057082}
```

**Comment by AlfredSK** [comment] 2022-07-19 19:59
RSS/Atom: contacts page -> no rss protocol anymore

![grafik](https://user-images.githubusercontent.com/3656054/179837693-ee6b887c-569c-415b-8eca-b1217a639ebf.png)

**Comment by AlfredSK** [comment] 2022-07-19 20:10
Diaspora: Checked out an earlier commit. Diaspora is working again. The emergency fix has damaged it for me. 😀

HEAD is now at 06698cc5f Test?

**Comment by AlfredSK** [comment] 2022-07-19 20:17
For me this PR #11747 has made a change to Diaspora that made all incoming Diaspora content invalid. I went back one commit before that and it seems to work again.

**Comment by Quix0r** [comment] 2022-07-19 22:25
2 major changes to `src/Protocol/Diaspora.php` I'm seeing there:
 * `Network::unparseURL()` is being replaced with `Uri::fromParts()` which does the same
 * `Diaspora::sendProfile()` has a changed signature, from `bool` to `array` in 2nd parameter.

I guess the first one isn't the cause, more I suspect second one.

**Comment by DetroitLibertyPenguin** [comment] 2022-07-20 04:12
But my RSS :-(

**Comment by annando** [comment] 2022-07-20 05:18
`Diaspora::sendProfile()` is completely irrelevant for this. It is called when the profile was changed.

**Comment by AlfredSK** [comment] 2022-07-20 05:25
In my log I see that the key is fetched from the remote Diaspora user - then the incoming post is logged as invalid.

**Comment by annando** [comment] 2022-07-20 06:13
It is fixed with this PR: https://github.com/friendica/friendica/pull/11757

**Comment by Quix0r** [comment] 2022-07-20 09:56
Still we should find proper type-hints for it. I just stick to documentation and check usage of it.

**Closed as completed** 2022-07-20 11:58 UTC
Labels: Bug

**Comment by annando** [comment] 2022-07-20 13:59
Some functions simply don't work with type hints. it's possibly better to rethink that whole functionality.

**Comment by MrPetovan** [comment] 2022-07-20 16:08
It's fine not to have type-hints, but it isn't when the actual type hint doesn't match the documentation type hint. In this case the phpDoc said "string" so there was no easy way of knowing it was more than that.

**Comment by AlfredSK** [comment] 2022-07-20 16:46
I want to mention that all RSS/Atom contacts are still lost on my node. I don't have a single RSS contact anymore. Some other users are reporting the same thing.

How can I find out what happened? When I check the contact table in my database all the RSS (feed) contacts have UID=0. So, how is the relationship to the user accounts done? Is there some other table that holds that information? How can I check that? What queries can help me to find out what is wrong?

**Comment by annando** [comment] 2022-07-20 17:28
Give me some time. Currently I'm still at work. Possibly I can have a look it, when I'm at home.

**Comment by DetroitLibertyPenguin** [comment] 2022-10-11 07:27
I see this is closed. Do we have a separate bug for the RSS issue?

Sent from my Smartphone, please dismiss not-so-smart typos.
________________________________

**Comment by MrPetovan** [comment] 2022-10-11 12:30
Yes: https://github.com/friendica/friendica/issues/11807
