### ISSUE TITLE
diabook nav-search-bar - help

### ISSUE THREAD

**Issue by bytedeez** [friendica/friendica#1595] opened 2015-05-23 08:09 UTC
How do i link the nav-search-bar in the diabook theme to the local directory?
Right now it doesn't seems like its useful at all as it does not find friends is the local or global directory.
I know this is a "unsupported theme" but any help would be fantastic and greatly appreciated. Thanks in advance!

**Comment by fabrixxm** [comment] 2015-05-23 15:38
as per [nclude/nav.php](https://github.com/friendica/friendica/blob/bf28cc0f754e22cf8c52d017665e32de69208a45/include/nav.php#L120-L127) , if the system is set as "singleuser", then global directory url is used (because, if the system is set as singleuser, there should be a single user.. so local directory would be quite unusefull)

Check your site settings under `/admin/site/` url

**Comment by fabrixxm** [comment] 2015-05-23 15:41
If you want to keep singleuser settings but link to local directory, you need to modify `view/theme/diabook/templates/nav.tpl`, line 88, change to `href="directory"`

**Comment by bytedeez** [comment] 2015-05-23 18:12
Thanks!
Just to make sure we are on the same page as to what i am trying to do.
My site is set as "multi-user instance".
What i am trying to achieve is using the nav-search-bar to search the site directory. In order to find friends within my private friendica site that is being used just for my community / friends. Right now the way it is in order to search for friends a user has to go to directory and then search for them there. However i would like to make it where they can use the diabook nav-search-bar to find friends. As it stands right now the nav-search-bar yields no results.

**Comment by fabrixxm** [comment] 2015-05-23 18:44
No, you're right, we aren't on same page :)
I don't undestand what is "nav-search-bar" you refer to.
Can you take a screenshot?

**Comment by bytedeez** [comment] 2015-05-23 18:51
![image](https://cloud.githubusercontent.com/assets/7134028/7785375/2ce0e010-015b-11e5-89e2-b824e4ae533f.png)

**Comment by fabrixxm** [comment] 2015-05-23 19:03
ooook.
So, that's not a Diabook issue.
That searchbar is a shorcut to standard search page.
Search page search in posts by default, but if the search term starts with "#" it search in terms, and if it starts with "@" it fetch results from page `/dirfind`.
`mod/dirfind.php` fetch search results from default global directory. If  global directory is not defined (you do that if you want a node detached from global network), it should search in local directory, [but..](https://github.com/friendica/friendica/blob/develop/mod/dirfind.php#L32-L39)

**Comment by bytedeez** [comment] 2015-05-23 19:11
ok gotcha! i am not the best at php i am a novice at best but if i change the address to from my the global directory to http://www.jabbleme.com/directory?search=  it should search from within mu directory correct?

or

do i need to uncomment the line of code after the todo to activate fallback of local site

**Comment by fabrixxm** [comment] 2015-05-23 19:47
if you change the directory url, you don't get any global directory functionality.
And anyway, no, the search would not work.
And no, uncomment will not work, because the code for local search don't exists.

**Comment by rabuzarus** [comment] 2015-07-07 10:00
maybe want to close this? This bug is a question about how to change the behavior of an unsupported theme.

1.) it's a support question (not a bug)
2.) it's not about changing friendicas default behavior
3.) diabook is marked as unsupported

**Comment by annando** [comment] 2015-07-07 16:13
Not really. This search bar is a standard element. Question is if we should transform this issue in a feature request. For example I would like to change the behaviour of the search as well.

**Comment by rabuzarus** [comment] 2015-07-08 12:15
how would you like to change the behavior of the search (nav search field)?

present state:
- enter a term does search for the term in all public conversations on the local instance
- @username search for an user in global directory
- #tagname search for an tag on local instance

What I would like to see is a nice auto completion for tags and directory searches like in diaspora and red (in red autocompletion is only supported for usernames).

**Comment by annando** [comment] 2015-07-08 12:59
Additionally I would like to add "username@domain.tld" for a user search. And I would like to search not only in the global directory but also local and via poco.

Maybe it would also be possible to add a search parameter where you can select between the different search targets.

**Closed** 2015-11-08 12:08 UTC
Labels: UI/Theme
