### ISSUE TITLE
Privacy doesn't work aka strange behaviour

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4616] opened 2018-03-17 09:01 UTC
Checked on frio and vier
Actually I was trying frio and stumbled about a really strange behaviour. I cant restrict reading access at the moment at all. :(

When setting the reading restrictions and nothing is selected except one person. This post will be public. See https://horche.demkontinuum.de/display/2196d4ee985aac1b68146de699484754

An when I select "not to display" to a special group "Alle Mensch" it will do the following
![00_temp](https://user-images.githubusercontent.com/24474762/37553519-f58f8bbc-29c9-11e8-843c-ed88f8a17bb1.jpg)

_Friendica 'Asparagus' 3.6-dev - 1256_

**Comment by hoergen** [comment] 2018-03-17 09:06
Seems, that the first group is hardcoded ? I can't remove it.

**Comment by annando** [comment] 2018-03-17 09:13
Could you test on RC as well?

**Comment by hoergen** [comment] 2018-03-17 09:20
No im sorry. Maybe someone on RC could test?

**Comment by annando** [comment] 2018-03-17 09:33
@tobiasd did some tests. But of course we don't know if you are having a special setup. Possible @MrPetovan can check on his system? I guess he is driving on "dev".

**Comment by hoergen** [comment] 2018-03-17 09:34
What could be a special setup?

**Comment by annando** [comment] 2018-03-17 09:46
Maybe I know after breakfast :-)

**Comment by hoergen** [comment] 2018-03-17 10:02
The tension rises .... ;)

**Comment by MrPetovan** [comment] 2018-03-17 13:52
Yeah, I firmly am on develop until further notice.

**Comment by MrPetovan** [comment] 2018-03-18 14:35
Wasn't this fixed on RC? If so, which PR?

**Comment by annando** [comment] 2018-03-18 14:36
I guess the bug wasn't fixed in RC, but was invented on Dev ;-)

**Comment by MrPetovan** [comment] 2018-03-18 14:46
Fair enough.

**Comment by hoergen** [comment] 2018-03-23 22:07
Didn't thought about it, when switched form branch 3.6 to develop again. Now im struggeling again with this privacy bug :(
Should I revert to 3.6 again?

**Comment by MrPetovan** [comment] 2018-03-23 22:11
I’m not sure you can because potential DB changes.

**Comment by annando** [comment] 2018-03-23 22:25
I can only say that we are using the field "allow_cid". "allow_gid", "deny_cid" and "deny_gid" for a list of allowed or denied contact ids and group ids. These doesn't seem to be filled correctly via the new ACL class.

**Comment by hoergen** [comment] 2018-03-23 23:34
To describe it a little more

When I open new post. Nothing is selected. But there should be the group "Alle Mensch" selected. 
1. Reality 
2.  What I want to have
![00_temp1](https://user-images.githubusercontent.com/24474762/37857290-35b7812e-2efa-11e8-8449-049d91597583.jpg)

In the settings there is also nothing selected. I'm able to select it, but I can't save that selection. When I reopen this setting, there is again nothing selected.

![00_temp2](https://user-images.githubusercontent.com/24474762/37857332-804a1170-2efa-11e8-96e1-918e791272e8.jpg)

When I write a post there is always "Alle Mensch" like hardcoded selected, but not visible. If I select "not display" the post will look like the second picture on the right side (selected, ~~not selected~~)
![00_temp3](https://user-images.githubusercontent.com/24474762/37857367-b4df2cb8-2efa-11e8-9a95-760d5a66f87c.jpg)

**Comment by MrPetovan** [comment] 2018-03-24 00:06
Thanks for the detailed explanation, I'll try to reproduce the issue.

**Comment by tobiasd** [comment] 2018-03-24 06:41
In the Vagrant VM it seems that the additional selected "not" group alsways overrides the selection "show" group. I'll test that from my account as well (though that is on the stable branch and I'm not updating because of this issue here ;-) ).

**Comment by rabuzarus** [comment] 2018-03-24 08:53
Have you checked in your browser console if there are some js errors?

**Comment by hoergen** [comment] 2018-03-24 09:07
Thanks @tobiasd your workaround works https://github.com/friendica/friendica/issues/4616#issuecomment-375850328 <3 
@rabuzarus I can't see any errors. I don't think it'S GUI related, there is something in the Backend.

**Comment by tobiasd** [comment] 2018-03-24 10:13
> Thanks @tobiasd your workaround works
> https://github.com/friendica/friendica/issues/4616#issuecomment-375850328
> <3

It's the way, I always change my ACL default settings. Default are 4 groups active. Those I reset make the posting public and then select the new recipients.

> @rabuzarus I can't see any errors. I don't think it'S GUI related,
> there is something in the Backend.

Nothing in the browser console here.

**Comment by MrPetovan** [comment] 2018-03-24 12:55
I was able to verify that the ACL screen doesn't show the current default permission settings, which would explain both problems.

**Comment by annando** [comment] 2018-03-24 13:51
@MrPetovan Are you working on this?

**Comment by MrPetovan** [comment] 2018-03-24 13:56
No, if it was up to me, I would replace the ACL selector with an auto-completed tag-like field instead of this huge gallery.

**Comment by annando** [comment] 2018-03-24 14:02
We need a quick solution so that "develop" is working reliable again. After this we can have a look at improving this dialog.

**Comment by MrPetovan** [comment] 2018-03-24 14:09
I'm leaving to march against gun violence right now, good luck to anyone tacking this!

**Comment by annando** [comment] 2018-03-24 15:45
Marching against gun violence is much more important!

**Comment by annando** [comment] 2018-03-24 18:49
The issue is found and corrected. It's just waiting to be merged.

**Comment by MrPetovan** [comment] 2018-03-24 19:48
Closed through #4674

**Comment by hoergen** [comment] 2018-03-24 20:08
Something is still not ok. I have to click 5 times on the default group, so that it is not selected any more. Or use the workaround from @tobiasd

**Comment by MrPetovan** [comment] 2018-03-24 20:18
I just tested with the latest version, and clicking once was enough to deselect the default selected group and for "Visible for everybody" to be selected instead. Not sure how to reproduce this new issue.

**Comment by MrPetovan** [comment] 2018-03-24 20:21
Actually, I'm not able to revert my default permission setting to "Visible to everybody", so something is still amiss indeed.

**Comment by hoergen** [comment] 2018-03-24 20:24
I found the same 5-times-click behaviour in the settings. It's kind of funny, because every group else it's only one click needed, only the default group wants to have the 5-timer ;)

**Comment by MrPetovan** [comment] 2018-03-24 20:25
Ah, never mind, I didn't press "Save Settings" after having changed the default permission setting. Back to square one. I can't reproduce the issue you still have.

**Comment by MrPetovan** [comment] 2018-03-24 20:25
Please try the frio theme?

**Comment by hoergen** [comment] 2018-03-24 20:26
I'm using actually frio them since some days. I tried it also with vier. The same.

**Comment by annando** [comment] 2018-03-24 21:13
I guess that you had to remove it 5 times, since it had been added five times.

**Comment by hoergen** [comment] 2018-03-24 23:48
After the last git pull there is only 1 time clicking necessary. So I think the issue can be closed now?

**Comment by MrPetovan** [comment] 2018-03-24 23:53
You can do it yourself but I'll gladly do it for you!

**Closed by MrPetovan** 2018-03-24 23:53 UTC
Labels: Bug
