### ISSUE TITLE
instantly reflect use of "like" toggle in UI

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#2845] opened 2016-10-05 11:46 UTC
**Currently:** User presses the thumbs up / like toggle but there is no indication the toggle press was accepted. Basically nothing happens. This is very bad UX.

**Expected:** Ideally, friendica would instantly update the like status and show the users that liked the post in question, including the user that just pressed the toggle.

I have no idea, what the technical limitations are here or what's missing to implement this. Also a brief search showed this issue did not yet exist. So I hope I did not file a dupe.

Any work in this area would be appreciated.

**Comment by tobiasd** [comment] 2016-10-05 12:08
> Currently: User presses the thumbs up / like toggle but there is no
> indication the toggle press was accepted. Basically nothing happens.
> This is very bad UX.

Which theme are you using?

In quattro/vier after clicking on the like button, there is a spinning wheel in the upper right corner of the posting. After it stops, the list of people who liked the posting is updated.

**Comment by foss-** [comment] 2016-10-05 12:17
vier, dark, Firefox 49.0.0 on macOS 10.12
@tobiasd you happen to be in friendica IRC?

**Comment by annando** [comment] 2016-10-05 12:25
This is a side effect of the "like_no_comment" switch in the .htconfig.php

**Comment by Hypolite** [comment] 2016-10-10 03:26
Wait, the rotator should still show when the Like link is clicked, right? There's no condition on its display. 🤔

**Comment by zotlabs** [comment] 2016-10-10 04:06
// Since our ajax calls are asynchronous, we will give a few
    // seconds for the first ajax call (setting like/dislike), then
    // run the updater to pick up any changes and display on the page.
    // The updater will turn any rotators off when it's done.
    // This function will have returned long before any of these
    // events have completed and therefore there won't be any
    // visible feedback that anything changed without all this
    // trickery. This still could cause confusion if the "like" ajax call
    // is delayed and NavUpdate runs before it completes.

    function dolike(ident,verb) {
        unpause();
        $('#like-rotator-' + ident.toString()).show();
        $.get('like/' + ident.toString() + '?verb=' + verb, NavUpdate );
        liking = 1;
        force_update = true;
    }

**Comment by strk** [comment] 2016-10-22 10:16
I'm also experiencing this problem with Frio.

**Comment by Hypolite** [comment] 2016-10-22 18:31
Hi @strk, what branch is your server on? On the `master` branch the rotator has been activated recently (it wasn't used before). It should appear next to the post date. If you're on the `develop` branch then the change has not been added to it because of my pull request mistake.

**Comment by foss-** [comment] 2016-10-23 12:04
Tested. Here's what I found:

**Currently**

- clicking the thumbs-up icon results in a spinner being displayed at the top right of the corresponding post

**Expected**

1. The spinner should be displayed directly at the icon at which an action was initialted. E.g. if a thumbs-up icon is pressed, that icon should switch to the spinner while information is processed.
2. When processing is done, switch back to default icon.
3. When processing is done, ideally the list of users that "thumbed-up" a certain post should be updated. In my test this was no the case.

Is someone doing work in this area? Should this ticket be assigned?

**Comment by tobiasd** [comment] 2016-10-23 16:25
If you work on the issue assign it to yourself; if it is not assigned feel free to fix it ;-)

**Comment by Hypolite** [comment] 2016-10-24 15:34
Is there any way to assign a ticket to a non-collaborator?

**Comment by tobiasd** [comment] 2016-10-24 18:17
Who wants it? Just say you are working on ot and make a PR with a fix for the development branch.

**Comment by Hypolite** [comment] 2016-10-24 20:20
I was just asking about the GitHub "Assignees" filed on the right. Is it project collaborator-only?

**Comment by strk** [comment] 2016-10-25 18:17
On Sat, Oct 22, 2016 at 11:31:39AM -0700, Hypolite Petovan wrote:

> If you're on the `develop` branch then the change has not been added
> to it because of my pull request mistake.

Does it mean the flow is broken forever now ?
... or I'll just repose my trust in maintainers to fix this soon :)

--strk;

**Comment by Hypolite** [comment] 2016-10-25 18:23
The flow is supposed to be merged on the next release, but the PR #2827 could be merged at any time before that.

**Comment by tobiasd** [comment] 2016-12-12 06:41
I think this can be closed with the cherry-picked changes from #2965 right?

**Comment by strk** [comment] 2016-12-12 07:38
I'm running from commit a25910db84af18ea8e465d3bc3b7feca39a4bfd0 and
still don't get the visual feedback of likes. Changes in #2965 *seem*
to be included in that state, do you confirm ?

**Comment by foss-** [comment] 2016-12-12 08:37
Not working on the friendica instance I tested this w which is 3.5.1-dev-1209. Using Firefox 50.0.2 if that matters.

**Comment by Hypolite** [comment] 2016-12-13 16:31
It's working for me on the frio theme for sure. I didn't test the other themes even though I changed them.

**Comment by strk** [comment] 2016-12-13 16:41
I am using the frio them too, and isn't working. What could it be ?

**Comment by strk** [comment] 2016-12-13 16:43
Ok I've just re-tested, and it seems to work when *adding* a like (or dislike)
but not when *removing* it (second click).

In both cases you see the turning circle, but when adding the
"Likes to <nick>" appears while upon re-clicking it does NOT disappear
(it takes a page reload to disappear).

**Comment by Hypolite** [comment] 2016-12-13 17:27
Hi @strk , I can't reproduce the issue. Testing on one of my posts without any likes, clicking on "Like" makes the loading animation appear, then the post is updated with the highlighted "Like" link and the mention I like the post.

Clicking on the "Like" button again, the loading animation shows up one more time, and the post correctly updates with the default Like link and no mention anyone is liking he post.

Original state:
<img width="269" alt="screen shot 2016-12-13 at 12 22 13 pm" src="https://cloud.githubusercontent.com/assets/925415/21151088/40a4f3c6-c12f-11e6-9586-4123bba2c205.png">

Like link clicked (notice the underline and the loading animation):
<img width="269" alt="screen shot 2016-12-13 at 12 21 24 pm" src="https://cloud.githubusercontent.com/assets/925415/21151111/5574b232-c12f-11e6-9291-b2ef83a1b85f.png">

Liked state:
<img width="268" alt="screen shot 2016-12-13 at 12 21 28 pm" src="https://cloud.githubusercontent.com/assets/925415/21151123/5e40851c-c12f-11e6-8d0f-6069c8f4a375.png">

Like link clicked again:
<img width="269" alt="screen shot 2016-12-13 at 12 21 35 pm" src="https://cloud.githubusercontent.com/assets/925415/21151142/6a3553fc-c12f-11e6-946f-9e14207e27b4.png">

Final state (identical to starting):
<img width="269" alt="screen shot 2016-12-13 at 12 22 13 pm" src="https://cloud.githubusercontent.com/assets/925415/21151088/40a4f3c6-c12f-11e6-9586-4123bba2c205.png">

**Comment by strk** [comment] 2016-12-13 17:44
I just tested again, also with another browser.
Both Firefox and Chromium give me all passages correct but the last one,
where the "xxx likes this." message does not disappear.

At this point I wonder if I'm running an old version of something.
Friendica is commit 29bc27fa6a03a2c3ca173b75abeb23e70f35cbc6
addon/ is commit 8ef2b13360c9b7908798b8912cea8af4c218e7ca
what else is left to debug ?

**Comment by Hypolite** [comment] 2016-12-13 18:05
I'll add that this issue didn't deal with the "XXX likes this" part, only with the styling of the Like link. If the loading animation shows up every time you click on the "Like" link and this link is correctly styled according to your latest action (like or unlike), even if it is after a reload, then the problem you are experiencing is out of the scope of this issue and deserves its own issue.

**Comment by foss-** [comment] 2016-12-14 23:16
I wonder what I may be doing wrong. Still running 3.5.1-dev-1209 tested frio since it was mentioned the fix should be working with that. for me nothing happens.

Oh I think now I see something. Wow this is working quite differently from how I imagined it would be working:

Currently: There is a spinner animation right after clicking the like icon. The spinner appears right next to the post date (at least in frio). The spinner then ends and I see no change of the like info.

Expected: I expected the like icon to change to a spinner while work was happening and one the like info has been updated, spinner ends and the like icon re-appears.

So I would not consider this solved and probably should have provided a better description right-away. Sorry for that.

Does that description above make sense? What do you all think how this should behave?

**Comment by Hypolite** [comment] 2016-12-15 02:12
@foss- I wanted a spinner next to each action but the way the spinner is currently implemented in the Js library shared by all themes, there's only one spinner for all the actions of a post, whether it's Like, Dislike, Attend, Maybe or Not Attending.

Also every time you act on a post (including comment), the whole updated post is fetched and replaces the current one. Which means that when the like action is done, what you see isn't the same post whose Like link has been changed, it's a whole new post with a new Like link.

I hope it clears any confusion and helps you refine your request.

**Comment by foss-** [comment] 2016-12-15 17:56
few thoughts:

- **spinner location:** despite the spinner being shared (which is far from ideal, but let's stick to that limitation) accross more than one action, I still think it should be next to the icons where the action is triggerd. depending on the length of a post, the user clicks the icon but the spinner is off screen → not good ux. thus, suggest to put the spinner next to the icons at the bottom of the post
- **update for like icon after clicking action**: it was mentioned that the post is reloaded after the like icon has been clicked. I can confirm that the spinner is now spinning and stoppen as soon as the post is reloaded, *but* I don't see the user name show below the icons claming user_xyz mag das (likes this post). when reloading the website the user name shows. So that's another thing that should be auto-updating after clicking the like icon
- **same as above for "unlike":** when pressing the like icon again, the post should update and the user name be remomved from the list of users who liked the post

That's my current thoughts and a few action tasks if the observations are correct so far. hope they are constructive and useful.

**Comment by Hypolite** [comment] 2016-12-15 20:44
I decided the spinner location when I was testing on a small post, in this context it made sense. My problem was that the number of action links is wildly variable depending on the post type and even the network. Putting the spinner in a location shared by all posts seemed the best idea for me but I didn't think about longer posts.

The two other points you've mentioned aren't related to my work, they're supposed to be taken care of with the normal post update. I only added the Like link styling when you've already liked a post.

I'm guessing your server has the htconfig "like_no_comment" setting activated, which prevents the display of a post to be automatically updated on a Like. (check [the doc](https://github.com/friendica/friendica/blob/master/doc/htconfig.md) out)

**Comment by MrPetovan** [comment] 2018-02-08 01:22
It's been more than a year, I've been using the like function extensively and I can't reproduce the problem, closing for now.

**Closed by MrPetovan** 2018-02-08 01:22 UTC
Labels: New Feature, UI/Theme

**Comment by foss-** [comment] 2018-02-08 15:11
Tested on pirati.ca and it seems to work as expected by now. Thanks for going through the old backlog tickets.

**Comment by MrPetovan** [comment] 2018-02-08 15:19
You’re welcome, it always is satisfying to bring the number of open issues down!
