### ISSUE TITLE
e-coin profile fields

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1488] opened 2015-04-07 02:06 UTC
Hi!
I'm playing around with "e-coin integration" into profiles. For now I simply use the "location" field in the profile as bitcoin/litecoin field as well as the different "profile chapters" (about/hobby/interests).
I think it would be really interesting to provide several fields in the profile for e-coins. Maybe with a prefix field where the user can choose the respective e-coin currency. Actually the filled coin fields could be displayed simply by a small icon of the respective coin, as the real digits aren't very usefull and a link to a site where the wallet and QR code is displayed would be enough.
In this profile  https://tupambae.net/profile/lahpxyne5muvfqrtytsxhdfhjkfec6rxy9/?tab=profile you can see the kind of implementations I'm thinking about. I actually used a litecoin address as account name in this case. As a result those accounts show up in google searches and basically link a wallet to a social profile "to talk to". As the owner of the wallet can by signiture verify at any given moment the ownership of the account/wallet or particular statements we basically create social wallet profiles with an option like this.

**Comment by MrPetovan** [comment] 2018-02-22 03:27
Duplicate of #1606

**Closed by MrPetovan** 2018-02-22 03:27 UTC
Labels: New Feature, UI/Theme
