### ISSUE TITLE
No way to wall-to-wall post to a forum 

### ISSUE THREAD

**Issue by dfsklar** [friendica/friendica#3833] opened 2017-10-29 18:46 UTC
To repro:
1. Set up a public forum account and provide for automatic acceptance of new friends.
2. Login to a regular account.
3. Go to the forum's profile and hit CONNECT.  You will get automatically accepted and you'll see notifications confirming that you are now a "contact" of the forum (Forum is sharing with you).
4. Visit the forum's "Status" subpanel.  You will be able to see posts that the forum itself created but  you will not be able to add posts to that wall. There are no edit boxes available. This contradicts the information found on https://github.com/friendica/friendica/wiki/Friendica-forums-and-community-pages, which specifies that we will be able to post directly on the forum's status panel (which I assume is what the doc means by "wall to wall").

I've double-confirmed that the regular account is indeed a true "contact" of the public forum's account.  The confirmation email made it clear that the regular account was deemed a "FAN" only, however since the forum is public and since the public forum's settings say "allow friends to post to status page", the regular account *should* be able to post onto the forum's status panel.  

See attached images for clarifications.  The final image shows that the status panel is not allowing the regular user (a confirmed fan/friend) to react to the forum's posts (e.g. "like") nor to post to the forum's status wall.

![screen shot 2017-10-29 at 2 29 56 pm](https://user-images.githubusercontent.com/1151882/32147101-de385482-bcb7-11e7-8436-5c41b73b92e6.png)

![screen shot 2017-10-29 at 2 30 32 pm](https://user-images.githubusercontent.com/1151882/32147105-e3665fd0-bcb7-11e7-8b7f-8862110351e3.png)

![screen shot 2017-10-29 at 2 31 10 pm](https://user-images.githubusercontent.com/1151882/32147107-eb6019ce-bcb7-11e7-8d51-74f42cc52701.png)

![screen shot 2017-10-29 at 2 30 48 pm](https://user-images.githubusercontent.com/1151882/32147108-fb266a02-bcb7-11e7-9690-e8d2a3d75d54.png)

**Comment by dfsklar** [comment] 2017-10-29 19:15
There is evidence that there was an attempt to establish a difference between "readonly" fans and "read/write" fans.  But this was never exposed in the GUI in any settings area.

E.g. I found this:
```
$a->strings["Automatically approve all connection/friend requests as read-write fans"] = "";
```
but never found it in any settings area in the GUI.

**Comment by dfsklar** [comment] 2017-10-29 20:13
WORKAROUND:  Tamper with the DB and set the contact rel to 3 (mutual friendship).  This allows the regular user to indeed post on the forum's wall.  So really this issue is indeed one re: settings not revealing sufficient options:  there is no setting allowing the default contact type to be mutual friend, not "just a fan".  This setting should be exposed for all forum types.

**Comment by annando** [comment] 2017-10-30 06:58
Wall-to-Wall-posts at a forum's page are currently possible. I just tested it with the support forum. The text that you discovered above is used for personal accounts, not for forum accounts.

So we now have to check two things:
1. Does the subscribe to a forum currently work
2. Which configuration issues could exist when creating a forum account

**Comment by tobiasd** [comment] 2017-10-30 08:09
> 4. Visit the forum's "Status" subpanel. You will be able to see posts that the forum itself created but you will not be able to add posts to that wall. 

If you visit the forum page via a magic link (the link in the contacts overview should work I think), you will be greeted by the forum node. Then you can write new postings, comment and dis-/like entries etc..

But you do not need to write wall-to-wall on a forums wall to publish new entries there. You can just write a new posting on your node. Set the access rights such that the forum receives the posting and @-mention it. Your posting will be distributed to all other persons using that forum.

**Comment by tobiasd** [comment] 2017-10-30 08:17
> WORKAROUND: Tamper with the DB and set the contact rel to 3 (mutual friendship). This allows the regular user to indeed post on the forum's "network wall"

This is not how a forum is supposed to work. A forum is just meant to distribute your postings in which you @-mention it to all the other contacts following the forum. These postings will be shown at the forums profile "Status" tab. 

The network tab of a forum account is *just* noise you don't have to think about. You can even set this noise to be automatically deleted after a day. All postings that contain the @-mention for the forum will be *posted* by the forum to all its followers, so they are not foreign postings concerning the auto-deletion settings.

**Comment by kittmcgregor** [comment] 2018-04-08 00:44
Hi,
Is this something that can be modified easily with a plugin/add-on?If no-one else is doing this I'm keen to.
I'd also like to add a lot of other features, BUT is the current forum system the best place to do this?
I've seen a lot of people wanting a system like Discourse http://discourse.org
Do we need to start again to create something like that or can we modify the current forum?

**Comment by MrPetovan** [comment] 2018-04-08 01:03
Hi @kittmcgregor, thanks for your interest, currently very few behaviors can be significantly modified through addons because we use a small number of hooks, usually it is more about adding new features.

A full-featured forum addon would then be an additional feature on its own that would need to be completely defined outside of the current forum feature.

Let me know if you need more information about addons/hooks.

**Comment by annando** [comment] 2018-04-08 05:28
@kittmcgregor What do you want to change? This issue is - to my understanding - based on some misinterpreting how the forum functionality on Friendica works.

**Comment by kittmcgregor** [comment] 2018-04-08 07:42
I want to change the absence of a post button/field when viewing the forum wall.
The issue is the lack of user friendliness.

I simply want to provide the option to post on the wall - from the wall - in place.
Rather than visiting a forum and not finding a post button - which is counter intuitive.

The standard functionality of every forum I've ever seen is to start a topic/question. Where is the start a topic button? 

Right now I can see on this forum a "New issue" button - top right.
The fact that a similar button is missing from Friendica forums is the very issue which has been raised.
If it can be solved with an add-on I'm surprised nobody has done it yet.

Out of interest why were Friendica forums designed to be different to normal forums?
Was this idea adopted from somewhere else?

I just want a button to encourage users to contribute instead of researching how to contribute.
Thanks.

**Comment by rabuzarus** [comment] 2018-04-08 13:32
> I want to change the absence of a post button/form when viewing the forum wall.
The issue is the lack of user friendliness.

Like @tobiasd already said, there should be a post button if the user is connected with the forum and he/she visits the forum through a magic link (when a user is visiting another friendica contact through a magic link, the user will be authenticated and he/she can write to the wall of the contact - the only exception is if the contact has disabled the feature).

When I visit the support forum through the magic link I can see a post button:
![remote_auth_forum](https://user-images.githubusercontent.com/3750381/38468062-5202b774-3b41-11e8-9150-36f8c5f4b30d.png)

**Comment by MrPetovan** [comment] 2018-04-08 13:38
So it’s a matter of adding magic links in more place than now.

**Comment by MrPetovan** [comment] 2018-04-08 16:52
This is tricky. The "magic auth" URL is something like "http://example.com/profile/forum?zrl=http://yourdomain.com/profile/you". Without the zrl parameter, the remote forum server doesn't have any way to know it's you. You don't have a login/password on the remote instance so you can't authenticate explicitly either.

Maybe we should provide a field for magic auth in the login form but it could be confusing too. What everyone else's think?

**Comment by annando** [comment] 2018-04-08 17:26
@MrPetovan Small correction: The "magic auth" is done via the "/redir/" links. We can try to find all profile links and replace them with these links.

**Comment by rabuzarus** [comment] 2018-04-08 21:09
@AlfredSK 
`/redir` links are the links for real authentification (remote_auth). In this case you should be `guest`. The `zrl` parameter doesn't really authenticate you, because at the moment we can't ensure that the profile page (contact) which is passed through the `zrl` parameter is really the profile which it claims to be.
Originally the `zrl` parameter was used to give users a possibility to jump home to their own profile page. I have extended it for frio to some kind of "fake authentication". Means, that visitors of profiles on foreign servers should have some kind of nav bar which is in the look and feel similar to the one on their own server. But they aren't really authenticated.

Like I wrote already in a friendica comment, i have startet some work on porting hubzillas magic-auth implementation through `OpenWebAuth`. https://github.com/rabuzarus/friendica/tree/20171117_-_magic_auth_test . But at the moment I don't have much time to work on it. And we need to discuss it if we want to implement it this way.

**Comment by kittmcgregor** [comment] 2018-04-08 21:59
This link from /network authenticates the user and displays the post icon.
https://mydomain.com/network?f=&cid=10
The following dialog inserts !forum@mydomain.com
But this is the only scenario where this option is available.

My suggestion still stands - why not always show the post icon to encourage participation and worry about authentication once users show their intent by clicking to contribute?

**Comment by rabuzarus** [comment] 2018-04-08 22:09
OK I tested it and I can reproduce it. There seems to be a problem if the user and the forum are on the same account. I guess there is an issue with the permission check. We need to fix it

**Comment by rabuzarus** [comment] 2018-04-09 12:10
@annando 
The problem is in `function can_write_wall()`. The function does respect the case if `local_user()` is the profile owner and the case if `remote_user()` is a friend but not the case if `local_user()` is a friend.

We can change https://github.com/friendica/friendica/blob/develop/include/security.php#L209 to
```
if (remote_user() || local_user()) {
```
This would solve the problem. But while permission checking is a very complex thing I don't know if it produces side effects. What is your opinion?

**Comment by annando** [comment] 2018-04-09 18:07
I really don't know. I guess we should try to set the ```remote_user``` correctly.

**Comment by rabuzarus** [comment] 2018-04-09 18:58
but you have said that "You cannot be local and remote at the same time"
https://github.com/friendica/friendica/commit/21d27c2124996e1eaa35541cc5092c651c1375b7#diff-7d46ee16e8c1fe64c3bda458889f3b79

**Comment by annando** [comment] 2018-04-09 21:49
Hmm, okay. Sounds like we really have to think it over.

**Comment by rabuzarus** [comment] 2018-04-09 23:13
I don't know which bug was fixed by https://github.com/friendica/friendica/commit/21d27c2124996e1eaa35541cc5092c651c1375b7#diff-7d46ee16e8c1fe64c3bda458889f3b79 but I like the idea to separate clearly between local_user and remote_user (even if he/she is visiting a profile on a local server). Means if local_user is visiting a foreign profile he/she should be a remote_user.

**Comment by annando** [comment] 2018-04-10 04:52
I know that there had been bugs, but I can't remember details. Possibly we have to try.

**Comment by rabuzarus** [comment] 2018-04-10 16:43
Just to make that clear. You mean we should uncomment https://github.com/friendica/friendica/commit/21d27c2124996e1eaa35541cc5092c651c1375b7#diff-7d46ee16e8c1fe64c3bda458889f3b79 in `develop` and see what happens?

**Comment by annando** [comment] 2018-04-11 19:20
I have a bad feeling about this. But possibly we have to.

**Comment by rabuzarus** [comment] 2018-09-21 14:14
https://github.com/friendica/friendica/pull/4823 fixes this issue

**Closed by rabuzarus** 2018-09-21 14:14 UTC
