### ISSUE TITLE
Click on friendica profile names with (AP) lands in nirvana

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#6174] opened 2018-11-20 09:09 UTC
![https meld de outbox andersostberg dfrn_id 0 5f9ddca84be9451bf56081a1e45f9c0723c84248974a0c0a0e572c44d9995523 dfrn_version 2 23 type profile sec 70f2e493cf94d544543f378654ae2bd9ddf1a9a981206cc6c1267e8e1a0773ff](https://user-images.githubusercontent.com/12480023/48762931-6d795b80-ecac-11e8-9eca-fcdb5c8d5b8b.png)
### Expected behavior
You should land on the profile page
### Actual behavior
Click on profile name from friendica contacts with AP lands in nirvana
### Steps to reproduce the problem
Go to you contacts, click on the name of one friendica contact in develop (AP)
### Friendica version you encountered the problem
dev
see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
git
### PHP version
7.2
### SQL version
5.0.12

**Comment by annando** [comment] 2018-11-20 13:09
I can reproduce this. That's why we don't release yet :-)

**Comment by MrPetovan** [comment] 2018-11-20 13:18
Duplicate of #6168

**Closed by MrPetovan** 2018-11-20 13:18 UTC
