### ISSUE TITLE
cronhooks.php brings server down

### ISSUE THREAD

**Issue by seraphyn** [friendica/friendica#1817] opened 2015-08-13 13:41 UTC
It seems that there are some problems with friendica/include/cronhooks.php.
My Hoster send me an email today with the content that this script is running out of mind and it is not possible for other users to use their webspace anymore:

>Sehr geehrter Herr Grube,

>soeben mussten wir ein Script auf Ihrem Webspace abschalten, da dies den Server komplett  überlastete. Es handelt sich folgendes Script:

> /www/htdocs/MYUSERNAME/friendica/include/cronhooks.php

> Durch einen mehrfachen Aufruf des Scripts bei einem Test stößt der Server an seine Leistungsgrenzen und andere Kundenseiten sind dadurch nicht mehr wie gewohnt erreichbar.

> Das Script musste abgeschaltet werden. Sie können Ihre Webmaster/Programmierer bitten das Script zu überarbeiten und ggf. performanter gestalten.

I do not have any logs about it, but this problem seems to start with the latest stable update.

I saw in cronhooks.php that it is possible to set a maxload average, but it seems it is impossible to set/use this on a shared webhost.

My Installation runs since 2014 on http://fr.got-tty.org

**Comment by annando** [comment] 2015-08-13 21:25
cronhooks.php only calls the cron processes from the addons. That means the problem is caused by an addon. The problem lies in one of these addons that you are using:

* fromgplus
* privacy_image_cache
* pumpio
* statistics_json
* twitter

At first: Please deactivate privacy_image_cache. This is obsolete since the last version. But I guess this won't be the problem. If your database is getting bigger and bigger, the statistics_json addon could cause problems - but only once a day. Pumpio sometimes can cause problems as well.

BTW: Have you updated your addons lately? This would be best.

**Comment by seraphyn** [comment] 2015-08-14 12:05
Hi annando,
I disabled privacy_image_cache, updated plugins, but do not disabled statistics.
I Think statistics is important for the friendica network.
If there is something wrong with that plugin, how could I split the generation in small portions?

If this doesn't help, I will disable pump.io...

Thanks for advice and help
Christian

**Comment by annando** [comment] 2015-09-05 15:08
How is it going? Your site appears to be really fast. Have you disabled some of the addons?

**Comment by annando** [comment] 2015-10-17 21:08
@seraphyn How is the current situation? Can we close the issue?

**Comment by annando** [comment] 2015-11-17 19:58
No reaction - but a running instance. I guess everything is alright :)

**Closed by annando** 2015-11-17 19:58 UTC
