### ISSUE TITLE
Profile Photo Links to Raw XML

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5222] opened 2018-06-15 17:04 UTC
### Expected behavior

Clicking a profile photo should zoom the photo or some other useful action.

### Actual behavior

I get a nasty screen full of raw XML in Chrome.  In Safari for iOS it actually prompts me to open the News App.

### Steps to reproduce the problem

Currently using Frio theme.

### Friendica version you encountered the problem

2018.08-dev

**Comment by annando** [comment] 2018-06-15 18:36
It opens up the profile feed. This seems to be the expected behaviour by the programmer - but is a little bit unexpected for visitors.

**Comment by fabrixxm** [comment] 2018-06-18 10:11
I support the idea that linking user feed l from user profile photo is quite unexpected....

**Comment by tobiasd** [comment] 2018-06-18 16:08
I think it is _only_ the case for RSS/Atom feeds. For other networks I'm directed to the profile page.

**Comment by miqrogroove** [comment] 2018-06-18 19:10
I've also noticed that the Tags in this theme have 3 or 4 different formats.  One of them is the yellow icon on the Network feed that has a link like https://example.com/redir/11?url=https://example.com/~nickname 

So these Tag icons, in this specific format, also link to XML, which is really annoying.

**Comment by rabuzarus** [comment] 2018-06-18 23:02
BTW this is not a theme issue because they are present in all topics.

**Comment by miqrogroove** [comment] 2018-06-18 23:51
Same problem when clicking a name of someone who liked a post, it just shows me XML.  Much of this is theme-specific, but raburzarus is also correct because the Tags are linking to XML in multiple themes.

**Comment by miqrogroove** [comment] 2018-06-18 23:55
Also confirmed rabuzarus is correct about specific network posts.  If I try to click on my own name or photo in the network or community feeds, it will show me XML in other themes.  Everyone else's links are normal.

Please revert the Issue Title.

**Comment by fabrixxm** [comment] 2018-06-19 07:00
Another issue, which I think is related, is that also when unauthenticated, all profile photos of friendica contacts links to /redir/ , also the profile photo of the current profile
(see https://kirgroup.com/profile/fabrixxm as unauthenticated visitor )
In this case clicking a contact's profile photo gives you the login form.

If you are authenticated and watch you profile page, you profile photo is stil linked to /redir/ . In this case you get the feed when you click on it, but I believe is not what should happen..

As @miqrogroove said, also profile photos next to posts are linked to /redir/, with same effect.

**Comment by MrPetovan** [comment] 2018-06-22 15:12
Closed via #5270

**Closed by MrPetovan** 2018-06-22 15:12 UTC
Labels: Bug, UX
