### ISSUE TITLE
worker.php stopped working

### ISSUE THREAD

**Issue by casperrutten** [friendica/friendica#9514] opened 2020-11-09 10:53 UTC
I have a problem with the worker.php. Admin says that the last worker execution was on 4th of november and I have over 3000 (increasing) messages in the queue. Cronjob runs every 10 minutes and gives no output on execution (terminates within one second).
VPS with Debian 10 / MariaDB / Apache

Any suggestions?

**Comment by ghost** [comment] 2020-11-09 11:20
This is a newly appeared issue with PHP 7.2 and MariaDB. Please update your system to at least PHP 7.3.

**Comment by casperrutten** [comment] 2020-11-09 12:13
Thanks for you reply @copiis 
You mean php-cli?
Server is running under 7.4, but lowest php on the system is 7.2, so it is possible it runs with cron on that. Any idea how to check this.

**Comment by MrPetovan** [comment] 2020-11-09 13:46
You can use `$ php --version` to check the CLI version.

**Comment by MrPetovan** [comment] 2020-11-09 13:47
Duplicate of #9499

**Closed as completed** 2020-11-09 14:40 UTC
Labels: Sup­port Request
