### ISSUE TITLE
Contacts issue : adress error :  Error 400 bad request

### ISSUE THREAD

**Issue by feydreva** [friendica/friendica#6714] opened 2019-02-21 00:08 UTC
### behavior
This is on a new install 
I added 2 "friends" : Friendical Developers and Friendica News.
if I go to Contacts, and on the picture, choose View Status, I get a "Page not found"
if I choose view profile, I get a Error 400 - Bad Request.

if I choose view contact and click submit, i get a error pop-up Warning : Could not locate the selected profile
if I go to Notification and privacy, and change one of the settings, and I click on Submit,  I get the same error, and none of the settings has changed.

### Notes : 
When i do view profile: it changes the adress to : http://tribe.randome.camp/profile?zrl=http%3A%2F%2Ftribe.randome.camp%2Fprofile%2Ffeydreva
which looks strange.
same for View Status : https://tribe.randome.camp/status?zrl=https%3A%2F%2Ftribe.randome.camp%2Fprofile%2Ffeydreva

server is installed on tribe.randome.camp and my user is feydreva.

### Friendica version you encountered the problem
Friendica 'The Tazmans Flax-lily' 2019.01 - 1293 

### Friendica source (git, zip)
it is a fresh install, from git master

### PHP version
`php -v
PHP 7.0.33-0+deb9u1 (cli) (built: Dec  7 2018 11:36:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
`
### SQL version

    Serveur : Localhost via UNIX socket
    Type de serveur : MariaDB
    Version du serveur : 10.1.37-MariaDB-0+deb9u1 - Debian 9.6
    Version du protocole : 10
   Jeu de caractères du serveur : UTF-8 Unicode (utf8)

**Comment by MrPetovan** [comment] 2019-02-21 01:39
The `zrl` parameter is used for "magic links". It's a special Friendica feature that allows you to be authenticated on remote servers and interact with your contact on their own node.

**Comment by MrPetovan** [comment] 2019-02-21 01:45
It seems you're missing your own profile. each user account (login and password) can have multiple profiles and contacts can be configured by profile. You should always have at least one profile and it seems you're lacking the default one.

**Comment by tobiasd** [comment] 2019-02-21 05:30
I think this is a duplicate of #6532

**Comment by feydreva** [comment] 2019-02-21 08:17
there is a copy of the profile table : 


localhost/friendica/profile/		http://10.1.5.18/phpmyadmin/sql.php?db=friendica&token=c9bdef4bb9320881b1d856b3d60d7c1c&goto=db_structure.php&table=profile&pos=0
 Affichage des lignes 0 -  1 (total de 2, Traitement en 0.0004 secondes.)

SELECT * FROM `profile`


id	uid	profile-name	is-default	hide-friends	name	pdesc	dob	address	locality	region	postal-code	country-name	hometown	gender	marital	with	howlong	sexual	politic	religion	pub_keywords	prv_keywords	likes	dislikes	about	summary	music	book	tv	film	interest	romance	work	education	contact	homepage	xmpp	photo	thumb	publish	net-publish	
1	1	défaut	1	0	Feydreva Paradize		1980-12-31					France					0001-01-01 00:00:00				randome, burningman, nowhere, 3dprint, arduino																	http://tribe.randome.camp/photo/profile/1.jpg	http://tribe.randome.camp/photo/avatar/1.jpg	1	1	
2	2	default	1	0	Padi Lours		0000-00-00										0001-01-01 00:00:00																					http://tribe.randome.camp/photo/profile/2.jpg	http://tribe.randome.camp/photo/avatar/2.jpg	1	1

**Comment by feydreva** [comment] 2019-02-21 08:19
we can see there is 2 profile , 1 for each user of this node

**Comment by MrPetovan** [comment] 2019-02-21 14:07
@tobiasd 
> I think this is a duplicate of #6532

Except both profiles are on the same node, there's no remote node involved.

**Comment by MrPetovan** [comment] 2019-02-21 14:08
> we can see there is 2 profile , 1 for each user of this node

And this looks perfectly fine, we have to look elsewhere for the issue. What happens when you browse `/profiles` ?

**Comment by feydreva** [comment] 2019-02-21 17:23
I get the error, whether it is a remote profile or a local node progile

**Comment by feydreva** [comment] 2019-02-21 17:38
if I go to tribe.randome.camp/profiles ?
it goes to https://tribe.randome.camp/profiles/1 and display my information/picture

**Comment by MrPetovan** [comment] 2019-02-21 17:56
Ok, so it may be a redirection issue like @tobiasd suggested.

**Comment by feydreva** [comment] 2019-02-21 17:59
what should be the proper apache2 config file ?
mine is : 
`<VirtualHost *:80>
 DocumentRoot /var/www/friendica
 ServerName tribe.randome.camp

<Directory /var/www/friendica/>
  Options +FollowSymlinks
  AllowOverride All

 SetEnv HOME /var/www/friendica
 SetEnv HTTP_HOME /var/www/friendica
 Satisfy any

</Directory>

 ErrorLog /var/log/apache2/virtualhosts/tribe.randome.camp_error.log
 CustomLog /var/log/apache2/virtualhosts/tribe.randome.camp_access.log common
</VirtualHost>

`

**Comment by MrPetovan** [comment] 2019-02-21 18:34
This looks fine. If you can access the `/network` page than you Apache Virtual Host and `.htaccess` rewriting is correctly set up. It is most probably an issue with the magic links. @rabuzarus maybe?

**Comment by MrPetovan** [comment] 2019-02-23 03:35
This is confirmed to be a duplicated to #6532

**Closed by MrPetovan** 2019-02-23 03:35 UTC
Labels: Bug
