### ISSUE TITLE
Error with first access of Website

### ISSUE THREAD

**Issue by ddeimeke** [friendica/friendica#5027] opened 2018-05-11 06:47 UTC
### Expected behavior

See anything.

### Actual behavior

See neothing.

### Steps to reproduce the problem

Take the steps described in https://github.com/friendica/friendica/blob/develop/doc/Install.md on CentOS 7 with Remi PHP 7.2

### Friendica version you encountered the problem

Recent development clone.

### Friendica source (git, zip)

Git

### PHP version

7.2.5

### SQL version

MariaDB 5.5.56

**Comment by tobiasd** [comment] 2018-05-11 06:50
I assume this is a duplicate of #4956. Please install using the master branch and then switch to the develop branch (or better the 2018.05-rc branch) afterwards if you want to use the development code.

**Comment by ddeimeke** [comment] 2018-05-11 07:05
I forgot to attach the relevant part of the error-logfile:

`
[Fri May 11 08:38:51.749241 2018] [php7:error] [pid 24190] [client 194.56.165.5:20031] PHP Fatal error:  Uncaught Exception: No system theme config value set. in /srv/www/friend.d5e.org/src/App.php:1122\nStack trace:\n#0 /srv/www/friend.d5e.org/src/App.php(1107): Friendica\\App->computeCurrentTheme()\n#1 /srv/www/friend.d5e.org/index.php(325): Friendica\\App->getCurrentTheme()\n#2 {main}\n  thrown in /srv/www/friend.d5e.org/src/App.php on line 1122
[Fri May 11 08:38:51.868929 2018] [php7:error] [pid 24174] [client 194.56.165.5:20083] PHP Fatal error:  Uncaught Exception: No system theme config value set. in /srv/www/friend.d5e.org/src/App.php:1122\nStack trace:\n#0 /srv/www/friend.d5e.org/src/App.php(1107): Friendica\\App->computeCurrentTheme()\n#1 /srv/www/friend.d5e.org/index.php(325): Friendica\\App->getCurrentTheme()\n#2 {main}\n  thrown in /srv/www/friend.d5e.org/src/App.php on line 1122
[Fri May 11 08:38:51.969040 2018] [php7:error] [pid 24176] [client 194.56.165.5:20091] PHP Fatal error:  Uncaught Exception: No system theme config value set. in /srv/www/friend.d5e.org/src/App.php:1122\nStack trace:\n#0 /srv/www/friend.d5e.org/src/App.php(1107): Friendica\\App->computeCurrentTheme()\n#1 /srv/www/friend.d5e.org/index.php(325): Friendica\\App->getCurrentTheme()\n#2 {main}\n  thrown in /srv/www/friend.d5e.org/src/App.php on line 1122
`

**Comment by tobiasd** [comment] 2018-05-11 07:33
Yes, then it is an duplicate. I'll close this issue then, but thanks for reporting!

**Closed by tobiasd** 2018-05-11 07:33 UTC
