### ISSUE TITLE
Contact data not updated in notification popup and like section after refetch

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#3493] opened 2017-05-25 05:28 UTC
After utf8mb4 conversion I refetched the data of some contacts to repair their usernames.
They are still displayed with question marks in the notification window.

**Comment by Hypolite** [comment] 2017-05-25 22:18
Notifications have a life of their own. They are created with the contact name as it currently is, and don't care much about any subsequent changes.

**Comment by annando** [comment] 2017-05-26 03:48
We could change that :)

**Comment by Hypolite** [comment] 2017-05-26 03:50
Yes, I was just explaining that "It's not a bug, it's feature"™️ even though it should probably be changed.

**Comment by rebeka-catalina** [comment] 2017-05-26 04:59
On 2017.05.25, Hypolite Petovan wrote:
> Yes, I was just explaining that "It's not a bug, it's feature"

Hmmm, an what exactly is the the feature in it?


> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/friendica/friendica/issues/3493#issuecomment-304184087

-- 
question = ( to ) ? be : ! be;
	~ Wm. Shakespeare ~ by fortune, bsd-games.

**Comment by Hypolite** [comment] 2017-05-26 15:50
That I couldn't fully explain to you since it's been done before I arrived. I guess it can be useful if you need a notification about someone removing its account (so the name reference couldn't work) or to prevent a couple table joins when fetching notification which would indeed be faster.

**Comment by rebeka-catalina** [comment] 2017-06-02 05:14
Also in network stream it appears in the broken way - in the list of likes.
Sorry, but to me this looks like a bug.

**Comment by annando** [comment] 2018-08-10 20:12
The displayed author name is now always fetched from the contact table. So we had fixed the second part.

Can we just declare this as fixed? I think the first part is best be fixed by creating a complete new notification class.

**Comment by tobiasd** [comment] 2018-08-17 07:55
@rebeka-catalina what do you think? Can we close the issue?

**Comment by rebeka-catalina** [comment] 2018-08-17 12:39
On 2018.08.17, Tobias Diekershoff wrote:
> @rebeka-catalina what do you think? Can we close the issue?

Oh, did I really forget to answer?!__m(00)m__ I'm sorry.
Yes, sure. It can be closed :-)

**Closed** 2018-08-17 13:38 UTC
Labels: Bug
