### ISSUE TITLE
Wrong personal tag cloud links (or results)

### ISSUE THREAD

**Issue by damianwajer** [friendica/friendica#12704] opened 2023-01-20 18:15 UTC
- [X] I have searched open and closed issues for duplicates

### Bug Description

Personal tag cloud link from the bottom-left corner of the profile page `/profile/[user]` points to all posts instead of just with selected tag.

### Steps to Reproduce

1.  Open profile page of a contact with personal tag cloud. You can see personal tags on your profile if you enable: Settings > Additional features > Advanced Profile Settings > Tag Cloud (`/settings/features`)
2.  Click on the tag in the bottom-left corner of the contact profile (`/profile/[user]`)
3.  You'll see more posts then just with selected tag (all posts?)

Actual Result:

Post unrelated to selected tag. I think the URL should be: `/profile/[user]/status/?tag=[tag]` instead of `/profile/[user]/?tag=[tag]`

Expected Result:

Posts with only selected tag like when you visit `/profile/[user]/status/?tag=[tag]` (this link seems to return correct results for personal tag).

### Screenshots

![personal-tag-cloud](https://user-images.githubusercontent.com/8630866/213773929-a8a56a04-da66-4704-acc8-30a67ba5a571.png)

### Platform Info

Friendica Version: 2023.01

**Comment by MrPetovan** [comment] 2023-01-20 18:17
Thank you for your report, this is a duplicate of #12683

**Closed as not planned by MrPetovan** 2023-01-20 18:17 UTC
Labels: Bug

**Comment by damianwajer** [comment] 2023-01-20 18:33
Oh, right, my bad. I was searching for issues with "personal tag" and "tag cloud" keywords, not "hashtag"

**Comment by MrPetovan** [comment] 2023-01-20 18:44
It's okay, this issue will provide additional search information for people looking for the other issue.
