### ISSUE TITLE
Remove relayed posts from timeline is missing

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5186] opened 2018-06-10 10:21 UTC
### Expected behavior
Able to remove relayed posts that are coming from saved hashtags from timeline like those ones from people you follow directly

### Actual behavior
There is no option to remove those messages

### Steps to reproduce the problem
Wait until a hashtag relayed post pops up in your timeline. Then go for a hunt for the "remove" or trashcan button ;)

### Friendica version you encountered the problem
Friendica develop / git / php7.0 / 5.5.5-10.0.32-MariaDB-0+deb8u1

**Comment by annando** [comment] 2018-06-10 10:32
It's not a bug, it's a missing feature 😄 

We can solve this after the "big database update", that I'm currently working on.

**Comment by hoergen** [comment] 2018-06-10 10:34
Ah ok .. but I have to specify it anyway. Normaly I use the action menu on the top right with the entry "remove from timeline". That is missing.
But I can remove it with using the check button on the lower right and delete it with the trashcan. This is a nice workaround.

**Comment by hoergen** [comment] 2018-06-10 17:05
I can do it here on my node

**Comment by MrPetovan** [comment] 2018-06-11 00:10
The original post is a duplicate of #5158

This new issue is completely different.

**Comment by MrPetovan** [comment] 2018-06-13 19:55
The deletion part of this issue has been fixed by #5207

**Comment by MrPetovan** [comment] 2018-09-11 14:40
Reopened because of #5757

**Comment by annando** [comment] 2021-03-27 08:55
I'm closing this since in the meantime we have changed the way posts with subscribed tags are stored. You are now able deleting them.

**Closed by annando** 2021-03-27 08:55 UTC
Labels: Bug
