### ISSUE TITLE
vier menu disappeares on android tablets in develop branch

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#2056] opened 2015-11-08 21:33 UTC
The menu in vier fully disappears on the network tab and it's not possible to switch to another theme, because the display menu entry disappeared from the the settings menu.

**Comment by rebeka-catalina** [comment] 2015-11-08 21:39
Oh I'm sorry it's the wrong branch

**Comment by tobiasd** [comment] 2015-11-08 21:42
duplicate of #2057

**Closed by tobiasd** 2015-11-08 21:42 UTC
Labels: Berlin2015
