### ISSUE TITLE
Schedule Publications

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#9503] opened 2020-11-08 11:55 UTC
### Is the feature request related to a problem? Please describe.

No

### Describe the feature you'd like

It would be nice if it would be possible to plan the time of publication.

### Describe alternatives you've considered

In Fedilab there is a possibility to schedule posts, either via the app or via the server. Both options don't work for me.

### Additional context

**Comment by MrPetovan** [comment] 2020-11-08 13:34
Duplicate of #8038

**Closed as completed by MrPetovan** 2020-11-08 13:34 UTC
Labels: New Feature
