### ISSUE TITLE
Can't reshare Mastodon posts

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#11853] opened 2022-08-21 06:29 UTC
- [X] I have searched open and closed issues for duplicates

### Bug Description

When I reshare (at least) mastodon posts, they do not appear anywhere in my stream or profile.

### Steps to Reproduce

reshare a mastodon post

Actual Result:

The posts shows, that I have reshared it. and counts me as a resharer, but I can't see it in my profile or stream.

Expected Result:

reshare should work as usual

### Platform Info
I'm only a user:

Diese Friendica-Instanz verwendet die Version 2022.09-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1481/1481 und die Post-Update-Version 1452/1452.

**Comment by foss-** [comment] 2022-08-21 09:34
This is a case of https://github.com/friendica/friendica/issues/11604 right? Mastodon API needs work.

**Comment by annando** [comment] 2022-08-22 10:21
This is possibly fixed by https://github.com/friendica/friendica/pull/11855

**Comment by AlfredSK** [comment] 2022-08-22 15:32
Update done. @haheute Can you test again please?

**Comment by haheute** [comment] 2022-08-22 16:29
Ok. I tried with 2 different mastodon accounts. Didn't work. by the way: "markieren" ("star" in english?) did not work, too.

**Comment by haheute** [comment] 2022-08-22 21:07
It seems, reshare and star does also not work with diaspora posts for me. I tried with 2 posts from a pluspora user.

**Comment by haheute** [comment] 2022-08-23 12:09
I tried again with 2 users of diaspora.psyco.fr : I could star 2 posts of one user, I am friends with. But I could not star a post from another user, I am not friends with. .. if that helps..

edit: 
same with the Mastodon posts. It seems, I can reshare and star, when I am friends with that user. .. but not when I'm not.

**Comment by annando** [comment] 2022-08-23 12:56
Please stick to the topic or open a second issue. Is there an issue with resharing Mastodon posts, Diaspora posts or with bookmarking posts?

**Comment by haheute** [comment] 2022-08-23 13:05
You're right. To stick with the topic: It looks as if I can reshare mastodon posts when I am friends with the user. But not when I am not.

**Comment by foss-** [comment] 2022-08-25 07:49
Another data point: sharing and liking mastodon posts of users I am not following was possible on pirati ca. The posts were comments. It seems I was unable to un-re-share however (or the UI was not updated correctly).

Sharing posts (not comments) from accounts I am not following was also possible.

This is Friendica, version 2022.09-dev that is running at the web location https://pirati.ca. The database version is 1481/1481, the post update version is 1452/1452.

Since versions are identical, not sure what to make of this 🤷

**Comment by foss-** [comment] 2022-08-25 07:56
@haheute  can you send a screenshot of a mastodon post of a contact you are not following after pressing "reshare"? Note that the UI can be confusing, since sometimes the reshare post interaction option becomes bold after a reshare and in other cases it remains normal font but the reshare is only indicated at the top of the post as `Username reshared this.` (in which case I am also unable to un-reshare).

**Comment by haheute** [comment] 2022-08-25 08:16
![friendica-cannot-share-mastodon-post](https://user-images.githubusercontent.com/5753419/186611219-cccf22b2-2fcc-4e72-bdd8-6157f901fe18.jpg)
The problem is, the post does not seem to appear somewhere in the 'streams' (/network or /profile).
I tried multiple times to un-reshare and reshare again. (the UI seemed to work)

**Comment by AlfredSK** [comment] 2022-08-27 13:05
Looks like you don't follow the original author. Where did you find the original post? On the global community page or in your network page? I want to try to reproduce the issue.

**Comment by haheute** [comment] 2022-08-27 13:16
I think I have clicked the username because of another interesting post (on my network page). Then, on the page of that user , I found this post.
(that means, I was scrolling through this page: https://libranet.de/contact/1367416/conversations ) (don't know if this link works for you -- otherwise you must search for the name)

**Comment by MrPetovan** [comment] 2022-08-28 04:13
Thank you for your report!

**Closed as completed** 2022-08-28 04:12 UTC
Labels: Bug
