### ISSUE TITLE
Do not require shell_exec for installation

### ISSUE THREAD

**Issue by ice552** [friendica/friendica#1289] opened 2015-01-12 14:44 UTC
Please help I have some problem with instalation Friendica on my domain :

Warning: session_start() [function.session-start]: Cannot send session cookie - headers already sent by (output started at /data/web/virtuals/90107/virtual/www/boot.php:309) in /data/web/virtuals/90107/virtual/www/index.php on line 85

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /data/web/virtuals/90107/virtual/www/boot.php:309) in /data/web/virtuals/90107/virtual/www/index.php on line 85

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/90107/virtual/www/boot.php:309) in /data/web/virtuals/90107/virtual/www/index.php on line 127

Warning: shell_exec() has been disabled for security reasons in /data/web/virtuals/90107/virtual/www/mod/install.php on line 316

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/90107/virtual/www/boot.php:309) in /data/web/virtuals/90107/virtual/www/index.php on line 537,

Command line PHP  
 Could not find a command line version of PHP in the web server PATH.
 If you don't have a command line version of PHP installed on server, you will not be able to run background polling via cron. See 'Activating scheduled tasks'
PHP executable path  
Enter full path to php executable. You can leave this blank to continue the installation.

Url rewrite in .htaccess is not working. Check your server configuration. 

Can you please help me where is the problem? (I have default .htacces) from instalation.

Thank you very much

**Comment by tobiasd** [comment] 2015-01-13 06:45
The problem is that shell_exec is disabled on you server:

> Warning: shell_exec() has been disabled for security reasons in 

friendica needs it for background processes

**Comment by ice552** [comment] 2015-01-13 09:33
Web provides sad : On our webhosting we cant support shall command

**Comment by silke** [comment] 2015-01-14 15:22
Sounds like you can't install friendica with your hoster. :(

I propose to close this issue because it's not a bug in friendica.

**Comment by fabrixxm** [comment] 2015-01-22 20:41
can we transform this into a "feature request", and think if there is a way to not use shell_exec ?

**Comment by Beanow** [comment] 2015-01-24 20:41
@fabrixxm I second this.

**Comment by tobiasd** [comment] 2016-12-12 07:18
@annando what is the current state of this issue?

**Comment by annando** [comment] 2016-12-12 10:58
With the enabled front end worker the system will work in some way - but I haven't checked the installation routine concerning this.

**Closed** 2017-12-27 19:25 UTC
Labels: Installation, New Feature
