### ISSUE TITLE
Reshare with too many line breaks

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7275] opened 2019-06-16 15:00 UTC
### Expected behavior
A reshared post should look the same, like the original one

### Actual behavior
original post
![00_temp](https://user-images.githubusercontent.com/24474762/59565806-0e1fd600-9058-11e9-9c35-cfdb55abcbf2.jpg)

Reshared post looks like this
![01_temp](https://user-images.githubusercontent.com/24474762/59565814-255ec380-9058-11e9-87f9-218659946082.jpg)

### Steps to reproduce the problem
Reshare

### Friendica version you encountered the problem
Friendica 'Dalmatian Bellflower' 2019.06-rc - 1313

**Comment by MrPetovan** [comment] 2019-06-16 15:02
Do you have a public link to the reshare and the original post?

**Comment by hoergen** [comment] 2019-06-16 15:40
The original on the original node
https://friendica.produnis.de/display/6036f0c5-355d-064f-0b65-acb689548224

The original on my timeline 
https://horche.demkontinuum.de/display/6036f0c5-355d-064f-0b65-acb689548224

The reshared post
https://horche.demkontinuum.de/display/2196d4ee-435d-0652-8a16-a68591607048

**Comment by hoergen** [comment] 2019-06-16 16:40
Have another example (not from me)
My Timeline
https://horche.demkontinuum.de/display/6a1356e072800137dad7268acd52edbf

Original Post
https://pod.geraspora.de/posts/6a1356e072800137dad7268acd52edbf

**Comment by hoergen** [comment] 2019-06-16 19:56
Original
https://friendica.mrpetovan.com/display/735a2029-235d-068a-fb21-bda450250861

My Timeline
https://horche.demkontinuum.de/display/735a2029-235d-068a-fb21-bda450250861

**Comment by AlfredSK** [comment] 2019-06-16 20:44
You can also look at the support forum. I restarted a post to the forum. Same issue.

**Comment by MrPetovan** [comment] 2019-06-16 22:18
Most probably caused by #7274

**Comment by MrPetovan** [comment] 2019-06-17 11:21
Fixed with #7276

**Closed by MrPetovan** 2019-06-17 11:21 UTC
Labels: Bug
