### ISSUE TITLE
Private message from unknown

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1769] opened 2015-07-18 09:31 UTC
I received a private message from an unknown user.
I actually know who the user is, but the system considers her an unkonwn user
(Unknown sender - Firsname Lastname)

The "Send Reply" form has an empty "To:" field.
The sender name is a link to /redir/0, showing a padlock on hover.
Following the sender name link takes me back to my network tab.

What's going on ?

\cc @robe2

**Comment by rabuzarus** [comment] 2015-07-18 12:19
Seems like you have received a wallmessage. If "allow getting private messages from unknown people" is enabled in you settings there will a send a message button appear on your profile page.

The problem is that all messages which will be send with this feature will get an unknown sender even if you are connected with this person.

There are to enhancements I would love to see:
1.) sending/saving friendica user address of the sender (username@friendicainstance.com) to make replies possible (even if the person is unknown)

2.) check against the database if the sender is connected or not (if the sender already connected delete the unknown flag)

**Comment by annando** [comment] 2016-05-22 10:12
I never worked with that feature - how can I send these messages?

**Comment by rabuzarus** [comment] 2016-05-22 18:04
If you visit someones profile page there is a button on the left aside for sending pm / wallmessage (this feature have to be enabled in the settings)

**Comment by annando** [comment] 2016-05-22 19:12
Doesn't seem to work on my test acount: https://pirati.ca/profile/soapbox

**Comment by rabuzarus** [comment] 2016-05-22 20:07
Do you have  "Dürfen Dir Unbekannte private Nachrichten schicken?" enabled?

Or have a look at https://friendica.kommune4.de/profile/rabuzarus

**Comment by fabrixxm** [comment] 2016-05-23 06:46
> 1.) sending/saving friendica user address of the sender (username@friendicainstance.com) to make replies possible (even if the person is unknown)
> 
> 2.) check against the database if the sender is connected or not (if the sender is already connected delete the unknown flag)

1 could be done, but 2 would be insecure without authenticate the sender...

**Comment by rabuzarus** [comment] 2016-05-23 08:30
> 1 could be done, but 2 would be insecure without authenticate the sender...

If someone who is connect to someone else visit his/her profile page he/she should be authenticated. Or am I wrong? (OK I think not in all cases but in the most if the users is redirected from his/her own own page to the one of his/her friend)

On my friendica node I realized, that some friends rather visit my profile page and hit the wallmessage button if they want to write messages to me. This is the way they remember. Somehow logical. If you want to get in contact, visit the profile page and look for possibilities :-)

**Comment by fabrixxm** [comment] 2016-05-23 08:40
to visit someone profile page as authenticated contact, you need to click on contact's avatar on your site, where the mouse turn in a pointer finger with a lock (it should change in every theme...).
At this point you (as authenticated contact) will see a  "send private message" button, and your message will be stored as "sent by contact xxzz".

if you simply visit someone profile writing the url in browser, you aren't authenticated, and usually you don't see a "send me a pm" button, unless the user activated the option to receive anonymous pms.
If you click that button, the server don't know who you are, you aren't authenticated.
We could ask you for you "webbie", but that would not be authenticated, because you could write any thing you want in it. If we simply match that input with user contacts, you could send a message to the user impersonating any of his contacts.

back to the issue:
if @strk has enabled the option to receive anonymous private messages, and that message is one of this, it's an UX issue: should be evident that the message is from someone we could not authenticate, and maybe we should not show the "reply" button.
If that's not the case, it's a bug somewere else...

**Comment by strk** [comment] 2016-05-23 09:00
Sorry I don't remember what I do have or not have enabled,
but you can try going to my profile and send me a message :)

Ideally we should let users authenticate themselves in some
ways (OpenID would be a great addition, for example).

**Comment by rabuzarus** [comment] 2016-05-23 09:04
> At this point you (as authenticated contact) will see a "send private message" button, and your message will be stored as "sent by contact xxzz".

I don't think so. profile_vcard.tpl points every time to `href="wallmessage/{{$profile.nickname}}`. And `function send_wallmessage` does always insert a `unknown` in the mail table (https://github.com/friendica/friendica/blob/master/include/message.php#L221).
I can't find any part which is checking if an user is authenticated.

**Comment by fabrixxm** [comment] 2016-05-23 09:14
Ok, delete almost everything I said in my last comment :-)
I was using my not-so-functional memory, without check facts...

So, the "message" button is shown in profile only if selected in options, and the code don't check for 'remote user'.
options:

- let the code check for remote user and fill message table correctly
    - leave the option as is, if the user choose to show the message button, the button is shown to authenticated and not-authenticated visitors, and the code do it's work
   - leave the option as is, but the button is shown always then the visitor is authenticated, and the option is honored only for not-authenticated visitors
   - split the option between authenticated and not-authenticated cases

**Comment by rabuzarus** [comment] 2016-05-23 09:27
I would suggest,
* let the code do all it's work
* The button is every time available for authenticated users
* The option is for showing this button for non authenticated users or not
* if enabled non authenticated users should be displayed  in the messages list with webbie (username@friendicainstance.com)  - Additionally we can think about an option for templates to show something like an unknown tag/symbol

**Comment by rabuzarus** [comment] 2016-05-23 09:53
btw: another question in this scope.
The case:
A authenticated users is writing a wallmessages. Is there a secure possibility to send this authenticated user a copy of this message to the db of his/her own friendica node so that this message is in his/her message list?

**Comment by annando** [comment] 2016-05-29 17:35
I just checked the functionality: Sending messages is only available when the user is authenticated via "zrl=..." - and I think that this is okay.

I only found one issue: The link to the profile was incorrect (.../redir/0). I changed it so that it contains a "zrl=..." link. This means that you could go to the remote profile and could answer the post if you don't know that person.

Additionally there is a usage problem: When you send a message then you stay on the message window - and you can not easily see if the message was sent.

I will create a pull request for that.

I think that it is okay to not change the behaviour so that you could easily press the reply button. Thing is: you can easily trick the system with providing some random profile link. So the user should not only see some small hint but the whole system should react differently - like it is doing right now.

I suggest that we could enhance the functionality so that the sender could be redirected to his own page if both users are known to each other. Then the sender would had a copy of the mail and the receiver could answer it easily.

This is step that I would plan for the 3.5.1.

**Comment by rabuzarus** [comment] 2016-05-29 21:10
Yes I think this is OK. But what is with replacing `unknown` with the addr. of the profile (e.g. rabuzarus@kommune4.de) + transform the `unknown` to something like a tag/symbol

**Comment by annando** [comment] 2016-05-29 21:37
In fact it is looking that way:
![image](https://cloud.githubusercontent.com/assets/844208/15636154/26383a86-25f6-11e6-8544-d7a19ddf730b.png)

![image](https://cloud.githubusercontent.com/assets/844208/15636158/40700302-25f6-11e6-9af6-81b2e84e1f1d.png)

**Comment by rabuzarus** [comment] 2016-05-29 22:30
I would suggest (the second picture) not to have "unknown sender - rabuzarus". Rather something like "rabuzarus@kommune4.de" and a tag (which could be placed by the template) with "unknown" (or a symbol or a mark or something other). The name/address is not "unknown" so it should be hardcoded. "Unknown" should be rather an optical hint.

**Comment by annando** [comment] 2016-05-30 04:02
Maybe "unchecked sender" would be more correct. But I would like to leave it as obvious as it is now.

**Comment by strk** [comment] 2016-05-30 04:28
>Maybe "unchecked sender" would be more correct

+1

**Comment by annando** [comment] 2016-05-31 20:04
Can we close the issue? I think that we could do the whole UI stuff (renaming it or applying icons or something else) in a different issue.

**Comment by strk** [comment] 2016-05-31 21:26
Fine by me (I don't plan to test/reproduce this anyway).

**Comment by annando** [comment] 2016-06-11 08:33
Since no one disagrees, I'm now closing this issue.

**Closed by annando** 2016-06-11 08:33 UTC
Labels: UX
