### ISSUE TITLE
Attempts to create initial admin account fails

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9065] opened 2020-08-23 23:20 UTC
### Friendica version you encountered the problem

see `example.com/friendica` on your Friendica node for the version information.

**Comment by 4nanook** [comment] 2020-08-23 23:25
Expect to successfully create an account but after entering information I get:

The form security token was incorrect.
This probably happened because the form
not been submitted within three hours.

The form was submitted within five minutes.  I have cleared browser history, cache, etc
and tried again, same thing.

**Comment by MrPetovan** [comment] 2020-08-24 00:54
Thank you for the report, sorry about that, did you run Composer after cloning the git repository?

**Comment by 4nanook** [comment] 2020-08-24 00:57
Yes, I did.

**Comment by MrPetovan** [comment] 2020-08-24 01:19
Very good, do you have any PHP errors in your webserver log?

**Comment by 4nanook** [comment] 2020-08-24 01:42
There is.  Many.  They point to issues with both my web server compile and PHP compile.  I had installed openssl 3.0.0 but Apache did not compile against it successfully, so I deleted and installed openssl 1.1.1g, but it appears some things did compile against it except it's no longer here.  So I need to recompile these things again.  Thanks for pointing me there, don't know why
I did not check to begin with, I should know better.

**Comment by 4nanook** [comment] 2020-08-24 09:31
Ok, I've fixed I believe issues with my PHP and Apache installation, at least other things are not generating random errors and I can start php cleanly, but I am getting this error when I try to register the initial account with friendica:

[Mon Aug 24 02:27:27.921981 2020] [:error] [pid 2743676:tid 139903515678464] [client 50.251.249.49:48904] PHP Notice:  Trying to access array offset on value of type null in /misc/www/friendica/src/BaseModule.php on line 161, referer: https://friendica.eskimo.com/register

**Comment by MrPetovan** [comment] 2020-08-24 15:52
Thank you, thanks to this error message, I now know why registering an admin account isn't possible. And, if I'm not mistaken, no other account may be registered either on the develop branch.

**Comment by MrPetovan** [comment] 2020-08-24 16:03
Caused by #9041

**Comment by MrPetovan** [comment] 2020-08-24 16:04
Fixed by #9067

**Closed** 2020-08-24 16:36 UTC
Labels: Bug, Installation
