### ISSUE TITLE
Mastodon: delivery to Mastodon broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5298] opened 2018-06-29 06:11 UTC
### Expected behavior
When I write a public post a Mastodon contact who follows me should get that post.

### Actual behavior
Since about two days nothing is delivered to Mastodon.

### Steps to reproduce the problem
I tried two different Friendica accounts. I posted public posts and comments. I also mentioned a Mastodon contact. The Mastodon contact has a bi-directional relationship with the Friendica accounts.
I tested it with mastodon.social and a user of my node also reported the same issue with 101010.pl.

### Friendica version you encountered the problem
2018.08-dev (current code)

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
10.0 (MariaDB)

**Comment by AlfredSK** [comment] 2018-06-29 07:07
Supplemental: If a public post is initiated by the Mastodon contact I get the post on Friendica. I can comment that post and the comments are successfully delivered to Mastodon.
Seems that our top-level posts don't arrive in the timeline on Mastodon.

**Comment by MrPetovan** [comment] 2018-06-29 09:32
Could it have been already fixed by #5298 ?

**Comment by AlfredSK** [comment] 2018-06-29 09:51
Maybe. I'll check later.

**Comment by AlfredSK** [comment] 2018-06-29 15:11
Checked and failed. Still no success. No posts are delivered to Mastodon.

**Comment by AlfredSK** [comment] 2018-06-29 15:34
Hmm. That's odd...
When I go to https://libranet.de/contacts/123456 I see that I have a bi-directional connection with the Mastodon contact. When I update the contact the relationship is switched to "you follow xyz". :-/ That's bad.
When I renew the connection from Mastodon's side the Friendica contact has a bi-directional connection again. After updating the contact once more it falls back to uni-directional connection "you follow xyz" again.
Hmm.

**Comment by MrPetovan** [comment] 2018-07-10 19:38
Closing as duplicate of #5355

I was able of having a conversation with a Mastodon account this morning on latest develop.

**Closed by MrPetovan** 2018-07-10 19:38 UTC
Labels: Bug, Federation
