### ISSUE TITLE
Matomo / Piwik add-on doesn't allow setting change

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#6711] opened 2019-02-20 22:20 UTC
### Expected behavior

In the Matomo / Piwik adminitrative settings, the "Show opt-out cookie link? " should allow you to turn it on or off.

### Actual behavior

The setting resets to checked/On after unchecking it and saving the setting.

### Steps to reproduce the problem

Go to /admin/addons/piwik.  Uncheck the "Show opt-out cookie link?" setting and click "Save Settings"

### Friendica version you encountered the problem

2019.03-rc - 1302

### Friendica source (git, zip)

git

### PHP version

7.3.1

### SQL version

mariadb 10.3.12

**Comment by realkinetix** [comment] 2019-02-20 22:41
Further information:  For some reason, the "optout" value is being taken from piwik/config/piwik.config.php even though it should be managing the value to/from the DB.

Some odd going on there.  However, if I change true to false for 'optout' in that file, it shut the value off... and now the admin page settings are able to take effect.

I suspect this is something outside of the piwik addon module itself?

**Comment by MrPetovan** [comment] 2019-02-20 23:58
Possibly related to the recent Config refactoring by @nupplaphil

**Comment by nupplaphil** [comment] 2019-02-21 06:55
Sounds like a true/false config save problem. Thanks for the report.

**Comment by realkinetix** [comment] 2019-02-21 07:22
Between this and 6712 I'm also seeing on my dev node the inability to change the system registration policy from Open to anything else.  I'm not sure if mentioning it on this bug is the right place, but I have the feeling that there's some admin(?) config handling bits that are currently problematic.

**Comment by nupplaphil** [comment] 2019-02-21 07:48
Seems like the same type of issue. I'll check both. Friday evening ist my next possible timeslot for config-fixings.

**Comment by realkinetix** [comment] 2019-02-21 16:39
Switching config_adapter from jit to preload fixes these issues.

**Comment by nupplaphil** [comment] 2019-02-21 17:03
Uhoh.. Sounds like a regression because of the preload bugfix..

**Comment by nupplaphil** [comment] 2019-02-23 12:06
Fixed with #6724

**Comment by tobiasd** [comment] 2019-02-23 12:21
@realkinetix could you check if this is fixed in the current RC branch?

**Closed** 2019-02-23 13:47 UTC
Labels: Bug, Sup­port Request

**Comment by realkinetix** [comment] 2019-02-23 22:53
I've done a fresh pull and changed a few settings back & forth to try and replicate the issue, but haven't seen the problem again.

**Comment by tobiasd** [comment] 2019-02-24 06:05
Thanks for checking @realkinetix :-)

**Comment by realkinetix** [comment] 2019-02-24 17:32
My pleasure!
