### ISSUE TITLE
[2022.09] PHP Notices

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#11632] opened 2022-06-11 11:47 UTC
Please report here any PHP Notice message obtained running the 2022.06 stable or 2022.09-dev versions.

Close #11218

**Comment by Quix0r** [comment] 2022-06-16 19:43
````
[16-Jun-2022 18:03:40 UTC] PHP Notice:  Undefined index: contact-type in /var/www/.../htdocs/src/Module/Directory.php on line 169
[16-Jun-2022 18:03:40 UTC] PHP Stack trace:
[16-Jun-2022 18:03:40 UTC] PHP   1. {main}() /var/www/.../htdocs/index.php:0
[16-Jun-2022 18:03:40 UTC] PHP   2. Friendica\App->runFrontend($router = *uninitialized*, $pconfig = *uninitialized*, $auth = *uninitialized*, $page = *uninitialized*, $httpInput = *uninitialized*, $start_time = *uninitialized*) /var/www/.../htdocs/index.php:44
[16-Jun-2022 18:03:40 UTC] PHP   3. Friendica\LegacyModule->run($request = *uninitialized*) /var/www/.../htdocs/src/App.php:722
[16-Jun-2022 18:03:40 UTC] PHP   4. Friendica\LegacyModule->content($request = *uninitialized*) /var/www/.../htdocs/src/BaseModule.php:239
[16-Jun-2022 18:03:40 UTC] PHP   5. Friendica\LegacyModule->runModuleFunction($function_suffix = *uninitialized*) /var/www/.../htdocs/src/LegacyModule.php:73
[16-Jun-2022 18:03:40 UTC] PHP   6. forumdirectory_content($a = *uninitialized*) /var/www/.../htdocs/src/LegacyModule.php:96
[16-Jun-2022 18:03:40 UTC] PHP   7. Friendica\Module\Directory::formatEntry($contact = *uninitialized*, $photo_size = *uninitialized*) /var/www/.../htdocs/addon/forumdirectory/forumdirectory.php:127
````

See my "diary" at the forum: "[Working on type-hints, please watch out](https://forum.friendi.ca/profile/developers)"

**Comment by Quix0r** [comment] 2022-06-16 20:58
````
[16-Jun-2022 20:24:12 UTC] PHP Notice:  Undefined index: causer-id in /var/www/.../htdocs/src/Content/Conversation.php on line 157
[16-Jun-2022 20:24:12 UTC] PHP Stack trace:
[16-Jun-2022 20:24:12 UTC] PHP   1. {main}() /var/www/.../htdocs/index.php:0
[16-Jun-2022 20:24:12 UTC] PHP   2. Friendica\App->runFrontend($router = *uninitialized*, $pconfig = *uninitialized*, $auth = *uninitialized*, $page = *uninitialized*, $httpInput = *uninitialized*, $start_time = *uninitialized*) /var/www/.../htdocs/index.php:44
[16-Jun-2022 20:24:12 UTC] PHP   3. Friendica\LegacyModule->run($request = *uninitialized*) /var/www/.../htdocs/src/App.php:722
[16-Jun-2022 20:24:12 UTC] PHP   4. Friendica\LegacyModule->content($request = *uninitialized*) /var/www/.../htdocs/src/BaseModule.php:239
[16-Jun-2022 20:24:12 UTC] PHP   5. Friendica\LegacyModule->runModuleFunction($function_suffix = *uninitialized*) /var/www/.../htdocs/src/LegacyModule.php:73
[16-Jun-2022 20:24:12 UTC] PHP   6. display_content($a = *uninitialized*, $update = *uninitialized*, $update_uid = *uninitialized*) /var/www/.../htdocs/src/LegacyModule.php:96
[16-Jun-2022 20:24:12 UTC] PHP   7. Friendica\Content\Conversation->create($items = *uninitialized*, $mode = *uninitialized*, $update = *uninitialized*, $preview = *uninitialized*, $order = *uninitialized*, $uid = *uninitialized*) /var/www/.../htdocs/mod/display.php:301
[16-Jun-2022 20:24:12 UTC] PHP   8. Friendica\Content\Conversation->builtinActivityPuller($activity = *uninitialized*, $conv_responses = *uninitialized*) /var/www/.../htdocs/src/Content/Conversation.php:741
````
Addressed in https://github.com/friendica/friendica/pull/11652

**Comment by AlfredSK** [comment] 2022-07-13 15:26
2022.09-dev, PHP 7.4

`Trying to access array offset on value of type bool in .../src/Navigation/Notifications/Factory/Notification.php on line 186`

Addressed in https://github.com/friendica/friendica/pull/11734

**Comment by Quix0r** [comment] 2022-07-13 18:54
Can you tell what you have done to cause this? `$link_item` seem to be not fetched (no record in database I suspect).

**Comment by AlfredSK** [comment] 2022-07-13 18:58
> Can you tell what you have done to cause this? `$link_item` seem to be not fetched (no record in database I suspect).

No idea. I have tons of these in my PHP log. It is no new notice. I already had those in the last stable version. ☺️ 
I can try to find a corresponding entry with the same time stamp in my ~~friendly~~ Friendica log.

**Comment by Quix0r** [comment] 2022-07-13 20:06
Ah, okay. So this message isn't related to latest changes then, okay. Since the record in `$link_item` isn't there, I recommend adding an `if()` block before it.

**Comment by AlfredSK** [comment] 2022-07-16 08:30
2022.09-dev, PHP 7.4

`Undefined index: object-type in .../src/Protocol/OStatus.php on line 1171`

**Comment by Quix0r** [comment] 2022-07-16 10:17
> 2022.09-dev, PHP 7.4
> 
> `Undefined index: object-type in .../src/Protocol/OStatus.php on line 1171`

That's a logger message. The proper array is `$item` here.

**Comment by Quix0r** [comment] 2022-07-18 21:49
`Notice:  Undefined index: account_removed in /var/www/../src/Model/Profile.php on line 224`
Addressed in #11741

**Comment by ghost** [comment] 2022-07-19 14:30
latest dev

`PHP Notice:  iconv(): Detected an illegal character in input string in /src/Util/ParseUrl.php on line 313`

**Comment by AlfredSK** [comment] 2022-07-19 19:22
2022.09-dev

```
Undefined variable: contact in .../src/Protocol/Diaspora.php on line 4097
Trying to access array offset on value of type null in .../src/Protocol/Diaspora.php on line 4097
```

**Comment by Quix0r** [comment] 2022-07-19 21:44
> 2022.09-dev
> 
> ```
> Undefined variable: contact in .../src/Protocol/Diaspora.php on line 4097
> Trying to access array offset on value of type null in .../src/Protocol/Diaspora.php on line 4097
> ```
This is because `$item['author-link']` wasn't empty (see some lines above) and laziness of not correctly initializing your variables. :-)

**Comment by Quix0r** [comment] 2022-07-19 21:55
> latest dev
> 
> `PHP Notice: iconv(): Detected an illegal character in input string in /src/Util/ParseUrl.php on line 313`

If I just put an `@` in front of it, `$body` is suddenly empty and the script would continue with it like normal. So in this case, no `$siteinfo` would be returned,

**Comment by ghost** [comment] 2022-07-20 14:02
```
PHP Notice:  Undefined index: guid in /src/Model/FContact.php on line 95
PHP message: PHP Notice:  Undefined index: request in /src/Model/FContact.php on line 107
PHP message: PHP Notice:  Undefined index: nick in /src/Model/FContact.php on line 107
PHP message: PHP Notice:  Undefined index: addr in /src/Model/FContact.php on line 108
PHP message: PHP Notice:  Undefined index: guid in /src/Model/FContact.php on line 108
PHP message: PHP Notice:  Undefined index: batch in /src/Model/FContact.php on line 109
PHP message: PHP Notice:  Undefined index: notify in /src/Model/FContact.php on line 109
PHP message: PHP Notice:  Undefined index: poll in /src/Model/FContact.php on line 110
PHP message: PHP Notice:  Undefined index: confirm in /src/Model/FContact.php on line 110
PHP message: PHP Notice:  Undefined index: alias in /src/Model/FContact.php on line 111
PHP message: PHP Notice:  Undefined index: pubkey in /src/Model/FContact.php on line 111'
```

**Comment by Quix0r** [comment] 2022-07-20 14:44
This is why I like to check each parameter if it is valid and then throw a proper exception, to have a clean API. On top of that, more unit tests which also do positive testing (means tests how the method/class behaves on wrong parameter) so you can be sure the same exception will come each time you provide an invalid parameter.

**Comment by Quix0r** [comment] 2022-07-20 14:45
@copiis Do you have any backtrace?

**Comment by ghost** [comment] 2022-07-20 14:46
> backtrace?

What is that?

**Comment by Quix0r** [comment] 2022-07-20 14:47
See my comment: https://github.com/friendica/friendica/issues/11632#issuecomment-1158067177

**Comment by Quix0r** [comment] 2022-07-20 14:50
In this case, I would always check on mandatory array elements, or that a `int $contactId` is never < 1 because that's normally not possible/wanted. Or that `int $birthYear` is never to old (people won't live so long). Or that `string $email` isn't empty and a valid one.

**Comment by MrPetovan** [comment] 2022-07-20 16:27
PHP Notices don't provide backtraces by default, you have to install XDebug for this and it isn't recommended on production systems.

**Comment by ghost** [comment] 2022-07-21 15:09
`PHP Notice:  Trying to access array offset on value of type bool in /src/Protocol/ActivityPub/Transmitter.php on line 659`

**Comment by Quix0r** [comment] 2022-07-22 07:24
> `PHP Notice: Trying to access array offset on value of type bool in /src/Protocol/ActivityPub/Transmitter.php on line 659`

`$parent` could not be fetched from database (no record). I had introduced `DBA::isResult()` for fetched results, not for successful `UPDATE` or `DELETE` statements. That should be done directly. I would love to fix that (by removing the `is_bool()` part and check all occurrences) because now the method is pretty useless for returned results from a `SELECT` statement.

**Comment by Quix0r** [comment] 2022-07-22 07:33
If I put a (intended) `DBA::isResult($parent)` check here, the same `E_NOTICE` will come again, because of that said `is_bool()` block.

**Comment by ghost** [comment] 2022-07-25 11:54
```
PHP Notice:  Trying to access array offset on value of type bool in /src/Model/Group.php on line 151
PHP Notice:  iconv(): Wrong charset, conversion from `x-sjis' to `UTF-8//TRANSLIT' is not allowed in /src/Util/ParseUrl.php on line 313
```
Addressed in https://github.com/friendica/friendica/pull/11770

**Comment by ghost** [comment] 2022-07-27 08:14
```
PHP Notice:  iconv(): Wrong charset, conversion from `x-sjis' to `UTF-8//TRANSLIT' is not allowed in /src/Util/ParseUrl.php on line 313'
```

`PHP Notice:  Undefined offset: 1 in /mod/photos.php on line 796`

**Comment by MrPetovan** [comment] 2022-07-27 11:43
> ```
> PHP Notice:  iconv(): Wrong charset, conversion from `x-sjis' to `UTF-8//TRANSLIT' is not allowed in /src/Util/ParseUrl.php on line 313'
> ```

It looks like the message was in a Japanese charset, it's probable your system doesn't have it installed so it can't convert from it.

**Comment by ghost** [comment] 2022-07-29 09:42
`PHP Notice:  Undefined index: public in /src/Model/Contact.php on line 2972`

**Comment by ghost** [comment] 2022-08-03 07:15
`PHP Notice:  iconv(): Detected an illegal character in input string in/src/Util/ParseUrl.php on line 313'`

**Comment by AlfredSK** [comment] 2022-08-30 16:35
`Undefined index: nick in .../src/Model/APContact.php on line 580`

2022.09-dev, PHP 7.4

Addressed in https://github.com/friendica/friendica/pull/11922

**Comment by ghost** [comment] 2022-09-06 07:20
posts are no longer distributed tu Tumblr on latest rc
Here is what i found in the logs

```
PHP Notice:  Undefined index: tumblr_page in /addon/tumblr/tumblr.php on line 255', referer:  /settings/connectors
PHP Notice:  session_start(): A session had already been started - ignoring in /addon/tumblr/tumblr.php on line 88
PHP Notice:  Undefined variable: o in /addon/tumblr/tumblr.php on line 137', referer: /settings/connectors/tumblr
PHP Notice:  session_start(): A session had already been started - ignoring in /addon/tumblr/tumblr.php on line 143', referer: https://www.tumblr.com/
```

**Comment by Quix0r** [comment] 2022-09-12 16:58
> posts are no longer distributed tu Tumblr on latest rc Here is what i found in the logs
> 
> ```
> PHP Notice:  Undefined index: tumblr_page in /addon/tumblr/tumblr.php on line 255', referer:  /settings/connectors
> PHP Notice:  session_start(): A session had already been started - ignoring in /addon/tumblr/tumblr.php on line 88
> PHP Notice:  Undefined variable: o in /addon/tumblr/tumblr.php on line 137', referer: /settings/connectors/tumblr
> PHP Notice:  session_start(): A session had already been started - ignoring in /addon/tumblr/tumblr.php on line 143', referer: https://www.tumblr.com/
> ```
The 1st one (those with `session_start()` are followups and can be ignored) is not easy to locate for me, as I don't know much about the internals about Friendica and how how it handles form fields. It is a bit guessing here.

The 2nd one is easy to explain: `header('Location: https://...');` does not end the script, it will be further executed and then ends in that error as `$o` isn't defined. 

I guess this part needs rewriting to Friendica's API?

**Comment by Quix0r** [comment] 2022-09-12 17:08
@copiis Plus this is an addon-specific issue, not general Friendica.

**Comment by xundeenergie** [comment] 2022-09-12 23:49
With php8.1 i get the following Line
`PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/soc.schuerz.at/view/smarty3/compiled/d4/73/af/d473af9cb1f73501efa3fb9ddfbeeb00e5346f23_2.file.wall_thread.tpl.php on line 329`

This happens for all this line-numbers in the named file:
27
28
42
62
64
67
71
83
86
96
113
114
138
232
240
247
266
289
297
326
329
411
484
498

Addressed in https://github.com/friendica/friendica/pull/11904

**Comment by Quix0r** [comment] 2022-09-13 12:13
@xundeenergie It origins from a template. Have you tried to remove all `*.tpl.php` files from `view/smarty3/compiled/` directory?

**Comment by xundeenergie** [comment] 2022-09-13 13:54
No. Because i didn't know, that i can safely remove them. 

Do i have to do something after deleting this files? Run composer again?

**Comment by Quix0r** [comment] 2022-09-13 15:09
No, no composer or so needed. Just you might have some slow-downs as the templates needs rendering again. And it might not actually fix it but reduce bug origins (broken template caches).

**Comment by rickgardner077** [comment] 2022-09-16 11:01
I get similar notices on PHP 8.1.10, for example:
`2022-09-16T10:58:32Z index [NOTICE]: E_DEPRECATED: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated {"code":8192,"message":"htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated","file":"/var/www/virtual/rick6/friendica/view/smarty3/compiled/c57e7841bd9766908abe31285ce847411b16bb0a_2.file.nav.tpl.php","line":484} - {"file":"smarty_internal_errorhandler.php","line":82,"function":"handleError","uid":"7525ec","process_id":6660}`

I moved all files from view/smarty3/compiled/ as suggested by @Quix0r above. Afterwards the same issues persist

Addressed in https://github.com/friendica/friendica/pull/11904

**Comment by xundeenergie** [comment] 2022-09-17 17:51
I deleted this too... issue persists.

**Comment by MrPetovan** [comment] 2022-09-18 00:20
It's [a Smarty PHP 8 compatibility issue](https://github.com/smarty-php/smarty/issues/750) that has been fixed in the latest version that we should upgrade to this release.

**Comment by ghost** [comment] 2022-09-21 02:27
Latest RC

`PHP Notice:  Undefined index: network in /src/Model/Contact.php on line 3329`

**Comment by Quix0r** [comment] 2022-09-21 22:03
> /compiled/c57e7841bd9766908abe31285ce847411b16bb0a_2.file.nav.tpl.php

This tells me that your Friendica code isn't up-to-date. Friendica makes use of Smarty's "use sub-dirs" feature. Which adds 3 directories deep directories for each hash. So in short, `/compiled/c5/7e/78/c57e7841bd9766908abe31285ce847411b16bb0a_2.file.nav.tpl.php` should be the resulting path. Please don't create them by yourself. Smarty does this "on-the-fly" for you. :-)

**Comment by AlfredSK** [comment] 2022-09-28 15:19
Notices about the wordpress add-on:

```
PHP Notice:  Undefined index: wp_backlink in .../addon/wppost/wppost.php on line 93
PHP Notice:  Undefined index: wp_shortcheck in .../addon/wppost/wppost.php on line 94
PHP Notice:  Undefined index: wp_backlink_text in .../addon/wppost/wppost.php on line 95
```

2022-09-rc, PHP 7.4

Addressed in https://github.com/friendica/friendica-addons/pull/1283

**Comment by ghost** [comment] 2022-10-03 17:20
`PHP Notice:  Undefined index: object_object_type in /src/Protocol/ActivityPub/Receiver.php on line 891'`

Addressed in https://github.com/friendica/friendica-addons/pull/1283

**Comment by MrPetovan** [comment] 2022-10-03 17:48
Looks like a typo @annando ?

**Comment by annando** [comment] 2022-10-03 17:50
The `object_object_type` is intended that way.

**Comment by AlfredSK** [comment] 2022-10-11 18:38
New in 2022.09-rc

```
Undefined index: author-id in .../src/Model/Item.php on line 3415
Undefined index: author-network in .../src/Model/Item.php on line 3416
```
Addressed in https://github.com/friendica/friendica/pull/11988#event-7568322234

**Comment by MrPetovan** [comment] 2022-10-12 01:53
@annando The issue is in `Model\PlinkL::getPlink` where the keys of the parameter array are missing. I believe the invocation comes from `Model\Event::prepareListForTemplate` where these keys aren't set up. I'm not sure how to conjure them into existence in this context.

**Closed as completed** 2022-10-19 16:23 UTC
Labels: Bug
