### ISSUE TITLE
Easy way to see to which server a post couldn't be delivered.

### ISSUE THREAD

**Issue by schiessle** [friendica/friendica#8483] opened 2020-04-01 14:09 UTC
In the header of my post I see this:

![image](https://user-images.githubusercontent.com/1589737/78146611-ac87f700-7432-11ea-96d1-45d7b67e5244.png)

But there is no (easy) way to find out to which servers/users the post couldn't be delivered. This information would be really useful to discover dead accounts/server or to debug issues between servers. It would be nice if I could click on the icon and get a list of servers/accounts to which the post was delivered and to which it wasn't delivered. It could even open a new browser window with a plain text list, doesn't have to be fancy.

**Comment by MrPetovan** [comment] 2020-04-01 14:32
Duplicate of #8373

**Closed by MrPetovan** 2020-04-01 14:32 UTC
