### ISSUE TITLE
Diaspora links in the body of the post appear as text

### ISSUE THREAD

**Issue by romariorios** [friendica/friendica#6633] opened 2019-02-10 18:55 UTC
### Expected behavior

Links in the body of a post coming from Diaspora should appear as a link in Friendica as well.

### Actual behavior

They appear as non-clickable plain text

### Steps to reproduce the problem

Check the following post:
In Friendica: https://libranet.de/display/f36e00a00f8e013788640007cb0b4960
In Diaspora: https://diaspora.libertais.org/posts/f36e00a00f8e013788640007cb0b4960

### Friendica version you encountered the problem

This is Friendica, version 2019.03-dev that is running at the web location https://libranet.de. The database version is 1302, the post update version is 1297.

**Comment by MrPetovan** [comment] 2019-02-11 02:17
This issue can be debugged using the admin `/babel` and `/itemsource` pages.

**Comment by annando** [comment] 2019-02-27 20:34
I had a look in the source of the original post. The link in that post isn't marked as link. Means: It is just text. Diaspora seems to interpret links in text as well - we don't do this for Diaspora links. And I'm unsure if we should do so, since we already do have some issues with our link detection system.

**Comment by MrPetovan** [comment] 2019-02-27 20:38
Maybe there's a Markdown parser option for this?

**Comment by annando** [comment] 2019-02-27 20:41
Problem could also be that the link text is in some headline..

**Comment by MrPetovan** [comment] 2019-02-27 20:50
That's why I'm mentioned a Markdown parser option, which would assume would only look for links in text paragraphs. We can do it ourselves after the Markdown conversion, but it would require us to re-tokenize the result, which would basically be a duplicate of what the Markdown parser does.

**Comment by MrPetovan** [comment] 2019-03-06 06:07
I found a PHP Markdown library with an auto-link feature: https://github.com/erusev/parsedown-extra

I need to try it to compare specific texts that we are handling with the options of the current parsers:
- Hard Wrap: verify that it adds line breaks on `\n` without two trailling spaces
- Code Class Prefix: Verify that we can add a prefix to fenced code blocks HTML class for the text highlighter to work.
- Hashtag Protection: Verify that titles are only with a space after hash marks

**Comment by nupplaphil** [comment] 2019-03-06 10:59
Do we really want to add new libraries for the RC (because of the current milestone)? I think this is something for 2019.06, isn't it?

**Comment by MrPetovan** [comment] 2019-03-06 13:42
I guess we can push it to next release.

**Comment by MrPetovan** [comment] 2019-03-10 04:32
Turns out we didn't need any additional library nor upstream changes, just the good ol' inheritance magic.

**Comment by MrPetovan** [comment] 2019-03-10 04:32
Fixed by #6845

**Closed** 2019-03-10 12:51 UTC
Labels: Bug, Federation, Junior Jobs, UX
