### ISSUE TITLE
Successfull: Update from stable version to developer version.

### ISSUE THREAD

**Issue by gurussia** [friendica/friendica#4481] opened 2018-02-21 03:15 UTC
Hi guys

you are wondefull. it sucessfully update from stable to developer version, but again messages don't appear, so someone comment how to get e-mails that are in mysql and not in friendica.

**Comment by MrPetovan** [comment] 2018-02-21 04:14
Duplicate of #4478, please keep commenting in the original issue.

**Closed by MrPetovan** 2018-02-21 04:14 UTC
Labels: Sup­port Request
