### ISSUE TITLE
Newbie question: Theme modding, Frio's <title> tag

### ISSUE THREAD

**Issue by Narrekapp** [friendica/friendica#6805] opened 2019-03-03 23:25 UTC
Hello, i need a newbie tip on how to mod the <title> tag by changing a variable in the frio theme. 
I actually play with a local installation of friendica, i like it and want to understand it before an install. :)

I know this theme uses $page['title'] in frios default.php, i can enter a test string there, works fine
<title>testtest <?php if (!empty($page['title'])) echo $page['title'] ?></title>

Now i try to append a searched hashtag to page['title'] in /mod/search.php to page['title']

        if ($tag) {
                $title = L10n::t('#%s ', $search);
                $a->page['title'] .= $title;
                $a->page['htmlhead'] .= '<meta name="title" content="'.$title.'" />'."\n";

Appending to page['title'] doesnt work, appending to page['htmlhead'] works fine as expected.

I alway get <title>test.local (search)</title>

Where is my mistake?

**Comment by MrPetovan** [comment] 2019-03-04 03:46
Hi @Narrekapp and thanks for checking out Friendica. What version are you currently testing?

**Comment by MrPetovan** [comment] 2019-03-04 04:05
So I looked into it, and it turns out we simply are overwriting the `$a->page['title']` variable after the module execution in `src/App.php:561-563`. This is an unfortunate regression, thanks for bringing it up.

Now there are (at least) two ways of allowing modules to update the title:
1. Either we let the modules have complete control over the page title, and we only show `Site title (module)` when no custom title has been provided. This would require a module custom title to append manually the site title if it's intended to stay.
2. Or we only allow modules to append a custom string to a fixed prefix, like `Site title | <custom string>`.

Either way is fine, but both can't be done at the same time. Since you looked into it yourself, what would you expect?

**Comment by Narrekapp** [comment] 2019-03-04 07:38
Hello Mr. Petrovan, thx a lot in advance! I test with 2019.1 stable.

Whats the goal? 

I think the title should look similar to diaspora.

#intel - diaspora pod diasporg
https://diasp.org/tags/intel
Posts tagged: intel. ... bluesbabysoul64@diasp.org ... You should if you use #proprietarysoftware or #intel chips with back doors and have no physical switch for ...

 Imho it would be best if src/App.php appends the hostname  data to $page['title'] with a leading " | " if $page['title'] is not empty, else set it if still empty.

**Comment by MrPetovan** [comment] 2019-03-04 10:43
Fair enough, this fix will be included in the upcoming release of Friendica in the coming weeks.

**Comment by nupplaphil** [comment] 2019-03-04 14:17
Fixed at #6806

**Closed by nupplaphil** 2019-03-04 14:17 UTC
Labels: Bug, Help Wanted, Junior Jobs
