### ISSUE TITLE
Sometimes the pager isn't available on hashtag searches although there are more pages of search results

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#9165] opened 2020-09-08 15:45 UTC
### Expected behavior
Always show a pager for hashtag search if there are more than one page of search results

### Actual behavior
If you search for an hashtag (or if you visit your saved hashtag searches) sometimes the pager isn't shown at the bottom of the page although there is are more results. If you manually add the parameter '&page=2' to the url you will get the other results. Unfortunately I can't say in which cases this behavior is reproducible.

### Friendica version you encountered the problem
2020.09-rc

### PHP version
PHP 7.4

### SQL version
MariaDB 10.3

**Comment by MrPetovan** [comment] 2020-09-09 04:28
Can you please verify #9170 fixes this issue (or not)? I have the feelings both #9164 and this issue are connected but I haven't been able to reproduce this. I tested after writing #9170 so it's possible that the fix covers both issues.

**Comment by rabuzarus** [comment] 2020-09-15 14:10
Unfortunately https://github.com/friendica/friendica/pull/9170 doesn't fix the problem. I have the issue if I search for `#friendica` on libranet. If I search for `#friendica` on your instance (through remote auth) I have also the issue

**Comment by AlfredSK** [comment] 2020-09-15 15:18
It doesn't work on stable, too. I just checked searching for a hashtag with lots of content: `#art` No pager buttons/links on stable, develop and RC.

Btw. what is the correct URL query parameter? Is it `/search?q=%23art` or is it `search?tag=art`?

I found out that when you add `&page=2` to the URL you get content. But there is only a "back" (newer) button - no "forward" (older) button.

**Comment by MrPetovan** [comment] 2020-09-17 15:40
> Unfortunately #9170 doesn't fix the problem. I have the issue if I search for `#friendica` on libranet. If I search for `#friendica` on your instance (through remote auth) I have also the issue

So, on my main node, page 1 doesn't show the next page link, neither does page 2, but it shows on page 3 (!), and disappears again on page 4 and 5 (!?), and shows again on page 6 (!!).

On my dev node, it shows on page 1 but not on page 2 since the page 3 is empty.

I'm thoroughly confused now. Why the multiples of 3? Why the difference between my main node and my dev node?

**Comment by AlfredSK** [comment] 2020-09-17 15:54
Sounds like an interesting problem. :-) For me it's different. 
Page 1: no buttons
Page 2-5: back button only
Page 6: both buttons! :-)
Page 7-11: back button only
Page 12: both buttons! :-)

My display settings:
Number of items per page: 30
Number of items to display per page when viewed from mobile device: 20

Ahaaaa! When I change the number of items per page to 50:
Page 1: no buttons
Page 2-15 !!!: back button only
Page 16: both buttons! :-)

**Comment by AlfredSK** [comment] 2020-09-17 16:02
When I set the number of items per page to 2 both buttons are on every page with content* except page 1.

*) some pages are showing a 'no results' info bubble.

**Comment by MrPetovan** [comment] 2020-09-17 16:03
Well, after reading the search code I'm a little less confused.

To work properly the pager expects a total number of items that can be returned by a given query before we run the paginated query. This allows the normal pager to show the last page link, and it allows the minimal pager to show the next page button if the total number of item is greater or equal to the page size. This is important.

In the case of tag search, however, this count is never provided. Instead we just retrieve as most URI Ids as the page size for the given hashtag. And then we run them through `Item::selectForUser` which result may contain less than the page size even if the initial query returned exactly as many rows as the page size. This is important.

Both are important because it is the final count of items that is fed to the pager as the total number of items. There are multiple consequences:
1. The next page link will only be shown if the URI Ids query returns as many results as the page size and all of them have a corresponding item for the current user. In this case the total number of items is equal to the page size. On my dev node where I do not receive random public items, this is the case and that's why the pager has been consistent. On any other node where all the items are not owned by a single user, the pager will break. Not consistently, this edge case can still happen, but it is less likely.
2. Since the query with the page size limit is then filtered possibly under the page size, moving to the next page will ignore all the URI Ids that were found in the previous query but discarded because they didn't have a local user counter-part. So users are missing on search results just because they never interacted with a given public post. I don't think this is desirable.

The remediation to these issues is respectively easy and hard:
1. Obtain a full count of URI Ids for a given tag (easy).
2. Make sure that the query returning items from these URI Ids returns exactly as many rows than URI Ids provided (hard).

I do not have a good enough grasp on the URI Id/Item relationship to reliably ensure number 2. and have to call @annando for help since he's the one who came up with this concept and applied it to the tag search.

**Comment by MrPetovan** [comment] 2020-09-18 04:20
This needs to stay open for the second part, ensuring that the user has access to all the search results returned by `Tag::getUriIdsByTag`, not just the ones that are returned by `Item::selectForUser`.

**Comment by AlfredSK** [comment] 2020-09-18 11:12
Pager buttons are back. :-)

**Comment by annando** [comment] 2020-09-18 18:16
@MrPetovan I can understand why we keep this open, but we should reschedule it to the next milestone, shouldn't we?

**Comment by MrPetovan** [comment] 2020-09-18 20:16
I didn't know if you planned on tackling this for this release.

**Comment by MrPetovan** [comment] 2020-09-18 20:16
Oooh, multiple assignments on issues, I didn't know GitHub had implemented that feature.

**Comment by annando** [comment] 2020-09-18 20:36
I would like to touch this issue again when using views for the item related queries. And this won't come in the next days.

**Comment by annando** [comment] 2020-11-26 19:32
Is this still an issue?

**Comment by AlfredSK** [comment] 2020-11-26 19:57
Cannot check. There is infinite scroll now. :-)

**Comment by AlfredSK** [comment] 2020-11-26 20:02
Disabled infinite scroll. Went back in time with the #friendica hashtag. Page 1 to 20 worked perfectly fine.

**Closed** 2020-11-27 04:57 UTC
Labels: Bug, UX
