### ISSUE TITLE
Not able to change password

### ISSUE THREAD

**Issue by casperrutten** [friendica/friendica#7792] opened 2019-11-01 13:53 UTC
### Expected behavior
In Account Settings-> Change Password:
- Enter new password
- Confirm new password
- Enter old password

Message: Password successfully changed
### Actual behavior
Failure: 'Login Failed' and ' Password unchanged'

### Steps to reproduce the problem
- Logout and login
Enter your username
Enter a space and then your password
After successful login try to change the password

### Friendica version you encountered the problem
2019-09 - 1323
see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
zip
### PHP version
7.2
### SQL version
MariaDB 10.2.27

I think I found a bug.
I encountered this problem, because I double-clicked the password in the confirmation email and pasted it in the (FF) browser. I could not see there was (probably) a TAB value in the copied password. Everything goes fine, as long as you don't try to change the password.
I debugged it until I noticed that in the src/Model/User.php -> getIdFromPasswordAuthentication there was a space prior the value of $password. Non of the conditions was valid an error was returned (line 333).

Work around:
Logout and login with your password without prefix.

Not a big thing, but it took me some time to find the issue.

**Comment by MrPetovan** [comment] 2019-11-01 14:59
So, let me resume:
- Stored password doesn't have a whitespace character (space, tab, line feed)
- Copied password from the email has a whitespace character
- Login works, presumably because we strip whitespace characters from the password input
- Changing password with the same copied password doesn't work, presumably because we don't strip whitespace characters from the password input.

What about changing the password with the correct password (excluding whitespace characters)?

**Comment by casperrutten** [comment] 2019-11-01 18:29
Yes, that works. But if you didn't notice that there was a whitespace character in the password, because it is saved in your browser, than the average user get lost

**Comment by MrPetovan** [comment] 2019-11-01 18:37
Aaaah, the famous "authentication worked, so my browser saved it as is" issue. Duplicate of #7719, will be solved when we eventually allow users to submit their own password.

Maybe we should stop trimming whitespace characters from input when authenticating as well.

Closed as duplicate, please add any relevant information on #7719.

**Closed by MrPetovan** 2019-11-01 18:37 UTC
Labels: Needs More Info, Sup­port Request

**Comment by jluttine** [comment] 2023-12-12 18:22
This bug hit me as well. A few suggestions:

- Don't put a tab in the email. I mean, when copying the password from the email, it shouldn't contain any whitespace. I verified that Thunderbird highlights only text but for some reason the copied text has a tab at the beginning. No idea why. I suppose there's something weird in that part of the email. This has never happened before with any other service when I copy-paste passwords from emails, so there is something atypical in the email.

- Don't strip whitespace from passwords when authenticating - or strip it everywhere.

I didn't comment on the other issue because I think it's a bit separate matter.
