### ISSUE TITLE
Relationship status and gender fields show on profile when empty

### ISSUE THREAD

**Issue by WeAreGeek** [friendica/friendica#6630] opened 2019-02-10 13:51 UTC
### Expected behavior
When relationship status and gender are not filled in, it should show nothing on your profile page.

### Actual behavior
On the profile page the relationship and gender icons are showed, followed by the word EMPTY

### Steps to reproduce the problem
Go to Settings > Profiles
Enable "Show more profile fields"
Click Submit
Expand Relation section
Click Submit in Relation section, without filling any field.
(Gender icon appears on profile followed by the word EMPTY)
Click Submit in Relation section again, without filling any field.
(Relationship icon appears on profile followed by the word EMPTY)

### Friendica version you encountered the problem
Friendica version 2019.03-dev
Database version 1302
Post update version 1297.

### PHP version
PHP 7.2.10

### SQL version
MariaDB 10.1.38

[Edit 1] : See this profile as an example: https://libranet.de/profile/testnerd/?tab=profile
It seems that Sexual Preference field is also affected (in the Advanced tab)
[Edit 2]: Typo: Expend -> Expand
[Edit 3]: Updated with PHP/SQL versions used on libranet.de

**Comment by MrPetovan** [comment] 2019-02-10 14:04
Hi @WeAreGeek and thanks for your report, this is peculiar indeed.

FYI, you can know the version of any Friendica server by checking https://libranet.de/friendica

**Comment by AlfredSK** [comment] 2019-02-10 14:38
Confirmed on libranet.de. Actually, it shows `EMPTY never`. :-)

Like reported... Friendica 2019.03-dev
PHP 7.2.10
MariaDB 10.1.38

**Comment by AndyHee** [comment] 2019-02-18 04:29
Relates to this: https://github.com/friendica/friendica/issues/6105 .

**Comment by AlfredSK** [comment] 2019-02-18 17:46
After I edited my profile I have this:
Gender: EMPTY
♥ Status: EMPTY never
Sexual Preference: EMPTY

...which is kind of sad. ;-)

**Comment by WeAreGeek** [comment] 2019-02-18 18:49
> After I edited my profile I have this:
> Gender: EMPTY
> ♥ Status: EMPTY never
> Sexual Preference: EMPTY
> 
> ...which is kind of sad. ;-)

Haha! Yes. Which is why I chose to fill in the fields anyway, because having EMPTY on my profile page is quite sad indeed, but now it says "♥ Status: Single never", which is even more saddening. :')

**Comment by AlfredSK** [comment] 2019-02-18 19:14
@WeAreGeek I fixed both our profiles by editing the database.

The three mentioned fields had really the value of `EMPTY` stored in the DB. :-/

**Comment by MrPetovan** [comment] 2019-02-24 11:59
Closed via #6737

**Closed by MrPetovan** 2019-02-24 11:59 UTC
Labels: Bug, Help Wanted, Junior Jobs, UX

**Comment by MrPetovan** [comment] 2019-02-24 12:01
Since there was no release between the introduction of the localized gender label feature and this fix, the existing "EMPTY" values have to be overwritten by saving the profile settings, there will be no backward-compatibility.
