### ISSUE TITLE
user profile not available after registration

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4042] opened 2017-12-08 13:25 UTC
Hello,
see discussion here: https://forum.friendi.ca/display/0b6b25a8125a297737e6a4e212566317

There's an issue with registrations and creation of user profiles. I think this is a high priority bug because it prevents new users from actually using Friendica.

Code base: current 3.6-dev
PHP: 7.0 (don't know if this is relevant)

Description:
After a new user has registered the user is able to login but gets an error notification "profile not available". Each click on buttons/links related to the user's profile triggers the "profile not available" notification. The user cannot post, upload photos, edit profile, add contacts and so on. The user is also not able to delete the account.
Additionally, new users are not visible on admin/users.

What I see in the DB:
The user is created (table user); the profile is created (table profile); there is no 'self' contact (table contact).

Urgency:
Please make this a high priority bug because it keeps us from gaining world domination. :-)

Thank you!

**Comment by MrPetovan** [comment] 2017-12-08 13:27
Duplicate of #4041, please post your comment over there, thanks!

**Closed by MrPetovan** 2017-12-08 13:27 UTC
