### ISSUE TITLE
Solved: Error 1709: Index column size too large. The maximum column size is 767 bytes

### ISSUE THREAD

**Issue by gurussia** [friendica/friendica#4458] opened 2018-02-14 16:25 UTC
HI guys. When i install friendica it comment me this errors: Error 1709: Index column size too large. The maximum column size is 767 bytes

So i change it in utf8_unicore utf_ci and something didn't work. So i find this solution and now maybe it work 100 % completly. I can put photos in my wall and etc. Thanks again on friendica guys for making and defending humankind of all government corruption

https://bgzashtita.es/git/peturbg/mysql/src/master/Error%201709:%20Index%20column%20size%20too%20large.%20The%20maximum%20column%20size%20is%20767%20bytes

It can comment gogs, but it will maybe works on all database that comment Error 1709: Index column size too large. The maximum column size is 767 bytes This problem maybe come from problematic mariadb, if you install friendica on old MYSQL it will work. i known that mariadb is SHIT.

**Comment by MrPetovan** [comment] 2018-02-14 16:41
This looks like a duplicate of #4448, if you solved your issue please comment over there instead.

**Comment by annando** [comment] 2018-02-14 17:14
From my point of view it seems like a duplicate to #4448 - so @gurussia please close this one, if you agree. And please tell how you solved it. And especially: Please tell us the version number of your database server software and if you are using MyISAM or InnoDB. Thing is: We have to see if this problems comes because of some old or same brand new version. And no: MariaDB is a good piece of software. I'm using it every day.

**Comment by AlfredSK** [comment] 2018-02-14 20:24
Without knowing your exact DB configuration I can only tell two things...

**You can prevent that issue by not using utf8mb4 but plain old utf8 instead.** Utf8mb4 does allow a maximum column size of 767 bytes. Utf8 does allow more than 1000 bytes (don't know the exact figures). A workaround for utf8mb4 is to reduce the length of varchar fields from 255 to 191 characters.

**The more elegant solution is to use 'Barracuda' file format for InnoDB.** 'Barracuda' supports the dynamic row format (as described in the issue you linked above). Dynamic rows don't have the issue with unique indexes and max column size. But there is more to do than just change the row format. Here is a interesting link...

https://docs.nextcloud.com/server/12/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by MrPetovan** [comment] 2018-02-14 20:33
Thanks for the link, I wasn't aware of the Barracuda file format.

**Comment by annando** [comment] 2018-02-14 21:39
Normally we shouldn't have any unique index that is longer than allowed. So it would be nice to know more. But @gurussia hadn't really provided yet exact details about which table does the problem.

**Comment by AlfredSK** [comment] 2018-02-14 22:09
> Normally we shouldn't have any unique index that is longer than allowed.

That's right. That's why I didn't convert the Friendica database.
...and because the DB is huge and it would take hours and hours to convert it. :-)

**Comment by gurussia** [comment] 2018-02-15 01:10
the exact issue table is... ufff... i cant remember, but maybe it was " contacts, tracker... if i remember correctly they was 3 issue table or more i dont remember. and table in general is innodb, so this issue more than 7xx bytes dont have to exist. now  as for collation table, it has to be utf8mb4_unicore_cli..in utf8_unicore_cli it works from first install, now i read someone comment utf8mb has all 17 for that it is good to be in utf8mb4, include when i found solution amd i convert all tables by hands " thanks you all my souls, it is not easy to convert all tablets by hands " now everything works include i can upload photos. mariadb IS SHIT. i read that this maria has issue with 7xx but in linus is so stupid to permit bugged maria to be  installed now all peoples have to fault linus torvalds include i read yestarday that there is bug in kernel from years 2013 or year 2014 and linus tarval didnt want to solve, bulgarian man fix kernel linus torval and linus torval insult him include linus torvalds tell bulgarian man kill himself.

**Comment by MrPetovan** [comment] 2018-02-15 01:12
Issue solved, then.

**Closed by MrPetovan** 2018-02-15 01:12 UTC
Labels: Installation, Sup­port Request
