### ISSUE TITLE
[master] Favoriting/Liking in Friendica of a GNUSocial notice doesn't end up in GS

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#2339] opened 2016-02-10 18:41 UTC
I run latest master on my server (both). GS<->GS likes/faves are going through, also GS->Friendica but not Friendica->GS. I have activated the addon for GNU Social federation. Also without it, I can "like" in Friendica but it doesn't show up in my GNU Social instance.

I have retried this with many other popular GS instances, like quitter.se, gnusocial.de/ch and such, no difference.

**Comment by tobiasd** [comment] 2016-02-10 21:15
You don't need any addon for communication between Friendica and GNU Social, you only have to check "Enable OStatus support" in your admin panel to activate the communication.

The addon is for reposting public entries from your Friendica account on a GNU Social account elsewhere.

**Comment by Quix0r** [comment] 2016-02-11 10:26
Okay, I have deactivated it now. Maybe I got a bit confused with it. :)

And no, still not showing up (my fave from Friendica -> GS):
https://gnusocial.de/notice/7047713

**Comment by tobiasd** [comment] 2016-02-11 13:41
I have the same issue with current develop brach @annando but I remember it worked before

**Comment by Quix0r** [comment] 2016-02-11 16:11
This comes from a local installation: https://social1 is GNUSocial master and https://friendica is "develop" Friendica code.
````
2016-02-11 16:02:25 LOG_INFO: [social1:queuedaemon.php:3969] claiming queue item id = 86 for transport pushin
2016-02-11 16:02:25 LOG_DEBUG: [social1:queuedaemon.php:3969] claim succeeded.
2016-02-11 16:02:25 LOG_DEBUG: [social1:queuedaemon.php:3969] DBQueueManager (main): Got array with 3 elements (keys:[feedsub_id,post,hmac]) for transport pushin
2016-02-11 16:02:25 LOG_INFO: [social1:queuedaemon.php:3969] FeedSub::receive: packet for "https://friendica/dfrn_poll/quix0r"! sha1=3143ee35e9ec4ebda655f4bee7fc359750d01ef8 <?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:thr="http://purl.org/syndication/thread/1.0" xmlns:georss="http://www.georss.org/georss" xmlns:activity="http://activitystrea.ms/spec/1.0/" xmlns:media="http://purl.org/syndication/atommedia" xmlns:poco="http://portablecontacts.net/spec/1.0" xmlns:ostatus="http://ostatus.org/schema/1.0" xmlns:statusnet="http://status.net/schema/api/1/">
  <generator uri="https://friendi.ca" version="3.5-dev-1194">Friendica</generator>
  <id>https://friendica/profile/quix0r</id>
  <title>Roland Haeder timeline</title>
  <subtitle>Updates from Roland Haeder on Friendica Social Network</subtitle>
  <logo>https://friendica/photo/215cf3d43b94e278b0a6ee9992781e7e-4.png</logo>
  <updated>2016-02-11T16:02:24Z</updated>
  <author>
    <activity:object-type>http://activitystrea.ms/schema/1.0/person</activity:object-type>
    <uri>https://friendica/profile/quix0r</uri>
    <name>Roland Haeder</name>
    <link rel="alternate" type="text/html" href="https://friendica/profile/quix0r"/>
    <link rel="avatar" type="image/jpeg" media:width="175" media:height="175" href="https://friendica/photo/215cf3d43b94e278b0a6ee9992781e7e-4.png"/>
    <link rel="avatar" type="image/jpeg" media:width="80" media:height="80" href="https://friendica/photo/215cf3d43b94e278b0a6ee9992781e7e-5.png"/>
    <poco:preferredUsername>quix0r</poco:preferredUsername>
    <poco:displayName>Roland Haeder</poco:displayName>
    <poco:note/>
    <poco:address>
      <poco:formatted>Krefeld, Nordrhein-Westfalen, Germany</poco:formatted>
    </poco:address>
    <poco:urls>
      <poco:type>homepage</poco:type>
      <poco:value>https://daedalus</poco:value>
      <poco:primary>true</poco:primary>
    </poco:urls>
    <followers url="https://friendica/viewcontacts/quix0r"/>
    <statusnet:profile_info local_id="2"/>
  </author>
  <link href="https://friendica/profile/quix0r" rel="alternate" type="text/html"/>
  <link href="https://friendica/pubsubhubbub" rel="hub"/>
  <link href="https://friendica/salmon/quix0r" rel="salmon"/>
  <link href="https://friendica/salmon/quix0r" rel="http://salmon-protocol.org/ns/salmon-replies"/>
  <link href="https://friendica/salmon/quix0r" rel="http://salmon-protocol.org/ns/salmon-mention"/>
  <link href="https://friendica/api/statuses/user_timeline/quix0r.atom" rel="self" type="application/atom+xml"/>
  <entry>
    <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
    <id>urn:X-dfrn:friendica:2:a4285f1d2056bcb08e18d6d150649060</id>
    <title>New note by quix0r</title>
    <content type="html">&lt;a href="https://friendica/profile/quix0r" target="_blank"&gt;Roland Haeder&lt;/a&gt; likes Roland Haeder &lt;a href="https://social1/roland" target="_blank"&gt;https://social1/roland&lt;/a&gt;'s status &lt;a href="https://friendica/display/quix0r/86" target="_blank"&gt;https://friendica/display/quix0r/86&lt;/a&gt;</content>
    <link rel="alternate" type="text/html" href="https://friendica/display/000000004a883c1cc96ee1079aa00e0a7b95fa3e"/>
    <status_net notice_id="90"/>
    <activity:verb>http://activitystrea.ms/schema/1.0/like</activity:verb>
    <published>2016-02-11T16:02:22Z</published>
    <updated>2016-02-11T16:02:22Z</updated>
    <thr:in-reply-to ref="tag:social1,2016-02-11:noticeId=14:objectType=note" type="text/html" href="https://friendica/display/2d8adac7b26e14486ef5671ac8ca614a2b58bcc8"/>
    <link rel="related" href="https://friendica/display/2d8adac7b26e14486ef5671ac8ca614a2b58bcc8"/>
    <link rel="ostatus:conversation" href="https://friendica/display/quix0r/79"/>
    <ostatus:conversation>https://friendica/display/quix0r/79</ostatus:conversation>
    <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/person" href="https://social1/admin"/>
    <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/person" href="http://social1/admin"/>
    <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/person" href="https://social1/roland"/>
    <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/person" href="http://social1/roland"/>
    <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/collection" href="http://activityschema.org/collection/public"/>
    <statusnet:notice_info local_id="90" source="web"/>
  </entry>
</feed>
2016-02-11 16:02:25 LOG_DEBUG: [social1:queuedaemon.php:3969] Failed to store activity object in database (Notice has no object type.), deleting notice id 16
2016-02-11 16:02:25 LOG_ERR: [social1:queuedaemon.php:3969] Entry threw exception while processing a feed from push: Notice has no object type.
2016-02-11 16:02:25 LOG_INFO: [social1:queuedaemon.php:3969] DBQueueManager (main): [pushin:array with 3 elements (keys:[feedsub_id,post,hmac])] Successfully handled item
````

**Comment by Quix0r** [comment] 2016-02-14 15:47
@tobiasd then it might be a regression?

**Comment by tobiasd** [comment] 2016-02-14 16:13
Or something has changed on the other side. Or it was a coincident to work before... distributed debugging is hard, federated debugging is even harder. @annando has changed some things under the hood, so maybe it is a regression.

**Comment by annando** [comment] 2016-02-14 19:35
@Quix0r Thanks for the information. I will have a look into it.

**Comment by annando** [comment] 2016-04-02 16:22
The latest changes in Friendica have solved this. Liking (and native resharing) should now work reliable. Does anyone wants to test it before we close the issue?

**Comment by tobiasd** [comment] 2016-04-02 20:30
I liked some postings after merging this PR and all likes reached their targets. But that is only a limited test as I don't remember which GS/SN versions worked before this merge and which did not.

**Comment by annando** [comment] 2016-04-02 23:47
That's easy: It hadn't worked before at all :-)

It is still not working with Statusnet - but this is caused by Statusnet which hadn't distributed the "likes" at all.

**Comment by tobiasd** [comment] 2016-04-03 04:57
> That's easy: It hadn't worked before at all :-)

Nope it did, very unreliable but on some nodes it did. Anyway it is working now so I think we can close this issue.

**Comment by annando** [comment] 2016-04-03 14:54
Okay, I'm closing it.

**Closed by annando** 2016-04-03 14:54 UTC
Labels: Bug, Federation
