### ISSUE TITLE
Addons and connectors completely disabled

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7383] opened 2019-07-15 07:01 UTC
After my last git pull this morning, all Addons and connectors are disabled and can't be activated again.

### Friendica version you encountered the problem
git, Develop, MariDB, PHP7.2

**Comment by nupplaphil** [comment] 2019-07-15 07:08
Confirmed on local node
Caused by #7372 
Should be fixed by #7384

**Comment by nupplaphil** [comment] 2019-07-15 14:15
@hoergen does it work again?
I've the fear that you do have to re-enable all addons & connectors again. Big sorry for that!

**Comment by hoergen** [comment] 2019-07-15 14:56
It works again and as you said all addons had to be activated again. But fortunately all configurations are still there 👍

**Closed** 2019-07-15 15:09 UTC
Labels: Bug
