### ISSUE TITLE
Mastodon users can not follow my Friendica account

### ISSUE THREAD

**Issue by schiessle** [friendica/friendica#3822] opened 2017-10-23 20:57 UTC
I run Friendica, the latest version from master. People told me that they can't follow me from mastodon so I tested it by myself. I set the log level to "debug" in my Friendica instance and tried to connect with my mastodon.social account. This is shown in the log file:

````
2017-10-23T20:54:02Z@sgmlvksda4eofb5tusvoqsk6eb	[DEBUG]:Probe.php:103:hostMeta	Probing for bjoern@mastodon.social
2017-10-23T20:54:02Z@sgmlvksda4eofb5tusvoqsk6eb	[DEBUG]:Probe.php:157:hostMeta	Probing successful for bjoern@mastodon.social
2017-10-23T20:54:02Z@sgmlvksda4eofb5tusvoqsk6eb	[DEBUG]:dfrn_request.php:474:dfrn_request_post	dfrn_request: url: https://mastodon.social/authorize_follow?acct={uri},network=stat
2017-10-23T20:54:02Z@hpjbg4rcsdölkölf43fdjhfkjsf6v89	[TRACE]:session.php:39:ref_session_read	no data for session hpjbg4rcsdölkölf43fdjhfkjsf6v89
````

on Mastodon I got this error: " Unfortunately, there was an error looking up the remote account "

Any idea what's wrong here?

**Comment by schiessle** [comment] 2017-10-23 21:28
I just found this https://github.com/tootsuite/mastodon/issues/789

I will try it tomorrow, if the suggested URL change works it is probably a Mastodon issue.

**Comment by annando** [comment] 2017-10-24 06:18
Please list all log entries with "sgmlvksda4eofb5tusvoqsk6eb" in it. This marks a session.

This issue from Mastodon shouldn't matter. This was from April - and snarl is always on master. In the meantime we improved the OStatus connection massively.

**Comment by schiessle** [comment] 2017-10-24 10:05
@annando in debug mode I just have this messages in the log:

````
2017-10-24T10:00:34Z@qi8varqha4q1d8occvsepmms63	[DEBUG]:Probe.php:103:hostMeta	Probing for bjoern@mastodon.social
2017-10-24T10:00:34Z@qi8varqha4q1d8occvsepmms63	[DEBUG]:Probe.php:157:hostMeta	Probing successful for bjoern@mastodon.social
2017-10-24T10:00:34Z@qi8varqha4q1d8occvsepmms63	[DEBUG]:dfrn_request.php:474:dfrn_request_post	dfrn_request: url: https://mastodon.social/authorize_follow?acct={uri},network=stat
2017-10-24T10:00:34Z@6mmlst3upud89ikgmkl0q5a70c	[TRACE]:session.php:39:ref_session_read	no data for session 6mmlst3upud89ikgmkl0q5a70c
````

If I set the log level to "all" I see this (though not all seems to be relevant for the subscription process, but maybe you find something useful): https://www.schiessle.org/debug.all.log

**Comment by annando** [comment] 2017-10-24 12:11
So there were only three lines with that value? "all" mostly doesn't matter. BTW: You had activated OStatus on your system?

**Comment by schiessle** [comment] 2017-10-24 12:20
yes, this are the only lines written to the log while I try to connect via mastodon. This log also contain some xml content which was send back and forth, don't know if this is useful: https://wolke.schiessle.org/s/HvfU1E1cSO2mqcL

OStatus support is enabled and I can connect with my GNU Social account just fine.

**Comment by annando** [comment] 2017-10-24 12:52
I can follow you from Friendica, GNU Social and Pleroma, but not from Mastodon. So Mastodon does something different. I will try to reproduce it. But possibly you could add a comment as well to the linked Mastodon issue?

**Comment by schiessle** [comment] 2017-10-24 13:19
@annando ok, i will add a comment to the Mastodon issue

**Comment by Alkarex** [comment] 2017-10-24 21:47
Related https://github.com/friendica/friendica/issues/3566

**Comment by annando** [comment] 2017-10-25 05:26
@Alkarex no, it isn't. The reason for issue https://github.com/friendica/friendica/issues/3566 is that the salmon doesn't arrive at the target. This here is some problem inside of Mastodon that seems to be caused by some unexpected answer that we are providing.

**Comment by annando** [comment] 2017-10-25 05:33
This seems to be a Mastodon bug concerning their used HTTP library: https://github.com/tootsuite/mastodon/issues/4254

**Comment by annando** [comment] 2018-03-18 13:22
From my point of view we can close this issue, since this seemed to be a (now solved) Mastodon Bug. All my tests looked really fine.

**Comment by AlfredSK** [comment] 2018-03-18 13:34
Yep. Works. :-)

**Comment by annando** [comment] 2018-03-20 21:07
@MrPetovan Is there a reason that we keep this issue open?

**Closed** 2018-03-20 22:42 UTC
Labels: Bug, Federation
