### ISSUE TITLE
updated to 3.3.1 from 3.2 , categories working oddly. 

### ISSUE THREAD

**Issue by plankatron** [friendica/friendica#1251] opened 2014-12-17 21:59 UTC
When I add something to a category after the update it will show up, but any pre 3.3.1 category shows nothing, however the posts do show up in the archives. 

Also the categories dont show up at all if I click on the main logo link, or the activity feed, they only show up when i click on my account name link. 

Any help is much appreciated.

**Comment by silke** [comment] 2015-03-20 08:56
How to procede? This is not so easy to reproduce as both are (now) old versions.

**Comment by annando** [comment] 2015-03-26 21:33
I sometimes heard weird behaviour about the categories when the threads were introduced. Mostly it seemed to work, but sometimes there was a problem. But like you said: The problem was when converting from 3.2 to 3.3.

Additionally I heard from some people that the system seemed to heal itself. I can imagine that the problem occurred on systems where the threads weren't created completely.

**Comment by plankatron** [comment] 2015-03-26 21:36
annando ,  if the system never healed itself, is there any kind of possible workaround ?

**Comment by annando** [comment] 2015-03-27 05:29
The question is if "threadupdate.php" really ran until the end. Normally this problem can only occur if there are categories in the item table but the items aren't connected to a thread. How good are you in SQL? Then you could have a look into the item table for some of the empty categories. Then you could see if the "parent" value is found in the "thread" table. (In the field "iid").

**Comment by tobiasd** [comment] 2015-11-08 12:33
what is the status of this issue?

**Comment by plankatron** [comment] 2015-11-08 18:42
hi there, was unesolved because i wasnt that good at mysql, i could however
see if a friend of mine who is could check out. thanks for the reminder !

On Sun, Nov 8, 2015 at 4:33 AM, Tobias Diekershoff <notifications@github.com

**Comment by tobiasd** [comment] 2015-11-08 20:40
:+1:

**Comment by annando** [comment] 2017-08-20 21:14
Currently we are at 3.5.3 - question is if this is still an issue. Does anyone disagree to close it?

**Comment by MrPetovan** [comment] 2017-11-11 23:04
3 months later, let's close it.

**Closed by MrPetovan** 2017-11-11 23:04 UTC
Labels: Bug
