### ISSUE TITLE
[2021.06] PHP Warnings

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#10168] opened 2021-04-26 08:12 UTC
Please report here any PHP Warning message obtained running the 2021.01 stable or 2021.06-dev versions.

Closes #9748

**Comment by 4nanook** [comment] 2021-04-27 23:05
I am running 2021.06-dev and getting a large amount of these:
2021-04-27T22:58:01Z worker [WARNING]: Minimal memory reached. {"free":502,"memtotal":64318,"limit":"1024"} - {"file":"Process.php","line":193,"function":"isMinMemoryReached","uid":"ee7d3f","process_id":1913177}
2021-04-27T22:58:01Z worker [WARNING]: Memory limit reached - quitting [] - {"file":"Process.php","line":257,"function":"run","uid":"ee7d3f","process_id":1913177}
2021-04-27T22:58:01Z worker [WARNING]: Minimal memory reached. {"free":502,"memtotal":64318,"limit":"1024"} - {"file":"Process.php","line":193,"function":"isMinMemoryReached","uid":"ee7d3f","process_id":1913177}
2021-04-27T22:58:01Z worker [WARNING]: Memory limit reached, quitting. [] - {"file":"Worker.php","line":187,"function":"isReady","uid":"ee7d3f","process_id":1913177}
2021-04-27T22:59:01Z worker [WARNING]: Minimal memory reached. {"free":499,"memtotal":64318,"limit":"1024"} - {"file":"Process.php","line":193,"function":"isMinMemoryReached","uid":"bb831c","process_id":1913557}
2021-04-27T22:59:01Z worker [WARNING]: Memory limit reached - quitting [] - {"file":"Process.php","line":257,"function":"run","uid":"bb831c","process_id":1913557}
2021-04-27T22:59:01Z worker [WARNING]: Minimal memory reached. {"free":499,"memtotal":64318,"limit":"1024"} - {"file":"Process.php","line":193,"function":"isMinMemoryReached","uid":"bb831c","process_id":1913557}
2021-04-27T22:59:01Z worker [WARNING]: Memory limit reached, quitting. [] - {"file":"Worker.php","line":187,"function":"isReady","uid":"bb831c","process_id":1913557}
2021-04-27T23:00:01Z worker [WARNING]: Minimal memory reached. {"free":481,"memtotal":64318,"limit":"1024"} - {"file":"Process.php","line":193,"function":"isMinMemoryReached","uid":"a0a6dc","process_id":1913966}
2021-04-27T23:00:01Z worker [WARNING]: Memory limit reached - quitting [] - {"file":"Process.php","line":257,"function":"run","uid":"a0a6dc","process_id":1913966}
2021-04-27T23:00:01Z worker [WARNING]: Minimal memory reached. {"free":480,"memtotal":64318,"limit":"1024"} - {"file":"Process.php","line":193,"function":"isMinMemoryReached","uid":"a0a6dc","process_id":1913966}
2021-04-27T23:00:01Z worker [WARNING]: Memory limit reached, quitting. [] - {"file":"Worker.php","line":187,"function":"isReady","uid":"a0a6dc","process_id":1913966}
I have my memory limit set to: memory_limit = 429496729, 4GB ought to be enough for any reasonable PHP script.

**Comment by tobiasd** [comment] 2021-04-28 04:33
The message comes from the background process and refers to the "minimum memory" setting in the admin panel -> site configuration. A worker is only spawned, if there is more then the minimal memory avail-able.

Check if the queue is processed, then maybe fewer worker processes might be enough (but keep one fastlane enabled), and check that the other "Worker" settings are reason-able.

**Comment by 4nanook** [comment] 2021-04-28 04:42
Ok, thanks for the clue.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment] 2021-04-28 04:44
I think this was actually caused by my attempt to get a Mastodon working.
Something caused it to go apeshit and eat up all system memory (64GB).

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by ghost** [comment] 2021-04-28 08:57
Im on stable PHP 7.4
`PHP Warning:  Illegal offset type in /friendica/src/Model/GServer.php on line 853`

Addressed in #10345

**Comment by 4nanook** [comment] 2021-04-29 23:25
```
2021-04-29T20:03:28Z index [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'url' at row 1","callstack":"Media::insert, Processor::storeAttachmentAsMedia, Processor::storeAttachments, Processor::updateItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent, call_user_func","params":"INSERT INTO `post-media` (`uri-id`, `type`, `url`, `mimetype`, `height`) VALUES (774760, 16, 'magnet:?xs=https%3A%2F%2Fvideos.lukesmith.xyz%2Flazy-static%2Ftorrents%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.torrent&xt=urn:btih:beea58577a63cd19067aad7047ba7f61617965f8&dn=REACTS%3A+%F0%9F%96%90%EF%B8%8F%F0%9F%98%AE%F0%9F%96%90%EF%B8%8F+The+Fish+%22shell%22+is+not+a+shell+and+is+cringe+to+use.&tr=https%3A%2F%2Fvideos.lukesmith.xyz%2Ftracker%2Fannounce&tr=wss%3A%2F%2Fvideos.lukesmith.xyz%3A443%2Ftracker%2Fsocket&ws=https%3A%2F%2Fvideos.lukesmith.xyz%2Fstatic%2Fwebseed%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.mp4', 'application\/x-bittorrent;x-scheme-handler\/magnet', 1080) ON DUPLICATE KEY UPDATE `uri-id` = 774760, `type` = 16, `url` = 'magnet:?xs=https%3A%2F%2Fvideos.lukesmith.xyz%2Flazy-static%2Ftorrents%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.torrent&xt=urn:btih:beea58577a63cd19067aad7047ba7f61617965f8&dn=REACTS%3A+%F0%9F%96%90%EF%B8%8F%F0%9F%98%AE%F0%9F%96%90%EF%B8%8F+The+Fish+%22shell%22+is+not+a+shell+and+is+cringe+to+use.&tr=https%3A%2F%2Fvideos.lukesmith.xyz%2Ftracker%2Fannounce&tr=wss%3A%2F%2Fvideos.lukesmith.xyz%3A443%2Ftracker%2Fsocket&ws=https%3A%2F%2Fvideos.lukesmith.xyz%2Fstatic%2Fwebseed%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.mp4', `mimetype` = 'application\/x-bittorrent;x-scheme-handler\/magnet', `height` = 1080"} - {"file":"Database.php","line":765,"function":"e","uid":"9b7366","process_id":1833188}
```

**Comment by 4nanook** [comment] 2021-04-29 23:26
```
2021-04-29T21:01:25Z index [ERROR]: DB Error {"code":1054,"error":"Unknown column 'type' in 'where clause'","callstack":"Post::select, Item::deleteForUser, api_fr_photo_delete, api_call, api_content, LegacyModule::runModuleFunction, LegacyModule::content, call_user_func","params":"SELECT `id`, `uid`, `uri-id` FROM `post-user-view` WHERE (`uid` = 16 AND `resource-id` = '6801493265607e430c881bb855243336' AND `type` = 'photo')"} - {"file":"Database.php","line":662,"function":"p","uid":"51434b","process_id":1876557}
2021-04-29T21:27:45Z index [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'k' at row 1","callstack":"Database::update, DatabaseCache::set, Images::getInfoFromURLCached, ParseUrl::Friendica\\Util\\{closure}, array_walk, Item::insert, Processor::postItem, Receiver::processActivity","params":"REPLACE `cache` (`k`, `v`, `expires`, `updated`) VALUES ('https:\/\/www.rawstory.com\/media-library\/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yNjExMjk5My9vcmlnaW4ucG5nIiwiZXhwaXJlc19hdCI6MTY1NzQ5MjgwMH0.uHqUH_vUlYXVDAPIJ3fjkSluOOjZbu0dga-ehhFPk-w\/image.png?width=1200&coordinates=0%2C25%2C0%2C25&height=600', 'a:7:{i:0;i:1200;i:1;i:600;i:2;i:3;i:3;s:25:\\\"width=\\\"1200\\\" height=\\\"600\\\"\\\";s:4:\\\"bits\\\";i:8;s:4:\\\"mime\\\";s:9:\\\"image\/png\\\";s:4:\\\"size\\\";i:1527958;}', '2021-04-29 21:32:45', '2021-04-29 21:27:45')"} - {"file":"Database.php","line":765,"function":"e","uid":"816b34","process_id":1900760}
```

**Comment by 4nanook** [comment] 2021-04-29 23:26
```
2021-04-29T21:27:45Z index [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'preview' at row 1","callstack":"Item::insert, Processor::postItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent, call_user_func, Module::run, App::runFrontend","params":"INSERT INTO `post-media` (`uri-id`, `type`, `url`, `preview`, `description`, `name`, `author-url`, `author-name`, `publisher-url`, `publisher-name`, `mimetype`, `preview-height`, `preview-width`, `author-image`, `publisher-image`) VALUES (1229244, 17, 'https:\/\/www.rawstory.com\/tim-scott-rebuttal\/', 'https:\/\/www.rawstory.com\/media-library\/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yNjExMjk5My9vcmlnaW4ucG5nIiwiZXhwaXJlc19hdCI6MTY1NzQ5MjgwMH0.uHqUH_vUlYXVDAPIJ3fjkSluOOjZbu0dga-ehhFPk-w\/image.png?width=1200&coordinates=0%2C25%2C0%2C25&height=600', 'On Wednesday evening, Sen. Tim Scott (R-SC), the only Black Republican senator, delivered the official Republican rebuttal to President Joe Biden\\'s address to a joint session of Congress.', '\u2018SO PATHETIC\u2019: GOP\u2019s Tim Scott ignites backlash after denying systemic racism during his Biden rebuttal', NULL, 'Matthew Chapman', NULL, 'Raw Story - Celebrating 17 Years of Independent Journalism', 'text\/html; charset=utf-8', 600, 1200, NULL, 'https:\/\/www.rawstory.com\/media-library\/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yNDk4MDQwMC9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTY0NTg5Njc0NH0.2k-i0Bmt9G9sEw2sThL5Lif6YvM-wT4jdowU5K9cWVg\/image.jpg?width=210') ON DUPLICATE KEY UPDATE `uri-id` = 1229244, `type` = 17, `url` = 'https:\/\/www.rawstory.com\/tim-scott-rebuttal\/', `preview` = 'https:\/\/www.rawstory.com\/media-library\/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yNjExMjk5My9vcmlnaW4ucG5nIiwiZXhwaXJlc19hdCI6MTY1NzQ5MjgwMH0.uHqUH_vUlYXVDAPIJ3fjkSluOOjZbu0dga-ehhFPk-w\/image.png?width=1200&coordinates=0%2C25%2C0%2C25&height=600', `description` = 'On Wednesday evening, Sen. Tim Scott (R-SC), the only Black Republican senator, delivered the official Republican rebuttal to President Joe Biden\\'s address to a joint session of Congress.', `name` = '\u2018SO PATHETIC\u2019: GOP\u2019s Tim Scott ignites backlash after denying systemic racism during his Biden rebuttal', `author-url` = NULL, `author-name` = 'Matthew Chapman', `publisher-url` = NULL, `publisher-name` = 'Raw Story - Celebrating 17 Years of Independent Journalism', `mimetype` = 'text\/html; charset=utf-8', `preview-height` = 600, `preview-width` = 1200, `author-image` = NULL, `publisher-image` = 'https:\/\/www.rawstory.com\/media-library\/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yNDk4MDQwMC9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTY0NTg5Njc0NH0.2k-i0Bmt9G9sEw2sThL5Lif6YvM-wT4jdowU5K9cWVg\/image.jpg?width=210'"} - {"file":"Database.php","line":765,"function":"e","uid":"816b34","process_id":1900760}
```

**Comment by 4nanook** [comment] 2021-04-29 23:26
```
2021-04-29T21:44:46Z index [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'k' at row 1","callstack":"Database::update, DatabaseCache::set, Images::getInfoFromURLCached, ParseUrl::Friendica\\Util\\{closure}, array_walk, Item::insert, Processor::postItem, Receiver::processActivity","params":"REPLACE `cache` (`k`, `v`, `expires`, `updated`) VALUES ('https:\/\/www.rawstory.com\/media-library\/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yNjExNDE2MS9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTY1MjU0NzY3MX0.E11fVIcCo7ZTD_xhcwcbQt1vODuAV7icZHMH8wNNeFM\/image.jpg?width=1200&coordinates=0%2C46%2C0%2C46&height=600', 'a:8:{i:0;i:1200;i:1;i:601;i:2;i:2;i:3;s:25:\\\"width=\\\"1200\\\" height=\\\"601\\\"\\\";s:4:\\\"bits\\\";i:8;s:8:\\\"channels\\\";i:3;s:4:\\\"mime\\\";s:10:\\\"image\/jpeg\\\";s:4:\\\"size\\\";i:37331;}', '2021-04-29 21:49:46', '2021-04-29 21:44:46')"} - {"file":"Database.php","line":765,"function":"e","uid":"794cdf","process_id":1915662}
```

**Comment by 4nanook** [comment] 2021-04-29 23:27
```
2021-04-29T21:44:46Z index [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'preview' at row 1","callstack":"Item::insert, Processor::postItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent, call_user_func, Module::run, App::runFrontend","params":"INSERT INTO `post-media` (`uri-id`, `type`, `url`, `preview`, `description`, `name`, `author-url`, `author-name`, `publisher-url`, `publisher-name`, `mimetype`, `preview-height`, `preview-width`, `author-image`, `publisher-image`) VALUES (1229328, 17, 'https:\/\/www.rawstory.com\/california-fire-was-started-to-cover-up-a-police\/', 'https:\/\/www.rawstory.com\/media-library\/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yNjExNDE2MS9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTY1MjU0NzY3MX0.E11fVIcCo7ZTD_xhcwcbQt1vODuAV7icZHMH8wNNeFM\/image.jpg?width=1200&coordinates=0%2C46%2C0%2C46&height=600', 'A California fire that killed two people last year was intentionally set to cover up a murder, investigators revealed in a press briefing.', 'Deadly California fire was started to cover up a murder: police', NULL, 'Agence France-Presse', NULL, 'Raw Story - Celebrating 17 Years of Independent Journalism', 'text\/html; charset=utf-8', 601, 1200, NULL, 'https:\/\/www.rawstory.com\/media-library\/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yNDk4MDQwMC9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTY0NTg5Njc0NH0.2k-i0Bmt9G9sEw2sThL5Lif6YvM-wT4jdowU5K9cWVg\/image.jpg?width=210') ON DUPLICATE KEY UPDATE `uri-id` = 1229328, `type` = 17, `url` = 'https:\/\/www.rawstory.com\/california-fire-was-started-to-cover-up-a-police\/', `preview` = 'https:\/\/www.rawstory.com\/media-library\/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yNjExNDE2MS9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTY1MjU0NzY3MX0.E11fVIcCo7ZTD_xhcwcbQt1vODuAV7icZHMH8wNNeFM\/image.jpg?width=1200&coordinates=0%2C46%2C0%2C46&height=600', `description` = 'A California fire that killed two people last year was intentionally set to cover up a murder, investigators revealed in a press briefing.', `name` = 'Deadly California fire was started to cover up a murder: police', `author-url` = NULL, `author-name` = 'Agence France-Presse', `publisher-url` = NULL, `publisher-name` = 'Raw Story - Celebrating 17 Years of Independent Journalism', `mimetype` = 'text\/html; charset=utf-8', `preview-height` = 601, `preview-width` = 1200, `author-image` = NULL, `publisher-image` = 'https:\/\/www.rawstory.com\/media-library\/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yNDk4MDQwMC9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTY0NTg5Njc0NH0.2k-i0Bmt9G9sEw2sThL5Lif6YvM-wT4jdowU5K9cWVg\/image.jpg?width=210'"} - {"file":"Database.php","line":765,"function":"e","uid":"794cdf","process_id":1915662}
```

**Comment by annando** [comment] 2021-04-30 04:39
@4nanook these are no PHP warnings, but database errors in the friendica log file. Could you open a separate issue for them?

**Comment by 4nanook** [comment] 2021-04-30 04:40
Sure, will do.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment] 2021-04-30 06:23
Well I tried to but something is amiss with github and the submit button
is greyed out.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by bkil** [comment] 2021-04-30 18:57
`PHP Warning: Undefined array key "userinfo" in .../view/smarty3/compiled/..._2.file.nav.tpl.php on line 24` along with a bunch of other array keys (like `notifications`, `4`, `trace`, `thrown`, `delegation`, `tos`, `apps`).

This is on PHP 8, haven't tested on other versions, though. I'm running `composer.phar` on a development machine and then deploy to another kind of environment, maybe this is related.

**Comment by tobiasd** [comment] 2021-05-01 13:39
With PHP8 I get some more of these Undefined Array keys @bkil is reporting. I'll group them for the different tpl files that are reported in the PHP log.

* `nav.tpl`: admin, apps, community, events, home, langselector, login, logout, messages, network , notifications, remote, search, userinfo
* `wall_thread.tpl`: comment_firstcollapsed, comment_lastcollapsed, orig_title, postopts, total_comments_num
* `comment_item.tpl`: edvideo, type
*  `field_input.tpl` and `field_password.tpl` 4, 5
* `vcard.tpl`: address, edit, upubkey
* `threaded_conversation.tpl`: item

Partially addressed in https://github.com/friendica/friendica/pull/10228

**Comment by MrPetovan** [comment] 2021-05-01 14:50
I guess it was bound to happen, I thought Smarty was silently ignoring missing keys but evidently they aren't doing it very cleanly, I'll try to update Smarty first, see if they have a patch for PHP8.

**Comment by tobiasd** [comment] 2021-05-01 14:59
Yes, up to PHP7.4 missing keys were ignored, or _false_. when evaluated  I think we are already using the last released version of SMARTY (3.1.39 from Feb this year).

**Comment by bkil** [comment] 2021-05-01 15:09
It seems to be mentioned in one of their issues:
- https://github.com/smarty-php/smarty/issues/617#issuecomment-756497082
- https://github.com/smarty-php/smarty/pull/629 - not merged yet

They tracked fatal incompatibilities here and closed all other issues as a duplicate, but I think they might have forgotten about warnings and/or the above PR might fix it:
- https://github.com/smarty-php/smarty/issues/605

**Comment by AlfredSK** [comment] 2021-05-10 20:03
Markdown issue. Putting the warning and the notice in here because they belong together.

2021.04 stable, PHP 7.4

```
PHP Notice:  Trying to access array offset on value of type bool in .../vendor/michelf/php-markdown/Michelf/MarkdownExtra.php on line 525
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in .../vendor/michelf/php-markdown/Michelf/MarkdownExtra.php on line 528
```

**Comment by tobiasd** [comment] 2021-05-11 10:20
PHP8, Friendica 2021.06-dev

```
PHP Warning:  strtotime(): Epoch doesn't fit in a PHP integer in /src/Protocol/DFRN.php on line 1614
```
Addressed in https://github.com/friendica/friendica/pull/10231

**Comment by MrPetovan** [comment] 2021-05-11 11:47
Oh no, it's the 2021 bug!

**Comment by ghost** [comment] 2021-05-18 09:44
latest dev

```
PHP Warning:  sem_acquire(): failed to acquire key 0x66030a21: Identifier removed in  /src/Core/Lock/SemaphoreLock.php on line 63
```

**Comment by AlfredSK** [comment] 2021-05-23 16:10
2021.06-rc, PHP 7.4, API related

`reset() expects parameter 1 to be array, null given in .../src/Object/Api/Mastodon/Status.php on line 117`

Addressed in #10305

**Comment by AlfredSK** [comment] 2021-05-29 21:45
2021.06-rc, PHP 7.4, Mastodon API

```
[29-May-2021 21:08:10 UTC] PHP Notice:  Array to string conversion in .../src/Module/Api/Mastodon/Apps.php on line 53
[29-May-2021 21:08:10 UTC] PHP Notice:  Undefined variable: Array in .../src/Module/Api/Mastodon/Apps.php on line 53
[29-May-2021 21:08:10 UTC] PHP Warning:  array_merge(): Expected parameter 2 to be an array, null given in .../src/Module/Api/Mastodon/Apps.php on line 53
```

A warning and two notices. Reporting them here because they belong together.

Fixed by https://github.com/friendica/friendica/pull/10339

**Comment by MrPetovan** [comment] 2021-05-31 04:37
> Markdown issue. Putting the warning and the notice in here because they belong together.
> 
> 2021.04 stable, PHP 7.4
> 
> ```
> PHP Notice:  Trying to access array offset on value of type bool in .../vendor/michelf/php-markdown/Michelf/MarkdownExtra.php on line 525
> PHP Warning:  count(): Parameter must be an array or an object that implements Countable in .../vendor/michelf/php-markdown/Michelf/MarkdownExtra.php on line 528
> ```

This is a regular expression error in a third-party library, without the source text that triggered this error there isn't much I can do about it.

**Comment by ghost** [comment] 2021-06-19 09:58
No idea, if this fits in here, but currently I' running on Friendica 'Siberian Iris' 2021.06-rc - 1423 and have php7.3, php7.4 and php8.0 installed on my Debian Buster: 

```
# update-alternatives --config php
There are 3 choices for the alternative php (providing /usr/bin/php).

  Selection    Path             Priority   Status
------------------------------------------------------------
* 0            /usr/bin/php8.0   80        auto mode
  1            /usr/bin/php7.3   73        manual mode
  2            /usr/bin/php7.4   74        manual mode
  3            /usr/bin/php8.0   80        manual mode
```
With that setting it appears that deleted users are not being purged even after days: 

![Bildschirmfoto 2021-06-18 um 13 20 26](https://user-images.githubusercontent.com/18173881/122638525-d3445300-d0f4-11eb-8c44-29286295afb4.png)

While the webfrontend is using php7.4 through socket configuration in Nginx, the worker uses the default php symlink, which is in this case the php8.0 packages from https://packages.sury.org/php/. 

I get the following php warnings in syslog with php set to php8.0: 
```

Jun 19 11:39:01 vserv1 sessionclean[15148]: PHP Warning:  PHP Startup: Unable to load dynamic library 'memcache.so' (tried: /usr/lib/php/20180731/memcache.so (/usr/lib/php/20180731/memcache.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/memcache.so.so (/usr/lib/php/20180731/memcache.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Jun 19 11:39:01 vserv1 sessionclean[15148]: PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20180731/memcached.so (/usr/lib/php/20180731/memcached.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/memcached.so.so (/usr/lib/php/20180731/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Jun 19 11:39:01 vserv1 sessionclean[15148]: PHP Warning:  PHP Startup: Unable to load dynamic library 'memcache.so' (tried: /usr/lib/php/20180731/memcache.so (/usr/lib/php/20180731/memcache.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/memcache.so.so (/usr/lib/php/20180731/memcache.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Jun 19 11:39:01 vserv1 sessionclean[15148]: PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20180731/memcached.so (/usr/lib/php/20180731/memcached.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/memcached.so.so (/usr/lib/php/20180731/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Jun 19 11:39:01 vserv1 sessionclean[15148]: PHP Warning:  PHP Startup: Unable to load dynamic library 'memcache.so' (tried: /usr/lib/php/20180731/memcache.so (/usr/lib/php/20180731/memcache.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/memcache.so.so (/usr/lib/php/20180731/memcache.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Jun 19 11:39:01 vserv1 sessionclean[15148]: PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20180731/memcached.so (/usr/lib/php/20180731/memcached.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/memcached.so.so (/usr/lib/php/20180731/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

However, when switching php to php7.4 via `update-alternatives -config php` the worker seems to run successfully again and purges the deleted users finally. 

Maybe this is not strictly a bug in Friendica itself, but maybe worth mentioning it somewhere... maybe the worker could through some worthwhile node into logs/friendica.log as well or displays a warning in the webfrontend.

**Comment by MrPetovan** [comment] 2021-06-19 10:30
A dynamic library loading warning wouldn't prevent any PHP script to run,  but it would make any call to the library functions fail with a Fatal Error if there's an assumption they should be available.

**Closed as completed** 2021-12-12 20:05 UTC
Labels: Bug
