### ISSUE TITLE
Consistent language logic in settings and descriptions

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#10640] opened 2021-08-29 11:22 UTC
This isn't really a bug report because it is a request for a consistent language usage. It is a kind of "logical bug". :)

### Current situation
In the admin/side section there are these option under "Policies"

![grafik](https://user-images.githubusercontent.com/24474762/131247602-89f64c77-16c2-48cd-ac75-c09e91243770.png)

### Suggestion 
There should be a guideline to express something negative, or positive, so there is not a mix of both. Because this is always a place where users and admins have to pay a lot more attention:  the logic may turned on this parameter the other way around. Or a "disable" is maybe not meant not "enable", or not ;) Or maybe just: enable.

It would be very helpful if options or parameters, that can be switched on/off or enabled/disabled always follows the same global language logic AND description.

So the developers should e.g. decide if they globally want to write
- enable options    ... or
- disable options

And if **enable/disable** or **on/off** should be emphasized. 
For example if the decision is to emphasize "enable/disable" it make as well sense to write "enable" instead of "on". Or the other way around, if the decision goes to "on/off"  .. "on" is chosen, if it the content allows it.

From my point of view it would be better, as well in a psychological view, to use "enable" or "on"  options.

In the current example the options would look like

- [X] **Enable OStatus support** - Enable built-in OStatus (StatusNet, GNU Social etc.) compatibility. All communications in OStatus are public, so privacy warnings will be occasionally displayed.
- [ ] **Enable Diaspora support** - Enable built-in Diaspora network compatibility for communicating with diaspora servers.
- [X] **Enable all contacts (instead Friendica only)** - Enable to communicate with with all fediverse contacts (Mastodon, Pleroma, Pixelfed, etc). If this option is disabled, communication is only possible between Friendica accounts (Servers).

### Conclusion : 2 decisions

The less logical variations are used, the clearer it is for the user/admin.

1. Using a consistent language logic
2. Emphasis for **`enable/disable`** or **`on/off`**

### System
Friendica Source: git / 2021-09.rc
PHP version: 7.4
SQL version: MariaDB

**Comment by annando** [comment] 2021-08-29 16:28
It's not a bug but a historically grown thingy. And interestingly enough the setting "only allow Friendica contacts" means that the the ActivityPub protocol still would work since Friendica now mostly rely on this protocol.

**Comment by hoergen** [comment] 2021-08-29 17:44
Before this thread goes the completely wrong way I would suggest to talk about the topic I suggested in the issue.

**Comment by MrPetovan** [comment] 2021-08-30 17:37
I agree with you, I hate "Disable" options, but changing the label which is easy would require us to change the internal setting name for consistency, which would harder because we would need to keep supporting the original name for backward compatibility with existing nodes' config files.

For admin settings it's relatively easier since we can run a database update to update settings names and values, still not trivial.

**Comment by hoergen** [comment] 2021-08-30 18:20
It's a suggestion to bring in a general guideline for a better user experiences to follow 1 logic. It could be one step to bring the UX to a higher level. As I wrote it is about that the developing team decide if the program logic will be presented in one logic way for a clearer and more professional UX or in several  different logics to confuse user and admins.

**Comment by MrPetovan** [comment] 2021-08-30 18:57
It's a good suggestion but the decision has already been made years ago, even before anyone from the current development team came into the project. Steering away from the current confusing state would take way more work than it clearly did to come up with these setting names in the first place.

**Comment by annando** [comment] 2021-08-30 19:08
My suggestion is to use it for more protocols. So we should have options to enable/disable:

- OStatus
- Diaspora
- Mail

Also it is not a huge problem to keep the setting variables but to invert the value when read and stored.

**Comment by MrPetovan** [comment] 2021-08-30 19:43
I guess the transformation can be limited to the settings page.

**Comment by hoergen** [comment] 2021-08-30 20:51
Not relevant anymore because [former development team took decision](https://github.com/friendica/friendica/issues/10640#issuecomment-908602247) for the current state.

**Comment by MrPetovan** [comment] 2021-08-30 20:55
Reopening as @annando has started working towards setting names normalization.

**Comment by MrPetovan** [comment] 2021-08-30 21:38
@annando Will you also normalize all the other "Disable X" settings?

**Comment by annando** [comment] 2021-08-31 04:41
I guess that my PR only had been the start. These protocol settings had been the most confusing ones, but they aren't alone.

**Comment by foss-** [comment] 2021-09-03 08:41
Moving my PR comment here:

Thanks for working on this. Display Settings > Content/Layout still has:

- Don't show emoticons: Should be `Show emoticons` (Enabled by default)
- Disable smart threading: Should be `Enable smart threading` (Enabled by default)
- Hide the dislike feature: Should be `Show dislikes` (Enabled by default)

<img width="648" alt="display settings   Content:Layout" src="https://user-images.githubusercontent.com/5708172/131639946-1bd0a7d8-5a68-4813-9bdb-dcd9fb70d3ee.png">

**Comment by tobiasd** [comment] 2021-09-03 08:56
These are fixed in the current RC since yesterday I think.

**Comment by annando** [comment] 2021-09-03 10:06
@tobiasd yes, it is. I'm waiting if someone finds some other places.

**Comment by annando** [comment] 2021-09-04 07:15
@hoergen do you know of any other irritating admin/user setting description?

**Comment by hoergen** [comment] 2021-09-05 09:29
> @hoergen do you know of any other irritating admin/user setting description?

Not I'm aware of, but didn't look for it.

**Closed as completed** 2021-09-06 19:32 UTC
Labels: Bug

**Comment by MrPetovan** [comment] 2021-09-06 19:52
Thank you for your report @hoergen !
