### ISSUE TITLE
Notifications for posts that are not mine and I never interacted with them

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7470] opened 2019-08-04 10:20 UTC
### Expected behavior
When someone is commenting on a post from someone else I shouldn't get a notification that someone commented on **my** post. Because A - it isn't my post. And B - I never interacted with the whole thread. Not at all.

### Actual behavior
I constantly get notifications that 'X commented on your post'. When I click on the notification I'm redirected to some post that wasn't posted by me. When I check the whole thread I find that I never interacted with any of the items.
**This only happens with posts from local users.** Might be a coincidence but I never experienced this with users from remote nodes.

### Friendica version you encountered the problem
2019.09-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by MrPetovan** [comment] 2019-08-04 11:27
I don't have any other local user on my node so I would be hard-pressed to reproduce this issue.

**Comment by AlfredSK** [comment] 2019-08-04 11:36
This is an example where I got notifications that Ɠεɱɩoɠ and Fitheach (both from Mastodon) commented on my post. But the post is from Claes Wallin (韋嘉誠) who is a local user.

https://libranet.de/display/0b6b25a8-415d-4076-b754-1f6018326423

**Comment by MrPetovan** [comment] 2019-08-04 11:48
Well, you're the admin so you own all the posts, muhahahaha!

**Comment by AlfredSK** [comment] 2019-08-04 11:52
I'll watch for the next occurrence. The thing is the last time this happend was 5 days ago (I collected the issues as personal notes during the last week). So, maybe, it has already been repaired...

**Comment by annando** [comment] 2019-08-04 12:18
I guess it was fixed with the "contact-id" mess that I created.

**Comment by MrPetovan** [comment] 2019-08-04 12:22
Caused by #7452
Fixed by #7455

**Closed by MrPetovan** 2019-08-04 12:22 UTC
Labels: Bug, UX
