### ISSUE TITLE
Read notifications are not shown in web interface when friendica is accessed via other client

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1063] opened 2014-08-01 09:02 UTC
When I get notifications and access friendica via another client the read notifications are not listed anymore on the website, no matter if I accessed the post that caused that notification or not.

This makes it hard to find the thread again where the notification was generated and it happens that I miss f.e. mentions because I can't find them anymore.

**Comment by annando** [comment] 2015-03-24 06:38
I really don't see the "bug" here. When working via the API, no markers are set that an item was seen. Only the Friendica-App is using the regular notification function.

**Comment by annando** [comment] 2015-03-30 10:03
@tugelbend I just had a look into the api. I really can't reproduce the behaviour that you described. I'm using the API very much and I really see all notifications via the web client - even when I accessed them with a mobile client before.

**Comment by annando** [comment] 2015-04-01 19:16
What do we do with this issue?

**Comment by fabrixxm** [comment] 2015-04-03 07:35
@tugelbend 
are you talking about the count of unseen posts in network Ⓐ  or notifications about posts you're involved in Ⓑ ?
![fnotif](https://cloud.githubusercontent.com/assets/309361/6979454/09d9e6aa-d9e4-11e4-8206-26656dc1abb7.jpg)
Because Ⓑ list isn't modified by API, while Ⓐ is decreased by timeline API: posts returned by API call are set as "seen". (see [api.php:1135](https://github.com/friendica/friendica/blob/master/include/api.php#L1135) ).
In this case we could unset the "unseen" flag only on `/statuses/show` and `/conversation/show` API, that should be called only when the user select a post from the timeline..

**Comment by fabrixxm** [comment] 2015-04-03 07:38
Meanwhile I notice that `api_statuses_home_timeline()` set _all_ unseen items as seen, are they returned by api call or not...

**Comment by tugelbend** [comment] 2015-04-03 10:57
I have to check if this issue still exists as I don't use twidere regularly at the moment.

The issue was that just by using the api client, notifications did not appear in the we interface anymore as if I had visited all posts with notifications already. This happened for both types of notifications (A) and (B) as far as I can tell.

**Comment by fabrixxm** [comment] 2015-04-03 13:41
pull #1472 should close this:
only items fetched by api call are marked as read (so, if you have 10 unread posts, and your client fetch last 5 posts, you get 5 unread posts in web interface at Ⓐ). I think it's the correct thing to do :-)

**Comment by annando** [comment] 2015-04-03 15:10
I think this issue is solved by now. The behaviour should now have no more problems. I think we can close this issue.

**Closed** 2015-04-03 15:42 UTC
Labels: Bug, UX
