### ISSUE TITLE
Vote not work

### ISSUE THREAD

**Issue by Mannshoch** [friendica/friendica#13386] opened 2023-08-28 20:39 UTC
- [x] I have searched open and closed issues for duplicates

### Bug Description

Votings not work

### Steps to Reproduce

1.  Search vor a Vote
2.  Try to vote

Actual Result:

bulletpoints instead of radio buttons

Expected Result:

radiobuttons

### Screenshots

![Bildschirmfoto vom 2023-08-28 22-10-38](https://github.com/friendica/friendica/assets/7795891/6e03163a-22d0-4045-b733-f5cad6dd8f19)

### Platform Info

Friendica Version:

Friendica 'Giant Rhubarb' 2023.05 - 1518

Friendica Source: Git

PHP version:

version | 8.0.30
upload_max_filesize | 2048M
post_max_size | 2048M
memory_limit | 2048M
MySQL / MariaDB
max_allowed_packet | 1073741824

**Comment by MrPetovan** [comment] 2023-08-28 20:42
Duplicate of #11093. There's no plan to add interaction to polls yet, at the moment we intentionally just display them.

**Closed as not planned by MrPetovan** 2023-08-28 20:42 UTC
Labels: Bug

**Comment by Mannshoch** [comment] 2023-08-28 21:17
Thanks, I upvoted this first post and hope it will considered to been enhanced soon.
