### ISSUE TITLE
Sort saved folders alphabetically

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5048] opened 2018-05-14 14:32 UTC
Could you please sort the saved folders alphabetically, so that the left side widget (frio)  and the select dialog them shows  alphabetically,  when you save an article in your folders.

**Comment by tobiasd** [comment] 2018-05-14 14:39
This is not theme dependent I think.

**Comment by hoergen** [comment] 2018-05-14 15:00
Think so too, that it is something like an unsorted array that is handover to the theme.

**Comment by annando** [comment] 2018-05-15 05:10
Isn't this a duplicate to the other issue you created?

**Comment by hoergen** [comment] 2018-05-15 06:05
No, this one is for the saved folders .. the other one was for the saved searches.

**Comment by annando** [comment] 2018-05-15 06:44
Sorry, my brain was in start up when I wrote this.

**Comment by hoergen** [comment] 2018-05-15 06:59
No problem. Happy to can help at least on this point ;) Hope one day I'm able not just open such issues, but to solve it myself with a merge request ;)

**Comment by annando** [comment] 2018-05-15 10:41
Reporting and testing is an important part of the work as well.

**Comment by hoergen** [comment] 2018-11-23 02:36
Ping

**Comment by MrPetovan** [comment] 2018-11-23 03:04
Pong.

**Comment by hoergen** [comment] 2018-11-24 07:59
Any hint where I can find the relevant code? searched via fgrep on $folders, but don't see it
In which table are the saved folders stored? And how?

**Comment by AlfredSK** [comment] 2018-11-24 08:59
Don't know. But that thing is called 'filed items' or something similar.

**Comment by MrPetovan** [comment] 2018-11-24 13:49
Here's the code:
https://github.com/friendica/friendica/blob/6b845b35d3c525a7fdef3443c39ce31dd9a8ada6/src/Content/Widget.php#L166-L204

The array you need to sort is `$terms`.

**Comment by ikejosh** [comment] 2019-05-14 06:03
Hello, is this issue still open? How can i help?

**Comment by tobiasd** [comment] 2019-05-14 07:53
Hey @ikejosh yes the issue is still open. See @MrPetovan comment above for the starting point for the solution. If you encounter problems, please feal free to ask here or at the [Friendica developers forum](https://forum.friendi.ca/profile/developers).

**Comment by ikejosh** [comment] 2019-05-14 13:42
> Hey @ikejosh yes the issue is still open. See @MrPetovan comment above for the starting point for the solution. If you encounter problems, please feal free to ask here or at the [Friendica developers forum](https://forum.friendi.ca/profile/developers).

Sorry, i won't be able to look into this issue.

**Comment by AlfredSK** [comment] 2019-11-01 20:48
This is an associative array, right? So, sorting that array is done by asort()?

**Comment by MrPetovan** [comment] 2019-11-01 20:51
You are right.

**Comment by AlfredSK** [comment] 2019-11-01 21:33
Probably fixed by #7794

**Closed** 2019-11-02 02:58 UTC
Labels: Enhancement, Junior Jobs, UI/Theme
