### ISSUE TITLE
Hyperlink broken when including special character (Crosspost from Diaspora)

### ISSUE THREAD

**Issue by carlinhush** [friendica/friendica#6887] opened 2019-03-15 10:50 UTC
### Expected behavior
Hyperlink should work

### Actual behavior
Hyperlink that includes the letter ä breaks

### Steps to reproduce the problem
Post a hyperlink on Diaspora that includes the letter ä, when post arrives in Friendica the link is broken

Example - Original post on Diaspora
https://pluspora.com/posts/c5b2785029390137cfd3005056264835

Same post with broken link on Friendica
https://ricks.uber.space/display/cea96bb0293b0137cfcd005056264835

### Friendica version you encountered the problem
Friendica 'The Tazmans Flax-lily' 2019.01 - 1293

see `example.com/friendica` on your Friendica node for the version information.

### PHP version
7.1.27

**Comment by AlfredSK** [comment] 2019-03-15 10:56
Works in 2019.03-rc. Not beautiful but the link works.
Example: https://squeet.me/display/cea96bb0293b0137cfcd005056264835

**Comment by MrPetovan** [comment] 2019-03-15 13:18
The "not beautiful" part comes from the URL preview code which is a separate issue.

**Comment by MrPetovan** [comment] 2019-03-15 13:19
Closed a duplicate of #2487

**Closed by MrPetovan** 2019-03-15 13:19 UTC
Labels: Bug
