### ISSUE TITLE
Endless scrolling in the community pages

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#7936] opened 2019-12-12 11:29 UTC
In order to make the user experience more homogeneous, it should be possible to scroll endlessly in the community pages as well. The setting for the network view should be adopted. The current pagination of the pages already looks very old-fashioned and outdated.

**Comment by AlfredSK** [comment] 2019-12-12 16:08
Great but that's a duplicate of #5562 .

**Comment by MrPetovan** [comment] 2019-12-12 16:11
Duplicate of #5562

**Closed by MrPetovan** 2019-12-12 16:11 UTC
Labels: Enhancement, UI
