### ISSUE TITLE
Navigating to index page with HTTPS forced does not redirect to HTTPS.

### ISSUE THREAD

**Issue by Beanow** [friendica/friendica#1034] opened 2014-06-25 07:36 UTC
In my case we're talking about `fc.oscp.info` if I navigate directly to `http://fc.oscp.info/` with the force HTTPS setting enabled, I'm not redirected to HTTPS until I navigate or log in.

**Comment by Beanow** [comment] 2015-01-24 19:11
Agreeing now that an .htaccess configuration is the best way to do this. I think it should be documented and possibly mentioned with HTTPS related config values in the admin section.

**Comment by annando** [comment] 2015-01-24 19:34
We are having the option "Force SSL". This does the expected behaviour.

**Comment by Beanow** [comment] 2015-01-24 19:38
At the time it didn't, was it changed?

**Comment by annando** [comment] 2015-02-01 22:49
"Force SSL" is active since 3.3.2, I guess.

**Comment by silke** [comment] 2015-11-07 16:11
@Beanow Can I close this issue?

**Comment by Hypolite** [comment] 2017-01-07 15:32
Does the changes in the SSL docs I added are enough to dissipate any doubts about the "Force SSL" setting?

**Closed** 2018-08-02 16:16 UTC
Labels: Docs
