### ISSUE TITLE
network-type is wrong

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#10626] opened 2021-08-23 13:35 UTC
- [ ] I have searched open and closed issues for duplicates

### Bug Description

If i search for @stux@mstdn.social the search-result shows "ActivityPub (AP)".
When i follow this account, it's shown as RSS/Atom.

Then i can not answer postings.

This happens with all Mastodon-Accounts.

### Screenshots
Search gives Mastodon (correct)
![grafik](https://user-images.githubusercontent.com/5894829/130456242-742de17d-9ba5-4b80-85ac-25e15cc7157b.png)

After following, its RSS/Atom
![grafik](https://user-images.githubusercontent.com/5894829/130456338-26d1a1bf-8f33-4b2f-b1a2-e3e94a20d861.png)

### Platform Info

Friendica Version:

Friendica Source: 2021.09-dev

PHP version: 7.3

SQL version: mariadb 10.3

**Comment by xundeenergie** [comment] 2021-08-23 13:37
maybe it's a duplicate of https://github.com/friendica/friendica/issues/10623 because there are also troubles in getting the correct network-type.

**Comment by xundeenergie** [comment] 2021-08-23 14:28
This works in stable

**Comment by annando** [comment] 2021-08-23 19:17
I guess that this is also related to PR https://github.com/friendica/friendica/pull/10619

**Comment by MrPetovan** [comment] 2021-08-24 15:44
Duplicate of #10625, closing

**Closed as completed by MrPetovan** 2021-08-24 15:44 UTC
Labels: Bug
