### ISSUE TITLE
Single 'tall' photo gets stretched and becomes blurry

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#13506] opened 2023-10-06 15:59 UTC
### Bug Description

When I post a "tall" photo, with "portrait" orientation, not "landscape", it will be stretched to width:100% and becomes blurry (and big).

I don't know what to do about that. Maybe @MrPetovan has an idea.

When this would work better, meaning I could post small or tall photos, another problem will occur - the background image will be partly visible.

### Platform Info

Friendica Version:

"Diese Friendica-Instanz verwendet die Version 2023.09-dev, sie ist unter der folgenden Adresse im Web zu finden https://boerdica.de. Die Datenbankversion ist 1534/1534 und die Post-Update-Version 1507/1507."

PHP version: 8.1.23

SQL version: mysql  Ver 15.1 Distrib 10.11.5-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by MrPetovan** [comment] 2023-10-07 03:37
Please post an example, in my tests both landscape and portrait pictures were displaying correctly.

**Comment by haheute** [comment] 2023-10-07 06:49
Here, this photo is displayed bigger than it naturally is. 
https://boerdica.de/display/a1e4bf6c-4865-2024-6bb1-b88173065070

**Comment by Tslmuun** [comment] 2023-10-07 07:18
> Please post an example, in my tests both landscape and portrait pictures were displaying correctly.


Hi.
I think maybe I have encountered a similar problem as you. After upgrading to friendica 2023.09-rc, posts with images take up too much screen space.

![2424973787651e077711fb7537549864-1](https://github.com/friendica/friendica/assets/50679343/8008678b-92e9-4687-bf23-13285a706f0a)
![1453012237651e077bd2f23666499766-1](https://github.com/friendica/friendica/assets/50679343/fdc73d70-ad78-4373-b6dc-4b5aad68dd48)

**Comment by haheute** [comment] 2023-10-07 07:20
Have you tried to hard reload the page/ clear the cache? Maybe it helps

**Comment by MrPetovan** [comment] 2023-10-07 09:20
@haheute Can you please test with the change in this PR: https://github.com/friendica/friendica/pull/13512

It should work better.

**Comment by haheute** [comment] 2023-10-07 09:39
I hope I did it correctly. (git noob) My repo was then 68 commits ahead of friendica/friendica but it seems the changes in  `src/Content/Image.php` were in it. But even after hard reload, the photo looks the same.

uh oh.. Photos in other posts are suddenly wider then their container..

**Comment by MrPetovan** [comment] 2023-10-07 09:58
Your timeline looks okay, can you provide an example? Also it doesn't look like you applied the changes on boerdica.de, I can still see this HTML markup:
```html
<figure class="img-allocated-height" style="width: auto; padding-bottom: 141.5%">
    <a data-fancybox="uri-id-2896697" href="https://boerdica.de/photo/169314794865202199025e5146945155-0.jpg">
        <img src="https://boerdica.de/photo/169314794865202199025e5146945155-1.jpg" alt="inktober 2023 sketch for 06-golden: A clueless person whose heart is in a golden cage is standing in front of a village or maybe monastery and one hand of the person seems  to adjust the hand of  a (golden) clock. Above that, there is a beetle. The picture has a white background." title="inktober 2023 sketch for 06-golden: A clueless person whose heart is in a golden cage is standing in front of a village or maybe monastery and one hand of the person seems  to adjust the hand of  a (golden) clock. Above that, there is a beetle. The picture has a white background." loading="lazy">
    </a>
</figure>
```
See the first line, it should read `width: 452px` instead of `width: auto` like in this test post I made using the same image: https://dev-friendica.mrpetovan.com/display/b5f438f2-7165-212a-90ce-d43175201939.

**Comment by haheute** [comment] 2023-10-07 10:00
Here I see a too wide photo: https://boerdica.de/display/90267e7041b5013cd03528a1592b385a
(I see `width: 768px; padding-bottom: 133.33333333333%` there)..

**Comment by MrPetovan** [comment] 2023-10-07 10:06
Hmm, interesting, no preview image is created for this obviously big image. Give me a minute, I have a solution for this. It relies on CSS so it will need a browser cache clear.

**Comment by haheute** [comment] 2023-10-07 10:08
Thanks.. take your time.. :+1:

**Comment by MrPetovan** [comment] 2023-10-07 10:10
The PR was updated.

**Comment by haheute** [comment] 2023-10-07 10:26
I have now fetched it into a new branch from upstream, pushed that branch to origin, pulled that branch to the server from origin and checked out into it. . The second photo looks good now, but my photos still have width:auto..

The first time, I had merged the new branch locally and pushed develop to origin. I must somehow find out which way is right and fix that. :face_with_spiral_eyes:

**Comment by MrPetovan** [comment] 2023-10-07 15:39
The sequence of git commands I suggest you:
```
> git checkout -- . 
> git remote add MrPetovan https://github.com/MrPetovan/friendica.git
> git fetch MrPetovan
> git checkout MrPetovan/bug/13506-allocated-width
```
The first command resets all the locally changed files in your working directory. Then it adds my repository as a remote, updates it and checks out the current version of the PR branch.

**Comment by MrPetovan** [comment] 2023-10-07 16:29
Even better, you can now pull the `2023.09-rc` from the `friendica/friendica` remote and test for yourself.

**Comment by MrPetovan** [comment] 2023-10-07 16:40
And now after the update I can reproduce the runaway images 😭

**Comment by MrPetovan** [comment] 2023-10-07 16:52
Alright, the fix wasn't a fix. 

Here's what the HTML should show for 
```html
<div class="body-attach">
    <div style="max-width: 768px;">
        <figure class="img-allocated-height" style="width: auto; padding-bottom: 133.33333333333%">
            <a data-fancybox="uri-id-7288234" href="https://friendica.mrpetovan.com/photo/media/1896385">
                <img src="https://friendica.mrpetovan.com/photo/preview/1024/1896385" alt="" title="" loading="lazy">
            </a>
        </figure>
    </div>
</div>
```
Notice the classless `<div style="max-width: 768px;">`, it's currently missing from https://boerdica.de/display/90267e7041b5013cd03528a1592b385a (because of the faulty fix). Once you pull `2023.09-rc` again, please check if this markup appears.

**Comment by haheute** [comment] 2023-10-07 18:13
Ok... I did that. It seems the `max-width: 768px` is there

**Comment by MrPetovan** [comment] 2023-10-07 21:12
Ok, I've identified The issue. Strap in, we're in for a ride.

Images were displaying differently whether they were attached to the post or inline the post body. In the case of https://boerdica.de/display/a1e4bf6c-4865-2024-6bb1-b88173065070, it's inline because there's text afterwards. I first made the mistake of using the same image, but without text afterwards, which made it an attached picture instead of an inline picture.

Then you shared https://boerdica.de/display/90267e7041b5013cd03528a1592b385a which is a Diaspora post. Despite visually having text after the photo, it is not an inline picture because, specifically for Diaspora, we attach pictures at the top of the post, not at the bottom like any other platform.

So I kept testing with attached pictures even though your issue was with inline pictures!

Once I figured this out, I was able to reuse the same image in an inline capacity, and I identified the bug. Both the following images should now display the same, which wasn't the case before the fix:
- Attached image: https://dev-friendica.mrpetovan.com/display/b5f438f2-7165-212a-90ce-d43175201939
- Inline image: https://dev-friendica.mrpetovan.com/display/b5f438f2-1565-21c7-2363-cc4911050967

**Comment by haheute** [comment] 2023-10-08 04:48
It seems...... to work now. super!
(on my node it works.. on your dev node I see the correct width, but the images are missing)

**Comment by MrPetovan** [comment] 2023-10-08 12:27
Photo permissions again. *sigh*

**Comment by MrPetovan** [comment] 2023-10-08 12:28
Confirmed fixed by https://github.com/friendica/friendica/pull/13517

**Closed as completed by MrPetovan** 2023-10-08 12:28 UTC
Labels: Bug
