### ISSUE TITLE
Wrong Email Headers Causing Delivery Failures

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#5190] opened 2018-06-10 22:51 UTC
### Expected behavior

The PHP mail function must be called with the 5th argument to correctly set the envelope from address.

### Actual behavior

As described in Issue #719, Friendica fails to deliver registration messages.  It does not set the e-mail envelope parameters and only uses a From header, which is normally rejected by industry standard spam filters.

### Steps to reproduce the problem

Try registering with a live.com email address on a shared host.  Typically the shared host will use its own domain when the envelope is incomplete, causing live.com to blackhole the mail.

For your reference, the fifth arg to mail() must be specified, and should be formatted like “-f admin@domain.com”. I will hack this change into my site now to verify that it solves the problem.

### Friendica version you encountered the problem

2018.08-dev - 1268

**Comment by miqrogroove** [comment] 2018-06-10 23:10
in src/Util/Emailer

`		$res = mail(
			$hookdata['to'],							// send to address
			$hookdata['subject'],						// subject
			$hookdata['body'], 	 						// message body
			$hookdata['headers'],						// message headers
			'-f ' . $params['fromEmail']
		);`

**Comment by miqrogroove** [comment] 2018-06-10 23:28
I confirmed the code above helps Google to validate SPF records very nicely.

Live.com is another matter as they have apparently blocked the host’s network completely.

**Comment by MrPetovan** [comment] 2018-06-13 01:33
This appears to only work with Sendmail though. What about other MTAs?

**Comment by MrPetovan** [comment] 2018-06-13 01:39
More info from http://php.net/manual/en/function.mail.php:

>The user that the webserver runs as should be added as a trusted user to the sendmail configuration to prevent a 'X-Warning' header from being added to the message when the envelope sender (-f) is set using this method. For sendmail users, this file is `/etc/mail/trusted-users`.

Even more info from http://php.net/manual/en/function.mail.php#107321:

> I was having delivery issues from this function to Gmail, Yahoo, AOL, etc.  I used the notes here to figure that you need to be setting your Return-Path to a valid email to catch bounces.  There are two extra delivery gotchas on top of that:
> 
> 1) The domain in the email used in the -f option in the php.ini sendmail parameter or in the mail() extra parameters field, needs to have a valid SPF record for the domain (in DNS as a "TXT" record type for sure and add an additional  "SPF" type record if possible).  Why? That's header field being used for spam checks.
> 
> 2) You should also use a domain key or DKIM.  The trick here is that the domain key/DKIM is case sensitive!  I used Cpanel to create my domain key which automatically used all lowercase domain names in the key creation.  I found when  sending email and using a camel case "-f account@MyDomainHere.Com" option, my key was not accepted.  However it was accepted when I used "-f account@mydomainhere.com".

This isn't straightforward at all. It probably should be put behind a config switch as it may break working setups without Sendmail and/or without SPF record.

**Comment by miqrogroove** [comment] 2018-06-13 05:29
SPF records are not a requirement for setting the correct envelope address. It’s the other way around.  Without a correct envelope, SPF only works as configured for the domain of the mail relay.

**Comment by MrPetovan** [comment] 2018-06-13 12:28
So `-f` would work with or without an SPF/DKIM record? What if the server isn't using Sendmail like Postfix or Exim? Would the parameter still work as intended?

**Comment by annando** [comment] 2018-06-13 13:22
We need to do this optional. We can't guarantee that it would work, for example, with qmail or some other obscure system.

**Comment by miqrogroove** [comment] 2018-06-13 13:30
The only real concern I’ve ever been aware of is that you have to remove the fifth arg if safe_mode evaluates as true.

> The additional_parameters parameter is disabled in safe_mode and the mail() function will expose a warning message and return FALSE when used.

4.2.3 | The additional_parameters parameter is disabled in safe_mode and the mail()function will expose a warning message and return FALSE when used.
-- | --




4.2.3 | The additional_parameters parameter is disabled in safe_mode and the mail()function will expose a warning message and return FALSE when used.
-- | --


4.2.3 | The additional_parameters parameter is disabled in safe_mode and the mail()function will expose a warning message and return FALSE when used.
-- | --





4.2.3 | The additional_parameters parameter is disabled in safe_mode and the mail()function will expose a warning message and return FALSE when used.
-- | --

**Comment by miqrogroove** [comment] 2018-06-19 19:53
Good news: safe_mode was removed in PHP 5.4.0 and we have 5.6+ required for Friendica.

**Comment by MrPetovan** [comment] 2018-06-19 21:55
Closed via #5245

**Closed by MrPetovan** 2018-06-19 21:55 UTC
Labels: Bug, Needs Ideas
