### ISSUE TITLE
Funkwhale ActivityPub Support

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7771] opened 2019-10-25 07:20 UTC
Please add Funkwhale ActivityPub support.

Site: https://funkwhale.audio/
git: https://dev.funkwhale.audio/funkwhale/funkwhale
dev doc: https://docs.funkwhale.audio/developers/index.html

**Comment by annando** [comment] 2019-10-25 12:23
Are there Funkwhale accounts that post stuff in a very frequent interval?

**Comment by hoergen** [comment] 2019-10-25 14:48
I can do with my funkwhale account 
https://tanukitunes.com/library/artists/6509/

**Comment by annando** [comment] 2019-10-25 14:57
#Hackathon

**Comment by annando** [comment] 2019-11-02 22:38
The problem is caused by missing value in JSON-LD: https://dev.funkwhale.audio/funkwhale/funkwhale/issues/961

**Comment by EliotBerriot** [comment] 2019-11-03 09:13
Hi there (Funkwhale developper here)! Someone shared the lin to this discussion on the fediverse, and I wanted to let you know I'm willing to help finding and fixing any bug that could prevent federation with Friendica from working.

> The problem is caused by missing value in JSON-LD: https://dev.funkwhale.audio/funkwhale/funkwhale/issues/961

Thank you for opening this issue @annando, I'll have a look next week, it shouldn't be that hard to fix.

I also wanted to say that the next Funkwhale release (due in Q1 2020) will implement a channel system, in a way that should bring compatibility with any ActivityPub server that support Audio objects.

In this system, and similarly to PeerTube, users will be able to create channels, and each channel will get a followable Actor. When sharing an audio file in a channel, the channel Actor will broadcast a Create/Audio activity to the followers.

The other federation part, that's currently implemented, relies around the concept of libraries. A Library is basically a Collection of Audio objects, belonging to a user. Funkwhale uses libraries to federate collections of audio files:

1. Libraries can be followed, just like actors
2. Library can be public or private (if private, then follows are approved manually, and non-followers cannot fetch the library content)

The main difference between libraries and channels is that libraries are primarily intended to aggregate a collection of audio files from different creators (e.g. the personnal music collection you have on your hard drive), while channels will be owned by creators themselves, to publish their work.

Depending on your goals, you may want to support only one of these, or both :) Let me know if you have any questions.

References:

- https://docs.funkwhale.audio/federation/index.html

**Comment by annando** [comment] 2019-11-03 10:53
@EliotBerriot thanks for your reaction! Concerning your libraries and channels I guess that I will have a look at it, once that it works. Then I can see, how to make it work with Friendica. I really would like to make Friendica compatible with all these different systems and to better support the media handling.

**Comment by EliotBerriot** [comment] 2020-03-11 13:49
So, I took a moment to test federation between Funkwhale channels and Friendica today.

The good news:

- I can search and find a Funkwhale channel in Friendica using its username, e.g @compositions@channels.tests.funkwhale.audio 
- I can send a follow request to this actor from Friendica, and receive it properly in Funkwhale
- I can retrieve a friendica profile from Funkwhale

![image](https://user-images.githubusercontent.com/1970915/76422960-5a5d3400-63a6-11ea-8f8a-5c0b13cf7b55.png)

![image](https://user-images.githubusercontent.com/1970915/76422979-6517c900-63a6-11ea-9041-dc23a9b5e9bb.png)

At a basic level, it looks like federation of profiles is working! Same for follows (the Follow/Accept dance went properly.)

However, content published by @compositions@channels.tests.funkwhale.audio  isn't processed by Friendica. I kind of expected it, and I willing to dedicate some time to fix this, if someone familiar with Friendica can do the same :)

For the record, this is the activity that was generated by Funkwhale and sent to the Friendica follower:

```json
{
    "to": [
        "https://channels.tests.funkwhale.audio/federation/actors/compositions/followers"
    ],
    "type": "Create",
    "actor": "https://channels.tests.funkwhale.audio/federation/actors/compositions",
    "object": {
        "id": "https://channels.tests.funkwhale.audio/federation/music/uploads/c49c0490-cad9-42da-a563-bde97aaac184",
        "to": "https://www.w3.org/ns/activitystreams#Public",
        "tag": [
            {
                "name": "#funkwhale",
                "type": "Hashtag"
            },
            {
                "name": "#tests",
                "type": "Hashtag"
            }
        ],
        "url": [
            {
                "href": "https://channels.tests.funkwhale.audio/api/v1/listen/925fce8c-ae05-4cca-af43-3b9bf2d67823/?upload=c49c0490-cad9-42da-a563-bde97aaac184&download=false",
                "type": "Link",
                "mimeType": "audio/ogg"
            },
            {
                "href": "https://channels.tests.funkwhale.audio/library/tracks/75",
                "type": "Link",
                "mimeType": "text/html"
            }
        ],
        "name": "Compositions - Testing friendica",
        "type": "Audio",
        "content": "<p>Content</p>",
        "summary": "#funkwhale #tests",
        "@context": [
            "https://www.w3.org/ns/activitystreams",
            "https://w3id.org/security/v1",
            {
                "manuallyApprovesFollowers": "as:manuallyApprovesFollowers"
            }
        ],
        "mediaType": "text/html",
        "published": "2020-03-11T13:33:18.426587+00:00",
        "attributedTo": "https://channels.tests.funkwhale.audio/federation/actors/compositions"
    },
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        "https://w3id.org/security/v1",
        {
            "manuallyApprovesFollowers": "as:manuallyApprovesFollowers"
        }
    ]
}
```

Let me know if you need additional details to troubleshoot this!

**Comment by annando** [comment] 2020-03-11 13:58
Currently we don't handle the `Audio` type at all. But I also saw that `mimeType` is used - so out internal validator can't handle that field. It should be `mediaType` instead. Or you would need to add the `mimeType` to the context as well. (Like `"mimeType": "as:mediaType"`)

**Comment by EliotBerriot** [comment] 2020-03-11 15:13
Indeed @annando, I've fixed the property issue, it should be `mediaType` now :)

**Comment by annando** [comment] 2020-03-11 17:07
Does looking great now. I will do some tests today, so that we do support "Audio" as well. After this we can possibly do some tests.

**Comment by annando** [comment] 2020-03-22 17:37
"today" is a very relativistic thing, I guess. :-) I try now.

**Comment by EliotBerriot** [comment] 2020-03-22 18:19
We all have busy lives, and software development isn't always the priority. Take care!

**Comment by annando** [comment] 2020-03-22 18:34
Oh yeah ... Busy times! I'm working as a developer and our customers belong to the group of "critical infrastructure" - they deliver supermarket chains, hospitals and clinics with fruits and vegetables.

Do you have a slightly larger list of posts? I will need to perform several tests.

**Comment by EliotBerriot** [comment] 2020-03-22 18:37
I haven't right now, I can create one tomorrow, otherwise you can use https://channels.tests.funkwhale.audio (login with demo/demo) and create as many channels / uploads as you want. This is a testing platform, so there's no trouble at all!

**Comment by annando** [comment] 2020-03-23 04:56
It should work now. I subscribed to that test channel, so that I can see if posts arrive.

**Comment by EliotBerriot** [comment] 2020-03-23 10:45
I've added two new uploads at https://channels.tests.funkwhale.audio/channels/compositions/, let me know if it worked :)

**Comment by EliotBerriot** [comment] 2020-03-23 15:54
@annando sorry, I'm lacking some context here. I've published two Audio earlier, using the account `compositionswith@channels.tests.funkwhale.audio`, which you followed with your account from `pirati.ca` (I assume it's you).

This is the content of the first `Audio` that was delivered to https://pirati.ca/inbox at 10:42 am:

```json
{
    "to": [
        "https://channels.tests.funkwhale.audio/federation/actors/compositions/followers"
    ],
    "type": "Create",
    "actor": "https://channels.tests.funkwhale.audio/federation/actors/compositions",
    "object": {
        "id": "https://channels.tests.funkwhale.audio/federation/music/uploads/ad910925-7f5e-4d6a-9002-a706517f19b3",
        "to": "https://www.w3.org/ns/activitystreams#Public",
        "tag": [
            {
                "name": "#funkwhale",
                "type": "Hashtag"
            },
            {
                "name": "#tests",
                "type": "Hashtag"
            }
        ],
        "url": [
            {
                "href": "https://channels.tests.funkwhale.audio/api/v1/listen/1b2ae833-c48c-4a63-863d-9455cb9b233e/?upload=ad910925-7f5e-4d6a-9002-a706517f19b3&download=false",
                "type": "Link",
                "mediaType": "audio/ogg"
            },
            {
                "href": "https://channels.tests.funkwhale.audio/library/tracks/3135",
                "type": "Link",
                "mediaType": "text/html"
            }
        ],
        "name": "Compositions - Another upload for friendica",
        "type": "Audio",
        "summary": "#funkwhale #tests",
        "@context": [
            "https://www.w3.org/ns/activitystreams",
            "https://w3id.org/security/v1",
            "https://funkwhale.audio/ns",
            {
                "Hashtag": "as:Hashtag",
                "manuallyApprovesFollowers": "as:manuallyApprovesFollowers"
            }
        ],
        "published": "2020-03-23T10:41:47.012631+00:00",
        "attributedTo": "https://channels.tests.funkwhale.audio/federation/actors/compositions"
    },
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        "https://w3id.org/security/v1",
        "https://funkwhale.audio/ns",
        {
            "Hashtag": "as:Hashtag",
            "manuallyApprovesFollowers": "as:manuallyApprovesFollowers"
        }
    ]
}
```

From my side, the delivery was successful (the POST request was answered with a 200 status code, or something similar). Was is processed by your server?


> I tried the url channels.tests.funkwhale.audio/federation/music/tracks/e7346add-20d7-4e59-9e06-462daaeb8b82 - but this doesn't contain any song information.

I'm not sure how you got this URL, however you have to query it witha `Accept: application/activity+json` header to get JSON data from it:

```
curl -k -H "Accept: application/activity+json" "https://channels.tests.funkwhale.audio/federation/music/tracks/e7346add-20d7-4e59-9e06-462daaeb8b82" 
```

However, this isn't the kind of objects we expect other implementations to support. Running `curl -k -H "Accept: application/activity+json" "https://channels.tests.funkwhale.audio/library/tracks/3135/"` should give you an output similar to the JSON I included in this post. I fixed an issue regarding this today, so maybe that's why you ended up with this URL?

**Comment by annando** [comment] 2020-03-23 17:33
In https://channels.tests.funkwhale.audio/library/tracks/3136/ there is a link "Federation" at the bottom. I used that.

**Comment by annando** [comment] 2020-03-23 17:40
I got the message `Invalid HTTP signature, message will be discarded.`.

The system took the key from: https://channels.tests.funkwhale.audio/federation/actors/compositions#main-key

Who signed it on your side?

**Comment by annando** [comment] 2020-03-24 05:12
There is something weird with your provided public key. On testing I get `supplied key param cannot be coerced into a public key`.

**Comment by EliotBerriot** [comment] 2020-03-24 08:17
> Edit: You are using a PKCS#1 RSA public key. Can you switch it to PKCS#8? (All major implementations do use the other format)

Indeed, I'll give it a go today

**Comment by EliotBerriot** [comment] 2020-03-24 08:54
@annando I've pushed a fix for this, and resent some of the activites to pirati.ca, can you check if it worked this time?

**Comment by annando** [comment] 2020-03-24 09:14
I have to check the logs. Will do so this day.

**Comment by annando** [comment] 2020-03-25 06:57
I just tested it with the testing platform: It worked fine! So the upcoming version will work with Funkwhale as well. @EliotBerriot thanks for your support!

**Comment by EliotBerriot** [comment] 2020-03-25 08:36
Amazing news! We did this together, thank you for being so responsive @annando!

**Closed** 2020-03-25 12:52 UTC
Labels: Berlin 2019, New Feature
