### ISSUE TITLE
"Blank Page After Clicking 'Next' in Friendica Installation Wizard"

### ISSUE THREAD

**Issue by Samir-Shakhbaz** [friendica/friendica#14641] opened 2024-12-30 04:49 UTC
x I have searched open and closed issues for duplicates
**Bug Description**
When trying to complete the installation of Friendica, the page loads correctly at the URL http://35.232.72.69:8080/install, but when I click the "Next" button, I am redirected to a blank page. I am unable to proceed with the installation.

**Steps to Reproduce**
Access the Friendica installation page: http://35.232.72.69:8080/install
Complete the initial installation page.
Click the "Next" button to proceed.

**Actual Result:**

The page redirects to a blank screen with no further progress. The server returns a 500 Internal Server Error.
**Expected Result:**

After clicking "Next," the installation process should proceed to the next step, not a blank page.

**What I've Tried So Far:**

- Checked and verified that the AllowOverride directive in /etc/apache2/apache2.conf is set to All for the appropriate directories.
- Ensured that the .htaccess file in /var/www/html/friendica has the correct rewrite rules.
- Restarted Apache (sudo systemctl restart apache2).
**Error log despite allowed rewrite rules:**
sudo tail -f /var/log/apache2/error.log
[Mon Dec 30 03:49:04.310293 2024] [mpm_prefork:notice] [pid 35715] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Dec 30 03:49:04.459724 2024] [mpm_prefork:notice] [pid 35819] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Mon Dec 30 03:49:04.459817 2024] [core:notice] [pid 35819] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 30 03:53:15.963767 2024] [mpm_prefork:notice] [pid 35819] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Dec 30 03:53:16.108151 2024] [mpm_prefork:notice] [pid 35912] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Mon Dec 30 03:53:16.108249 2024] [core:notice] [pid 35912] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 30 03:53:31.912465 2024] [core:alert] [pid 35913] [client 208.104.181.227:15793] /var/www/html/friendica/.htaccess: AllowOverride not allowed here
[Mon Dec 30 03:53:34.982720 2024] [core:alert] [pid 35915] [client 208.104.181.227:15803] /var/www/html/friendica/.htaccess: AllowOverride not allowed here
[Mon Dec 30 03:53:48.059749 2024] [core:alert] [pid 35917] [client 208.104.181.227:15809] /var/www/html/friendica/.htaccess: AllowOverride not allowed here
[Mon Dec 30 04:12:24.562555 2024] [core:alert] [pid 35914] [client 46.19.138.234:57732] /var/www/html/friendica/.htaccess: AllowOverride not allowed here

**Platform Info**
Friendica Version: 2024.08-325-gf2c1b326cb (from git describe --tags)
Friendica Source: Docker
PHP Version: PHP 8.1.2-1ubuntu2.20
SQL Version: MariaDB (not installed) or MySQL (you can check by running mysql --version if MySQL is installed)

**Comment by annando** [comment] 2024-12-30 13:20
This is a known issue and already fixed in the next version: https://github.com/friendica/friendica/issues/14450

**Comment by MrPetovan** [comment] 2024-12-30 16:29
Duplicate of https://github.com/friendica/friendica/issues/14450

**Closed as not planned by MrPetovan** 2024-12-30 16:29 UTC
Labels: Bug

**Comment by Samir-Shakhbaz** [comment] 2024-12-31 02:28
Thank you!
