### ISSUE TITLE
Post parsing problem with diaspora federation

### ISSUE THREAD

**Issue by AugierLe42e** [friendica/friendica#1838] opened 2015-08-21 20:26 UTC
The complete issue is explained [here](https://github.com/diaspora/diaspora/issues/6328). In short: Friendica strips linebreaks on comments so that a comment posted from a diaspora pod A on a post from a friendica pod relayed by it does not look the same on a diaspora pod B

**Comment by annando** [comment] 2015-08-23 09:20
Friendica internally is using BBCode. So we are having a converter "Markdown to BBCode" and "BBCode to Markdown". It seems as if there are parsing problems in one of these converters. I will have to check it.

**Comment by trev1ze** [comment] 2015-10-16 11:11
Hi, the following class could help to resolve this issue:

https://github.com/gutobenn/wp-to-diaspora/blob/master/lib/class-api.php

**Comment by annando** [comment] 2015-10-17 21:01
@trev1ze That project is using the same library to convert HTML to markdown like we are using. They are using a newer version. We have to see how we can update.

**Comment by redmatrix** [comment] 2015-10-17 22:18
It's probably a bit trickier because we're going from Markdown to HTML and then HTML to bbcode (unless this has changed significantly since I worked on that code). I believe it's in the HTML to bbcode that the whitespace is getting mangled as HTML considers multiple whitespace elements irrelevant.

**Comment by redmatrix** [comment] 2015-10-17 22:27
Sorry wrong direction, but I think it works the same going the other way. In the case of relayed posts we're doing the two conversions to end up with bbcode and then doing the same two conversions in reverse to go out again. With four conversions total there's a lot that could go wrong. It might make more sense to store the original markdown separately and use the original markdown text when relaying to Diaspora. I believe we're doing something like that in redmatrix/hubzilla in order to ensure that all the signatures validate end to end.

**Comment by annando** [comment] 2015-10-18 07:35
I thought about storing the original value as well. But that wouldn't solve the original problem that sometimes the "HTML to Markdown" is making problems. It would only reduce the total number of incidences.

**Comment by annando** [comment] 2015-12-06 21:38
The post is relayed via a Friendica server with a really old version (3.3.3). I can't reproduce this on the current version. I suggest that we close this issue.

**Comment by tobiasd** [comment] 2015-12-11 17:06
Ok, then I'll close it. @AugierLe42e should you discover this problem with a current Friendica node please let us know!

**Closed by tobiasd** 2015-12-11 17:06 UTC
Labels: Bug

**Comment by AugierLe42e** [comment] 2015-12-11 20:59
Thank you @tobiasd :)
