### ISSUE TITLE
Be able to remove an admin account as long as there is one admin account left

### ISSUE THREAD

**Issue by strk** [friendica/friendica#1625] opened 2015-05-29 20:04 UTC
Registration of multiple users with the same email address are accepted, but then in the "Admin"->"Users"  if one of them is the admin, all of them are considered admin so cannot be removed individually

**Comment by annando** [comment] 2015-05-31 17:14
It's not a bug. It is the intended behaviour.

**Comment by fabrixxm** [comment] 2015-06-01 06:47
same email is accepted to allow management of multiple accounts from single login:
https://amici.pallamondo.net/help/Forums "Managing Multiple forums"

**Comment by strk** [comment] 2015-06-01 13:55
I don't have a problem with accepting multiple accounts with same email, but I would still want to be able to threat them as different users so be able to individually remove/block each.

**Comment by annando** [comment] 2015-06-02 20:19
The property "admin" is based upon the mail address. This cannot be changed easily. But I guess your problem is a different one. You want to delete some users you created with the same mail address? if yes then we could change the description of the issue and could convert it to a pull request like: "Be able to remove an admin account as long as there is one admin account left"

Do you agree?

**Comment by strk** [comment] 2015-06-02 20:20
Agreed, but I'm not in a position to provide the PR myself

**Comment by annando** [comment] 2015-06-04 20:40
That's okay. I just wanted to have your opinion.

**Comment by fabrixxm** [comment] 2015-06-23 08:35
Only admins can view and edit `admin/users/` page.
So the rule is "be able to remove anyone but yourself", with "yourself" as "current logged user", and that would be an admin. And so one admin account undeletable.

**Comment by annando** [comment] 2015-06-23 12:46
I just tried out and it seems to run perfectly. I will close the issue.

**Closed by annando** 2015-06-23 12:46 UTC
Labels: Feature Request
