### ISSUE TITLE
Interacting with a post (Liking, Commenting, etc.) results in a mention notification in twidere

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1470] opened 2015-04-03 11:04 UTC
When interacting with a post (liking, commenting, etc.) the twidere client gets a notification that user has been mentioned in that post, which isn't the case.

**Comment by annando** [comment] 2015-04-06 16:49
By now a call to "statuses/mentions" includes every post of a thread where the user interacts with. (even older posts before the reply) I'm not sure how to cope with this.

**Comment by tobiasd** [comment] 2018-08-06 15:01
duplicate of #1303 closing this one

**Closed by tobiasd** 2018-08-06 15:01 UTC
Labels: Bug
