### ISSUE TITLE
Official support forum - "Message" button produces empty non-interactive modal dialog

### ISSUE THREAD

**Issue by dfsklar** [friendica/friendica#3838] opened 2017-10-30 21:01 UTC
Regarding the official support forum:  https://forum.friendi.ca/profile/helpers

I am a contact ("fan" level) of that forum.
For example, the "like" buttons appear for me when I visit that forum's status posts.

A "message" button appears on the left hand side inviting me to send a private message to that forum.  But it fails to produce a sane modal popup. See attached image.

![screen shot 2017-10-30 at 4 52 46 pm](https://user-images.githubusercontent.com/1151882/32195526-e1a15ace-bd93-11e7-8382-5206b39ad20e.png)

**Comment by tobiasd** [comment] 2017-10-31 07:07
> I am a contact ("fan" level) of that forum.
> For example, the "like" buttons appear for me when I visit that
> forum's status posts.
> 
> A "message" button appears on the left hand side inviting me to send
> a private message to that forum.  But it fails to produce a sane
> modal popup. See attached image.

I think this is a bug/unfinished construction side in the frio theme and one of the reasons why it is not enabled by default.

vier for instance should always offer you all interaction possibilities when arriving over a magic link.

**Comment by AlfredSK** [comment] 2017-10-31 14:34
I can confirm this. But it doesn't happen always. I tested this with several contacts of mine. Both sides are using frio. Sometimes it works and sometimes not. I'm always authenticated as guest.
If it works a special URL like .../message/new/dG9iaWFzQH... redirects me to my own node and a new message window appears with the TO field pre-filled with the receiver contact. Looking good. 
Sometimes the special URL is missing and I get a blank new message window. 
With the helpers forum I get the error shown above with "access denied" notification. That's odd because sending messages is enabled. Permit unknown people to send you private mail? => yes

**Comment by rabuzarus** [comment] 2017-10-31 17:17
Friendica should provide two different ways of handling the `Message` button.

If a person is a visitor (no established connection) the `Message` button on the profile page should point the visitor to `/wallmessage` (in frio it is opened in a modal). All messages which are written with `/wallmassege` are submitted as not validated author (because the system can't verify (at the moment) if the author of this wallmessage is really the author he/she claims to be. With other words, at the moment friendica is not able to authenticate contacts who aren't connected to the contact).

If a person is a guest (remote user - a contact with an established connection) the `Message` button on the profile page should redirect to the guests local `message` page (with additional data to tell the local `message` page the name and address of the recipient. The recipient should be the profile owner of the visited profile page). So it would be possible to send real private messages with authenticated contact information.

BTW: Frio can handle the two different situations (https://github.com/friendica/friendica/blob/develop/view/theme/frio/js/modal.js#L349)


Some bug tracing:
Which of the two links will be used is decided at https://github.com/friendica/friendica/blob/develop/include/identity.php#L268 (and L284).

When I visit the support forum as authenticated user (guest through magic-link) the `Message` button is pointing me to `/wallmessage/helpers`. But it should point to my local `message` module (because I'm a authenticated guest). Something went wrong here.

Because of the fact that I'm authenticated, no redirection url is submitted to the helpers forum (we don't need it because all data of an authenticated contact are stored in the contact table and we take all necessary date from this table) and `/wallmesage` will stop if we don't have an URL (https://github.com/friendica/friendica/blob/develop/mod/wallmessage.php#L77). In other themes `/wallmessage` will output an error message. Frio doesn't output this error message because the content of `/wallmessage` is loaded to a modal.

Back to the real problem? The big question is: Why do we don't get the redirection link to local `message` page for authenticated users? (https://github.com/friendica/friendica/blob/develop/include/identity.php#L268 and some lines below).


Semi-OT:
Is it useful to have the possibility to write private messages to forum accounts or should we remove it in such cases.

**Comment by tobiasd** [comment] 2017-10-31 17:39
> Is it useful to have the possibility to write private messages to forum accounts or should we remove it in such cases.

If you want to write a message to the forum "owner" but don't know who it is (or you are not connected otherwise) then I think it is useful yes.

**Comment by AlfredSK** [comment] 2018-12-31 22:03
The initial issue doesn't happen anymore. Just tested it. I could successfully write a PM to the forum account.

Closing or keeping because of the comment of @rabuzarus ?

**Comment by MrPetovan** [comment] 2019-01-01 05:47
Are you sure it hasn't been fixed by #5598 ? 😋

**Comment by MrPetovan** [comment] 2019-01-07 22:18
Closing here, extracted @rabuzarus 's comment in #6410

**Closed by MrPetovan** 2019-01-07 22:18 UTC
Labels: Bug
