### ISSUE TITLE
Composer is deleting text

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#10634] opened 2021-08-25 08:33 UTC
- [X ] I have searched open and closed issues for duplicates

### Bug Description

If  text is entered in pointed brackets like `<this text>` composer is deleting it completely 

### Steps to Reproduce

Write text in pointed brackets, send it and see the result.

Deleting the text in pointed brackets.

Expected Result:

Show the text with the pointed brackets.

### Screenshots

it looks like this: 

### Platform Info

Friendica **Vers**ion:
Friendica Source:  git / 021.09-dev / 1434/1434 & Post-Update-Version 1427/1427.
PHP version: 7.4
SQL version: MariaDB

**Comment by MrPetovan** [comment] 2021-08-25 14:26
Does this happen only in the Composer page? What happens in the modal form?

**Comment by annando** [comment] 2021-08-25 14:55
I guess that this is some HTML clean up, possibly in combination with the Markdown addon.

**Comment by hoergen** [comment] 2021-08-25 17:03
Pardon, forgot, that there is an extra composer page. I always use the modal page that you get as default editor.

**Comment by MrPetovan** [comment] 2021-08-25 17:08
Ok thank you for the clarification, it sounds like the HTML Purifier is aggressively stripping unknown tags from body content. We need to escape literal chevrons them before HTML purifier passes.

**Comment by MrPetovan** [comment] 2021-10-10 18:51
Looked into it more, using `This text there <this text here>` as source. The preview correctly shows the same text, but once the post is submitted it looks like `This text there`.

**Comment by MrPetovan** [comment] 2021-10-10 23:15
Did you enable the Markdown addon? If yes, there's a negative interaction in `Markdown::toBBCode` where the original text `This text there <this text here>` will be converted to the HTML string `<p>This text there <this text here></p>` and then the conversion from HTML to BBCode string will first strip illegal HTML and this will produce `This text there`.

This is because Markdown allows literal HTML even though in the Friendica context we do not expect it. The solution seems to be to escape HTML characters before performing the Markdown conversion to HTML.

Are we expecting literal HTML in the post form? Or anywhere we expect Markdown text from?

**Comment by MrPetovan** [comment] 2021-10-14 06:08
I wasn't able to reproduce this issue without the Markdown addon enabled, so the fix has been moved to the addon.

**Closed as completed** 2021-10-14 07:56 UTC
Labels: Bug, Addons
