### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#5002] opened 2018-05-08 18:05 UTC
### Expected behavior

Installation wizard to show up.

### Actual behavior

After running composer to fetch the dependencies and then calling the newly set up VM the apache error log contains a hint about Friendica complaining about a missing system theme.

> No system theme config value set in src/App.php 1122

(at Step 5 in INSTALL.txt)

### Steps to reproduce the problem

Try to install Friendica on a new server.

### Friendica version you encountered the problem

2018.05-rc git

### PHP version

7.0

**Comment by MrPetovan** [comment] 2018-05-08 18:12
Duplicate of #4956

**Closed by MrPetovan** 2018-05-08 18:12 UTC
Labels: Bug, Installation
