### ISSUE TITLE
Forum links - no posts

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#9410] opened 2020-10-11 13:23 UTC
The links on the left side below "Forums" ("Foren" ) open the forum, but without posts.
I have this problem on nerdica.net with "Nerdica Forum" and now also with a fresh account on libranet.de with the forums "Libranet Support" and "Friendica Support". 

- [x] I have searched open and closed issues for duplicates

### Bug Description

No posts appear when clicking a link below "Forums" on the /network page ( like: https://libranet.de/network?contactid=1319082 )

### Steps to Reproduce

1.  make a new account on friendica 
2.  search for !Friendica Support..
3.  open the contact --> conversations page of the forum
4. click "follow"
5. go to your /network page 
6. look for "Forums" on the left and click the link to the forum

Actual Result:

![friendica-libranet-forum](https://user-images.githubusercontent.com/5753419/95679477-6b3b8580-0bd3-11eb-8721-66c1cc5bfc40.jpg)
![friendica-nerdica-forum](https://user-images.githubusercontent.com/5753419/95679480-71316680-0bd3-11eb-9696-93febf4dc6a1.jpg)

Expected Result:

the posts, like for example can be seen on the contact -> conversations page.. ( like https://libranet.de/contact/1319082/conversations )

### Platform Info

Friendica Version:

"Diese Friendica-Instanz verwendet die Version 2020.12-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1370/1370 und die Post-Update-Version 1349/1350."

**Comment by haheute** [comment] 2020-11-02 13:59
From time to time, posts seem to arrive in the forums on libranet.de.
like: `vor 5 Monate (Empfangen vor 1 Stunde)` so maybe it just takes some time.

The 'Nerdica Forum' on nerdica.net is still empty for me. I have unfollowed and followed it again and will wait for the next stable release.

**Comment by AlfredSK** [comment] 2020-11-02 19:32
You will only get new post. Posts created before your registration will not appear there.

**Comment by haheute** [comment] 2020-11-02 20:13
Ok, good to know. That explains why there were no posts..
But.. .. I see a [post](https://libranet.de/display/5f617517-535e-d11b-6a10-d6b881155807) with `vor 5 Monate (Empfangen vor 8 Stunden)` and I am only registered since 1 month on libranet.de ... Maybe because that post received a new comment (?)

**Comment by AlfredSK** [comment] 2020-11-02 20:34
Possible. Since when are you a follower of `support@libranet.de`? I posted something to that forum yesterday.

**Comment by haheute** [comment] 2020-11-02 20:48
>Since when are you a follower of support@libranet.de

I don't know where I can see that. I think approximately since my registration on libranet.de (2020-10-11).

>I posted something to that forum yesterday.

If you mean [this](https://libranet.de/display/0b6b25a8-725f-9eaf-2b22-483239053679), I can't find it under the Forum Link. Only 4 posts there, the one from you I can't see.

**Comment by AlfredSK** [comment] 2020-11-02 20:56
Can you tell me your username on libranet.de, please?

**Comment by haheute** [comment] 2020-11-02 20:58
`xy@libranet.de`

**Comment by AlfredSK** [comment] 2020-11-02 20:59
ok :-)

**Comment by AlfredSK** [comment] 2020-11-02 21:16
Your contact at the forum looks ok. I just sent 2 test posts (one directly from the forum account, another as normal 'via' forum post).

**Comment by haheute** [comment] 2020-11-02 21:18
I only see the one saying "Test 1". 
To see both, i have to go to the Forum's contact / conversations page.

**Comment by AlfredSK** [comment] 2020-11-02 21:27
Test 1 was the direct post from the forum. The other one (Test 2) is the important one.

And I think I know what the problem is...

@annando We still have a problem with forums. The follower contact is shown as `Network type: friendica (via ActivityPub)`. These contact types of forums are making trouble. On the other hand forum followers of type `Network type: friendica` do work flawlessly.
Since the 'advanced' tab doesn't exist anymore I cannot 'repair' the contact to use `Network type: friendica` again.

Any thoughts on this?

**Comment by annando** [comment] 2020-11-03 13:41
@AlfredSK you still can refetch the contact data from the contact page. The option moved there. Concerning this `friendica (via ActivityPub)` - this looks okay from my point of view.

But: I noticed some other forum problems that I will have a look at.

**Comment by AlfredSK** [comment] 2020-11-04 20:35
Yep. The refetch is there but it does not change the network type anymore. I could do that in the past with the repair link.

Let's see how it works after the latest changes.

**Comment by AlfredSK** [comment] 2020-11-04 21:13
Looks like this #9490 might have fixed this issue.

**Comment by MrPetovan** [comment] 2020-11-04 21:28
Fixed by #9490

**Closed as completed by MrPetovan** 2020-11-04 21:28 UTC
Labels: Bug

**Comment by AlfredSK** [comment] 2020-11-04 21:30
Well, I said "might have fixed" it. Let's hope I was right.

**Comment by annando** [comment] 2020-11-05 03:44
@AlfredSK just some clarification: This `friendica (via ActivityPub)` is totally okay and expected. This means that it the contact is a Friendica contact and that the contact adding had been done via AP and not the legacy DFRN way. This is opposite to the situation some time ago, when sometimes a Friendica contact had been detected as AP contact, without detecting that it had been Friendica - but displaying "Friendica" because the server detection detected it correctly.
