### ISSUE TITLE
DB Error 1140

### ISSUE THREAD

**Issue by hellquist** [friendica/friendica#10002] opened 2021-03-07 09:47 UTC
- [X] I have searched open and closed issues for duplicates

### Bug Description

I was asked to submit my database errors [here by Michael Vogel](https://pirati.ca/display/ec054ce7-7760-224c-d426-08d369931464?owt=2d4546f4deb077df2ad1afb9455448f6). I can't really explain them, or what goes wrong, but was told the errors themselves contain all the needed information, so here it goes:

```2021-03-07T08:32:53Z index [ERROR]: DB Error {"code":1140,"error":"In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'friendica.post-user-view.parent-uri-id'; this is incompatible with sql_mode=only_full_group_by","callstack":"DBA::p, Profile::rawContent, call_user_func, Module::run, App::runFrontend","params":"SELECT DISTINCT(`parent-uri-id`) AS `uri-id`, MAX(`created`), MAX(`received`) FROM `post-user-view` WHERE `uid` = 2 AND NOT `contact-blocked` AND NOT `contact-pending` AND `visible` AND (NOT `deleted` OR `gravity` = 3) AND `wall` AND `received` > '2021-03-07 08:22:49' AND `private` != 1 ORDER BY `received` DESC"} - {"file":"Database.php","line":662,"function":"p","uid":"76dc59","process_id":103825}```

### Platform Info

Friendica Version:

Friendica Source: Friendica 'Red Hot Poker' 2021.03-dev - 1406

PHP version: 7.4.3

SQL version: 8.0.23

**Comment by MrPetovan** [comment] 2021-03-07 09:51
Thank you for the report, this is a duplicate of #9925 and was just fixed with #10001, please update your node to the latest RC branch commit.

**Closed as completed by MrPetovan** 2021-03-07 09:51 UTC
Labels: Bug
