### ISSUE TITLE
How to clean up erroneous  categories?

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#11234] opened 2022-02-10 16:49 UTC
Related to this issue https://github.com/friendica/friendica/issues/10552 (it never got any attention and would be great if it would be put on some waiting list): I just noticed that I have a lot of wrong categories displayed on my public profile page if logged off.

When I am logged in I see only the categories I use. If someone else looks at my profile page (or I log off) I see all categories on the server displayed there, some of which are used by someone else and some are categories I created erroneously (i.e. misspelled the name) and then stopped using them so they don't contain any posts anymore. If I click them they show nothing but they are still displayed.

Can I clean them out somehow? AFAIK there is no frontend for category editing/removal but maybe I can do it via API or directly in the database?

Logged in (correct categories):
![image](https://user-images.githubusercontent.com/35988439/153455386-57379990-ef82-41ae-9573-0f8766b66894.png)

Logged off (includes some junk):
![image](https://user-images.githubusercontent.com/35988439/153455643-3a995551-eae3-4b47-84b5-d5a4ec679680.png)

**Comment by MrPetovan** [comment] 2022-02-11 02:30
Are there any categories you created by assigning it to a post and then later removed this assignment but the category still shows in this list?

**Comment by MrPetovan** [comment] 2022-02-11 02:31
Thanks I believe we can look into both issues at once.

**Comment by annando** [comment] 2022-02-11 11:40
I guess that the origin of the problem is that we shouldn't display categories at all when not logged in.

**Comment by tobiasd** [comment] 2022-02-11 12:00
> I guess that the origin of the problem is that we shouldn't display categories at all when not logged in.

Why? As is blogs categories are a way to sort your postings. Visitors of my profile page might want to see only the postings I've put into the category "Berlin".

**Comment by MrPetovan** [comment] 2022-02-11 12:24
What should be working:
- On a profile only the categories of the profile's author should be shown
- Only the categories having at least one post should be shown

**Closed as completed** 2022-02-20 05:35 UTC
Labels: Bug, UX
