### ISSUE TITLE
Can not find or add gup.pe group

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#10624] opened 2021-08-23 12:26 UTC
- [X] I have searched open and closed issues for duplicates

### Bug Description

With stable i could search for EinwortMagie@gup.pe and add this group successfully.
Then i upgraded to devel-branch. Now the search for gup.pe groups deliver "no result"

### Steps to Reproduce

Actual Result:

No Searchresult for group search. Even loacl and remote

Expected Result:

Find forum and gup.pe group

### Platform Info

Friendica Version: 2021.09-dev

Friendica Source: 

PHP version: 7.3

SQL version: mariadb 10.3

Maybe it is the same problem as with peertube-channels (they work the same as gup.pe groups or friendica-forums) https://github.com/friendica/friendica/issues/10623

**Comment by MrPetovan** [comment] 2021-08-24 15:44
Duplicate of #10625, closing

**Closed as completed by MrPetovan** 2021-08-24 15:44 UTC
Labels: Bug
