### ISSUE TITLE
Community page federation to diaspora

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1575] opened 2015-05-19 23:49 UTC
When posting to a community page by adressing for example "@friendicasupport" in the post, the post get's displayed in the community stream and is  federated to the friendica contacts **but not to the diaspora contacts**.
Post's from diaspora addressed at a forum page are dilivered and displayed correctly to the forum and friendica contacts.
Example:
https://pod.geraspora.de/people/b65e236d029183a0
https://tupambae.net/profile/lzjiec2apbeqhveaz6vmzvhtefb3b9pygm

This actually leads to blank comunity pages on diaspora if the forum itself doesn't post at all, see helpers profile on geraspora for example, there is only one friend connection activity post from about a year ago.
https://pod.geraspora.de/people/6dec720532663356

**Comment by foss-** [comment] 2015-05-20 13:54
+1 sounds like what I ran into.
federation to diaspora seems to be broken since it's been updated to 5.x. Looks like the connector php script is in need of some adjustments.

**Comment by annando** [comment] 2018-08-06 19:13
The forum support had improved until then.

**Comment by AlfredSK** [comment] 2018-12-31 22:08
@ mentions of forum accounts do work. They appear as reshared posts on Diaspora (like the forum has reshared a post of the original author).
Looks like the issue is solved.
Closing?

**Closed** 2019-01-01 05:47 UTC
Labels: Bug, Federation
