### ISSUE TITLE
fix include/uimport.php to ignore guid field and create a new one

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1491] opened 2015-04-07 02:31 UTC
From joindispora and geraspora the profile lzjiec2apbeqhveaz6vmzvhtefb3b9pygm@tupambae.org can't be found (and their for can't be connected). Another profile on the same server with a litecoin address as profile name was found without problem (ltjus1lpwal8nymfqattzuh13ysjuzyhsc@tupambae.org).
Also a profile with the same litecoin name on a different server (net) is available lzjiec2apbeqhveaz6vmzvhtefb3b9pygm@tupambae.net .

Any reasonable explanation on this?

**Comment by tobiasd** [comment] 2015-04-08 14:04
Same here. The communication with small pods works though. From the logs the communication in all cases look successful in each case.

**Comment by TupambaeNet** [comment] 2015-04-08 16:22
What do you mean with same here?

**Comment by tobiasd** [comment] 2015-04-08 17:46
On my personal node.

**Comment by TupambaeNet** [comment] 2015-04-08 20:53
You mean you some profiles that are found and some that aren't?
Contacts are shown by friendica like if they are "legitimate" contacts but don't federate the messages to diaspora?

I suppose that if I could get one time a contact to some pod, from there I could federate messages with profile inside D* but I only have geraspora and joindiaspora at hand.

**Comment by tobiasd** [comment] 2015-04-09 05:25
I mean that big pods (joindiaspora, geraspoa) ignore my profile, while small ones are fine to communicate with. But looking at the logs communication with Diaspora always looks the same and successful.

**Comment by TupambaeNet** [comment] 2015-05-19 05:56
I actually doubt that it is a problem because of my server settings or big pod's. New profiles don't show these problems at all.
https://github.com/friendica/friendica/issues/1489

Do we have two well installed severs to test this some how?

**Comment by TupambaeNet** [comment] 2015-05-19 23:41
Just checked the webfinger results of:
lzjiec2apbeqhveaz6vmzvhtefb3b9pygm@tupambae.org
The Diaspora ID:
                    [rel] => http://joindiaspora.com/guid
                    [type] => text/html
                    [href] => __b65e236d029183a0__

Is the ID from the former Profile located at the .net domain!
https://joindiaspora.com/people/b65e236d029183a0

**Comment by fabrixxm** [comment] 2015-05-20 08:17
you moved from tupambae.net to tupambae.org?
how?

**Comment by TupambaeNet** [comment] 2015-05-20 16:20
Downloading profile and uploading profile. I did this with several Profiles and have the same problems with all of them.

**Comment by fabrixxm** [comment] 2015-05-23 15:26
In account file (exported from /uexport) there is the diaspora guid. That guid should be unique per every address.
But when an account file is imported, 'guid' field is imported from file in new account.
IMHO, that's is why diaspora can't find the profile: in their records that guid is linked to other urls.

I would close this issue and open a new one to fix `include/uimport.php` so that it ignore guid field and create a new one.

**Comment by TupambaeNet** [comment] 2015-05-25 06:19
Who would need to do that "closing and reopening", can't we just change the titelof the issue to: fix include/uimport.php to ignore guid field and create a new one ?

**Comment by fabrixxm** [comment] 2015-05-25 06:53
+1

**Comment by tobiasd** [comment] 2015-06-16 14:24
I would love to see a fix for profiles already moved so they wont have to move again.

**Comment by annando** [comment] 2015-07-15 16:13
Is the guid field used in any context inside the friendica communication?

**Comment by tobiasd** [comment] 2015-08-12 06:22
Importing an account now generates a new guid in the develop branch. Already moved accounts need another solution.

**Comment by annando** [comment] 2015-08-12 11:07
The task is simple. There is a simple function that needs to be called to generate a new guid. The problem is: This mustn't be called on an account that already works with diaspora. This would reliable kill any communication. 

That means that we need to create a function that asks Diaspora servers for the GUID of a contact. Then we could do a reliable check. Sounds like a nice task :)

**Comment by tobiasd** [comment] 2015-08-12 13:28
But it is no task that needs to be done for every account either. Why not let the admin hit a "generate new guid" button from the admin panel or something alike.

**Comment by annando** [comment] 2015-08-12 19:39
We need a security check. I already think of a possible. Please tell me your guid then I can check if it could work.

**Comment by annando** [comment] 2015-08-12 19:45
BTW: There could even be a situation when some servers connected you with the old address and some with the current one - with the same guid. The changing of the guid would enable the communication with the one half and kill the communication with the other half ...

**Comment by annando** [comment] 2015-08-12 20:45
Command reversed ... My idea can't work.

**Comment by tobiasd** [comment] 2015-08-15 05:27
Just a thought. What if the admin moves the node to a new location, is the GUID then correctly recreated?

**Comment by annando** [comment] 2015-08-15 07:49
No, this isn't covered by now.

**Comment by tobiasd** [comment] 2015-08-23 05:19
as the original issue shold be fixed I've created a followup for 3.4.3

**Closed by tobiasd** 2015-08-23 05:19 UTC
Labels: Bug
