### ISSUE TITLE
Forum - editor problems

### ISSUE THREAD

**Issue by blog2read** [friendica/friendica#2918] opened 2016-11-15 20:46 UTC
When you are in a forum and if you want to edit a new message:

1. The @ address for this forum message isn't composed at the beginning
2. In the opened editor window you can't write

**Comment by tobiasd** [comment] 2016-11-16 06:38
If you post a note at the wall of a forum, you do not need to mention it with the @-name in the posting.

Regarding the 2nd problem I've just written a new entry for the Support forum directly on the wall and had no problems using chromium based Vivaldi browser. Which browser did you use? And which theme did the forum use?

**Comment by blog2read** [comment] 2016-11-16 09:00
Perhaps I described it not correctly. I try it again - see screenshot:
If I am in a Forum and push the button to edit a new message the editor window which pops up has not the "@helpers+34" in the text and I can't edit any characters in the text field. The subject line is ok. If I switch to HTML view the "@helpers+34".

I tried with PaleMoon, Firefox, Chromium, Google Chrome on Windows and Linux - always same result.

![friendica-01](https://cloud.githubusercontent.com/assets/6249323/20340688/22443f42-abe3-11e6-9b2c-52e600eebf40.png)
 is there.

**Comment by tobiasd** [comment] 2016-11-16 09:08
Could you try with disabled Richtext-Editor (Settings -Y Additional Features -> Post Composition). There seem to be problems with the (experimental) Frio theme.

**Comment by annando** [comment] 2016-11-16 09:30
I would suggest that Frio automatically disables the rich text editor. For example we could define this in the capabilities of a theme.

**Comment by blog2read** [comment] 2016-11-16 09:30
Yes, with "Web Editor" switched off the editor window w is writable and @helper+34 is already inserted.

**Comment by tobiasd** [comment] 2016-11-16 11:39
I had the same idea. If that would be possible I think it would help.

**Comment by fabrixxm** [comment] 2016-11-16 15:54
we should kill the richtext editor... is quite unmantained and not fully
functional

**Comment by blog2read** [comment] 2016-11-16 16:03
@fabrixxm IMHO not quite a good solution - the richtext editor works with other themes.

**Comment by Hypolite** [comment] 2016-11-17 02:23
I'm pretty sure we can disable it only for the frio theme.

**Comment by rabuzarus** [comment] 2016-11-17 03:35
Yes we can :-) But @fabrixxm is right that the rich text editor is quite unmaintained

**Comment by Hypolite** [comment] 2016-11-17 03:54
I also agree with him, rich text editors are evil personified, but if it works, why removing it, since it's already protected behind a setting switch?

**Comment by rabuzarus** [comment] 2016-11-17 16:33
>  but if it works, why removing it, since it's already protected behind a setting switch

Right, this not something which needs do be done tomorrow. But in the future we will get more and more problems because at the moment nobody cares for the rich text editor part.
E.g. I ported the bbtag and contact completion from hubzilla to friendica, but I didn't find a way to make it work in the rich text editor. So I  didn't remove the old completion part because this would break for the rich text editor.
There are many other parts in friendica core where we have always to respect the the rich text editor.
What I want to say is, that I guess we will getting more and more problems in the future with the fact that we need to support two editors (while nobody of the developers is maintaining the rich text editor part).

**Comment by annando** [comment] 2016-11-17 20:51
Off Topic: For the tomorrow work: Could you add a character counter for the other editor? This is one thing that I'm missing.

**Comment by rabuzarus** [comment] 2016-11-18 21:54
@annando 
It's not the problem to have a character counter for the standard editor. The problem is rather, that it also counts all the bbtags

**Comment by rabuzarus** [comment] 2016-11-18 22:53
@annando You will find a very simple character counter for the frio jot here https://github.com/rabuzarus/friendica/commit/a8d1a3f9974b32312bd36279ef84d93bb20de088

**Comment by tobiasd** [comment] 2016-12-12 06:32
The problem is fixed in the current development branch. Hence I'll close it.

**Closed by tobiasd** 2016-12-12 06:32 UTC
Labels: UI/Theme
