### ISSUE TITLE
[2024.03] Fatal Errors

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#13763] opened 2023-12-24 18:09 UTC
Please report here any PHP Fatal error message obtained running the 2023.12 stable or 2024.03-dev/rc versions.

Replaces  #13156

**Comment by Raroun** [comment] 2023-12-28 06:48
Again I had to block a contact server wide, causing endless loops.

`https://mastodon.social/@persagen`

Post
`https://mastodon.social/@persagen/110697509011152834`
is referencing to post
`https://mastodon.social/@persagen/110662765514723258`

and vice versa.

**Comment by MrPetovan** [comment] 2023-12-28 06:53
Thank you for the report, it looks like we only handle same-posts self-references at the moment.

**Comment by ghost** [comment] 2023-12-29 11:24
latest dev

```
PHP Fatal error:  Uncaught mysqli_sql_exception: Connection refused in /src/Database/Database.php:191
Stack trace:
#0 /src/Database/Database.php(191): mysqli->__construct()
#1 /src/Database/Database.php(97): Friendica\Database\Database->connect()
#2 [internal function]: Friendica\Database\Database->__construct()
#3 /vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs()
#4 /vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#5 /vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#6 /vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#7 /vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#8 /vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#9 /vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#10 /vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#11 /bin/worker.php(59): Dice\Dice->create()
#12 {main}
  thrown in /src/Database/Database.php on line 191
```

**Comment by MrPetovan** [comment] 2023-12-29 15:07
Please check your database credentials on the Friendica side in the `config/local.config.php` file, then the database credentials in the database itself (reference table is `mysql.user`) including the host part, then the database utilization, raising the maximum connection limit if needed.

**Comment by haheute** [comment] 2024-01-09 07:10
I hope this is okay to add here. I currently use the `dev` version, but it was with `rc` , too.

I still see many:
`Fatal Error (E_ERROR): Allowed memory size of 536870912 bytes exhausted (tried to allocate 94388224 bytes)`

in:
`/var/www/localhost/friendica/src/Database/Database.php` 

on line: 
`568`

If a trace would help, please someone tell me how to create one.

**Comment by Quix0r** [comment] 2024-01-16 19:47
> src/Database/Database.php
> 568

That line is in `develop`: https://github.com/friendica/friendica/blob/develop/src/Database/Database.php#L568 And I don't see any problems there.

Edit: Maybe a huge data set was fetched?

**Comment by haheute** [comment] 2024-01-17 04:23
I don't know. It is this: https://github.com/friendica/friendica/issues/12777#issuecomment-1891053597

**Comment by ghost** [comment] 2024-01-22 16:40
```
worker [ERROR]: DB Error  - {"file":"Database.php","line":789,"function":"e","request-id":"65adfc2e21ccc","stack":"Database::e (1037), Database::insert (89), Database::put (454), Photo::store (641), Photo::importProfilePhoto (2400), Contact::updateAvatar (2900), Contact::updateFromProbeArray (2686), Contact::updateFromProbe (46), UpdateContact::execute, Worker::execFunction (386), Worker::execute (121), Worker::processQueue (87)","uid":"71efe1","process_id":2466800}
worker [ERROR]: Uncaught exception in worker execution {"class":"Friendica\\Core\\Storage\\Exception\\StorageException","message":"Database storage failed to update ","code":500,"file":"/src/Core/Storage/Type/Database.php:94","trace":"
#0 /src/Model/Photo.php(454): Friendica\\Core\\Storage\\Type\\Database->put()\n
#1 /src/Model/Photo.php(641): Friendica\\Model\\Photo::store()\n
#2 /src/Model/Contact.php(2400): Friendica\\Model\\Photo::importProfilePhoto()\n
#3 /src/Model/Contact.php(2900): Friendica\\Model\\Contact::updateAvatar()\n
#4 /src/Model/Contact.php(2686): Friendica\\Model\\Contact::updateFromProbeArray()\n
#5 /src/Worker/UpdateContact.php(46): Friendica\\Model\\Contact::updateFromProbe()\n
#6 [internal function]: Friendica\\Worker\\UpdateContact::execute()\n
#7 /src/Core/Worker.php(572): call_user_func_array()\n
#8 /src/Core/Worker.php(386): Friendica\\Core\\Worker::execFunction()\n
#9 /src/Core/Worker.php(121): Friendica\\Core\\Worker::execute()\n
#10 /bin/worker.php(87): Friendica\\Core\\Worker::processQueue()\n
#11 {main}","previous":"Exception: Got a packet bigger than 'max_allowed_packet' bytes in /src/Core/Storage/Type/Database.php:94\n
```

**Comment by AlfredSK** [comment] 2024-02-17 10:52
That looks wrong. :-) The URL ist `&maxwidth=425`. 

```
worker [ERROR]: Uncaught exception in worker execution {"class":"InvalidArgumentException","message":"Unable to retrieve the host in URL: &maxwidth=425","code":0,"file":"..../src/Network/HTTPClient/Client/HttpClient.php:73",
"trace":"
#0 .../src/Network/HTTPClient/Client/HttpClient.php(206): Friendica\\Network\\HTTPClient\\Client\\HttpClient->request()
#1 .../src/Network/HTTPClient/Client/HttpClient.php(287): Friendica\\Network\\HTTPClient\\Client\\HttpClient->get()
#2 ..../src/Content/OEmbed.php(121): Friendica\\Network\\HTTPClient\\Client\\HttpClient->fetchFull()
#3 .../src/Util/ParseUrl.php(258): Friendica\\Content\\OEmbed::fetchURL()
#4 .../src/Util/ParseUrl.php(354): Friendica\\Util\\ParseUrl::getSiteinfo()
#5 .../src/Util/ParseUrl.php(137): Friendica\\Util\\ParseUrl::getSiteinfo()
#6 .../src/Protocol/Feed.php(606): Friendica\\Util\\ParseUrl::getSiteinfoCached()
#7 .../src/Worker/OnePoll.php(188): Friendica\\Protocol\\Feed::import()
#8 .../src/Worker/OnePoll.php(95): Friendica\\Worker\\OnePoll::pollFeed()
#9 [internal function]: Friendica\\Worker\\OnePoll::execute()
#10 .../src/Core/Worker.php(572): call_user_func_array()
#11 .../src/Core/Worker.php(386): Friendica\\Core\\Worker::execFunction()
#12 .../src/Core/Worker.php(121): Friendica\\Core\\Worker::execute()
#13 .../bin/worker.php(87): Friendica\\Core\\Worker::processQueue()
#14 {main}","previous":null,"worker_id":"26be391","worker_cmd":"OnePoll"} - {"file":"Worker.php","line":577,"function":"execFunction","request-id":"65d08b64dac55","stack":"Worker::execFunction (386), Worker::execute (121), Worker::processQueue (87)","uid":"44baac","process_id":3550156}
```

2024.03-dev, PHP 8.1

Addressed in #13904

**Comment by ghost** [comment] 2024-02-17 21:49
`PHP Fatal error: gd-webp cannot allocate temporary buffer in /src/Object/Image.php on line 225`

**Comment by MrPetovan** [comment] 2024-02-18 03:32
@Friendlica What PHP version are you using?

**Comment by ghost** [comment] 2024-02-18 09:18
> @Friendlica What PHP version are you using?

PHP 8.1.2 maybe it has something with this to do https://github.com/friendica/friendica/issues/13906

**Comment by MrPetovan** [comment] 2024-02-18 23:53
Unlikely, I asked because lower versions of PHP don't support WebP but it doesn't seem to be the issue in your case.

**Comment by annando** [comment] 2024-02-19 04:12
See here for the WebP message: https://stackoverflow.com/questions/61394477/php-e-error-gd-webp-cannot-allocate-temporary-buffer

**Comment by MrPetovan** [comment] 2024-02-19 10:56
I found the same page, hence my PHP version question. It doesn't seem to be relevant in this case.

**Comment by ghost** [comment] 2024-03-06 14:22
```
2024-03-06T12:35:23Z app [ERROR]: Uncaught Exception TypeError: "implode(): Argument 
#1 ($array) must be of type array, string given" at /addon/url_replace/url_replace.php line 49 {"exception":"TypeError: implode(): Argument 
#1 ($array) must be of type array, string given in /addon/url_replace/url_replace.php:49\nStack trace:\n
#0 /addon/url_replace/url_replace.php(49): implode()\n
#1 /src/Module/Admin/Addons/Details.php(105): url_replace_addon_admin()\n
#2 /src/BaseModule.php(250): Friendica\\Module\\Admin\\Addons\\Details->content()\n
#3 /src/App.php(711): Friendica\\BaseModule->run()\n
#4 /index.php(46): Friendica\\App->runFrontend()\n
#5 {main}"} - {"file":null,"line":null,"function":null,"request-id":"65e8630ba51f6","stack":"ErrorHandler::handleException (128), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"8c1562","process_id":1475}
```
Duplicate of https://github.com/friendica/friendica/issues/13968

**Comment by MrPetovan** [comment] 2024-03-06 16:42
@Friendlica Can you please run `bin/console config url_replace twelvefeet_sites` and report the output?

**Closed as completed** 2024-03-22 06:29 UTC
Labels: Bug
