### ISSUE TITLE
After git pull friendica is down

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#5440] opened 2018-07-21 14:36 UTC
i did a git pull on friendica developer and addons and now my friendica is gone.

**Comment by hoergen** [comment] 2018-07-21 14:44
The webbrowser says "The requested URL /network was not found on this server."

**Comment by tobiasd** [comment] 2018-07-21 14:53
Please have a look if there is a `.htaccess` file or only a `.htacces-dist` file. If it is only the later one, please copy over the dist file

    $> cp .htaccess-dist .htaccess

**Comment by tobiasd** [comment] 2018-07-21 14:56
If that helps, this was caused by #5428 and is a duplicate of #5432 but should have been solved by #5435

**Comment by hoergen** [comment] 2018-07-21 15:04
I renamend .htaccess restarted apache and named it back. Now it works again .. dont understand it ... but everything seems to be fine again. I didnt edit any file. Is this the magic token everybody is taking of? ;)

**Closed** 2018-07-21 15:08 UTC
Labels: Bug, Sup­port Request

**Comment by MrPetovan** [comment] 2018-07-21 15:33
No, it was caused by a mistaken commit that renamed `.htaccess` to `htaccess-dist`, which removed all URL rewriting.
