### ISSUE TITLE
BBCode "table" inserts superfluous line breaks

### ISSUE THREAD

**Issue by MarkusF47** [friendica/friendica#6799] opened 2019-03-03 09:41 UTC
### Expected behavior
The BBCode `table` should produce html code without line breaks.
```
<table><tr><th>Kopfzeile 1</th><th>Kopfzeile 2</th><th>Kopfzeile 2</th></tr><tr><td>Zelle 1</td><td>Zelle 2</td><td>Zelle 3</td></tr></table>
```
### Actual behavior
The html code for the table contains a lot of line breaks.
```
<table><br><tr><th>Kopfzeile 1</th><br><th>Kopfzeile 2</th><br><th>Kopfzeile 2</th></tr><br><br><tr><td>Zelle 1</td><br><td>Zelle 2</td><br><td>Zelle 3</td></tr><br></table>
```
### Steps to reproduce the problem
Go to Personal Notes and create a new post with following text:
```
[table]
  [tr]
    [th]Kopfzeile 1[/th]
    [th]Kopfzeile 2[/th]
    [th]Kopfzeile 2[/th]
  [/tr]
  [tr]
    [td]Zelle 1[/td]
    [td]Zelle 2[/td]
    [td]Zelle 3[/td]
  [/tr]
[/table]
```
### Friendica version you encountered the problem
2019.03-rc

**Comment by tobiasd** [comment] 2019-03-03 09:52
probably part of #4488

**Comment by MarkusF47** [comment] 2019-03-03 09:57
As a workaround you can enter the BBCode without the line break, but that isn't very readable.
```
[table][tr][th]Kopfzeile 1[/th][th]Kopfzeile 2[/th][th]Kopfzeile 2[/th][/tr][tr][td]Zelle 1[/td][td]Zelle 2[/td][td]Zelle 3[/td][/tr][/table]
```

**Comment by MrPetovan** [comment] 2019-03-03 13:19
Hi @MarkusF47 and thanks for your report. Indeed, the current BBCode parser is pretty liberal with line breaks, unlike HTML rendering, which makes it counter-intuitive. We plan on replacing this obsolete parser with a lexer which would allow to expectedly disregard most line breaks in BBCode text, but this is a massive undertaking that will require some time to be completed, so please bear with us.

**Comment by MrPetovan** [comment] 2019-05-31 19:38
Pushed to 2019.09 to match #4488 scope

**Comment by annando** [comment] 2019-06-01 07:50
There is an quick and easy solution to this: We simply have to remove the leading and trailing line feeds of the BBCode elements that are used for tables.

**Comment by MrPetovan** [comment] 2019-06-01 12:16
Are you going to do it this milestone?

**Comment by annando** [comment] 2019-06-01 12:46
I could. Not this weekend though. But somewhere next week.

**Comment by MrPetovan** [comment] 2019-06-01 13:06
I would prefer you focus on the current federation issues I don't master, this issue will be fixed once I implement the lexer, which may happen next milestone since I'm done with the router and 2FA.

**Comment by annando** [comment] 2019-06-01 21:14
Which federation issues?

**Comment by AlfredSK** [comment] 2019-06-01 21:49
I guess these...
https://github.com/friendica/friendica/issues?q=is%3Aopen+is%3Aissue+milestone%3A2019.06+label%3AFederation

**Comment by MrPetovan** [comment] 2019-06-01 22:17
I was thinking about these: https://github.com/friendica/friendica/issues?utf8=✓&q=is%3Aopen+is%3Aissue+milestone%3A2019.06+assignee%3Aannando+

I assigned you to issues I can't tackle myself.

**Comment by nupplaphil** [comment] 2019-06-02 09:30
Fixed with #7221

**Comment by MrPetovan** [comment] 2019-06-02 11:42
Confirmed.

**Closed by MrPetovan** 2019-06-02 11:42 UTC
Labels: Bug

**Comment by annando** [comment] 2019-06-02 19:47
@MrPetovan I can have a look at these in the next days.

**Comment by MrPetovan** [comment] 2019-06-03 03:20
Yay!
