### ISSUE TITLE
[Twitter] When replying on own post, comment isn't send to Twitter as a reply

### ISSUE THREAD

**Issue by primis** [friendica/friendica#4647] opened 2018-03-22 02:24 UTC
So, I don't know if this is a known issue (I looked for it) but if you say, post out a status, and have that status mirror posted to twitter, that works fine, but if you then go to make a reply chain (common in clarifying / extending char count on twitter) the comment will not be posted to twitter as a reply, since the instance thinks your replying to your friendica post, not the twitter one. I don't know exactly how to remedy this either.

**Comment by MrPetovan** [comment] 2018-03-22 03:57
Hi @primis, I've noticed this as well, thanks for reporting it. We are cross-posting replies to imported posts from Twitter, so I'm sure something can be done to cross-post self-replies as well.

**Comment by annando** [comment] 2018-03-22 06:31
When you are replying to a Friendica post then your comment will only go to Friendica (and Diaspora and OStatus). It won't go to Twitter. This is an intended behaviour. Everything else would lead to the situation that you are commenting with others at Friendica and all of your replies to the Friendica comments would be posted to Twitter as well.

**Comment by MrPetovan** [comment] 2018-03-22 12:48
It is a `Wont Fix` then?

**Comment by annando** [comment] 2018-03-22 14:04
It's a design decision. "won't fix" sounds so negative. For third party networks the proposed way is to comment on the copies of our own posts that get reflected back to us. (Although for Twitter our own posts are only fetched when there replies on them)

**Closed** 2018-03-22 14:20 UTC
Labels: Addons, Won't Fix
