### ISSUE TITLE
Use the actual title if set for Atom feeds

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#5627] opened 2018-08-17 08:01 UTC
If you set a title while composing a new posting, this title should be used in the Atom feeds as well instead of the generic "New posting by nickname" title that is set at the moment.

Followup to #901

**Comment by MrPetovan** [comment] 2018-12-17 03:37
I can't reproduce this, see current content of https://friendica.mrpetovan.com/feed/hypolite/

```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:thr="http://purl.org/syndication/thread/1.0" xmlns:georss="http://www.georss.org/georss" xmlns:activity="http://activitystrea.ms/spec/1.0/" xmlns:media="http://purl.org/syndication/atommedia" xmlns:poco="http://portablecontacts.net/spec/1.0" xmlns:ostatus="http://ostatus.org/schema/1.0" xmlns:statusnet="http://status.net/schema/api/1/" xmlns:mastodon="http://mastodon.social/schema/1.0">
  ...
  <entry>
    <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
    <id>https://friendica.mrpetovan.com/objects/735a2029-145c-1673-26f4-007309627884</id>
    <title>A Twitch-type encounter</title>
    <content type="html">Yesterday I was Lost in Twitchslation. #&lt;a href="https://friendica.mrpetovan.com/search?tag=videogame" class="tag" title="videogame"&gt;videogame&lt;/a&gt; &lt;a href="https://blog.mrpetovan.com/slice-of-life/twitch-type-encounter/" target="_blank"&gt;blog.mrpetovan.com/slice-of-li&amp;hellip;&lt;/a&gt;</content>
    <link rel="alternate" type="text/html" href="https://friendica.mrpetovan.com/display/735a2029-145c-1673-26f4-007309627884"/>
    <published>2018-12-16T15:45:43Z</published>
    <updated>2018-12-16T15:45:43Z</updated>
    <link rel="enclosure" href="https://blog.mrpetovan.com/wp-content/uploads/2018/12/twitch_simcopter1.jpg" type="image/jpeg" length="114808"/>
  </entry>
  <entry>
    <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
    <id>https://friendica.mrpetovan.com/objects/735a2029-275c-1421-51a9-ae4433459710</id>
    <title>New note by hypolite</title>
    <content type="html">I individually posted the Articles of the Universal Declaration of Human Rights in a thread to test #&lt;a href="https://friendica.mrpetovan.com/search?tag=Friendica" class="tag" title="Friendica"&gt;Friendica&lt;/a&gt; software and now I'm turbo-bummed because of how far we are as a species from every single article. &amp;#128542;</content>
    <link rel="alternate" type="text/html" href="https://friendica.mrpetovan.com/display/735a2029-275c-1421-51a9-ae4433459710"/>
    <published>2018-12-14T21:32:01Z</published>
    <updated>2018-12-14T21:32:01Z</updated>
  </entry>
  ...
</feed>
```

**Comment by annando** [comment] 2018-12-17 08:43
I guess I changed that behaviour some time in the past, possibly after this issue had been created and without recognizing that there had been a matching issue at all.

**Comment by MrPetovan** [comment] 2018-12-30 06:17
Closed as unable to reproduce.

**Closed by MrPetovan** 2018-12-30 06:17 UTC
Labels: Bug
