### ISSUE TITLE
Adding Diaspora contacts broken in 2023.04-1?

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13102] opened 2023-05-08 06:48 UTC
Created a new Friendica account and tried to import contacts exported from my "live" one. Seems most of them get imported, except for Diaspora* ones. Tried to manually add these contacts and failed too:

![13412908846458969242104119868029](https://user-images.githubusercontent.com/685879/236753791-3fe8e003-2ef1-400a-9657-48ead09dbd24.png)

Is adding Diaspora* contacts somehow broken at the moment? I tried several out of the handful of my Diaspora* followers and it failed for all of those. 😔

**Comment by loma-one** [comment] 2023-05-08 07:07
Found the following error. Suspect that it is related to the error.
PHP8.1, sql 10.5

```2023-05-08T06:41:02Z index [ERROR]: Pending contact doesn't have an introduction. {"exception":"Friendica\\Network\\HTTPException\\NotFoundException in /var/www/html/friendica/src/BaseRepository.php:156\nStack trace:\n#0 /var/www/html/friendica/src/Contact/Introduction/Repository/Introduction.php(57): Friendica\\BaseRepository->_selectOne()\n#1 /var/www/html/friendica/src/Contact/Introduction/Repository/Introduction.php(134): Friendica\\Contact\\Introduction\\Repository\\Introduction->selectOne()\n#2 /var/www/html/friendica/src/Model/Contact.php(1216): Friendica\\Contact\\Introduction\\Repository\\Introduction->selectForContact()\n#3 /var/www/html/friendica/src/Module/Contact.php(597): Friendica\\Model\\Contact::photoMenu()\n#4 /var/www/html/friendica/src/Module/Contact.php(332): Friendica\\Module\\Contact::getContactTemplateVars()\n#5 /var/www/html/friendica/src/BaseModule.php(244): Friendica\\Module\\Contact->content()\n#6 /var/www/html/friendica/src/App.php(700): Friendica\\BaseModule->run()\n#7 /var/www/html/friendica/index.php(52): Friendica\\App->runFrontend()\n#8 {main}\n\nNext Friendica\\Contact\\Introduction\\Exception\\IntroductionNotFoundException: There is no Introduction for the contact 3337697 in /var/www/html/friendica/src/Contact/Introduction/Repository/Introduction.php:136\nStack trace:\n#0 /var/www/html/friendica/src/Model/Contact.php(1216): Friendica\\Contact\\Introduction\\Repository\\Introduction->selectForContact()\n#1 /var/www/html/friendica/src/Module/Contact.php(597): Friendica\\Model\\Contact::photoMenu()\n#2 /var/www/html/friendica/src/Module/Contact.php(332): Friendica\\Module\\Contact::getContactTemplateVars()\n#3 /var/www/html/friendica/src/BaseModule.php(244): Friendica\\Module\\Contact->content()\n#4 /var/www/html/friendica/src/App.php(700): Friendica\\BaseModule->run()\n#5 /var/www/html/friendica/index.php(52): Friendica\\App->runFrontend()\n#6 {main}"} - {"file":"Contact.php","line":1219,"function":"photoMenu","request-id":"6458997df0dcb","uid":"571d96","process_id":535207}```

**Comment by kr428** [comment] 2023-05-08 10:54
It doesn't too seem a general problem with 2023.04-1 installations; I've seen this working well on the systems holding my fallback accounts...

**Comment by loma-one** [comment] 2023-05-20 09:23
https://github.com/friendica/friendica/issues/13136

**Comment by kr428** [comment] 2023-05-20 11:27
Interesting however: When I opened this, it seemed this combination (Tumblr, Diaspora) worked on the same version on venera.social. Are there other aspects that might matter here?

**Comment by shiribailem** [comment] 2023-05-20 13:29
There's a patch available to fix it in the addon repo that they probably applied

**Comment by MrPetovan** [comment] 2023-05-20 14:49
Closing this one as duplicate of #1316 since there's more activity over there.

**Closed as not planned by MrPetovan** 2023-05-20 14:49 UTC
Labels: Bug
