### ISSUE TITLE
Friendica Broke Photo Gallery with latest Update AGAIN.

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#12515] opened 2022-12-23 13:34 UTC

**Comment by AlfredSK** [comment] 2022-12-23 13:58
Hmm. Cannot reproduce on stable and develop.

**Comment by 4nanook** [comment] 2022-12-24 00:32
It is a problem ONLY with Vier and not Frio just like the last update.  I detest Frio, no offense it's just aesthetics and organization I don't care for.

**Comment by tobiasd** [comment] 2022-12-24 10:46
Which part is broken for you? I'm using vier and for me the gallery seems to be working as exoected.

**Comment by foss-** [comment] 2022-12-24 11:23
If something does not work for you, why not provide a screenshot pointing out the issue along with exact details of the environment you are using. From what I understand, you are looking to get this addressed? Then provide all the details available so that this can be reproduced tested against and ideally be fixed further down the road.

Out of curiosity: which aspects of frio do you dislike (am aware this is off-topic, but I am curious to hear about that).

**Comment by 4nanook** [comment] 2022-12-24 11:49
Ok I apologize, I did not realize photo gallery showed up both in the main menu and when you selected images in post.  The photos option from the main menu works in both frio and vier, but the image selection in vier inside of post does not work.  In vier it shows no images here.

My environment is I'm using Ubuntu 22.04, Apache 2.4.54 somewhat modified so that it runs with the UID of the code owner.

PHP 8.0.26 (cli) (built: Dec  3 2022 19:21:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.26, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.26, Copyright (c), by Zend Technologies

mysql  Ver 15.1 Distrib 10.6.11-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

![frio](https://user-images.githubusercontent.com/3466797/209434503-17c0564d-3de2-40c2-bcb6-f9713011a0d7.png)
![vier](https://user-images.githubusercontent.com/3466797/209434519-db901fb7-95df-4fbe-9df6-6fb721ad1282.png)

**Comment by 4nanook** [comment] 2022-12-24 11:54
With respect to what I don't like about frio, I find it excessively cluttered with a distracting amount of eye candy, I also don't like the default color scheme but I did at least find where to change that.  I prefer the way that vier is organized although if it were I, it would be less convoluted than either and I am studying the theming section and attempting to create a theme but it's a learning curve.

**Comment by tobiasd** [comment] 2022-12-24 13:36
You are correct, the image selection for a new posting from the gallery is again broken in vier.

The URL of the images that should be loaded is missing the part between the domain of the server and the image filename.

**Comment by tobiasd** [comment] 2022-12-24 13:45
Correction, the img tag is not using the domain + path at all, it just references the original filename.

**Comment by tobiasd** [comment] 2022-12-24 14:03
@4nanook are you on stable or develop? One of the parameters passed to a template has the wrong number, so if you are on stable, you would need to exchange literally one digit in the file `view/templates/media/browser.tpl` in line 36 the `"{{$f.1}}` has to be a `"{{$f.2}}`.

**Comment by MrPetovan** [comment] 2022-12-24 15:31
Fixed in https://github.com/friendica/friendica/pull/12519

**Closed as completed by MrPetovan** 2022-12-24 15:31 UTC
Labels: Bug, Theme-specific, UI

**Comment by 4nanook** [comment] 2022-12-24 21:19
I am on the develop.  Pulled the most recent from github, all good now.  Thank  you!

**Comment by gbraad** [comment] 2022-12-26 07:37
I also noticed this yesterday, as it used the filename instead of the on-disk id. Glad to have seen this fixed.
