### ISSUE TITLE
Home Notifications page is showing wrong notifications

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7776] opened 2019-10-26 19:58 UTC
### Expected behavior
When there is no new notification for my home stream the page .../notifications/home shouldn't show any entries.

### Actual behavior
When there is no new notification for my home stream the page .../notifications/home does show a lot of entries for interactions that are not related to my own content.

This doesn't happen on master but on develop. Issue is probably caused by #7775.

### Steps to reproduce the problem
When you see no notification bubble on your home icon 🏠 in the top panel go to .../notifications/home.

### Friendica version you encountered the problem
2019.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by nupplaphil** [comment] 2019-10-27 21:37
I cannot reproduce it :-( .. 
- Is there any query-string after the url (e.g. `notification/home?show=all` )?
- "not related" means notifys of other users, or content of your timeline without interacting with it?

The selection of the notifies didn't change in the PR .. just the call how and when .. strange thing

**Comment by AlfredSK** [comment] 2019-10-27 21:48
Hmm. I made two screenshots. The first is made on a node on develop, the second on a node on master.


![Screenshot_20191027-223918](https://user-images.githubusercontent.com/3656054/67642388-81412f00-f90b-11e9-8828-24670fd2aaf0.png)
mordor.social - 2019.12-dev - develop


![Screenshot_20191027-223932](https://user-images.githubusercontent.com/3656054/67642402-acc41980-f90b-11e9-88f3-b14675ae9419.png)
venera.social - 2019.09 - master

**Comment by nupplaphil** [comment] 2019-10-27 21:58
Ha.. now I got it on my dev-node too .. thx for the screenshots!

**Comment by nupplaphil** [comment] 2019-10-27 22:36
@annando could this issue be related to ACLs? I don't think, this bug is a regression of #7775 , because the selection doesn't change. I believe it's more related to https://github.com/friendica/friendica/pull/7765/files#diff-bad4f750df47fac3629847af7c335b1bR10 , because it seems like the notifies are based on wrong stored items too :-( ..

**Comment by nupplaphil** [comment] 2019-10-27 23:04
Should be fixed with #7780

**Closed** 2019-10-27 23:48 UTC
Labels: Bug
