### ISSUE TITLE
Hide, not only collapse, posts based on language

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#10052] opened 2021-03-17 15:40 UTC
I see a lot of "collapsed" posts since on Friendica there are many great german minds haha, that post in both english and german, and it is confusing for me who only knows english. Same is true for the global community that is filled with collapsed posts. Would really help if we can enable so that such posts based on language, will be hidden altogether. This way users can see more relevant content.

**Comment by MrPetovan** [comment] 2021-04-21 20:21
Thank you for the suggestion, #10136 is a duplicate of it but there is more conversation over there, closing here.

**Closed as completed by MrPetovan** 2021-04-21 20:21 UTC
Labels: New Feature
