### ISSUE TITLE
Image Upload not uploading image with large file size, unhelpful error message

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12166] opened 2022-11-12 14:43 UTC
Tried uploading a 2,3 MB image and received the info `Invalid Request`. Reduced image size to > 1MB and upload worked fine.

If there is such a restriction, tweaking the error message should help users understand, why the upload is failing. Currently it is hard to understand what is going wrong.

![1](https://user-images.githubusercontent.com/5708172/201479482-6880afd2-214b-4ab0-baaf-adbb98338846.png)

**Comment by AlfredSK** [comment] 2022-11-12 14:47
There are multiple possibilities. :-) The first one I'd check is the max image size in the admin panel. The second one (2MB sounds very suspicious) is the max upload size in you server's PHP configuration.

**Comment by foss-** [comment] 2022-11-12 14:50
This issue is less about how this specific problem can be resolved for admins, but rather how such situations can a) be prevented in the first place and b) if they happen, how users can be better informed as to what is going wrong so they can change image properties to manage a successful upload.

**Comment by MrPetovan** [comment] 2022-11-18 21:06
Duplicate of https://github.com/friendica/friendica/issues/7807

**Closed as not planned by MrPetovan** 2022-11-18 21:06 UTC
Labels: Bug
