### ISSUE TITLE
followers_count and friends_count are always 0 in users/show.json

### ISSUE THREAD

**Issue by Rudloff** [friendica/friendica#4072] opened 2017-12-15 22:39 UTC
Hello,
When displaying a user in Twidere, it calls the API like this: https://social.rudloff.pro/api/users/show.json?include_blocking=true&user_id=13&include_blocked_by=true.
Most of the info is OK but the `followers_count` and `friends_count` keys always have a value of `0` (even for my own profile).

**Comment by MrPetovan** [comment] 2017-12-16 03:31
Same issue as #4069, passing `user_id` to API calls only queries public information about this user, however followers and friends are treated as private info. Try removing the `user_id` parameter.

**Comment by annando** [comment] 2017-12-16 08:16
@MrPetovan since Twidere is doing so, we possibly should change the behaviour so that we accept our own user id?

**Comment by Rudloff** [comment] 2017-12-16 11:02
Also, as I said in #4069 my friends count is displayed publicly on [my profile](https://social.rudloff.pro/profile/rudloff) so I'm not sure why the API should not return it.
(And for Mastodon users, it is also a public information.)

**Comment by MrPetovan** [comment] 2017-12-16 14:29
I agree this should be public information, but I'm always weary about changing anything about the API since I don't know how many external systems are using it under the present form.

We need a versioning system for each method so that we won't break an unspecified amount of third-parties whenever we make a change.

> @MrPetovan since Twidere is doing so, we possibly should change the behaviour so that we accept our own user id?

This for example touches many parts of the API, the `user_id` parameter is processed in `api_get_user()` which is used 46 times in the API. I would like to know first how Twidere got this specific `user_id`.

**Comment by Rudloff** [comment] 2017-12-16 14:35
Twidere seems to get the user_id by calling `api/account/verify_credentials.json`.

**Comment by annando** [comment] 2017-12-16 17:36
@MrPetovan sounds like you want to rework the API functions ;-)

**Comment by MrPetovan** [comment] 2017-12-16 19:03
I want to put all methods in Controller classes indeed! For the rest, it's more a matter of philosophy, should the list of followers be public? Should the list of mutual friends be public? Should the list of followed be public? I know it is on Twitter, but should it be the same on Friendica?

**Comment by MrPetovan** [comment] 2017-12-16 19:51
Reopening for further discussion.

**Comment by annando** [comment] 2017-12-17 09:16
We should reproduce via API what is accessible via the web frontend. Means: On the contacts you have a link for "allfriends", which tells you something similar. So for your own contact you could return your data, but for every other contact you could do the same like ```mod/allfriends.php``` is doing.

**Comment by MrPetovan** [comment] 2022-07-24 18:24
Marked as closed by Marco R.

**Closed by MrPetovan** 2022-07-24 18:24 UTC
Labels: Sup­port Request, API
