### ISSUE TITLE
@structure gets lost / is changed, when editing post

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#3061] opened 2017-01-02 14:17 UTC
**Problem**

After editing a post done in a forum group, the group was no longer mentioned / linked in that post, after the post was edited.

**Reproduce**

1. Join the Friendica Developers forum here http://helpers.pyxis.uberspace.de/profile/developers
1. write a new post to that forum. any new post to such a group will always include the following: @developers+89250 that string translates to a tag which is added to the post and links to that forum group. it looks like this in frio:
![tag](https://cloud.githubusercontent.com/assets/5708172/21590663/2c6a7fd2-d0fe-11e6-9f4d-226f5c5fc8ca.jpg)
1. edit post

**Currently**

The tag is gone and @developers+89250 is changed to @Friendica Developers which then does not get translated to a tag. The consequence being, that the post is no longer showing for the forum group in question.
![tag_gone](https://cloud.githubusercontent.com/assets/5708172/21590718/78d3402a-d0fe-11e6-820e-ec9cf299e04c.jpg)

**Expected**

Such tags should never be changed when editing a post.

**Comment by fabrixxm** [comment] 2017-01-02 14:32
duplicate of #2880

**Closed by fabrixxm** 2017-01-02 14:32 UTC
