### ISSUE TITLE
don't open another browser tab when deleting a contact

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#1986] opened 2015-10-25 21:40 UTC
### Workflow

* Username > Contacts
* select a contact and delete contact

### Currently

* a new browser tab will open with a dialog requesting confirmation of the deletion
* confirm
* contacts list is reloaded

→ user ends up with two tabs with his contacts

### Expected

This action should not trigger another tab. It is confusing and superfluous. Opening a new tab might be useful when "show profile" is selected because the user may find themselves on a whole different website. but for deleting a contact this should happen in a single tab.

**Comment by silke** [comment] 2015-11-07 16:28
I cannot reproduce this behaviour, neither on my real server nor in the test instance. @foss- could it be a browser setting of yours that enforces it?

**Comment by fabrixxm** [comment] 2015-11-07 19:30
Should be fixed in develop branch.

**Closed by fabrixxm** 2015-11-07 19:30 UTC
Labels: UX

**Comment by foss-** [comment] 2015-11-07 19:48
Great stuff (:
Are you guys having the meetup atm? Anyhow, thanks for fixing and contributing code <3
