### ISSUE TITLE
mouse cursor should be active in the share section of a new post, after user click the new post icon in frio

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#3101] opened 2017-01-21 21:12 UTC
Probably theme related I'd guess. When clicking the button for a new post, well the new post editing view opens up. But there is no active cursor so users cannot type away their post and hit enter to post. But need to leave the keyboard, find their mouse, click into the "share" section of the create post UI and only then can they type away.

I understand this is a minor and priority is low(est). But I still thought I'd file it. It's the details that matter (:

**Comment by Hypolite** [comment] 2017-01-22 11:22
Hi @foss- , your request would make more sense if you accessed the new post editing view via a keyboard stroke, but you said you clicked on it? I agree this could be slighty improved by having the editing field pre-focused, but you already had the hand on your mouse anyway 😉

**Comment by foss-** [comment] 2017-01-22 13:07
If there is a keyboard shortcut for new posts I am happy to adapt. So far I was unaware.

**Comment by Hypolite** [comment] 2017-01-22 13:45
I'm also unaware if there are any keyboard shortcuts at all. With the frio theme, this request befalls to @rabuzarus.

**Comment by foss-** [comment] 2017-01-22 13:49
What I was trying to says was, the fact that new posts can currently not be triggered via keyboard, does not mean, this is not a valid request.

There's a reason why the cursor is right in the search field ready for users to type away, when visiting https://duckduckgo.com/, right?

**Comment by Hypolite** [comment] 2017-01-22 13:52
Sorry, I didn't mean to dismiss your request entirely, just point out that your use case was slightly inaccurate since we don't seem to have keyboard shortcuts at the moment.

**Comment by foss-** [comment] 2017-01-22 14:00
No offense taken. However you turn it, moving to a more usable UI is always a good idea and it's such details that make a service great in the end. Since I am not a coding person, I have no idea how hard this is to implement, but I'd assume it's do-able.

**Comment by Hypolite** [comment] 2017-01-22 14:01
I assure you it's trivial, and I'll probably submit a PR towards it in the next hours.

**Comment by Hypolite** [comment] 2017-01-22 16:04
@foss- There you are! 😎

**Comment by Hypolite** [comment] 2017-01-23 17:15
Can you pull the latest version of `develop` and confirm it works as you expected?

**Comment by annando** [comment] 2017-01-23 22:12
He's on my server. But since I'm currently fighting with my new router, I hadn't got time to update it.

**Comment by AlfredSK** [comment] 2017-01-23 22:38
On my phone the cursor is active in the *title* field now and the keyboard is launched automatically. Instant typing is possible. Now we have to decide if the title field is the most convenient place to start typing. :-)
Also, I'm too tired to fire up my laptop and test this on a bigger screen.

**Comment by rabuzarus** [comment] 2017-01-23 23:04
On mobile I don't think the keyboard should be opened automatically (without pressing on an input field). On my phone the keyboard takes half of the screen.

Also auto focusing the title field seems to me a bad UX when you want to edit or share a post

**Comment by foss-** [comment] 2017-01-24 09:12
This request was and is about having auto focus in the share field (not the title). The title option is a speciality of the federated social networks and not used that much. Confirming the auto-focus is indeed title now. I should have made that much clearer in the original request.

@rabuzarus Why do you think this behavior is a bad idea on mobile? I understand keyboards take up a lot of screen estate on mobile, but if a user clicks on "new post" they want to create a new post, no? So why is showing the keyboard a bad idea for that scenario on mobile?

**Comment by rabuzarus** [comment] 2017-01-24 12:55
@foss- 
Yes they want to create a new post. But a new post doesn't automatically mean 'writing a post'. Maybe they just want to insert images/audio/attachment links through the jot buttons

**Comment by Hypolite** [comment] 2017-01-24 15:09
@foss- The problem is the JOT is used for many a thing, not just for post writing, see the calendar for example. That's why I kept the feature as simple as possible.

Besides, focusing the second input field seems confusing to me. The important part for me is to be able to jump on the keyboard after the "Write Post/Add Event" button is clicked/tapped, and the content field is just a tab away.

About the keyboard showing up, it is a design decision from the mobile browser not to show up the keyboard when a field is focused on a non-user event (ready, load, etc...) while they show it for user-initiated interaction like click.

I'd like to have more user input before I change anything to this PR.

**Comment by MrPetovan** [comment] 2018-10-14 16:37
Closing after more than 1 year.

**Closed by MrPetovan** 2018-10-14 16:37 UTC
Labels: New Feature, UX
