### ISSUE TITLE
Can't manage other accounts

### ISSUE THREAD

**Issue by gitkald** [friendica/friendica#1241] opened 2014-12-08 08:34 UTC
If i try to manage an forum account, to post in the name of it, friendica switches automaticaly back to my orignal account. So it's impossible to post in the name of the forum account.

If I wrote to slow, the browser refreshes the site and after that, I post under my personal account. Have anyone the same problem?

**Comment by silke** [comment] 2015-01-09 15:23
Well - on the other hand I keep seeing a person's posts as posts from a forum account. (tugelblend's to be precise.) Sounds different, but there might be issues with switching.

**Comment by Beanow** [comment] 2015-01-24 20:32
Unable to reproduce here as well. @gitkald can you tell us the precise steps you're taking?

**Comment by tobiasd** [comment] 2015-01-31 18:57
I've tested this now a bit but had no problems (version 3.3.3rc here)

**Comment by AlfredSK** [comment] 2018-10-03 14:08
@gitkald Is this still an issue? Cannot reproduce. Can we close this?

**Comment by annando** [comment] 2018-10-03 16:04
I guess we can close this. @AlfredSK thanks for digging this out ;-)

**Closed** 2018-10-04 12:03 UTC
