### ISSUE TITLE
Cron Warnings

### ISSUE THREAD

**Issue by miqrogroove** [friendica/friendica#6087] opened 2018-11-06 11:54 UTC
`PHP Warning:  constant(): Couldn't find constant  in /src/Protocol/PortableContact.php on line 1376`

**Comment by MrPetovan** [comment] 2018-11-06 13:33
Duplicate of https://github.com/friendica/friendica/issues/5911#issuecomment-436101442
Fixed by #6086

**Comment by miqrogroove** [comment] 2018-11-06 20:58
I will try this patch.  I've only seen the error one time though.

**Comment by MrPetovan** [comment] 2018-11-06 21:02
It depends on whether remote nodes running on develop have updated to the faulty version and how fast they have updated to the subsequent fix.

**Comment by miqrogroove** [comment] 2018-11-09 00:40
For the 2018.09 branch it is also necessary to add `use Friendica\Core\Logger;` with the patch.  Going to try this over again.

**Comment by miqrogroove** [comment] 2018-11-09 00:52
Nope.  Patch failed again.  Going to remove your call to `Logger::log()` and see if that works.

**Comment by MrPetovan** [comment] 2018-11-09 15:01
Which patch? Which Logger call?

**Comment by tobiasd** [comment] 2019-01-05 18:18
This adding `use Friendica\Core\Logger` maybe?

**Comment by MrPetovan** [comment] 2019-01-07 04:07
This issue will be permanently fixed with #6336

**Comment by MrPetovan** [comment] 2019-01-27 22:34
Closed via #6336

**Closed by MrPetovan** 2019-01-27 22:34 UTC
Labels: Bug, Needs More Info
