### ISSUE TITLE
Cron (Worker) Error

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#5330] opened 2018-07-07 14:08 UTC
`Undefined index: process in /home/users/zsemberi/www/friendica/include/dba.php on line 1112`

Friendica 'The Tazmans Flax-lily' 2018.08-dev - 1275

CPU | Common KVM processor \| Kerne: 4
Betriebssystem | Ubuntu 18.04 (64-Bit)
Kernel | 4.15.0-24-generic
Webserver | Apache/2.4.29 (Ubuntu)
PHP-Version | 7.2.7-0ubuntu0.18.04.2
Datenbank-Version | 5.5.5-10.1.29-MariaDB-6
FTP-Server | ProFTPD 1.3.5e
Datenbank-Administration | phpMyAdmin 4.8.0.1

**Comment by copiis** [comment] 2018-07-07 14:18
`PHP Notice:  Undefined variable: _SESSION in /home/users/zsemberi/www/friendica/boot.php on line 891`

**Comment by copiis** [comment] 2018-07-08 05:13
PHP Notice:  Undefined property: stdClass::$items in /home/users/zsemberi/www/friendica/addon/fromgplus/fromgplus.php on line 458
PHP Notice:  Undefined variable: plugin in /home/users/zsemberi/www/friendica/addon/pumpio/pumpio.php on line 658
PHP Notice:  Undefined property: stdClass::$items in /home/users/zsemberi/www/friendica/addon/fromgplus/fromgplus.php on line 458
PHP Notice:  Undefined property: stdClass::$items in /home/users/zsemberi/www/friendica/addon/fromgplus/fromgplus.php on line 458

**Comment by copiis** [comment] 2018-07-08 12:30
PHP Notice:  Undefined offset: 1 in /home/users/zsemberi/www/friendica/addon/twitter/twitter.php on line 1770
PHP Notice:  Undefined index: after in /home/users/zsemberi/www/friendica/src/Model/ItemContent.php on line 96
PHP Notice:  Undefined variable: _SESSION in /home/users/zsemberi/www/friendica/boot.php on line 891
PHP Notice:  Undefined variable: _SESSION in /home/users/zsemberi/www/friendica/boot.php on line 891
PHP Notice:  Undefined property: stdClass::$errors in /home/users/zsemberi/www/friendica/addon/twitter/twitter.php on line 608

**Comment by tobiasd** [comment] 2018-07-12 09:10
Calling the worker manually in the Vagrant VM (current develop) I get a couple of

    Notice: Undefined index: guid in /vagrant/src/Network/Probe.php on line 1145

On  the admin panel, user management I see a couple of

    Notice: Undefined index: page_flags_raw in /vagrant/mod/admin.php on line 1783

and on the user settings page I get

    Notice: Undefined index: public in /vagrant/mod/settings.php on line 1158

**Comment by annando** [comment] 2018-07-12 18:01
Yeah, we haven't got rid of all places.

**Comment by tobiasd** [comment] 2018-07-19 07:32
Fount another one

> PHP Notice:  Undefined property: stdClass::$parts in src/Protocol/Email.php on line 107

and

> PHP Notice:  Undefined offset: 3 in src/Protocol/Email.php on line 474
> PHP Notice:  Undefined offset: 1 in src/Protocol/Email.php on line 506
> PHP Notice:  Undefined offset: 1 in src/App.php on line 1070

**Comment by copiis** [comment] 2018-07-21 12:14
PHP Notice:  getimagesizefromstring(): Read error! in /home/users/zsemberi/www/friendica/src/Object/Image.php on line 789

**Comment by annando** [comment] 2018-08-10 05:35
Isn't this a duplicate of https://github.com/friendica/friendica/issues/5470?

**Comment by MrPetovan** [comment] 2018-08-11 21:06
Duplicate of #5470

**Closed by MrPetovan** 2018-08-11 21:06 UTC
Labels: Bug
