### ISSUE TITLE
Vier Theme: Logo will be scaled to wrong height

### ISSUE THREAD

**Issue by tugelbend** [friendica/friendica#1081] opened 2014-08-23 13:16 UTC
The vier theme scales images to the wrong height value. 

Example can be seen on snarl.de where the logo should be 32px \* 32px but instead is scaled to 32px \* 22px

The responsible entry in the styles.css is:

header #banner #logo-img {
    height: 22px;
    margin-top: 5px;
}

**Comment by tobiasd** [comment] 2016-02-23 07:14
with the recent changes on the view theme, is this still an issue?

**Comment by vinzv** [comment] 2019-08-19 23:03
I can't reproduce the problem. Let's close this issue.

**Comment by annando** [comment] 2019-08-20 03:58
If it's not reproducible then we can.

**Comment by MrPetovan** [comment] 2019-08-20 04:38
Cloclosingsing

**Closed by MrPetovan** 2019-08-20 04:38 UTC
Labels: UI/Theme
