### ISSUE TITLE
Import and export RSS feeds via OPML file

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#14124] opened 2024-04-30 22:06 UTC
I would like to suggest implementing the possibility to import and export RSS feeds via OPML file. Currently, each feed has to be imported or exported individually, which is very time-consuming and ultimately unnecessary.

**Comment by tobiasd** [comment] 2024-05-01 15:59
OPML export can be done via an [addon](https://git.friendi.ca/friendica/friendica-addons/src/branch/develop/opmlexport) that the admin of the Friendica instance needs to activate.

Not sure about the importing extend of #13095 @annando should know.

**Comment by ghost** [comment] 2024-05-01 16:24
@annando is currently on holiday. I will wait until he is back from holiday. He will certainly comment on this then.

**Comment by csolisr** [comment] 2024-05-10 14:17
Importing RSS feeds is already tracked by #13854 by the way. Do we close that one or this one as the duplicate?

**Comment by ghost** [comment] 2024-05-10 14:47
I would like to wait until @annando has commented on this. I'm already in contact with him about this.
And I don't understand the other discussions on the same topic - I'm "only" a simple user.

**Comment by MrPetovan** [comment] 2024-05-10 15:28
This present issue indeed is a duplicate of #13854 , please discuss the new feature over there.

**Closed as not planned by MrPetovan** 2024-05-10 15:28 UTC
Labels: New Feature

**Comment by ghost** [comment] 2024-05-11 15:00
Unfortunately, I can no longer follow: Can I continue to discuss and ask about the matter here or in #13854 or elsewhere? I'm asking because I'm new here.

**Comment by MrPetovan** [comment] 2024-05-11 22:06
It's okay! I closed this present issue as a duplicate, if you have additional information to provide towards the OPML import, please do so in https://github.com/friendica/friendica/issues/13854 that has seniority.

**Comment by ghost** [comment] 2024-06-25 19:48
I can somehow understand why nobody wants to discuss this topic (OPML export). 
In other words: Could the administrator of an instance offer this add-on on request? That would make the work involved much easier: there is a difference between being able to use an OPML file and having to enter each individual feed individually.
