### ISSUE TITLE
After server reboot, no messages displayed and now only posts since reboot are displaying.

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#10744] opened 2021-09-22 06:57 UTC
- [ ] I have searched open and closed issues for duplicates

### Bug Description
After server reboot, no messages displayed and now only posts since reboot are displaying.

I have had this issue before where it would not show old messages, more recently a pattern has emerged where this mostly happens after a server reboot.  I am not seeing errors in my mysql logs but am seeing tons of errors in the friendica.log so I have no idea what is actually relevant.  This is happening whether or not infinite scroll is enabled.

### Steps to Reproduce

1.  step one
2.  step two
3.  step three
This is not 100% reproducible but when it happens it tends to happen after a server reboot.
This has happened in the past but in the past only happened with infinite scroll.  Now it does not matter, on or off still
won't scroll past the point where the server was rebooted.

Actual Result:

Initially after reboot no messages were displayed in the global view, the local and home views are still normal.

Expected Result:

Expect to be able to scroll back a gazillion messages.
### Platform Info

Friendica Version:

This is Friendica, version 2021.09-dev that is running at the web location https://friendica.eskimo.com. The database version is 1434/1434, the post update version is 1427/1427.
Friendica Source: 
Github
PHP version:
PHP 7.4.23 (cli) (built: Aug 26 2021 15:51:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.23, Copyright (c), by Zend Technologies

SQL version:
Server version: 10.5.12-MariaDB-1:10.5.12+maria~focal-log mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

**Comment by 4nanook** [comment] 2021-09-22 09:35
After being up for about two hours, the old posts magically reappeared.

**Comment by MrPetovan** [comment] 2021-09-22 11:55
Glad to hear it, closing here.

**Closed as completed by MrPetovan** 2021-09-22 11:55 UTC
Labels: Bug

**Comment by 4nanook** [comment] 2021-09-22 15:21
I was kind of hoping whatever was wrong with the code that causes this ill behavior might get addressed.

**Comment by MrPetovan** [comment] 2021-09-22 16:10
Without a reliable way of reproducing this issue and since it includes an inconvenient hardware step, it is unlikely we'll be able to troubleshoot this, and the fact it restored the posts on its own makes it low severity in general. It would be a high cost, low gain potential bug to track and possibly fix, and we can't really afford chasing these.
