### ISSUE TITLE
Pinned posts functionality request

### ISSUE THREAD

**Issue by PerigGouanvic** [friendica/friendica#4828] opened 2018-04-13 05:01 UTC
Pinned posts have the advantages,

- for user accounts, to properly inform newcomers of the general feeling and things that are important to the user (and prevents the newcomer from being misled by the last couple of posts), and can also serve as a kind of homepage, with links, etc.

- for forum accounts, they are useful to detail the rules, important discussions, etc., and in particular, for the Newhere forum and the Support forum, they are an excellent place to inform people of what's already been discussed and of the most helpful posts and pages.

I believe that several people would enjoy the pinned post functionality as a way to craft rich content once in a while. 

Right now, the profile page serves the purpose of a pinned post, but is of course much more limited.

**Comment by MrPetovan** [comment] 2020-03-28 03:54
Duplicate of #4077
Closed by #7823

**Closed by MrPetovan** 2020-03-28 03:54 UTC
Labels: New Feature, Theme-specific
