### ISSUE TITLE
Peertube post formatting

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#9985] opened 2021-03-05 12:06 UTC
Posts from peertube don't reflect the format they have on the original source. This should be fixed.

## A post that looks on peertube like this

![00_temp01](https://user-images.githubusercontent.com/24474762/110113377-51355600-7db3-11eb-9caf-bc23942499e8.jpg)
Source: https://mytube.madzel.de/videos/watch/8841971c-cd14-4372-bff3-dc52f98b4577

## In Friendica it looks like this
![00_temp00](https://user-images.githubusercontent.com/24474762/110113459-6c07ca80-7db3-11eb-8e73-fb0d3045d3e9.jpg)
Source: https://horche.demkontinuum.de/display/8841971c-cd14-4372-bff3-dc52f98b4577

### Platform Info
Friendica Version:  2021.03-rc
Friendica Source: git
PHP version: 7.4
SQL version: mariadb latest

**Comment by annando** [comment] 2021-03-05 14:43
I guess that it is the same as issue https://github.com/friendica/friendica/issues/9912

I will try to have a look at it the next days.

**Comment by MrPetovan** [comment] 2021-03-05 15:02
It is indeed a duplicate of #9912, closing this one in favor of the earlier one.

**Closed as completed by MrPetovan** 2021-03-05 15:02 UTC
Labels: Bug

**Comment by hoergen** [comment] 2021-03-05 18:06
Thanks didn't see that :+1:
