### ISSUE TITLE
Introductions inaccessible

### ISSUE THREAD

**Issue by rebeka-catalina** [friendica/friendica#6864] opened 2019-03-12 08:59 UTC
### Expected behavior
A click on a introduction's notification should bring me to the introduction so that I can react to it.

### Actual behavior
Notifications are displayed, but the introductions are empty

### Steps to reproduce the problem
Receive a contact request by somebody and click on the notification

### Friendica version you encountered the problem
commit c567328ab22c9a6eac5236058ff7b73274cff3ca

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
git

### PHP version
PHP 7.2.14

### SQL version
mysql  Ver 15.1 Distrib 10.1.37-MariaDB

**Comment by tobiasd** [comment] 2019-03-12 09:17
It is working on the 2019.03-RC branch, this is a reminder to check it after the release in the development branch.

**Comment by MrPetovan** [comment] 2019-03-25 15:57
Closing here as a duplicate of #6936 since there's more details in the newer issue.

**Closed by MrPetovan** 2019-03-25 15:57 UTC
Labels: Bug
