### ISSUE TITLE
theme > frio: unread posts bubble not showing number of unread posts

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#14054] opened 2024-03-29 09:32 UTC
### Bug Description

unread posts bubble not showing number of unread posts

### Steps to Reproduce

Unsure. Maybe if the number of unread posts goes over 999, the bubble is unable to show the correct number?

Actual Result:

The bubble for unread posts is very small and does not show any number at all:
<img width="139" alt="1" src="https://github.com/friendica/friendica/assets/5708172/2307116f-0ebc-4a52-94a4-a79832f45d84">

Expected Result:

It would be nice to allow showing 4 digit numbers of unread posts. And if then the number of unread posts goes over 9999 it would be nice to show 9999+

### Platform Info

This is Friendica, version 2024.06-dev that is running at the web location https://pirati.ca. The database version is 1559/1559, the post update version is 1550/1550.

**Comment by annando** [comment] 2024-03-29 10:26
Please perform a forced reload on your system. The JS has changed.

**Comment by foss-** [comment] 2024-03-29 13:03
Clearing cache resolves the issues, thanks.

**Comment by foss-** [comment] 2024-03-29 15:08
Spoke too soon. Issue is back.

**Comment by MrPetovan** [comment] 2024-03-30 02:54
Duplicate of #14049

**Closed as not planned by MrPetovan** 2024-03-30 02:54 UTC
Labels: Bug
