### ISSUE TITLE
Endless scroll with frost-mobile doesn't work

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#1482] opened 2015-04-05 21:03 UTC
If endless scroll is enabled the pagination buttons in frost-mobile theme are disappearing. Looks like only the network page is affected.

**Comment by ddorian1** [comment] 2015-04-06 15:01
Actually this was intended by my patch a while ago, since I considered them useless and even confusing when endless scrolling is enabled. (Only the network page is affected because endless scrolling only works there atm)

**Comment by AlfredSK** [comment] 2015-04-06 15:51
Okay. Then the hiding of the buttons is fine, but the endless scrolling with frost-mobile does not work nonetheless.

**Comment by annando** [comment] 2015-04-08 06:33
@AlfredSK Could you test it again?

**Comment by AlfredSK** [comment] 2015-04-08 08:29
Hmm. I'm on the master branch. But I'll try to test it...

**Comment by AlfredSK** [comment] 2015-04-08 08:37
Test passed. Infinite scrolling is working with this fix.

**Comment by annando** [comment] 2015-04-08 12:38
Okay. Then I'm closing the issue.

**Closed by annando** 2015-04-08 12:38 UTC
