### ISSUE TITLE
Umlaut containing links will not be recognized

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#2487] opened 2016-04-27 18:00 UTC
A link such as https://friendica.wäckerlin.ch/friendica is not correctly recognized, it will show up as a link up to https://friendica.w and from there on as normal text. 

See in the thread here: https://friendica.wäckerlin.ch/display/51a50594105720f23c0cb2c239587447

**Comment by annando** [comment] 2016-04-28 16:57
Any help from someone who isn't in a steady fight with regular expressions could help :)

**Comment by silke** [comment] 2016-05-04 18:36
I think Friendica has to interpret idn domains correctly, similar to:
```
idn friendica.wäckerlin.ch
friendica.xn--wckerlin-0za.ch
```
From what I read here http://php.net/manual/en/ref.intl.idn.php php-intl should be able to handle it.

**Comment by annando** [comment] 2016-05-05 15:03
The idn extension will help, once that we know the complete url. But when someone just posts an url without using the "url" element, then the system has to detect the url in the content. For this we need a better regular expression.

**Comment by Hypolite** [comment] 2016-11-22 13:18
After closing #2964 I'm assigning myself this issue.

**Comment by MrPetovan** [comment] 2018-02-07 17:36
Reopening as the fixing code has been reverted.

**Comment by MrPetovan** [comment] 2018-02-07 17:37
Possibly related: Display issue in this post: https://friendica.mrpetovan.com/display/0c40ea67635a7b332cce3be770120356

**Comment by annando** [comment] 2018-02-07 20:12
That link looks more like some old "develop" branch.

**Comment by MrPetovan** [comment] 2018-02-07 20:14
And yet it's brand new.

**Comment by annando** [comment] 2018-02-07 20:33
Grmbl ... We will need a long test phase ...

**Comment by MrPetovan** [comment] 2018-02-07 20:35
Using autolink is always risky when combined with any other text formatting.

**Comment by annando** [comment] 2018-02-07 20:39
But hadn't we reverted this?

**Comment by MrPetovan** [comment] 2018-02-07 20:40
Yes, you did it personally, but this doesn't mean there wasn't an issue with the kind of post I submitted in the first place!

**Comment by MrPetovan** [comment] 2018-02-07 23:48
I forgot I opened #4295, closing here.

**Comment by MrPetovan** [comment] 2018-03-11 12:51
Actually, this still isn't fixed, see #4308

**Comment by annando** [comment] 2018-08-07 19:43
Couldn't we just define that people should use BBCode for specifying a link when it contains some special characters?

**Comment by MrPetovan** [comment] 2018-08-07 20:52
No, because we do have this autolink feature, and it should work as expected or be removed, even temporarily.

**Comment by annando** [comment] 2018-08-10 05:51
I prefer some "mostly works" before some "never works".

**Comment by MrPetovan** [comment] 2018-08-11 20:32
The problem is when the "mostly" refers to the number of characters of a given URL, not about specific whole cases. A quick workaround would be to prevent autolink when a special character right-bounds it. This way no wrong URL would be shown, only text when we can't insure it's a proper URL link.

**Comment by MrPetovan** [comment] 2019-03-09 03:44
I found this article about coming up with the best autolinker regular expression possible, I'm going to try it out on my server in the next few days,

**Comment by MrPetovan** [comment] 2019-03-09 04:30
URL I successfully tested the autolinker with that was tripping the previous version:
- https://de.wikipedia.org/wiki/Juha_Sipilä
- https://de.wikipedia.org/wiki/Dnepr_(Motorradmarke)
- https://friendica.wäckerlin.ch/friendica
- https://mastodon.social/@morevnaproject

**Closed** 2019-03-09 08:16 UTC
Labels: Bug

**Comment by nupplaphil** [comment] 2019-03-09 13:23
fixed by #6835
