### ISSUE TITLE
searching or adding peertube account fails

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#10623] opened 2021-08-23 11:56 UTC
- [x] I have searched open and closed issues for duplicates

### Bug Description

Searching for peertube-channels in acutal devel branch gives me no result for mobilsicher@peertube.mobilsicher.de and gives a result for eisenbahn@kino.schuerz.at

Trying to follow eisenbahn@kino.schuerz.at gives me this error
```Der Netzwerktyp wurde nicht erkannt. Der Kontakt kann nicht hinzugefügt werden.
Die angegebene Profiladresse liefert unzureichende Informationen.
Es wurden keine kompatiblen Kommunikationsprotokolle oder Feeds gefunden.
Der Netzwerktyp wurde nicht erkannt. Der Kontakt kann nicht hinzugefügt werden.
[ close all ]

```
But just before with stable i could add exactely this peertube-channel.

### Steps to Reproduce

1.  search for mobilsicher@peertube.mobilsicher.de -> no result
2.  search for @mobilsicher@peertube.mobilsicher.de -> no result
3.  search for eisenbahn@kino.schuerz.at -> result
4. press "Follow" -> see the error from above

Expected Result:

I want to find peertube-accounts/Channels and i want to add them.

### Screenshots

Found result:
![image](https://user-images.githubusercontent.com/5894829/130442854-66046d52-16bf-4c87-97a3-9cb12530cfa7.png)

Tried to follow
![image](https://user-images.githubusercontent.com/5894829/130442910-1d1225d8-8f16-448b-807b-51ae33542505.png)

Get no result:
![image](https://user-images.githubusercontent.com/5894829/130442969-8c3c8d0b-0335-4f8b-bc68-b45a0d2697af.png)

### Platform Info

Friendica Version: 2021.09-dev

Friendica Source: 

PHP version: 7.4

SQL version: mariadb 10.3

**Comment by xundeenergie** [comment] 2021-08-23 14:29
this works in stable

**Comment by annando** [comment] 2021-08-23 19:20
This is related to the other issues you created. There is currently an issue in the probing mechanism that had been introduced by PR https://github.com/friendica/friendica/pull/10619

**Comment by MrPetovan** [comment] 2021-08-24 15:44
Duplicate of #10625, closing

**Closed as completed by MrPetovan** 2021-08-24 15:44 UTC
Labels: Bug
