### ISSUE TITLE
Add support for right-to-left text directionality

### ISSUE THREAD

**Issue by omerori** [friendica/friendica#8262] opened 2020-02-09 17:01 UTC
Add support for posting RTL texts in languages such as Arabic and Hebrew.

Please report any incorrect display in this issue.

**Comment by annando** [comment] 2020-02-09 17:15
Can you provide what exactly has to be done? What happens when you enter Hebrew or Arabic content in Friendica?

**Comment by tobiasd** [comment] 2020-02-10 05:46
[Here](https://codex.wordpress.org/Right_to_Left_Language_Support) is some guide for styling Wordpress, but the actions taken are not WP specific.

**Comment by ahangarha** [comment] 2020-08-11 03:54
I have a suggestion. You just add `dir="auto"` to any element which can potentially contain RTL or LTR text. It makes the browser define direction of the content based on first character. I have used this on different projects and it works perfectly. I assume gitlab also does the same thing for handling its markdown in issues, MR, etc.

I have a firefox addon called [add bidi support](https://addons.mozilla.org/en-US/firefox/addon/add-bidi-support/) which applies this attribute to almost all elements. It is not supposed to work perfectly in all circumstances (due to different architecture of html in different websites, but it demonstrate how this approach would work.

I am not sure if I can do this on friendica as I have not seen the source code. So let me know if you can do it or not.

**Comment by ahangarha** [comment] 2020-08-11 03:58
> [Here](https://codex.wordpress.org/Right_to_Left_Language_Support) is some guide for styling Wordpress, but the actions taken are not WP specific.

This doesn't bring support for bidirectional text. This enforces RTL direction which would be problematic if you want to see LTR text. So this is not solution. On social media, we are dealing with situation in which people with different languages want to interact with each other. So the platform should be able to handle both RTL and LTR at the same time. It would be fine if the overall direction of page be either of LTR or RTL (perhaps based on selected interface language) but it shouldn't lead to wrong direction for individual texts. RTL should be seen RTL and LTR should be seen LTR.

**Comment by annando** [comment] 2020-08-11 04:16
Thanks for the hint with `dir="auto"`. This would need to be added to the appropriate template files.

**Comment by ahangarha** [comment] 2020-08-11 05:11
I am not sure about one thing. This approach also works in some scenarios. Just add these stylesheets:

``` css
.wall-item-body, .wall-item-body *, .media-heading {
  unicode-bidi: plaintext;
}
```

It needs to be set with more care as it can displace some other things such as RTL titles of a post fetched from RSS.

But rest, it works fine

**Comment by ahangarha** [comment] 2021-04-30 08:07
Any update in this regard?

**Comment by MrPetovan** [comment] 2021-04-30 20:06
Not yet, do you have a federated social media account that we could follow with RTL content to check our implementation?

**Comment by ahangarha** [comment] 2021-05-01 17:43
> Not yet, do you have a federated social media account that we could follow with RTL content to check our implementation?

I am on mastodon: https://mas.to/@ahangarha/

But also you can check some twitter subscription with some Persian hashtags like `#نرم‌افزار_آزاد`.

If needed, I can share some mixed text I sometimes use to check bidi support on different apps.

**Comment by MrPetovan** [comment] 2021-05-01 17:52
Thank you. The way I see it, there are two separate aspect of this, the UI and the content. The UI needs a full translation and then several tweaks on every page to make sure it feels right for RTL readers. For the content, it seems easier since only post bodies and profile information need to be correctly displayed. I believe the `dir="auto"` will be enough to satisfy RTL content, but the UI will need a whole different effort.

**Comment by ahangarha** [comment] 2021-05-01 18:49
That would be a good start. There are few other things we need to keep in mind. One is when a post starts with a username (like mentioning a person) mentions should be in `<bdi>`. Such kind of things needs to be addressed.

**Comment by MrPetovan** [comment] 2021-05-01 18:50
Thank you for the hint, I didn't know about this tag. so all display names should be wrapped with this tag.

**Comment by ahangarha** [comment] 2021-05-01 18:53
Yes. It might be possible to add `unicode-bidi: isolate` to those parts but it is discouraged to do so. Though I have done this on some projects like Sengi to prevent HTML manipulation.

And lets work with content first. Regardless of UI direction, content should show up in right direction. UI can be handled later.

**Comment by ahangarha** [comment] 2021-05-01 18:59
I have not tried to wrap things in `<bdi>` as the main approach. I have used `dir="auto"` and sometimes played with `unicode-bidi`.

I can make some test these days to see how would this approach work.

I am not sure if myself can run a local installation of Friendica to test. I will do it with sample texts.

**Comment by MrPetovan** [comment] 2021-05-01 18:59
Question for you: in the column where we show in order:
- Profile name
- Profile address
- Profile information

If the name and information are RTL, should the address also be RTL? Using `dir="auto"` on the parent element of these three, the address follows the detected text direction.

Using `dir="auto"` on each individual element leaves the address in LTR, is it expected?

![friendica-vcard-rtl](https://user-images.githubusercontent.com/925415/116792928-adee7d80-aa91-11eb-843f-4853d7c4fac4.png)

**Comment by ahangarha** [comment] 2021-05-01 19:33
Yes. this is how it should look like. It should apply direction based on the first strong character.

What is rendered in this image, is the exact expected result.

**Comment by MrPetovan** [comment] 2021-05-01 19:43
I added the `<bdi>` tag to the display names of the mentions, but since we have the mention's `@` outside of this tag, I'm not sure what is the expected display in the following cases:
- LTR message with RTL mention
- RTL message with LTR mention
- RTL message with RTL mention

Could you please provide sample displays for these cases?

**Comment by ahangarha** [comment] 2021-05-01 19:50
I just don't know how we can work on this together since I don't have enough technical knowledge to run local env.
I don't think we would anytime (at least any time soon) have RTL mention. Usernames are in latin character. I haven't seen RTL username.

**Comment by ahangarha** [comment] 2021-05-01 19:53
There is another important issue: there shouldn't be any hard alignment (left|right) at least for such contents. padding, margin, text-align and border should use `start|end` instead of `left|right`. For all these styles except text-align, we should use relevant bidirectional alternatives. For example instead of `padding-left: 1rem` we should use `padding-inline-start:1rem`.

**Comment by MrPetovan** [comment] 2021-05-01 20:04
> I just don't know how we can work on this together since I don't have enough technical knowledge to run local env.
> I don't think we would anytime (at least any time soon) have RTL mention. Usernames are in latin character. I haven't seen RTL username.

Friendica doesn't display usernames for mentions, it displays display names, which can be RTL.

Example with your display name:
```
@مصطفی آهنگرها Test mention at start of the message
```


> There is another important issue: there shouldn't be any hard alignment (left|right) at least for such contents. padding, margin, text-align and border should use `start|end` instead of `left|right`. For all these styles except text-align, we should use relevant bidirectional alternatives. For example instead of `padding-left: 1rem` we should use `padding-inline-start:1rem`.

But this is only relevant if we have asymmetrical paddings/margins, right? And I don't think we have many absolute `text-align` values.

**Comment by ahangarha** [comment] 2021-05-02 05:26
In this case (display name), it should be isolated so that the direction of rest of the text would be be determined by the main part of the post. You sample text is shown properly.

**Comment by MrPetovan** [comment] 2021-05-02 12:42
Ok, I think the user-submitted content part is covered thanks to your precious technical hints. It wasn't much to add, but I would have needed a lot of time to figure out what to add. Thank you!

**Comment by ahangarha** [comment] 2021-05-02 14:01
Is there any instance deployed directly from dev branch? So I test.

**Comment by annando** [comment] 2021-05-02 14:21
@ahangarha In several days (when I consider it stable enough), I will switch squeet.me to dev.

**Comment by ahangarha** [comment] 2021-05-03 12:40
Then I make an account there for test. I already have account on venera.social but I rarely post on that.

**Comment by annando** [comment] 2021-05-03 12:42
@ahangarha this weekend I updated squeet.me.

**Comment by ahangarha** [comment] 2021-05-19 10:45
Today I checked squeet.me. Individual posts and conversations are fine but indexes (like search, posts,...) are not.

![image](https://user-images.githubusercontent.com/11241315/118799635-30f63d00-b8b4-11eb-9913-7b6145a4f77b.png)

Addressed in #10270

**Comment by MrPetovan** [comment] 2021-05-19 12:47
Thank you for the report, I'll look into it.

**Comment by annando** [comment] 2021-05-19 13:35
@ahangarha yeah, this is a different template. After @MrPetovan made the changes, I will update squeet.me, so that you can check.

**Comment by MrPetovan** [comment] 2021-05-19 15:01
@annado You can update squeet.me now.

**Comment by annando** [comment] 2021-05-19 16:03
@ahangarha you can try.

**Comment by ahangarha** [comment] 2021-05-19 17:10
Well done!

Just I notice two issues:

1. at least in [this particular post](https://mas.to/@ahangarha/106163820221417590), the `dir="auto"` is set to outer `div` with makes whole of the inner `div` get RTL or LTR direction.
    
![image](https://user-images.githubusercontent.com/11241315/118855010-92390300-b8ea-11eb-98c0-6e7230f6a4f0.png)

2. Tags/hashtags need to be improved for RTL content. Not a big issue but it should be in the list.

Addressed in #10278

**Comment by ahangarha** [comment] 2021-05-19 17:30
Also the post creation form needs to support bidi.

![image](https://user-images.githubusercontent.com/11241315/118857655-8864cf00-b8ed-11eb-8b46-e70567601199.png)

Addressed in #10278

**Comment by ahangarha** [comment] 2021-05-19 17:31
Should I report all issues regarding bidi here?

**Comment by ahangarha** [comment] 2021-05-19 17:42
Post title doesn't have `dir="auto"`:

![image](https://user-images.githubusercontent.com/11241315/118859105-1a210c00-b8ef-11eb-84b6-22ed4119d46f.png)

[Post URL](https://venera.social/display/85a863ed-875f-d8c8-f211-8a5191331636)

Addressed in #10278

**Comment by MrPetovan** [comment] 2021-05-19 18:15
> Should I report all issues regarding bidi here?

Absolutely, it would be way too noisy in separate issues. I'll look into your most recent reports later.

**Comment by MrPetovan** [comment] 2021-05-20 11:41
The mentions seems not to work as expected either, in a RTL post the at-sign ends up at the end of the username like this: `danialbehzadi@`. This is because the `@` is outside of the `<bdi>` tag used for mentions.

Wrong: `@<a><bdi>danialbehzadi</bdi></a>`
Correct: `<bdi>@<a>dianalbehzadi</a></bdi>`

**Comment by MrPetovan** [comment] 2021-05-20 11:46
> 1. at least in [this particular post](https://mas.to/@ahangarha/106163820221417590), the `dir="auto"` is set to outer `div` with makes whole of the inner `div` get RTL or LTR direction.
> 
> ![image](https://user-images.githubusercontent.com/11241315/118855010-92390300-b8ea-11eb-98c0-6e7230f6a4f0.png)

Unfortunately I wasn't able to use `<bdi>` successfully to modify the direction of a line with just a URL on it. We don't have a paragraph structure, so we need to use `dir="auto"` on the parent `<div>` at the moment.

**Comment by MrPetovan** [comment] 2021-05-20 11:57
> ![image](https://user-images.githubusercontent.com/11241315/118855010-92390300-b8ea-11eb-98c0-6e7230f6a4f0.png)
> 
> 2. Tags/hashtags need to be improved for RTL content. Not a big issue but it should be in the list.

Is this the correct way it should display?

![friendica-rtl-hashtag-bdi](https://user-images.githubusercontent.com/925415/118974565-fa1a3880-b940-11eb-8ba9-031ce3eab4c4.png)

**Comment by ahangarha** [comment] 2021-05-20 11:58
> Unfortunately I wasn't able to use `<bdi>` successfully to modify the direction of a line with just a URL on it. We don't have a paragraph structure, so we need to use `dir="auto"` on the parent `<div>` at the moment.

It is fine to add `dir="auto"` but it is put in a wrong place (or at least it should be added to some other elements as well. Look at these screenshots:

![image](https://user-images.githubusercontent.com/11241315/118974518-286f3680-b988-11eb-9890-9839949849f9.png)
![image](https://user-images.githubusercontent.com/11241315/118974611-45a40500-b988-11eb-8418-775774cddf11.png)

The `span` and `div` elements related to `show-more` need `dir="auto"`.

Addressed in https://github.com/friendica/friendica-addons/pull/1118

**Comment by ahangarha** [comment] 2021-05-20 12:05
> Is this the correct way it should display?
> 
> ![friendica-rtl-hashtag-bdi](https://user-images.githubusercontent.com/925415/118974565-fa1a3880-b940-11eb-8ba9-031ce3eab4c4.png)

It is at least in shape. Though it would be ideal if it can show the # and the other sign in reverse order in RTL hashtags. but I would say it is fine for now.

I think we don't need to go for this much fine tuning at this stage at least. The priority is to make the UI work for RTL content. These details can be fine tuned later.

**Comment by MrPetovan** [comment] 2021-05-20 12:18
Thank you, I included the hash-mark in the `<bdi>` tag and it worked.

**Comment by tobiasd** [comment] 2021-07-03 17:47
Is this still an issue? Or should the expansion of the RTL support be another ticket?

**Comment by ahangarha** [comment] 2021-07-03 18:16
> Is this still an issue? Or should the expansion of the RTL support be another ticket?

Do you experience any issue? On some instances such as venera.social it is already working. I can say it is working fine.

**Comment by tobiasd** [comment] 2021-07-03 18:20
So we can close this ticket?

**Comment by ahangarha** [comment] 2021-07-03 18:34
I think so. If there be any issue, one can open a new issue.

**Comment by AlfredSK** [comment] 2021-07-03 18:51
I recently saw a reshared post with RTL text. In frio the text of the reshared content was overlapping the little network icon and link to source icon.

**Comment by MrPetovan** [comment] 2021-07-03 19:50
A screenshot and/or a link would be welcome.

**Comment by AlfredSK** [comment] 2021-07-03 20:04
Yes. The problem is to find it again.

**Comment by AlfredSK** [comment] 2021-07-04 10:02
Ha! Found one. :-)

![grafik](https://user-images.githubusercontent.com/3656054/124380777-f65b2f00-dcbe-11eb-96c1-6aaf33f14d4b.png)

Username and date of post are inserted on the right side. But it should be on the left side.

Steps to reproduce:
1. Import this post on your node https://venera.social/display/67851619-983298e32d387710-a32197cb
2. Or use the original https://persadon.com/@danialbehzadi/106521529502265000
3. Click on 'Quote Share'
4. Look at the preview

I only used the preview function to reproduce the issue. But the same happens with the submitted share.

**Comment by MrPetovan** [comment] 2021-07-04 13:09
Thank you, this is perfect.

@ahangarha, what would be the expected display in this case?

**Comment by tobiasd** [comment] 2021-07-04 18:31
Ok, but lets close this ticket never the less, new issues with the RTL support should get their own tickets.

**Closed by tobiasd** 2021-07-04 18:31 UTC
Labels: Enhancement, Needs More Info

**Comment by ahangarha** [comment] 2021-07-04 21:22
This is how it should look I think:

![image](https://user-images.githubusercontent.com/11241315/124399823-58ee1280-dd33-11eb-950c-8683a6fd3621.png)

All I did was to change css properies from left|right to relevant bidi values like start|end. If this is fine, then let me know. I will send PR.

**Comment by tobiasd** [comment] 2021-10-08 05:30
With #10849 the Arabic translation of the strings used in the web UI of Friendica arrives in the repository as it now covers more then 50% of all strings used. Guess the RTL support campaign enters the next step.
