### ISSUE TITLE
Adding a user previously deleted

### ISSUE THREAD

**Issue by davidep8922** [friendica/friendica#1790] opened 2015-07-24 08:55 UTC
I'm not add a previously deleted user .
I try to add me says :
" This user name has already been registered . Please choose a new one. "

I have to do something at the level of the mysql and what do I have to do?

**Comment by annando** [comment] 2015-07-25 07:38
The system does a lookup into a table where all users are stored. If it founds an entry it will return with this message. That means that you or someone else definitively tried that user name.

**Comment by silke** [comment] 2015-09-09 19:11
Hey, davidep8922, this is expected behavior. You *can* circumvent it by going into the database and changing the user name in question. It would be in the table "userd".

Closing this, as it's not a bug.

**Closed by silke** 2015-09-09 19:11 UTC
