### ISSUE TITLE
Host down after git pull

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4298] opened 2018-01-21 13:42 UTC
After last git pull my host https://horche.demkontinuum.de shows a login page, but after logging I only see a completely white page 

apache error log

> [Sun Jan 21 14:37:24.228545 2018] [:error] [pid 3790] [client 91.64.144.186:60652] PHP Fatal error:  Uncaught Error: Call to undefined function call_hooks() in /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/addon/smileybutton/smileybutton.php:99\nStack trace:\n#0 /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/src/Core/Addon.php(226): show_button(Object(Friendica\\App), '')\n#1 /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/src/Core/Addon.php(204): Friendica\\Core\\Addon::callSingleHook(Object(Friendica\\App), 'jot_tool', Array, '')\n#2 /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/include/conversation.php(1301): Friendica\\Core\\Addon::callHooks('jot_tool', '')\n#3 /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/mod/network.php(613): status_editor(Object(Friendica\\App), Array)\n#4 /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/mod/network.php(411): networkThreadedView(Object(Friendica\\App), 0)\n#5 /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/index.php(375): network_content(Object(Friendica\\App))\n#6 {main}\n  thrown in /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/addon/smileybutton/smileybutton.php on line 99

**Comment by MrPetovan** [comment] 2018-01-21 13:43
Duplicate of #4294:
```
cd /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/addon/
git checkout develop
git pull
```

**Closed by MrPetovan** 2018-01-21 13:43 UTC

**Comment by hoergen** [comment] 2018-01-21 13:49
Thanks .. I got the message, that I am already on develop. A git pull told me as well "already on develop" but it changed something and now im able to access my site again.

Thanks for the quick help! 🌻

**Comment by MrPetovan** [comment] 2018-01-21 13:53
No problem, please remember to pull from addon at the same time you pull from friendica. I added `git checkout develop` because we recently created it and I expect some people not to have switched yet.

**Comment by hoergen** [comment] 2018-01-21 14:02
I do every time:

git pull <friendica>
composer update
git pull <addon>

**Comment by annando** [comment] 2018-01-21 14:10
I guess it should be ```php util/composer.phar install``` instead of "update".

**Comment by MrPetovan** [comment] 2018-01-21 14:19
The full process to update your instance should be:
````
cd /path/to/friendica/
git pull
util/composer.phar install
if [ addon -d ]
    cd addon
    git pull
fi
````

Please don't use this script as is, I'm a bash noob.
