### ISSUE TITLE
github not open source

### ISSUE THREAD

**Issue by nitram** [friendica/friendica#3097] opened 2017-01-18 01:00 UTC
github is not open source.. it might be good to consider using a platform such as gitlab if you wish to become serious about open source software 

besides that I really love your project! please continue doing what you! much love <3

**Comment by tobiasd** [comment] 2017-01-18 06:33
duplicate, so I'll close this ticket

**Closed by tobiasd** 2017-01-18 06:33 UTC

**Comment by fabrixxm** [comment] 2017-01-18 08:05
for reference: duplicate of #1553
