### ISSUE TITLE
OAuth login: "Entity could not be processed"

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#13556] opened 2023-10-18 07:34 UTC
Seen with both Kaiteki (https://github.com/Kaiteki-Fedi/Kaiteki/issues/448) and Relatica (https://gitlab.com/mysocialportal/relatica/-/issues/48): Login to 2023.09RC instances seems not possible anymore. Error message:

![tempFileForShare_20231018-093120](https://github.com/friendica/friendica/assets/685879/3efc8e5e-7fcc-49a4-935e-7abe49438eb2)

This seems related to https://github.com/andstatus/andstatus/issues/569 and maybe (?) https://github.com/friendica/friendica/pull/12719 ; I've seen this problem before but the error message itself is rather brief.

**Comment by HankG** [comment] 2023-10-30 22:07
This issue is a regression caused by changes in PR #13299 . That change deconstructs the redirect URL, reconstructs it, and then somewhere down below checks if the reconstruction matches the original string. Unfortunately this deconstruction code makes assumptions that it cannot in this step for these client-based OAuth cases. I'll use the Relatica implementation for reference to make it concrete. For example on desktop apps the redirect URL is a localhost URL with a port number: `http://localhost:43824`. When this deconstruction/reconstruction happens the value checked is against `http://localhost` which of course does not match. It then borks the whole flow. On mobile clients it uses the private use URI schemes which look something like `<app_name>:/`. In Relatica's case the URL on mobile is `relatica:/`. I need to check and see why I only have one slash not two and just have an empty string afterward but these workflows did successfully complete on both Android and iOS previously. 

I don't want to try to "fix" the code without knowing why the change was being done as it was to make sure I don't create a regression around what was trying to be fixed in the original PR. @annando may be able to shed light on this.

**Comment by annando** [comment] 2023-10-30 22:43
This whole deconstruction thing is done, since Buffer provides some URL with some additional crap in it that we have to remove.

**Comment by HankG** [comment] 2023-11-06 01:43
I did some testing across a bunch of Mastodon and two Friendica clients that should work. I'm changing Relatica's in a way that parses into a URL like some of the ones that work but these notes should help with fixing the code that started the failure. The other one that used a single slash is Ivory. I wonder if we should reach out to them about making that more URL like like the other ones were...it seems to be the more conventional (maybe even proper) way to do it. 

Friendiqa: `http://127.0.0.1:1337/` (fails)
Relatica: `relatica:/` (fails)
Ivory: `com.tapbots.Ivory.16500:/request_token/<guid>` (fails)
Mastodon proper: `mastodon://joinmastodon.org/oauth` (works)
Mammoth: `mammoth://addNewInstance` (fails)
Ice Cubes: `icecubesapp://` (fails)
Tootle: `jp-morilab-mastodonapp://authorize` (works)
Woolie: `woolly://auth` (works)
Trunks: (Error logging in before Oauth)
Metatext: `metatext://oauth.callback` (works)
Mona: `com.jonny.mona://oauth` (works)
Megalodon: `megalodon-android-auth://callback` (works)
Moshidon: `moshidon-android-auth://callback` (works)
kaiteki: `web+kaitekisocial://go-router-is-poop/oauth/mastodon/<server domain name>` (fails)
Fedilab: TBD (no free version so didn't test)

**Closed as completed** 2023-11-06 18:12 UTC
Labels: Bug, API
