### ISSUE TITLE
Can't sort user list (in /admin) by Register date/Last Login/Last public item any longer

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#9665] opened 2020-12-16 21:52 UTC
[ ] I have searched open and closed issues for duplicates - I've only searched open items.

### Bug Description

As per title - in Frio as of a few weeks ago (back on the 2020.09 stable?) we could still sort users by Register date/Last Login/Last public item, but clicking on those items doesn't do it any longer.

### Steps to Reproduce

On 2020.12-RC, head to /admin/users, open up the expander next to a user, click on any of Register date/Last Login/Last public item

Actual Result:

Nothing happens.

Expected Result:

Sorting occurs.

### Platform Info

Friendica Version: 2020.12-rc - 1383

Friendica Source: git

PHP version: 7.4.13

SQL version: mariadb 10.3.27

**Comment by AlfredSK** [comment] 2020-12-16 22:08
I did the search for open issues for you.

Duplicate of #9518

**Comment by realkinetix** [comment] 2020-12-16 22:10
*facepalm*

Sorry about that.  I did have a look at open issues, but apparently didn't register what I was seeing.

**Closed as completed** 2020-12-16 22:11 UTC

**Comment by AlfredSK** [comment] 2020-12-16 22:15
I created a duplicate of my own issue yesterday. 😁
