### ISSUE TITLE
Mastodon friend request creates several requests

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4803] opened 2018-04-10 09:17 UTC
### Expected behavior
1 friend request from Mastodon (node https://mastodon.social)

### Actual behavior
Creates 6 friend requests (see screenshot below)
Notice the different times ...

### Steps to reproduce the problem
Wait for a friend request from Mastodon ;)

### Friendica version you encountered the problem
Friendica 'The Tazmans Flax-lily' 2018-05-dev - 1259

### Friendica source (git, zip)
git

### PHP version
PHP Version 7.0.29-1~dotdeb+8.1

### SQL version
MariaDB

![00_temp](https://user-images.githubusercontent.com/24474762/38547905-9edfaa14-3cb0-11e8-8643-04a73680a124.png)

**Comment by MrPetovan** [comment] 2018-04-10 09:25
I know it's a big problem for you, but we just can't let you open exact duplicates of your own ticket.

**Comment by MrPetovan** [comment] 2018-04-10 09:25
Closed as exact duplicate of #4803.

**Closed by MrPetovan** 2018-04-10 09:25 UTC
