### ISSUE TITLE
Profile change due to automatic page update

### ISSUE THREAD

**Issue by TupambaeNet** [friendica/friendica#1496] opened 2015-04-07 03:38 UTC
When I switch with the manage option to a different profile, after a short time the page reloads (or checks for new post's) and switches back to the previous profile.

**Comment by tobiasd** [comment] 2015-04-09 06:32
I've tested this with a chromium based browser but could not reproduce it. Which browser are you using? JavaScript is enabled I assume?

**Comment by TupambaeNet** [comment] 2015-04-09 15:42
Iceweasel, JavaScript is part of adobe flash I suppose, my setting asks for permission to use it on websites, I'll have a look at this detail.

**Comment by TupambaeNet** [comment] 2015-04-10 17:39
Also there was proc_runner enabled instead of poormancron, I will recheck this.

**Comment by TupambaeNet** [comment] 2015-04-10 17:59
Problem still exist's like if the profile change over the manage tab isn't really taken over, in the first attempt to open for example a new network tab it jumps back to the logged in profile. I have this issue with very old profile accounts (serveradmin and a common profile) which where linked together over same email and password, I often wonder if somewhere there is something messed up because of that.
Is it possible to change the server admin profile, like creating a new one and changing the profile address in the .htconfig.php?

**Comment by tobiasd** [comment] 2015-04-13 13:03
For a new admin account, just create one with a different email address and then change the .htconfig file accordingly.

**Comment by AlfredSK** [comment] 2020-02-15 15:50
I think this is outdated due to the changes to the user profiles. Should we close it?

**Comment by MrPetovan** [comment] 2020-02-15 18:32
I think it also was about multiple profiles, and that part has become invalid. Not sure about the account delegation management.

**Comment by annando** [comment] 2020-02-16 09:40
No, this is a different issue - and it is still an issue sometimes. When you have got multiple accounts that you manage, it can happen that you switch the account and some seconds later you are in the previous account again.

**Comment by AlfredSK** [comment] 2020-02-16 10:46
Yes, I can confirm that. When I manage the accounts on the forum node it happens from time to time.

**Comment by MrPetovan** [comment] 2023-07-28 16:48
Does this still happen? What's the typical user journey?

**Comment by annando** [comment] 2023-07-29 06:07
It's happen to me as well from time to time. I haven't yet seen any clear pattern. I'm asking myself, i this could be some timing issue, that is - for example - connected to the ping mechanism. Question is what is happening when the system currently creates the data for the notifications while you already switched to a different profile. Could this lead to this issue?

**Comment by MrPetovan** [comment] 2023-07-29 08:38
My question was mainly about the timing. How long after the initial main account login does the unwanted switch happen? I believe that when the current session inevitably expires, the cookie authentication kicks in and it may be still the main account's authentication cookie, which refreshes the session with the main account instead of any sub-account that was switched to.

I have to look more into it.

**Comment by annando** [comment] 2023-07-29 14:33
I've got the feeling that is happens especially when I switch very fast between my accounts.

**Comment by MrPetovan** [comment] 2023-07-29 14:37
I can try this too, although I don’t have a good hypothesis for why it would be detrimental.

**Comment by TupambaeNet** [comment] 2023-09-04 16:05
just passing by to say that I can't right now reproduce this or remember more than stated already, actually I was off for some time when it comes to friendica as I always had trouble due to shared hosting.

So I cant help at all with this for now but will have an eye on it.

**Comment by foss-** [comment] 2023-12-17 12:43
So this has not been reported for almost 4 years. @AlfredSK are you still able to reproduce in latest RC branch?
If no one can reproduce, it is probably fair to close and re-open when seen again?

**Comment by MrPetovan** [comment] 2023-12-19 01:48
I don't remember being able to reproduce the issue with my managed accounts on my dev instance. 🤷‍♂️

**Closed by MrPetovan** 2023-12-19 01:48 UTC
Labels: Bug

**Comment by TupambaeNet** [comment] 2023-12-21 01:11
This happend to me several times in the last months but actually I'm still trying to figure out when where or how, like to say if I can't find a pattern.

It happend meanwhile trying to change a profile picture, actually the picture doesn't show up in the profile photo gallery where it is erroniously displayed as profile picture:
https://tupambae.org/display/0ac89072-9365-5567-f152-102402657235
All this happend with firefox.

I'm kinda stuck with several things at the same time and I don't fell like being able to pin this down or/and at the same time consider to be working on a full standard normal working stable installation, as this is the first time I'm on own VPS.

I always work with lot's of windows open and think that could be a reason, as the older windows remain for a certain time with the previous profile displayed.

The avatar issue was/is very strange as I'm not even sure right know if I can find that avatar picture in any of the two involved profiles.

In another incident I managed to look/change the admin profile because of changing the respective profile email without realizing that the switch to the previous profile happend:
https://tupambae.org/display/0ac89072-1965-5b87-8b00-fdb979522241

**Comment by MrPetovan** [comment] 2023-12-21 03:08
We currently don't have specific provisions to update other tabs when logging in/out/switching profile than the current one that I know of, and I'm not sure it would be welcome either, since it would involve forcing a reload of the page, disregarding any work in progress, or we have to also account for it, which increases the complexity of the task.

**Comment by TupambaeNet** [comment] 2023-12-23 05:29
@MrPetovan

I wonder if there could be any use in researching what happend to the avatar change mentioned, if there could be any hint for the problem itself. If not I wil just change the avatar as intended. As of now I left those profiles "as is" to be able in any case to digg into that.

**Comment by MrPetovan** [comment] 2023-12-23 14:15
So far it's been sounding too specific for us to pursue any efficient line of investigation, so please resume your use of Friendica as you intended, I don't think we can glean any useful information from the state your accounts are in right now.
