### ISSUE TITLE
Unexpected ActivityPub profile page response for deleted accounts

### ISSUE THREAD

**Issue by vitalyster** [friendica/friendica#6553] opened 2019-01-29 20:24 UTC
I'm receiving activites to my ActivityPub inbox from several Friendica instances, and I can not verify it using HTTP signatures.
### Expected behavior
* Got activity signed with keyId of http://friendicainstance.tld/profile/username#main-key
* Request with `Accept: application/activity+json` header to http://friendicainstance.tld/profile/username should return:
1. HTTP 200 and ActivityPub Person object and his key
2. HTTP 404 for unknown user
3. HTTP 410 for known (gone) user
### Actual behavior
I see HTTP 200 and empty JSON array (`[]`) from some usernames and can not understand how to handle it.

### Friendica version you encountered the problem
Version 2019.01 as reported from one of these services

**Comment by vitalyster** [comment] 2019-01-30 08:19
Additional info: I did more debugging and these strange profile responses returned for actually deleted users, so I should receive HTTP 410 but not 200 for that.

**Comment by annando** [comment] 2019-01-30 08:47
That's a little bit too abstract. What kind of activity do you receive? Currently I don't know if the problem is that some wrong user was chosen to send an activity or if this just was the message that a user deleted his/her account.

**Comment by vitalyster** [comment] 2019-01-30 11:02
It is the message about account deletion, it has "actor" url which I tried to check and expect HTTP 410 to verify this user is deleted, but receive HTTP 200

**Comment by vitalyster** [comment] 2019-01-30 11:08
https://www.w3.org/TR/activitypub/#delete-activity-outbox

> If the deleted object is requested the server SHOULD respond with either the HTTP 410 Gone status

**Comment by tobiasd** [comment] 2019-01-30 14:06
Don't forget that the initial posting about the deletion could end up not received by all nodes, which later have to be able to get that information on the next poller run.

**Comment by MrPetovan** [comment] 2019-01-30 15:03
> Question is, how AP expects it. Is it expected that every deleted account immediately has to return 410? This would mean that we couldn't check the validity of the incoming deletion message.

If you receive 410 Gone when you check the validity of the deletion message, isn't it proof enough?

**Comment by vitalyster** [comment] 2019-06-21 16:35
Does it merged in some release? I see the same from `"Friendica 'Dalmatian Bellflower' 2019.04-1304; https://nerdica.net"`

**Comment by annando** [comment] 2019-06-21 17:01
I thought so. But possibly fixing this has to work for version 2019.09, since version 2019.06 will most likely be published this weekend.

**Comment by MrPetovan** [comment] 2019-08-26 02:00
Where are we on this? Any confirmed reggresion?

**Comment by annando** [comment] 2019-08-26 06:04
I haven't had a look at it.

**Comment by MrPetovan** [comment] 2019-09-13 14:40
Pushing to next milestone then.

**Comment by annando** [comment] 2019-09-14 07:18
I just compared our code with the specs. I think that we are doing it correctly. I just added a PR to make the code better readable in that part.

**Comment by MrPetovan** [comment] 2019-09-14 10:12
Closed via #7626

**Closed by MrPetovan** 2019-09-14 10:12 UTC
Labels: Bug, Federation
