### ISSUE TITLE
[2019.01-rc] PHP Fatal errors

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#6421] opened 2019-01-10 19:30 UTC
```
PHP Fatal error:  Uncaught Error: Call to undefined method Friendica\App::get_curl_content_type() in /addon/mailstream/mailstream.php:167
Stack trace:
#0 /addon/mailstream/mailstream.php(265): mailstream_do_images(Object(Friendica\App), Array, Array)
#1 /addon/mailstream/mailstream.php(345): mailstream_send(Object(Friendica\App), '<967eadf951d7f8...', Array, Array)
#2 /src/Core/Hook.php(196): mailstream_cron(Object(Friendica\App), NULL)
#3 /src/Worker/ForkHook.php(16): Friendica\Core\Hook::callSingle(Object(Friendica\App), 'cron', Array, NULL)
#4 [internal function]: Friendica\Worker\ForkHook::execute('cron', Array, NULL)
#5 /src/Core/Worker.php(363): call_user_func_array('Friendica\\Worke...', Array)
#6 /src/Core/Worker.php(253): Friendica\Core\Worker::execFunction(Array, 'ForkHook', Array, true)
#7/addon/mailstream/mailstream.php on line 167
```

**Comment by AlfredSK** [comment] 2019-01-10 19:57
I think that's a duplicate of...
https://github.com/friendica/friendica/issues/5913#issuecomment-450017405

**Comment by MrPetovan** [comment] 2019-01-10 20:10
It is, closing here.

**Closed by MrPetovan** 2019-01-10 20:10 UTC
