### ISSUE TITLE
Improve Twidere Compatibility

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5708] opened 2018-09-01 03:22 UTC
After [this discussion](https://forum.friendi.ca/display/96794102145b89cde9bfafc061766691), we got a bullet list of things to improve in the API for Twidere support:

- [x] Direct messages
- [x] Seeing fully profile like "tweets", follower, following just empty (including own profile)
- [x] Following people on other instances / plattforms not possible (error 501)
- [ ] Notification / refresh may takes twice an action
- [x] Symbols/numer of replies
- [x] Likes don't propagate to Friendica

**Comment by annando** [comment] 2018-09-01 03:31
Direct messages are already possible.

**Comment by JonnyTischbein** [comment] 2018-09-01 08:02
**Direct Messages**
That is really strange! Right now as I was trying to get the log via adb the result wasn't empty. Until now even after multiple restart and refresh no message was visible.

But now every message is displayed twice. When I lookup in the webinterface every message was sended only onces but creating a new thread for each. That isn't right I guess?
[![screenshoot](https://i.imgur.com/K57tTN0.png)](https://i.imgur.com/K57tTN0.png)
[![screenshot](https://i.imgur.com/HURZaeC.jpg)](https://i.imgur.com/HURZaeC.jpg)

Friendica 2018-05
Twidere 3.7.3 @ f-droid

**Comment by PolynomialDivision** [comment] 2018-09-02 06:45
@MrPetovan 
I think @JonnyTischbein is right and "Direct Messages" has not the behavior you actually want.
Starting a new Thread for every message is not good... :/

**Comment by tobiasd** [comment] 2018-09-02 12:48
I don't know how @fabrixxm does it, but Friendly (on SailfishOS) does not create a new thread for every PM one sends.

**Comment by JonnyTischbein** [comment] 2018-09-02 13:02
Twidere is sending when answering to a thread:

    - - - [02/Sep/2018:14:57:51 +0200] "POST /api/1.1/direct_messages/new.json HTTP/1.1" 200 2690

The friendica webinterface just

    - - - [02/Sep/2018:14:58:52 +0200] "POST /message HTTP/1.1" 302 -

Considering the API Readme [https://github.com/friendica/friendica/wiki/Friendica-API](https://github.com/friendica/friendica/wiki/Friendica-API#direct_messagessent--auth) there is directmessage function for new and sent:

**direct_messages/sent (*; AUTH)
Parameters**

    count: Items per page (default: 20)
    page: page number
    since_id: minimum id
    max_id: maximum id
    getText: Defines the format of the status field. Can be "html" or "plain"
    include_entities: "true" shows entities for pictures and links (Default: false)
    friendica_verbose: "true" enables different error returns (default: "false")

**direct_messages/new (POST,PUT; AUTH)
Parameters**

    user_id: id of the user
    screen_name: screen name (for technical reasons, this value is not unique!)
    text: The message
    replyto: ID of the replied direct message
    title: Title of the direct message


I don't know if this is an API or Twidere thing...

**Comment by fabrixxm** [comment] 2018-09-02 13:31
> Yes of course a private message!
> But why an GET ? The API Documentation I linked says POST or PUT ?

nevrmind, I read only the mail notification, not the full thread here with your edits.

> So then it is a bug at Twidere right ?

I think it could be a Friendica issue. Private messages in Friendica can work as email, threads with titles and  replies.
I don't know how DM in tiwtter works, but looks like is just a conversation with a contact, so every new message is a reply to the last.
Our api support `replyto` and `title` parameters that Twitter original api didn't supported ( https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-message ).
We decided to default to create new thread when no `replyto` is set.
In Friendly I  send alwais (when possibile) the `replyto`, creating a single thread conversation.
I think we should mimic as exactly as possible the behaviour  of twitter/GS api, and friendca-only functionality should have a custom api call (or an optional parameter to pass)

**Comment by MrPetovan** [comment] 2018-09-02 14:09
We're missing the parameters Twidere sends to Friendica. Maybe it sends a differently named `replyto` parameter.

**Comment by annando** [comment] 2018-09-02 17:42
AFAIK there is no "replyto" in the original API that Twidere uses.

**Comment by MrPetovan** [comment] 2018-09-02 20:53
There's no reference to the existing thread when there's a reply from Twidere?

**Comment by MrPetovan** [comment] 2018-09-03 01:00
Ah, fair point. it just is a stream of messages between two accounts.

**Comment by JonnyTischbein** [comment] 2018-09-05 20:00
Is there a reason why friendica supports multiple threads?

Or should be starting adding a replyto in friendica or should friendica do something like: look if no replyto but recent conversation with the same account and assume last thread as replyto? Ot changing friendica to no thread system like twitter API?

**Comment by annando** [comment] 2018-09-05 20:29
We could however just always chose the last thread when answering. This will mostly work fine, I guess.

**Comment by MrPetovan** [comment] 2018-09-06 00:03
We still need a consistent use of the API, no matter the client. If Twidere doesn't use the `replyto` param, we probably should require it, even empty, to create a new thread in Friendica-compatible apps.

So:
- No `replyto` param: attached to the last thread with the contact.
- `replyto` param with empty value: Creating a new thread, what about a `title`/`subject` param?
- `replyto` param set with the thread ID: attached to the relevant thread.

**Comment by annando** [comment] 2018-09-06 04:38
We already defined some "title" parameter, I think.

**Comment by MrPetovan** [comment] 2018-09-06 16:01
Even better:
- No `replyto` nor `title` parameter: Attach to last thread with contact.
- No `replyto` and `title` parameter: Create new thread with contact.
- Non-empty `replyto` parameter: Attach to relevant thread.

**Comment by JonnyTischbein** [comment] 2018-09-06 16:51
Sounds great!

What could we do about the 501 Not implementes function for following and unfollowing ?
Build a redirect / alias for

    POST /api/1.1/friendships/destroy.json

And

    POST /api/1.1/friendships/create.json

To the matching api functions?

**Comment by JonnyTischbein** [comment] 2018-09-07 21:29
Ahh now I get it! The functions are not implemented in the API at all! Thought that they are under a different command..

**Comment by JonnyTischbein** [comment] 2018-09-10 19:36
I'm trying to write the friendships/destroy API comand 81f9e16d36cad3fba74ad3b3543ccadcaf2036a4
But I'm getting an 403 Forbidden Response.
Could you may give me a hint ?

**Comment by MrPetovan** [comment] 2018-09-10 19:46
Sounds like you aren't correctly authenticated. Did you check the Auth part of the Friendica API wiki page: https://github.com/friendica/friendica/wiki/Friendica-API

**Comment by zeroadam** [comment] 2018-09-12 14:32
Adding to the list here... "Liking" doesn't seem to work as I would expect. Clicking the heart icon on a specific post changes it's color to read and provides a popup saying "Tweet liked". Upon viewing the "tweet" again in twidere, the heart is still colored red. However, on the Friendica node side, the posts that were liked do not show any indication of being liked by you.

**Comment by JonnyTischbein** [comment] 2018-09-12 18:40
Can confirm this too.

**Comment by annando** [comment] 2018-09-12 18:51
"liking" is translated as "marking". This is a behaviour I would like to make configurable.

**Comment by JonnyTischbein** [comment] 2018-09-12 19:40
Back to friendships_destroy again. I updated a bit, but now getting a strange error and cannot trace it back.
Did you have anything like this before or another hint or reference where I can look things up ?

    [] [proxy_fcgi:error] [] [client] AH01071: Got error 'PHP message: PHP Warning:  end() expects parameter 1 to be array, null given in /var/www/friendica/include/api.php on line 389\n'


(Commit 59d086551deeceb88798414727e481d0c12c84c3 )

**Comment by MrPetovan** [comment] 2018-09-12 23:45
See https://github.com/friendica/friendica/commit/59d086551deeceb88798414727e481d0c12c84c3#r30487235

**Comment by annando** [comment] 2022-12-04 05:42
Is anything from that list still an issue?

**Comment by foss-** [comment] 2022-12-05 11:07
Wanted to give this a try. Manage to sign-in and authorize client but Twidere crashes when refreshing timeline (reproduceable). Last commit was 2021 April. Maybe efforts should rather be focused on Twidere X which is seeing active development?

Tried Twidere X (Android): But sign-in is going in circles. After landing in web UI closing and re-opening app goes to Authorize screen. Tap "yes" but user lands on sign-in page again. After another round of authorize app loads with friendica account.

[x] Seeing fully profile like "tweets", follower, following just empty (including own profile): own profile, following, followers show fine)
[x] Following people on other instances / platforms not possible (error 501): following + unfollowing mastodon account without problem
Notification / refresh may takes twice an action: unsure what to test
[x] Symbols/numer of replies: showing fine
[x] Likes don't propagate to Friendica: they do now

Please close this issue. Any remaining issues should be filed as new issues.

Should we remove Twidere from list of recommended clients?

**Closed** 2022-12-05 12:20 UTC
Labels: Enhancement, API
