### ISSUE TITLE
Support postgres PDO

### ISSUE THREAD

**Issue by Extarys** [friendica/friendica#9788] opened 2021-01-14 17:17 UTC
### Is the feature request related to a problem? Please describe.

I mostly use postgres and play with yugabyte. Having to also use mariadb takes more server resources and seems conterproductive.

### Describe the feature you'd like

Like hubzilla, add a setting on the setup page to switch to postgres.

### Describe alternatives you've considered

Rent a larger VPS to accommodate MariaDB?

### Additional context
Please? :smile: I'm not really sure how to add such options and so it would requite me a lot of effort and time to try to implement this. If anyone have the technical knowledge to do so, it would be awesome.

**Comment by MrPetovan** [comment] 2021-01-15 14:20
Thanks for the issue, it is a duplicate of an old one: #699

Long story short, Friendica was designed for the MySQL dialect, and we're currently working at abstracting the database layer to allow using PostgreSQL instead of MySQL/MariaDB, but given the sheer amount of literal queries in the code it is a long and painstaking process that fixing bugs and adding exciting new features usually overtake in terms of development priority.

**Closed as completed by MrPetovan** 2021-01-15 14:20 UTC
Labels: New Feature

**Comment by Extarys** [comment] 2021-01-15 14:59
I'm sorry I didn't find that issue earlier (I swear I search for postgres, but not postgresql oops)

Yeah I saw some work being done to change some classes, etc. I guess it will eventually get there. Thanks!

**Comment by MrPetovan** [comment] 2021-01-15 15:19
> (I swear I search for postgres, but not postgresql oops)

I did the same mistake, looking for `postgres` first didn't yield any result for me. I guess I should add this keyword in the mentioned issue.
