### ISSUE TITLE
[frio] Logo interferes with search bar on long user name and wide screen

### ISSUE THREAD

**Issue by JonnyTischbein** [friendica/friendica#5931] opened 2018-10-15 11:18 UTC
### Expected behavior
The Friendica logo moves / disappears if a long user name is displayed.
### Actual behavior
On wide screens:
![bildschirmfoto - 15 10 2018 - 13 02 05](https://user-images.githubusercontent.com/10757520/46947723-08fb2900-d07c-11e8-9eb8-3678279e4e3a.png)
On smaller screens it works:
![bildschirmfoto - 15 10 2018 - 13 02 45](https://user-images.githubusercontent.com/10757520/46947598-98540c80-d07b-11e8-9add-bfe04b3aa26a.png)
For a shorter name it works on all screen:
![bildschirmfoto - 15 10 2018 - 13 03 04](https://user-images.githubusercontent.com/10757520/46947621-b3268100-d07b-11e8-9590-84b78dd399f8.png)

### Steps to reproduce the problem
On `firefox 62.0.3` with theme `frio`: 
1. Choose a long user name
2. Open friendica on a wide screen or zoom out
(3. Zoom in / reduce window size to see the name disapear)
(4. Choose a smaller user name to see the difference)

### Friendica version you encountered
This is Friendica, version 2018.09 that is running. The database version is 1283, the post update version is 1281.

### Friendica source (git, zip)
git

### PHP version
PHP 7.0.32-1~dotdeb+8.1

### SQL version
Ver 5.5.60-0+deb8u1

**Comment by MrPetovan** [comment] 2018-10-15 13:16
Duplicate of #5729, closing.

**Closed by MrPetovan** 2018-10-15 13:16 UTC
