### ISSUE TITLE
Missing notification when Mastodon contacts sends a private post mentioning me

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8666] opened 2020-05-19 21:44 UTC
Works: Private message thread started by a Friendica user with a Mastodon user.
Doesn't: Private message thread started by a Mastodon user with a Friendica user.

**Comment by annando** [comment] 2020-05-20 06:18
That's not a bug, but a specification problem. We cannot distinguish an incoming private message from a post with a limited audience. Pleroma is sending some custom field that helps, but Mastodon doesn't.

**Comment by MrPetovan** [comment] 2020-05-20 12:45
Shouldn't I have been notified about a private post mentioning me then? Because I haven't been either.

**Comment by annando** [comment] 2020-05-20 12:52
The mentioning should have happened, yes.

**Comment by annando** [comment] 2020-09-21 05:45
Is this still an issue? These days I received such a private post from Mastodon and got notified.

**Comment by MrPetovan** [comment] 2020-09-21 11:45
I remember receiving the private posts but I wouldn't be able to tell you if I had been notified since I go through everything my followed accounts post every day.

**Comment by SpcCw** [comment] 2022-12-25 14:30
@MrPetovan 
> Doesn't: Private message thread started by a Mastodon user with a Friendica user.

This currently works (just tested it to be sure - messages go through and notifications are showing) so this issue can be closed.

There are some problems with the opposite direction now though :) But this will be hopefully resolved in https://github.com/friendica/friendica/issues/12523 - if not then I'll create a separate issue.

**Closed** 2022-12-25 15:15 UTC
Labels: Bug, Federation
