### ISSUE TITLE
Implement passkeys (WebAuthn) for user login

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#13083] opened 2023-05-04 10:43 UTC
### Is the feature request related to a problem? Please describe.
No.

### Describe the feature you'd like
Implement passkeys for user login, also called [WebAuthn](https://en.wikipedia.org/wiki/WebAuthn). 

### Describe alternatives you've considered
This is some new unfishable way to login to systems, it is some kind of one time password. 

### Additional context
Google released this for login today.
https://blog.google/technology/safety-security/the-beginning-of-the-end-of-the-password/

PHP library for WebAuthn
https://github.com/web-auth/webauthn-lib

**Comment by lapo-luchini** [comment] 2023-05-04 17:02
Seems a duplicate of #12172.

**Comment by MrPetovan** [comment] 2023-05-04 17:14
I knew the protocol name was familiar!

**Closed as not planned by MrPetovan** 2023-05-04 17:14 UTC
Labels: New Feature

**Comment by utzer** [comment] 2023-05-05 05:56
Ah sorry about that.
