### ISSUE TITLE
Allow non-users to see posts

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#9426] opened 2020-10-15 15:57 UTC
I am feeding my twitter through friendica which is great, If I post a long post it with truncate on twitter and post the link. I assumed wrongly that people could click on that link and see the rest of my post.  Well it turns out if you aren't a fediverse member you can't so the twitverse has no idea what I'm saying.  It is possible to allow outside members to see a friendica post if they have a link to it? They would of course still have to comment through twitter unless they want an account but that would drastically increase the advantage of friendica as I thought it a was also acting as a web publishing blog spot like wordpress and people outside the fediverse could see your posts.  If there is already a way to do this please reply and close the request.  Thanks!

**Comment by annando** [comment] 2020-10-15 16:05
I have the feeling as if we already have got an issue with this content. And yes, this is some issue that we have to fix.

**Comment by MrPetovan** [comment] 2020-10-16 01:58
Do you have a restrictive default post permissions (i.e. not public)?

**Comment by anubis2814** [comment] 2020-10-16 02:00
Don't think so where would that be.

**Comment by MrPetovan** [comment] 2020-10-16 02:04
In Settings -> Security and Privacy Settings -> Default Post Permissions

For example, I have this Twitter post https://twitter.com/MrPetovan/status/1313341229510225921 that came from this long post: https://friendica.mrpetovan.com/display/735a2029-715f-7bba-2d23-1e5152999485 and it is accessible by anonymous users. I do have a public default post permissions though so I was wondering if this was preventing anonymous users to see your longer Friendica posts.

**Comment by anubis2814** [comment] 2020-10-16 02:07
Nope mine is listed as public.  If you go to the post logged out it says the post was deleted, log back in and its fine.

**Comment by anubis2814** [comment] 2020-10-16 02:09
https://twitter.com/CriticalDragon1/status/1316461489260097536?s=20 Here is the link I had in a conversation. Maybe its because its a conversation because if I'm logged in it takes me to the conversation.

**Comment by MrPetovan** [comment] 2020-10-16 02:21
Ah yes, in this case it is different. We make imported Twitter conversations private to you by default in Friendica because the target account might have protected their account and making it public would be a breach of privacy. Only you have access to this conversation, and currently you have to be mindful about the length of your replies because the read more links will not be accessible to anyone but yourself.

There are several obstacles to making these imported conversations public if we could determine whether the original author's account is protected or not:
- Anyone on your node or in the Fediverse would be able to interact with it, but other replies than yours wouldn't be forwarded to Twitter because only you have set up the Twitter connector.
- We wouldn't be able to detect if the original author has changed the protection status of their account, and we can't change the privacy of a post once it's published, especially not a public one, so it would be a breach of privacy once more.

**Comment by anubis2814** [comment] 2020-10-16 02:23
So there is no way you can just make it like an individual post when seen by someone outside?

**Comment by MrPetovan** [comment] 2020-10-16 02:28
You can quote share the original Twitter post with your longer response. Since it's going to be a new conversation, it won't be private anymore and the link will be accessible to anyone else.

**Comment by MrPetovan** [comment] 2020-10-16 02:29
I can't promise the original author will be mentioned, although it is probable.

**Comment by anubis2814** [comment] 2020-10-16 02:31
Gotcha Thanks!

**Comment by foss-** [comment] 2020-10-16 13:04
Dupe of https://github.com/friendica/friendica/issues/6853?

**Comment by MrPetovan** [comment] 2020-10-16 13:33
It is, yes.

**Comment by tobiasd** [comment] 2021-10-01 16:13
closing as it is a dupe.

**Closed as completed by tobiasd** 2021-10-01 16:13 UTC
Labels: Sup­port Request
