### ISSUE TITLE
Error when trying to login with Mastodon Android app

### ISSUE THREAD

**Issue by kalon33** [friendica/friendica#13548] opened 2023-10-15 20:33 UTC
- [X] I have searched open and closed issues for duplicates

### Bug Description

Trying to connect to a Friendica instance using Mastodon Android app seems to lead to an error. Surprisingly, I've no problem with it on another phone where I'm connected for months.

The error is:

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 22 column 25 path $.contact_account

Was the compatibility broken somewhere? The spec may have evolved on Mastodon side?

### Steps to Reproduce

1.  Open Mastodon Android app
2.  Connect using a custom server, to use a Friendica 2023-05 instance (I tried mine, social.badabam.net)
3. Got the error message trying to choose the server, I couldn't even try to enter the credentials

Actual Result:

Couldn't use the Mastodon app with a Friendica instance.

Expected Result:

I wish I could use it as before.

### Screenshots

![0f67c84d-8ac9-4b18-b08b-a3491ed9c9f0.jpg](https://github.com/friendica/friendica/assets/460731/e744b6a1-66cf-4b20-9ecd-272aef647990)

### Platform Info

Friendica Version:

2023-05

Friendica Source: GitHub, releases section from the repo

PHP version: 8.1

SQL version:

Thanks for your help and work!

**Comment by MrPetovan** [comment] 2023-10-15 20:58
Thank you for the report, this is a duplicate of https://github.com/friendica/friendica/issues/12530

**Closed as not planned by MrPetovan** 2023-10-15 20:58 UTC
Labels: Bug
