### ISSUE TITLE
At times private messages are sent to random users

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#11274] opened 2022-02-22 11:45 UTC
We have discussed this here https://social.trom.tf/display/dbc8dc44-1462-13a9-5919-bb3918828493

Basically I was sending a private message to someone who was not in my contacts list, and the message landed on a random user's "inbox". Others have reported it too. 

`This is Friendica, version 2021.09 that is running at the web location https://social.trom.tf. The database version is 1434/1434, the post update version is 1427/1427.`

**Comment by foss-** [comment] 2022-02-22 11:53
Can confirm this. I messaged myself and the message was sent to a random user from my contact list instead. The fact that Tio's message ended up with a user not even on their contact list is even more worrying.

EDIT: This is Friendica, version 2022.05-dev that is running at the web location https://squeet.me. The database version is 1452/1452, the post update version is 1452/1427.

**Comment by MrPetovan** [comment] 2022-02-22 12:10
@annando Are you looking into this?

**Comment by MrPetovan** [comment] 2022-02-22 13:13
This sounds like a confusion between public contact id and user-specific contact ids.

Does it always send the message to the same wrong recipient?

**Comment by tio-trom** [comment] 2022-02-22 13:19
> Does it always send the message to the same wrong recipient?

Sending to user A, always sends it to use B, in my experiment with 2 contacts. I do not know if I would send a message to user C that's also not in my contacts list, if that would reach the same user B. I  am a  bit concerned to keep on testing because I may bother people.

**Comment by MrPetovan** [comment] 2022-02-22 13:35
I understand your reticence, you've already been very helpful. It seems it sends the message to the same unexpected user, not a different random user each time.

**Comment by MrPetovan** [comment] 2022-02-22 13:41
Another question: In your Private Message list, does the message show as wrongly addressed?

**Comment by tio-trom** [comment] 2022-02-22 13:43
So I click to create a new message and I add user A. Click send then in the messages it shows user B.... So it shows user B.

**Comment by MrPetovan** [comment] 2022-02-22 13:44
Ok thanks!

**Comment by MrPetovan** [comment] 2022-02-22 13:47
Reproduced on my dev node, I can type anything in the recipient field and the message will be saved with another recipient.

**Comment by MrPetovan** [comment] 2022-02-22 13:54
New test: if I don't pick a valid recipient in the field, it always saves the same wrong contact. I'm closing in.

**Comment by informapirata** [comment] 2022-02-22 14:23
I tried to send a direct message to one user, but it was sent to a different user.

That user was not a random user, but the last user that was reported to me in the notification panel as he was the last user who had mentioned me in chronological order

(Friendica, ver. 2022.02 in esecuzione all'indirizzo web https://poliverso.org)
https://poliverso.org/display/0477a01e-2062-13b2-904d-6de302529589

**Comment by MrPetovan** [comment] 2022-02-22 14:31
In the New message  page, there is a `<select>` tag with all the valid targets that is taken over by the Javascript-powered tags input, when no valid targets are selected in the field, the last option is selected by default.

**Comment by MrPetovan** [comment] 2022-02-22 14:33
I'll try with vier but I believe this issue is limited to frio.

**Comment by MrPetovan** [comment] 2022-02-22 14:34
Nevermind, it affects vier as well, an empty/invalid recipient will make the message be sent to the last option in the select, again because of the autocomplete overlay.

**Comment by MrPetovan** [comment] 2022-02-22 14:56
The autocomplete overlay changes all the `<option>` tags in the `<select>` to be selected by default, even if no element has been selected via the autocomplete. I'm not sure why is that but we are using a modified version of the library already so I can further tinker with it.

**Comment by MrPetovan** [comment] 2022-02-22 15:06
I managed to fix the technical issue, but I'm still not comfortable with the solution. The form doesn't submit anymore when no valid recipient is selected, but it doesn't show what the issue is either because the original form input is hidden from view so the error message the browser wants to display doesn't show either.

The alternative is to use the HTML-native autocomplete feature with `<datalist>`, but we'd loose the nice autocomplete display with the avatar picture and the webfinger address.

What do you think?

**Comment by annando** [comment] 2022-02-22 15:11
Can we use the selector that we use in the ACL stuff?

**Comment by MrPetovan** [comment] 2022-02-22 15:12
It is the same selector, but in the post ACL stuff we don't expose all the possible values in an underlying `<select>` element.

**Comment by MrPetovan** [comment] 2022-02-22 15:15
The relative good news is that this issue was only sending messages to people we were supposed to be able to send messages to. The bad news is that the check we perform when saving the message is less restrictive than the one populating the list of valid recipients which means someone could send private messages to remote contact who haven't accepted the follow request yet.

I'm not sure if the fraudulent message would be accepted on the remote node but it definitely is a possibility.

**Closed as completed** 2022-02-24 04:16 UTC
Labels: Bug
