### ISSUE TITLE
Pages display in non-English language erroneously

### ISSUE THREAD

**Issue by Throne3d** [friendica/friendica#3138] opened 2017-01-30 15:06 UTC
For some reason, pages seem to ignore that I have English at the top of my language priority list, and instead pick the first non-English language in the list.

For example, [Libranet](https://libranet.de/register) displays in Dutch on Chrome (which has a language list of: English (United Kingdom), English, English (United States), Dutch, Italian, French, Japanese) and in French on Firefox (which has a language list of: English/United Kingdom [en-gb], English [en], French [fr]). If I reorder Chrome's language list to put Italian above Dutch, the page instead shows in Italian, and likewise if I put French above the others, even though I have the first three "English" types above them all.

The same thing happens with [Nerdica](https://nerdica.net/) and [Friendica.eu](https://friendica.eu/), so it doesn't seem to be isolated to just Libranet.

Example (screenshot):
![image](https://cloud.githubusercontent.com/assets/577128/22428000/41689a44-e6fd-11e6-9c69-b6ef834f2579.png)

Chrome language settings:
![image](https://cloud.githubusercontent.com/assets/577128/22428025/63e27338-e6fd-11e6-8830-31a27f9e4137.png)

Is this intentional for some reason, or have I encountered a bug?

*Edit*: If I remove these languages then the page does in fact display in English, so it's definitely available, but it ignores this when I have non-English languages in the list.

**Comment by tobiasd** [comment] 2017-01-30 15:22
This might be resolved in current development branch (see #/2752) which will be released soon as 3.5.1 (friendic.eu is on current stable 3.5)

**Comment by Throne3d** [comment] 2017-01-30 15:25
Oops. Sorry if it's a duplicate.

I'll let you know then?

**Comment by tobiasd** [comment] 2017-01-30 15:29
Sure :-)

**Comment by Hypolite** [comment] 2017-04-19 15:23
Closed as duplicate of #2752 and fixed by #2842 and #3355

**Closed by Hypolite** 2017-04-19 15:23 UTC
Labels: Bug
