### ISSUE TITLE
Images missing in quoted AP reshares when hashtags are added

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10454] opened 2021-07-01 08:13 UTC
Currently my time is limited. I will provide more info later today.

- [YES] I have searched open and closed issues for duplicates

### Bug Description

Later: A user of my node discovered that in quoted reshares the images of the original posts are missing. In the provided example the original has 4 attached images. The quoted reshare only has 0 image attached.

**Important! Add some hashtags above or below the quoted content**

Original post on Mastodon: https://climatejustice.global/@ViennaForFuture/106503299872975174
Original post on Friendica: https://libranet.de/display/ad799dbe-8922f586b7a37b05-4d141fb3
Quoted reshare on Friendica: https://libranet.de/display/0b6b25a8-1060-dd65-2e8d-fc1439086198

Discussion: https://libranet.de/display/0b6b25a8-1260-dd69-04de-248168845767

### Steps to Reproduce

1.  look for an AP post with multiple images attached
2.  quote-reshare it with adding some hashtags (!!!)
3.  look how many images are attached to the reshare

**Actual Result:**

No image is attached.

**Expected Result:**

All 4 images should be attached.

### Platform Info

Friendica Version:
2021.06-rc 1423 (in the meantime I have pulled the latest changes)

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by AlfredSK** [comment] 2021-07-01 18:22
Completed the description of the issue.

**Comment by AlfredSK** [comment] 2021-07-01 18:29
Ok. I tried to reproduce the issue myself. But it worked. So, maybe it has been fixed in the meantime or it was the Luftfeuchtigkeit again. :-)

I'll wait for confirmation of the user who reported it and then possibly close this.

**Comment by AlfredSK** [comment] 2021-07-01 18:42
Btw. is it the expected (new) behavior that remote images are now linked directly to the remote server? When I click on one of the images I'm redirected to the page/site where the original image is hosted. Previously the images were loaded from the local proxy folder.

**Comment by AlfredSK** [comment] 2021-07-01 19:20
For reasons unknown the user can still reproduce it. :-( But I tried it several times. For me it works.

I have pretty much of this in my log:

```
2021-07-01T19:10:08Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":117,"function":"rawContent","uid":"aee338","process_id":25496}
2021-07-01T19:10:08Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":117,"function":"rawContent","uid":"33a945","process_id":4166597}
2021-07-01T19:15:12Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":117,"function":"rawContent","uid":"be32b5","process_id":4165609}
2021-07-01T19:15:12Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":117,"function":"rawContent","uid":"b289db","process_id":37391}
```

The photo ID `.` looks weird.

**Comment by AlfredSK** [comment] 2021-07-01 20:56
Now I can reproduce it!

You need to **add some hashtags** above or below the quoted content.

**Example:**

```
#LobauBleibt #Wien #fff #FridaysForFuture #Klimakatastrophe 

[share author='FFF Wien - #LobauBleibt' profile='https://climatejustice.global/users/ViennaForFuture' avatar='https://libranet.de/photo/22409539915e4e3625e9cc2628583285-5.png?ts=1625107517' link='https://climatejustice.global/@ViennaForFuture/106503299872975174' posted='2021-07-01 03:49:47' guid='ad799dbe-8922f586b7a37b05-4d141fb3']Wir haben die "Klimamusterstadt Wien" begraben - denn diese Klimapolitik bringt uns direkt auf den HIGHWAY TO HELL

Die Ignoranz der Politik in Sachen Klimakrise gefährdet Leben. Wir lassen ein "Weiter wie bisher" und neue Autobahnen nicht zu! Komm daher am Freitag zur Großdemo gegen die Lobau-Autobahn!

Herzliches Beileid, Bürgermeister Ludwig.[/share]
```

**Result: (attached images missing)**

![IMG_20210701_225320](https://user-images.githubusercontent.com/3656054/124188242-4a97c080-dabf-11eb-8d91-525054e1b101.png)

**When I remove the hashtags:**

![IMG_20210701_225354](https://user-images.githubusercontent.com/3656054/124188311-64390800-dabf-11eb-81ac-101763af241d.png)

**Comment by annando** [comment] 2021-07-02 04:40
I think that we have got two different problems here. One seems to be the hashtags above the share. The other one (that is fixed in https://github.com/friendica/friendica/pull/10456) touches a problem with hashtags in author names.

**Comment by AlfredSK** [comment] 2021-07-02 06:18
Yep. Interesting. :-)

Here, without a hashtag in the username, it works. I haven't pulled the latest commits yet.

![IMG_20210702_081632](https://user-images.githubusercontent.com/3656054/124229567-1ac3d980-db0e-11eb-8982-fa4e42292e38.png)

**Comment by AlfredSK** [comment] 2021-07-02 07:17
With #10456 I can quote-share the original post with additional hashtags now. I tested it with the preview (didn't submit the post). The images are displayed now.

**Comment by AlfredSK** [comment] 2021-07-02 16:11
From linked PR: 
> "This should be finally fixed at another place, but this is a working quickfix."

Should I leave the issue open? The user reported it is working now.

**Comment by tobiasd** [comment] 2021-07-02 16:13
Yes, I think we keep this Issue open as an reminder for the later fix.

**Comment by norz** [comment] 2021-07-20 10:16
(I haven't followed the development closely, but) in my experience the `"Quote Share"` feature has this bug for a few months now : it seems that in the generated bb code the `[img]` and `[video]` tags are systematically missing.  

Unsure if the protocol of the original message plays a role : this bug happens also when the message comes from Twitter for instance. [^1] 

---
[^1]: ex:  https://libranet.de/display/a6551d717d2e8e44dbbbc5e85635e3f20bd42605

version: 2021.09-dev (mention for quick search: @norz)

**Comment by norz** [comment] 2021-07-20 10:22
**Workarounds** 
- easy: somehow bring the message on Hubzilla, then use the generated bbcode in Friendica  
- hard: find the resources (images, video, ...) urls and add them manually.

**Comment by annando** [comment] 2021-09-04 08:48
@norz can you create a separate issue for this? The original issue was caused by a hashtag in the author name, your issue most likely is caused by something else. But since the original poster's issue was solved, I would like to have it handled in separate issues. Please also have a look if the issue is only present in imported Twitter posts fore example.

**Comment by AlfredSK** [comment] 2021-10-01 16:20
...will try to reproduce this again.

**Comment by AlfredSK** [comment] 2021-10-01 16:30
Looks like its's working now!

![grafik](https://user-images.githubusercontent.com/3656054/135655467-03b0d53e-f62e-4501-b08a-694658ac843d.png)

Author has a hashtag in their name and I added some hashtags to the reshare? Closing?

**Closed as completed** 2021-10-01 16:56 UTC
Labels: Bug
