### ISSUE TITLE
Posts from private account are showing in Atom feed

### ISSUE THREAD

**Issue by gurussia** [friendica/friendica#4477] opened 2018-02-20 06:34 UTC
enter in friendica profile, he disable unknown peoples to see you, now go to atom read and you will see that they can read his public timeline and his account is disabled from public.

**Comment by tobiasd** [comment] 2018-02-20 16:04
I could not reproduce this with either the stable or the development branch. Just for clarification

 * I created a new account, set the details to hidden
 * I posted a public note saying something like "Test"
 * I opened a different browser and entered the profile URL or the test account.
 * There I was greeted with the notification bubble that the details of that account are hidden.
 * However here is a button with the link to the Atom feed in the side panel (that should maybe removed) but when I open that Atom feed no postings are in there.

Could you send me an email (encrypted if you like) to `tobias(dot)diekershoff(at)gmx(dot)net` peplace the `(dot)` and `(at)` with `.` and `@`, providing me a link to the profile in question so I can have a look.

**Comment by gurussia** [comment] 2018-02-20 19:06
tobiasd here is photo: https://bgzashtita.es/git/peturbg/for-all-descentralized-social-networks/issues/1

I try from firefox without user login " log from friendica and open new firefox after that point profile and atom feed and it comment, private wall messages, include private profile photo.

**Comment by tobiasd** [comment] 2018-02-21 06:30
There is something wrong in your setting. See [Jolly J.](https://snarl.de/~jollyj) it's the test account I created on the stable branch version of Friendica. When you open the Atom feed, do you see the postings I made with that account?

Please make sure that you selected

    Settings -> Account -> Security and Privacy Settings -> Hide your profile details from unknown viewers

so that the `YES` is visible and the `NO` is hidden by the slider.

From your screen-shot I cannot  tell what went wrong ;-) that is why I asked for the profile URL send to me privately by email. I will delete it after this issue is solved!

Regarding the profile image you are right, the profile picture of the main profile is not considered private. Same is true for the display name and the profile address. You can enable additional profiles in the settings and then create as many profiles you like, containing information you don't want to share on the main profile. These information are only view-able to contacts you select to show them the other profile.

**Comment by gurussia** [comment] 2018-02-21 08:25
when it go to settings it comment profile is not published. strange this is wrong thinking. So it comment Hide your profile and this need to be Yes. Yes for hide your profile and No don't hide your profile. Include if it is selected No it is worse, when you open /profile/user it show completly user profile. If Yes is triggered the same, it show user wall picture, include in the developer version it don't show atom feeder. in stable version there is atom version.

**Comment by MrPetovan** [comment] 2018-02-21 13:07
Not published means your profile won't appear in public directories, but it doesn't mean your profile is private.

**Comment by tobiasd** [comment] 2018-02-21 13:42
I will add some help texts to the settings which hopefully will clarify the meaning of the options.

**Comment by gurussia** [comment] 2018-02-22 12:10
petovan what is word HIDE. "  verb (used with object), hid, hidden or hid, hiding.
1.
to conceal from sight; prevent from being seen or discovered:
Where did she hide her jewels?
2.
to obstruct the view of; cover up:
The sun was hidden by the clouds.
3.
to conceal from knowledge or exposure; keep secret:
to hide one's feelings. "

http://www.dictionary.com/browse/hide

So if option is Hide Yes. this mean, to conceal from sight; prevent from being seen or discovered. So if someone press Yes hide, this mean his profiles is hide. This mean, yourdomain.com/profile/user and hire is Yes, then this need to write "TRUE this profile is hide " Or user has to put message that he write when his profile is hide or only profile is private, but private is another dictionary word. So in this case, it depend on the user what to do, but if you make hide, then stick to dictionary HIDE.

When hide is Yes - > to conceal from sight; prevent from being seen or discovered. But if user Hide is yes and someone go to yourdomain.com/profile/user and ihs profile is hide, it will show his profile, so this is not hide, this is exposure, breaching of security, violating of humankind rights. Hide is hide. But lets get from this corrupted cambridge dictionarry: https://dictionary.cambridge.org/es/diccionario/ingles/hide

 to put something or someone in a place where that thing or person cannot be seen or found, or to put yourself somewhere where you cannot be seen or found: 

to prevent something from being seen:

to not show an emotion: 

If you hide information from someone, you do not allow that person to know it: 

Past 20 years word HIDE was hide. Now in in 21 century everybody try lie, hide mean different things. But i assure you, when you comment hide is hide, ask your grandmother and your grandfather and they will tell you HIDE is hide. Why corrupted cambridge comment hide his emotions, becouse cambridge are STUPID. every normal person will understand that hide is hide, include when someone don't tell his real feelings, but here it enter in corrupted legal justice system. Peoples hide they real feelings, becouse justice system tell them to do in some countrys it is prohibited, forbiden to tell true. Include in sweden or in some country there is less men and women has to share men, it has been seen in this country that 4 women are walking with 1 men. So men is the most important from women, from men depend the future of the life. only men can have sperm, and sperm make baby. In england there was men who make from his sperm baby. If someone see he will know that in future humankind will be general slaved, this what you today in year 2018 will be privilege, in the future nobody will have privilege to have this freedom that peoples had in year 2018.

**Comment by annando** [comment] 2018-02-22 13:00
I guess the best thing to test this is:
* Please post a screenshot of your settings. It doesn't matter if they aren't in english.
* Provide us with a link to the profile.

I have the feeling that we are having massive communication issues. I guess that we are talking about different things.

**Comment by tobiasd** [comment] 2018-02-22 16:23
The problem may be, that in the settings there is no information about what the "details" are, that are hidden.

**Comment by gurussia** [comment] 2018-02-23 18:04
https://bgzashtita.es/git/for-all-descentralized-social-networks/friendica/issues/3

Maybe this is misconfiguration in what exactly is word. Open your dictionary and seek for word: HIDE:

If you tell on young person 9 years. I will count to 10 sec. go and hide, he is gonna hide. So this mean, you are opening friendica profile and it don't hide profile, this mean leak data, in the moment it leak 5 sensible data. Open website on the beggining of this message and you are gonna see it.

Include in the upper rights comment restricted... Do you know what restricted really mean. So get militarry they have restrictd area mean, nothing is visible what they do. So this is not really restricted.

**Comment by tobiasd** [comment] 2018-02-24 07:53
>  Open your dictionary and seek for word: HIDE:

And? The options is to hide details. Not your entire profile, and details are hidden. A PR with clarifying help texts is done.

As I said above, you always can create additional profiles and fill the public one with fake content you like. With the other profiles only shown to contacts you elect to be seen, so you can control which postings and profile information are shown to which contacts.

If you want a "social network" that does not show anything about it's users to anybody, then maybe Friendica is not the fitting platform for your needs. Obviously our use case in mind does not fit that use model.

**Comment by tobiasd** [comment] 2018-02-24 10:36
Regarding some of the points you address in the linked entry (I would really appreciate if you would not link to external platforms but keep the information in this thread).

 * the "e-mail" is not an e-mail address, but a different representation of the profile URL commonly used by decentral social media platforms (diaspora*, GNU social, Hubzilla, Mastodon to name some). It is simply nick@server
 * display name and profile picture are there, as we assume that users want to be found by other members of their social network, e.g. the node they are using, even if they do not want to share their content and other details with the internet. As said before, you can configure additional profiles, showing different information.

**Comment by gurussia** [comment] 2018-02-24 12:18
tobiasd you are contradicting yourself include you are wrong. What is HIDE.

tobiasd " And? The options is to hide details. Not your entire profile, and details are hidden. A PR with clarifying help texts is done. " HIDE is hide -> if it is not hide then it is not hide.

tobiasd " As I said above, you always can create additional profiles and fill the public one with fake content you like. With the other profiles only shown to contacts you elect to be seen, so you can control which postings and profile information are shown to which contacts. " tobiasd so in the real life you are Lying, robbery... i have goodluck not to know you i  real life, i dont like peoples who intent lying, robbery, intimidate, kill and etc. So making fake profile is LYING. why you make friendica when friendica is social network. If you put option HIDE in your friedinca then everybosy know you. So why in 21 century much more crimes, from 20 century or from 19 centruy. guys you can look bad example of tobiasd, this is bad thinking FAKE. in 20 century include in 19 peoplea didnt know woed FAKE, it was some bad. now whrn you see someone who kill other with sometbing dont HESTITATE and DONT DISTURB, becouse as i say tobiasd is the perfect profile for MAKING CRIME. 

tobiasd im sure you cant tell facebook you are FAKE profile. wowowowo... tobiasd " option is to hide details " tobiasd did you make crime to hide your profile. 


guys im busy. so maybe this will be the last message. and guys if you can move to diaspora i didnt see it, but people commemt diaspora have more addons include facebook

**Comment by annando** [comment] 2018-02-24 12:46
On Diaspora you cannot hide neither your name, your avatar or your public posts. But if you are so focussed on privacy, you could also have a look at Hubzilla.

**Comment by annando** [comment] 2018-03-11 21:31
Closing it for now.

**Closed by annando** 2018-03-11 21:31 UTC
Labels: Sup­port Request
