### ISSUE TITLE
Upload of images broken when 'js_upload' is used

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7880] opened 2019-11-29 19:57 UTC
### Expected behavior
When the add-on 'js_upload' is used the upload of new images should work.

### Actual behavior
When the add-on 'js_upload' is used the upload of new images doesn't work anymore. After selecting an image/photo nothing happens and an error pops up in the browser console.

```
upload:482 Uncaught TypeError: Cannot read property 'length' of null
    at getSelected (upload:482)
    at Object.onSubmit (upload:537)
    at qq.FileUploader._uploadFile (fileuploader.js:395)
    at qq.FileUploader._uploadFileList (fileuploader.js:388)
    at qq.FileUploader._onInputChange (fileuploader.js:372)
    at Object.onChange (fileuploader.js:309)
    at HTMLInputElement.<anonymous> (fileuploader.js:825)
```

Probably related to the changes that came with PR #7876 

### Steps to reproduce the problem
Enable add-on 'js_upload'. Go to .../photos/$user/upload. Click on 'select files for upload' or drag&drop an image to the drop zone.

### Friendica version you encountered the problem
2019.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by MrPetovan** [comment] 2019-11-30 15:56
I enabled the `js_upload` addon but nothing displays differently, neither on the Compose page nor on the frio jot, I have no idea how to use or test it. Can you be more specific about the theme and page you experienced this issue?

**Comment by AlfredSK** [comment] 2019-11-30 16:22
Ok. I created a photo story. :-)

### Steps to reproduce the problem
Enable add-on 'js_upload'. **Go to .../photos/$user/upload**. Click on 'select files for upload' or drag&drop an image to the drop zone.

![1](https://user-images.githubusercontent.com/3656054/69903109-c7b7fc80-1395-11ea-84cf-06e552732f3b.png)

![3](https://user-images.githubusercontent.com/3656054/69903112-cedf0a80-1395-11ea-838a-267f584e59b4.png)

![4](https://user-images.githubusercontent.com/3656054/69903114-d43c5500-1395-11ea-821a-245b5688ecb2.png)

![5](https://user-images.githubusercontent.com/3656054/69903115-da323600-1395-11ea-8f53-69a7dd076d3f.png)

**Comment by MrPetovan** [comment] 2019-11-30 16:24
Oh, nothing to do with the Compose page or the new ACL then?

**Comment by AlfredSK** [comment] 2019-11-30 16:29
Well it worked before I pulled the ACL PR. And it works when I locally revert that PR. There is a permission button in that dialogue! I guess it has something to do with that.

**Comment by MrPetovan** [comment] 2019-11-30 16:31
Ooooh.

**Comment by MrPetovan** [comment] 2019-11-30 17:08
Caused by #7876
Fixed by https://github.com/friendica/friendica-addons/pull/914

**Closed** 2019-11-30 19:52 UTC
Labels: Addons, Bug

**Comment by AlfredSK** [comment] 2019-11-30 21:14
Works very well now. Thank you!
