### ISSUE TITLE
Cannot interact on certain posts

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#11276] opened 2022-02-23 12:48 UTC
This is so weird and it started months ago. Example: I have a page trom@social.trom.tf and a friend roko@social.trom.tf. I am the owner of the page and my account is tio@social.trom.tf. All are on the same Friendica node. TROM makes a post. I can comment on it or like it, no problems. ROKO comments on the post. Now I want to reply to his comment or like his comment. But I cannot. No error message for the like behavior, and when I comment it takes a while to then (at times) see an error like Permission Denied.

This is the post I recently saw the issue https://social.trom.tf/display/dbc8dc44-8662-15a3-bfb0-b8c579156227

The TROM page is that kind of profile that accepts all friend requests automatically. I also "follow" the page.
 
I am baffled because this used to work. And it works to reply to other accounts that comment on that page, but not to some. And I never encountered this issue with any post on the fediverse so far.

How can we debug this?

Thanks!

**Comment by tio-trom** [comment] 2022-03-06 19:05
Ok found new ways of replicating from yet another account. Account S wants to like the comment from user R on a post made by page T. If user S sees the post itself (not on the page, but the post itself in the newsfeed or as a standalone) she cannot do that. But if she goes on page T and finds the post there, she can interact. We are talking about likes, dislikes, comments, etc. 

And she sees again Permission Denied.

**Comment by futureisfoss** [comment] 2022-03-30 16:15
https://user-images.githubusercontent.com/79040025/160881953-ee0e6e55-a80c-4aec-ba04-82fcfbf6227f.mp4

This video shows the problem of liking posts, it just keeps loading and then nothing happens. This only happens on some posts and I don't know why.

**Comment by futureisfoss** [comment] 2022-03-31 03:45
For some reason, the above video file is only playable on chromium browsers. I think its the issue of my recording, sorry.

**Comment by tio-trom** [comment] 2022-05-08 17:26
I think after we upgraded Friendica now seems to be ok. If @futureisfoss can please check too then I can close this issue.

**Comment by futureisfoss** [comment] 2022-05-11 08:15
I tested this on the same post shown on the video above, before I was not able to like that post but now its working fine. So I think maybe the issue is fixed now :)

**Closed as completed** 2022-05-11 09:45 UTC
Labels: Bug
