### ISSUE TITLE
Contact Details Submit button takes you to contacts/{id} instead of contact/{id}

### ISSUE THREAD

**Issue by zeroadam** [friendica/friendica#5943] opened 2018-10-17 11:09 UTC
### Expected behavior
Visit the details of one of your contacts, maybe add a note, or uncheck the hide this contact from others checkbox. Click Submit. Page submits changes and displays the contact details.

### Actual behavior
Clicking submit takes you to url/contacts/{id} and displays a empty page with "Page not found" at the top (header)

### Steps to reproduce the problem
Click any submit button on the contact details page.

### Friendica version you encountered the problem
Current dev branch as of 0700 EST

see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
2018.12-dev
The database version is 1287, the post update version is 1281

### PHP version
7.2.11

**Comment by zeroadam** [comment] 2018-10-17 11:28
https://github.com/friendica/friendica/pull/5944

I also see two references in include/conversation.php but thought it looked related to Diaspora and didn't change that....

**Comment by MrPetovan** [comment] 2018-10-17 11:41
Caused by #5891

**Comment by MrPetovan** [comment] 2018-10-17 11:43
> I also see two references in include/conversation.php but thought it looked related to Diaspora and didn't change that....

These instances still have to be changed:

https://github.com/friendica/friendica/blob/a21c1deb7e555940fb46c62414e65f68b9509cdd/include/conversation.php#L855-L858

**Comment by zeroadam** [comment] 2018-10-17 11:50
https://github.com/friendica/friendica/pull/5945

**Comment by MrPetovan** [comment] 2018-10-17 11:54
Closed via #5944 and #5945, thanks for your work!

**Closed by MrPetovan** 2018-10-17 11:54 UTC
Labels: Bug

**Comment by zeroadam** [comment] 2018-10-17 11:55
Welcome, It's been a while.. this was a quick little one! 😀
