### ISSUE TITLE
2023.3-rc WPoD - PHP

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#12979] opened 2023-04-08 09:57 UTC
After updating to the last 2023-rc, after I loggged in,  I get a White Page Of Death on the network page and the PHP log says

`[07-Apr-2023 21:34:39 UTC] PHP Notice:  Object of class Friendica\App\BaseURL could not be converted to int in /FRIENDICAWEBPATH/src/Model/Profile.php on line 337`

Using PHP 7.4 / Apache 2

**Comment by MrPetovan** [comment] 2023-04-08 14:31
Thank you for your report, can you please confirm what's on line 337 of your `/FRIENDICAWEBPATH/src/Model/Profile.php` file?

**Comment by hoergen** [comment] 2023-04-08 17:54
Its exactly the same like in here 

https://github.com/friendica/friendica/blob/c80566157e6e9b66ddf6226d00b48caaa331a653/src/Model/Profile.php#L337

After the error occured I did a hard reset that deletes all different files,mirroring the repos again and copying back config files from backup.

```
git reset --hard
git clean -dfx
```

But the error stayed.

**Comment by hoergen** [comment] 2023-04-10 06:22
Is there a workaround or something? My whole instance is completely unusable aka down since days now.

**Comment by AlfredSK** [comment] 2023-04-10 10:11
Are all pages not working or does the problem only occur on the network page? Can you manually go to other pages like settings or your profile page?

**Comment by MrPetovan** [comment] 2023-04-10 12:12
I'm not able to reproduce the problem in isolation and you have been the only one reporting the issue so I'm not exactly sure how to proceed. This line is only supposed to be hit for anonymous users browsing local user profiles so I don't think it should break your node after you log in. Are you sure there isn't another Fatal Error in your log?

Push comes to shove, we'll have to debug it directly on your live node, let me know if you'd like us to have a video chat.

**Comment by hoergen** [comment] 2023-04-10 13:16
> Are all pages not working or does the problem only occur on the network page? Can you manually go to other pages like settings or your profile page?

It seems it is the network,profile, community page that are completely blank.
I can reach the /message , /calendar /contact page. And when im there i can reach all the other setting pages (User/Mod/Admin) that's it .

I can see the notifications there, but if I click on them I get the blank page again.

I restarted apache, phpsession and cleaned up all firefox caches or cookie thingys. But that didn't help.

**Comment by MrPetovan** [comment] 2023-04-10 16:20
Thank you for the elaboration, the offending code displays the VCard for contacts, so it makes sense that it would stunt the network and community pages but not the message, calendar or contact pages.

I reiterate my offer for a remote conference, something looks very wrong with your system only, so the only way to get to the bottom of it is to debug on it.

**Comment by hoergen** [comment] 2023-04-10 18:09
> I reiterate my offer for a remote conference, something looks very wrong with your system only, so the only way to get to the bottom of it is to debug on it.

With "system" you mean friendica? That would be really strange because it is the exact mirror, except of the config, the homepage.html, css, pageheader.html .

**Comment by MrPetovan** [comment] 2023-04-10 18:51
I mean your server. With the exact same code I'm not getting the error, and nobody else so far has reported the same issue. I'm running PHP 7.4 as well so it isn't a version issue between us.

**Comment by hoergen** [comment] 2023-04-10 19:12
> I mean your server. With the exact same code I'm not getting the error, and nobody else so far has reported the same issue. I'm running PHP 7.4 as well so it isn't a version issue between us.

The server is running different other services with php flawlessly. (cloud, several blogs, rss server, wikis etc) 

I still think there is something wrong in the database still since years, where @annando already spent some times on it. Like I couldn't see as admin another user on my Friendica. Or I am not able to see my own Forums and so on and so forth. 

So I don't think its coming from the operating system and related services, because there every service is working since years with several updates on OS and application side.

**Comment by annando** [comment] 2023-04-10 20:59
Database issues don't cause these problems.

For testing purposes you could try changing that line to:
`if (!empty($profile['nickname']) && strpos($profile_url, DI::baseUrl()->__toString()) === 0) {`

**Comment by hoergen** [comment] 2023-04-10 22:15
> if (!empty($profile['nickname']) && strpos($profile_url, DI::baseUrl()->__toString()) === 0) {

I tried, but that didn't do the trick. Still the same  :(

I noticed something else, while I was trying to force the error. The entry in the log file can't be forced by me. It is forced by something else. Look at the times when the error hapens. I tried to force it  at 21:48 

```
[10-Apr-2023 20:08:43 UTC] 
[10-Apr-2023 20:08:43 UTC] 
[10-Apr-2023 20:23:05 UTC] 
[10-Apr-2023 20:40:11 UTC] 
[10-Apr-2023 20:40:11 UTC] 
[10-Apr-2023 20:57:56 UTC] 
[10-Apr-2023 21:02:42 UTC] 
[10-Apr-2023 21:10:04 UTC] 
[10-Apr-2023 21:11:12 UTC] 
[10-Apr-2023 21:12:23 UTC] 
[10-Apr-2023 21:12:24 UTC] 
[10-Apr-2023 21:12:24 UTC] 
[10-Apr-2023 21:16:50 UTC] 
[10-Apr-2023 21:34:24 UTC] 
[10-Apr-2023 21:38:55 UTC] 
[10-Apr-2023 22:01:25 UTC]
[10-Apr-2023 22:03:33 UTC]
[10-Apr-2023 22:03:53 UTC]
```
So maybe this isn't the error causing the WPoD, But there is no other error in the php log file. Now i have questions .....

**Comment by annando** [comment] 2023-04-11 01:43
Search for `[ERROR]` entries in the friendica log as well.

**Comment by hoergen** [comment] 2023-04-11 06:54
Ok I am having an eye on it and document it here

Currently there is this tumblr thingy

`2023-04-11T06:50:44Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected '|', expecting '{'" at /FRIENDICAPATH/addon/tumblr/tumblr.php line 469 {"exception":"ParseError: syntax error, unexpected '|', expecting '{' in /FRIENDICAPATH/addon/tumblr/tumblr.php:469\nStack trace:\n#0 /FRIENDICAPATH/src/Core/Hook.php(198): Friendica\\Core\\Hook::callSingle()\n#1 /FRIENDICAPATH/src/Core/ACL.php(300): Friendica\\Core\\Hook::callAll()\n#2 /FRIENDICAPATH/src/Module/Conversation/Network.php(164): Friendica\\Core\\ACL::getFullSelectorHTML()\n#3 /FRIENDICAPATH/src/BaseModule.php(244): Friendica\\Module\\Conversation\\Network->content()\n#4 /FRIENDICAPATH/src/App.php(700): Friendica\\BaseModule->run()\n#5 /FRIENDICAPATH/index.php(51): Friendica\\App->runFrontend()\n#6 {main}"} - {"file":null,"line":null,"function":null,"request-id":"643503443b39c","uid":"23ad01","process_id":87646}`


And this DB Server has gone away, but this must be a remote message, because the db server on my system is running smooth

`2023-04-11T06:54:43Z worker [ERROR]: DB Error {"code":2006,"error":"MySQL server has gone away","callstack":"DBA::selectFirst (796), GServer::detect (374), GServer::check (73), UpdateGServer::execute, Worker::execFunction (386), Worker::execute (121), Worker::processQueue (83)","params":"SELECT `network` FROM `gserver` WHERE (`nurl` = 'http://nova.community') LIMIT 1"} - {"file":"Database.php","line":704,"function":"p","request-id":"643503d689a10","uid":"e753fc","process_id":87895}`

**Comment by annando** [comment] 2023-04-11 07:49
How does the code look alike around the line 469 in tumblr.php? it should look that way: https://git.friendi.ca/friendica/friendica-addons/src/branch/2023.03-rc/tumblr/tumblr.php#L469

That second one is not a huge deal, this happens from time to time.

**Comment by hoergen** [comment] 2023-04-11 08:04
The tumblr addon was deactivated already .

```
456         }
457         return tumblr_client($consumer_key, $consumer_secret, $oauth_token, $oauth_token_secret);
458 }
459 
460 function tumblr_client(string $consumer_key, string $consumer_secret, string $oauth_token, string $oauth_token_secret): GuzzleHttp\Client
461 {
462         $stack = HandlerStack::create();
463 
464         $middleware = new Oauth1([
465                 'consumer_key'    => $consumer_key,
466                 'consumer_secret' => $consumer_secret,
467                 'token'           => $oauth_token,
468                 'token_secret'    => $oauth_token_secret
469         ]);
470         $stack->push($middleware);
471 
472         return new Client([
473                 'base_uri' => 'https://api.tumblr.com/v2/',
474                 'handler' => $stack
475         ]);
476 }
477 
478 function tumblr_get_page(int $uid, array $blogs = [])
479 {
480         $page = DI::pConfig()->get($uid, 'tumblr', 'page');
481 
482         if (!empty($page) && (strpos($page, '/') === false)) {
483                 return $page;
484         }
485 
486         if (empty($blogs)) {
487                 $blogs = tumblr_get_blogs($uid);
488         }

```

**Comment by hoergen** [comment] 2023-04-11 08:08
I did a hard reset on the addons again (like described above) 

Now the error is at 2023-04-11T08:01:15Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected '|', expecting '{'" at /FREINDICAPATH/addon/tumblr/tumblr.php line 445



```
444 
445 function tumblr_connection(int $uid): GuzzleHttp\Client|null
446 {       
447         $oauth_token        = DI::pConfig()->get($uid, 'tumblr', 'oauth_token');
448         $oauth_token_secret = DI::pConfig()->get($uid, 'tumblr', 'oauth_token_secret');
449 
450         $consumer_key    = DI::config()->get('tumblr', 'consumer_key');
451         $consumer_secret = DI::config()->get('tumblr', 'consumer_secret');
452 
453         if (!$consumer_key || !$consumer_secret || !$oauth_token || !$oauth_token_secret) {
454                 Logger::notice('Missing data, connection is not established', ['uid' => $uid]);
455                 return null;
456         }
457         return tumblr_client($consumer_key, $consumer_secret, $oauth_token, $oauth_token_secret);
458 }
459 

```

**Comment by hoergen** [comment] 2023-04-11 08:18
We are still using composer 1 right and supporting php7.4 Or did I miss the switch?

I found `https://github.com/Seldaek/monolog/issues/1597` that looks similar, but I don't know if this really related.

**Comment by annando** [comment] 2023-04-11 11:50
I guess that officially we still support 7.4, but I guess that the developers are on 8.x.

**Comment by hoergen** [comment] 2023-04-11 12:12
So, what you say is, that it is possible you already use php8 features that aren't supported by the official php7.4 ?

**Comment by MrPetovan** [comment] 2023-04-11 14:30
It looks like it from the recent Tumblr changes. It should be like this for PHP 7.4:
```php
445 function tumblr_connection(int $uid): ?GuzzleHttp\Client
```

**Comment by MrPetovan** [comment] 2023-04-11 14:32
@annando Do you have a way to adjust the target PHP version for your IDE code inspection tool?

**Comment by annando** [comment] 2023-04-11 14:51
Not sure if I can do this.

Update: it seems as if I can do this:
![image](https://user-images.githubusercontent.com/844208/231202266-24f45d8e-f552-4f39-8e5b-5d2274863654.png)

Update 2:
Yeah, it detects something:
![image](https://user-images.githubusercontent.com/844208/231202970-c7fdb486-8c72-4214-9187-89285236ba92.png)

**Comment by annando** [comment] 2023-04-11 18:03
PR is done: https://git.friendi.ca/friendica/friendica-addons/pulls/1370

**Comment by MrPetovan** [comment] 2023-04-11 19:13
PR is merged.

**Comment by tobiasd** [comment] 2023-04-12 05:32
@hoergen could you check if the problem is solved now for you?

**Comment by hoergen** [comment] 2023-04-12 07:28
I resettet again and pulled. I still have the WPoD, the tumblr error seems to be gone but the PHP error stayed

`12-Apr-2023 07:23:33 UTC] PHP Notice:  Object of class Friendica\App\BaseURL could not be converted to int in /FRIENDICAPATH/src/Model/Profile.php on line 337`

Status is the same, I can't use my node.

**Comment by annando** [comment] 2023-04-12 08:16
It's just a notice, not a bug that will lead to a WSOD. Have you updated all the composer dependencies?

**Comment by hoergen** [comment] 2023-04-12 08:22
I do the recommended commands from the documentation every time on the friendica repos and addons via a script, so I don't forget something.

Is there something special you want me to do?

**Comment by hoergen** [comment] 2023-04-12 08:52
I would kindly ask to reopen this issue again, because the problem is neither found nor solved!

**Comment by MrPetovan** [comment] 2023-04-12 09:06
Has the Parse Error message stopped appearing in your log at least?

**Comment by hoergen** [comment] 2023-04-12 11:26
As I wrote
https://github.com/friendica/friendica/issues/12979#issuecomment-1504797546

**Comment by annando** [comment] 2023-04-12 11:58
That line cannot be the cause since it is only called under certain circumstances. Question is if other pages work. So what about the community, what about displaying single threads, ...

Without any hints it's shooting in the dark :-(

**Comment by hoergen** [comment] 2023-04-12 12:29
I can give you everything you are asking. No problem.

And as I already wrote nothing changed here

> It seems it is the network,profile, community page that are completely blank.
> I can reach the /message , /calendar /contact page. And when im there i can reach all the other setting pages (User/Mod/Admin) that's it .
> 
> I can see the notifications there, but if I click on them I get the blank page again.

Additionally in Settings the /settings/connectors page is blank too


If you want me to do a reset again. No Problem. Just write exactly what I should do, so you can be sure we are on the same page.

**Comment by loma-one** [comment] 2023-04-12 12:34
I had reported the same problem here in the course. 
https://github.com/friendica/friendica/pull/12976#issuecomment-1501501471

With the pull it is fixed

**Comment by hoergen** [comment] 2023-04-12 13:15
> I had reported the same problem here in the course. [#12976 (comment)](https://github.com/friendica/friendica/pull/12976#issuecomment-1501501471)
> 
> With the pull it is fixed

Since you see, it didn't fix mine, let's call it "it has fixed YOUR problem".

How did you change the addon to *bak? I deactivated it in admin section but can't deactivated in my user settings because of the blank page.

**Comment by loma-one** [comment] 2023-04-12 14:19
Yes, of course. I just wanted to confirm that you are not the only one affected by the error.

I have changed the addon directly on the server in the addon directory. There was no other way to access the admin settings.

**Comment by hoergen** [comment] 2023-04-12 16:43
Did you mean, you renamed the directory ? Or removed it from the addons?

**Comment by hoergen** [comment] 2023-04-12 16:45
I removed the tumblr cirectory .. now im able to see all the pages again.
So there is still a problem with the tumblr addon.

**Comment by loma-one** [comment] 2023-04-15 07:22
Just give the folder a new extension *.bak
This is usually enough to deactivate it in the addon administration and make the server accessible again.
Of course, this is only a workaround and the last resort if nothing else works.

**Comment by MrPetovan** [comment] 2023-04-28 03:14
The tumblr addon has been heavily modified since you reported this issue, can you please pull the addons and re-enable it?

**Comment by hoergen** [comment] 2023-04-28 16:36
I just activated the addon, logged out and logged in again without problems the last 10 Minutes.  So this bug seems to be fixed. Thanks :+1:

**Closed as completed** 2023-04-28 16:36 UTC
Labels: Bug
