### ISSUE TITLE
Worker doesn't work

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5472] opened 2018-07-23 19:28 UTC
### Expected behavior
More than 0 or 1 worker should be started by cron.

### Actual behavior
On my big node only 1/24 workers is started. Therefore the workerqueue is growing.
On my small node 0/10 workers are started. I get a warning in admin panel about the issue.
The problem started today after pulling 3  hours ago.

### Steps to reproduce the problem
Watch htop and the log at debug level. In htop I nearly see no PHP processes at all.
Big node shows active workers 1 all the time. Small node shows 'couldn't select a workerqueue... quitting'.
When I run the worker.php by hand on big node I get 'sh: 1: /usr/bin/php bin/worker.php: not found'.

### Friendica version you encountered the problem
2018.08-dev

### Friendica source (git, zip)
git

### PHP version
PHP 7.0.30

### SQL version
10.0.34-MariaDB

**Comment by Quix0r** [comment] 2018-07-23 23:45
With latest `develop` code I get this:
````
$ sh: 1: php bin/worker.php --cron: not found
````
I have never seen that before. I'm confused if my fixes has caused this?

**Comment by MrPetovan** [comment] 2018-07-23 23:52
I’d assume @nupplaphil changes about the Process class are responsible for this, even if I don’t get why.

**Comment by MrPetovan** [comment] 2018-07-23 23:54
@copiis has the same issue. I suggested him to set config.php_path to the full php executable path but I’m starting to guess it won’t do it.

**Comment by MrPetovan** [comment] 2018-07-23 23:56
Duplicate of #5467

**Closed by MrPetovan** 2018-07-23 23:56 UTC

**Comment by AlfredSK** [comment] 2018-07-24 03:13
I have set the full path to php set in the config.

**Comment by MrPetovan** [comment] 2018-07-24 11:47
Did it fix the issue?

**Comment by AlfredSK** [comment] 2018-07-24 15:20
> I have set the full path to php set in the config.

Sorry for the bad English. I tried to say that I had set the full path before. Like in "never had it any other way". :-)
