### ISSUE TITLE
Set "Stay local" on server level

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#11633] opened 2022-06-12 05:52 UTC
### Describe the feature you'd like
Since some release there is the possibility under /settings/display function "stay local" to display the profile of another user in Friendica format. If this function is not activated, you are redirected to the original profile of the user, which is very confusing and many users find annoying.

There are correspondingly many queries from users, which considerably increases the administrative effort and reduces user satisfaction.

It would therefore be desirable to activate the "stay local" function for all users at the instance level. If the user wants a remote view, he should be able to activate it.

**Comment by MrPetovan** [comment] 2022-11-24 15:11
Duplicate of https://github.com/friendica/friendica/issues/9960

**Closed as not planned by MrPetovan** 2022-11-24 15:11 UTC
Labels: New Feature
