### ISSUE TITLE
Add JS uploader to editor to support drag and drop

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#11962] opened 2022-10-04 20:43 UTC
### Describe the feature you'd like

Friendica knows the addon "JS Uploader". This supports the upload of images via drag and drop in Friendica. Can this funktion be used to upload images directly to the post?

I imagine that the upload function is integrated directly into the editor. Every image that is imported this way should be saved in the Gallery. For this the current year is used.

After the upload, a link to the image should be automatically placed in the article.

There are probably still many pitfalls to consider. Still, I ask because that would be a noticeable improvement over the current status. Also, nothing new needs to be integrated, existing functions are used.

https://loma.ml/display/373ebf56-8663-3c64-61ed-22c672229576436358
https://libranet.de/display/0b6b25a8-1663-3c68-c1c9-392884093040

**Comment by xundeenergie** [comment] 2022-10-08 21:37
And add Copy&Paste please!!!

**Comment by MrPetovan** [comment] 2022-10-08 22:21
In what way?

**Comment by xundeenergie** [comment] 2022-10-09 00:10
for example, i make a screenshot to clipboard, and then i can insert with CTRL-V
Or i make "Copy" in filemanager on an image, and CTRL+V

**Comment by MrPetovan** [comment] 2022-10-09 01:50
Ok, I'm unfamiliar with this interaction, but I bet I can find some resources online.

**Comment by MrPetovan** [comment] 2022-10-09 01:51
Duplicate of #11825

**Closed as completed by MrPetovan** 2022-10-09 01:51 UTC
Labels: New Feature

**Comment by AlfredSK** [comment] 2022-10-09 07:05
> Ok, I'm unfamiliar with this interaction, but ...

This is how the editor here on GitHub works. 😉

**Comment by MrPetovan** [comment] 2022-10-09 07:18
I'm aware of that, but I'm not sure GitHub provides an easily readable version of their website source code, which means even if GitHub is doing it, I'll probably have to look elsewhere to implement the same feature in Friendica.

**Comment by loma-one** [comment] 2022-10-09 09:07
This is not a duplicate of https://github.com/friendica/friendica/issues/11825

The suggestion of mine describes a drag & drop method, using the addon "JS Uploader", which is already integrated in Friendica. My description would completely avoid the cumbersome selection of an image or video via the Gallery, as is the standard in Hubzilla and other similar applications.

Of course, it would be fine if they try to solve it with the duplicate. However, in that case, the description should be supplemented.

**Comment by MrPetovan** [comment] 2022-10-09 09:12
In https://github.com/friendica/friendica/issues/11825 I intend to add the behavior you are describing here.
