### ISSUE TITLE
Allow banner as background in Friendica view of other profiles.

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#13815] opened 2024-01-08 18:13 UTC
This is very small and unimportant feature that might be fun.  Many places like Mastodon have an avatar picture and a background picture.  It might be fun to have that banner but used as wallpaper when viewing their profile on Friendica.

**Comment by MrPetovan** [comment] 2024-01-08 18:41
Duplicate of #10847

**Closed as not planned by MrPetovan** 2024-01-08 18:42 UTC
Labels: New Feature
