### ISSUE TITLE
More smarty escaping issues on register page

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6294] opened 2018-12-21 20:46 UTC
### Steps to reproduce the problem
Page .../register - radio buttons and publish profile options looks broken.
And if "Display Privacy Statement" is enabled the URLs for 'uexport' and 'removeme' are also broken.

![grafik](https://user-images.githubusercontent.com/3656054/50362884-c832fb00-0569-11e9-9c88-b778cdd2401d.png)

### Friendica version you encountered the problem
2018.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by MrPetovan** [comment] 2018-12-21 20:54
What addons do you have enabled?

**Comment by AlfredSK** [comment] 2018-12-21 20:59
Happens on all nodes I have ;-)

**On mordor.social:**
fromapp
impressum
notifyall
nsfw
startpage
superblock
newmemberwidget
xmpp
catavatar
geocoordinates
openstreetmap
rendertime
twitter
unicode_smilies
wppost
blockem
blogger
buffer
fromgplus
ifttt
pumpio
showmore
tumblr
langfilter
js_upload

**And on my test-the-rc-instance I have these:**
catavatar
fromapp
geocoordinates
impressum
js_upload
nsfw
openstreetmap
rendertime
showmore
startpage
blockem
unicode_smilies

**Comment by MrPetovan** [comment] 2018-12-21 20:59
Maybe the `impressum` addon.

**Comment by AlfredSK** [comment] 2018-12-21 21:01
Hmm. The terms of service URL are ok when I simply go to the 'tos' page but not on the register page.
I'll check when 'impressum' is disabled....

**Comment by AlfredSK** [comment] 2018-12-21 21:02
Nope. It's the same w/o impressum.

**Comment by MrPetovan** [comment] 2018-12-21 21:06
Thanks for your report.

**Comment by MrPetovan** [comment] 2018-12-21 21:06
Related to #6208 
Caused by #6262

**Comment by AlfredSK** [comment] 2018-12-21 21:07
Ok. It's not an addon. I disabled ALL of them. The issue still exists.

**Comment by annando** [comment] 2018-12-21 21:12
Fixed with https://github.com/friendica/friendica/pull/6295

**Comment by AlfredSK** [comment] 2018-12-21 21:14
Whoa! :-)

Question: Shall I open a new issue when I find some more of this? Or is it ok to add them here?

**Comment by MrPetovan** [comment] 2018-12-21 21:14
Please open a new issue with all the new instances you found.

**Closed by MrPetovan** 2018-12-21 21:14 UTC
Labels: Bug, UX
