### ISSUE TITLE
Posting deletes user from their contact's list of contacts

### ISSUE THREAD

**Issue by deantownsley** [friendica/friendica#3571] opened 2017-07-08 15:47 UTC
After updating to 3.5.2, I had a situation on a private server where a user posting caused themselves to be deleted from the contacts list of the people receiving the post.  Based on sifting through things, this appears to only happen if the user has their profile marked private or if the server of the posting user has the "make otherwise public pages private" enabled.  (I'm not 100% sure if it is both or either.)

I'm not a friendica developer, so forgive me if I have misunderstood anything.  As best I can tell, the problem appears to be a combination of 3 separate issues, but the simplest is that in include/Contact.php, there is a DELETE query which, in attempting to delete extra uid=0 contact records, will delete all contact records with the same url.  In the normal case that doesn't happen due to the forgoing conditions, but due to other issues, this gets triggered.  I will add a pull request with this simplest fix shortly.  This is the change I applied to "fix" the problem.

The full sequence, as best I can tell and which is rather complex is this:

1. The incoming post triggers a get_contact() using the posting user's url and uid=0.
2. This is found in the contact table, but the avatar is out of date, triggering a fall-through to the contact updating code.
3. The Probe::uri() of the contact does not find the user@server form address because (First Bug) the noscrape JSON record returned for the sender is completely empty because it is a private profile (the hcard for private profiles still returns basic info like the addr)  and (Second Bug) the scraping of the hcard does not retrieve the user@server address (I'm not sure why that isn't implemented, the info is there).
4. As a result, the uid=0 contact table record for the sending user is updated with an EMPTY user@server form address.
5. Another get_contact() is performed using the user@server form address and uid=0.  Which now does not find the corresponding record because the addr has been blanked for it.
6. This causes the contact of the sender to be re-populated from the gcontact table.  (This actually creates a new entry, which is promptly deleted in the next step, which I don't completely understand.)
7. (Third and main bug) All entries (for all users) in the contact table with the corresponding url are deleted except for the original uid=0 one, which has now been found using the mapping from addr to url obtained from the gcontact information.

I can't think of a reason why the delete should apply to all users and not just uid=0.  Even the execution of the delete is protected by a "if uid=0".  Presumably this was just a simple mistake.

In the process I found another unexpected behaviour: the update code is nominally triggered if the avatar-date is older than 7 days.  But the avatar-date is not changed in the update, so it essentially always executes (although the url probe result is separately cached for 24 hours).  I'm not sure if that is the intended behavior or not.

Several of these issues are not new to 3.5.2, but it appears that some changes in 3.5.2 cause them to manifest problems.  Notably in both get_contact() and Probe::uri() the mapping between url and addr was being done manually but is now left to be implicit, which "should" work, but doesn't for private profiles due to the above-mentioned issues.

**Comment by annando** [comment] 2017-07-08 18:08
Thanks for this very detailed examination!

**Comment by annando** [comment] 2017-07-09 05:12
Since there seems to be a bug in the probing, it would be great if you could provide a profile that you know will fail. Then I will verify and correct the probing.

Concerning the avatar-date: This is done in the function "update_contact_avatar" that is called later in that function.

**Comment by annando** [comment] 2017-07-09 20:01
I tried with a test account: ```test1@squeet.me``` 

I cannot reproduce the probing problem.

**Comment by deantownsley** [comment] 2017-07-09 22:13
Thanks for looking into things and merging my pull!

If I go to https://squeet.me/noscrape/test1 I get a JSON file with just "hide: true".  On the other hand if I grab https://squeet.me/hcard/test1 it has the expected "directory" info (addr, public avatar, name, etc)

In my testing just now, it seems that if "publish in global directory" is yes  and "hide profile from unknown viewers" is no, then the /noscrape/ JSON data is there (example: https://friendica.deliquescence.net/noscrape/tusertwo) however, if either the global dir is set no or the hide is yes, then the /nocrape/ url gives no data.  (your example or https://friendica.deliquescence.net/noscrape/tuser1).  In all cases the expected basic directory info is returned for the hcard (e.g. https://friendica.deliquescence.net/hcard/tusertwo).  The relevant fields in the hcard do appear to be set correctly in all cases ("searchable" and "dfrn-global-visibility").

Is this the expected behavior?  It doesn't seem like it from the assumptions that the code in Probe seems to be making, but maybe I am misunderstanding.

I guess I should note that I'm using 3.5.2 with my patch applied, not the actual devel version.  I don't think I checked to see if the probe code had changed in devel.

Thanks again for your help!

**Comment by deantownsley** [comment] 2017-07-09 22:15
And just to say, the "tuser1" account mentioned above is the one I used to test the "delete on post" problem originally reported.

**Comment by deantownsley** [comment] 2017-07-09 22:37
My concern on the avatar was that in update_contact_avatar() (in include/Photo.php), if the "avatar" field is the same, nothing is done.  That means the avatar-date is not updated.  Under this condition I was expecting that it would update the avatar-date to reflect that the avatar had been checked.  But I may be misunderstanding the intended functionality.

My perception of the intended functionality is that "avatar-date" is the last time the avatar was checked (and possibly updated) and that it should be checked for possible updates if it has not been checked for 7 days.

In my situation,  I think the only reason this was an issue is that it caused it to try to update the contact every time because the avatar-date is not updated by update_contact_avatar().

**Comment by annando** [comment] 2017-07-10 09:31
Hmm, I really have to have a deeper look at these routines. Although you say that you aren't a Friendica developer you surely are some developer. Otherwise you wouldn't find such hidden bugs in our crappy and creepy code. :)

**Comment by annando** [comment] 2017-07-10 22:24
Okay, I can reproduce - as well with my test user, since I made a mistake with the probing. Many thanks for the hints. I will dig into it the next days, hours or minutes.

**Comment by annando** [comment] 2017-07-10 22:39
It is fixed with pull request https://github.com/friendica/friendica/pull/3577

**Comment by deantownsley** [comment] 2017-07-11 00:59
From my checks, your addition to Probe.php in  #3577  makes it get the user@host addr properly when a contact is fetched by url.  That fixes bugs 1 and 2 in my initial post, since it gets the addr regardless of whether the noscrape or hcard is retrieved.  I leave it up to you what the proper overall behavior of noscrape and hcard is with respect to the other info.

Thanks again for your help.  I really appreciate all of your work on friendica.  You guys are the defenders of the free world as far as I'm concerned.  I'm just trying to do my bit. :)

**Comment by annando** [comment] 2017-07-11 06:00
Concerning the "avatar-date" you are totally right. This is some functionality that changed over time but hasn't thought over completely.

**Comment by annando** [comment] 2017-07-13 07:34
Since I'm having a short perception, I hope that I now covered everything? What did you mean with this noscrape and hcard stuff? Which change would you suggest?

**Comment by annando** [comment] 2017-07-31 19:03
@deantownsley do you think we solved all issues?

**Comment by annando** [comment] 2017-08-20 20:54
Since @deantownsley hadn't answered, I guess we now solved all issues, I'm closing this issue.

**Closed by annando** 2017-08-20 20:54 UTC
Labels: Bug
