### ISSUE TITLE
Link previews of incomming Twitter quote-shares mistaken as posts

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#10481] opened 2021-07-10 04:01 UTC
- [X] I have searched open and closed issues for duplicates

### Bug Description
 
Incoming Twitter quote-shares containing certain URLs seem to cause issues for Friendia. 

The URLs which Twitter converts in link preview boxes appear to mistaken as posts by Friendia, with the message content of  the preview apparently being interpreted as usernames/ contact.

### Example 

- This tweet: https://mobile.twitter.com/SZarifi/status/1412387612568997890 quote-shares another tweet with a shortened URL
- The quote-shared tweet https://mobile.twitter.com/rachelreid6/status/1412370086099365890 previews the link.
- The preview box appeared to cause the following DB error:

```
2021-07-06T12:40:31Z worker [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'name' at row 1","callstack":"Media::insert, twitter_store_attachments, twitter_createpost, twitter_createpost, twitter_createpost, twitter_fetchhometimeline, twitter_sync_run, Worker::execFunction","params":"INSERT INTO `post-media` (`uri-id`, `type`, `url`, `name`, `mimetype`, `preview`, `preview-height`, `preview-width`, `description`, `author-url`, `author-name`, `author-image`, `publisher-url`, `publisher-name`, `publisher-image`) VALUES (4090692, 17, 'https:\/\/tinyurl.com\/p9f5vuce', 'Welcome! You are invited to join a webinar: Side-event on the Human Rights Situation in Afghanistan & Victims of Terrorism: Accountability to Safeguard the Rights of Victims of Terrorism and Human Rights Defenders. After registering, you will receive a confirmation email about joining the webinar.', 'text\/html; charset=UTF-8', 'https:\/\/umn.zoom.us\/w_p\/97052352091\/fd632736-9997-4ac6-b1c9-03d2d11f2fa6.jpg', 161, 896, 'This event will be co-sponsored by the Permanent Mission of the Islamic Republic of Afghanistan to the United Nations in Geneva, the Permanent Mission of of Norway to the United Nations in Geneva, Afghanistan\u2019s Independent Human Rights Commission, an\u2026', NULL, NULL, NULL, NULL, 'Zoom Video Communications', NULL) ON DUPLICATE KEY UPDATE `uri-id` = 4090692, `type` = 17, `url` = 'https:\/\/tinyurl.com\/p9f5vuce', `name` = 'Welcome! You are invited to join a webinar: Side-event on the Human Rights Situation in Afghanistan & Victims of Terrorism: Accountability to Safeguard the Rights of Victims of Terrorism and Human Rights Defenders. After registering, you will receive a confirmation email about joining the webinar.', `mimetype` = 'text\/html; charset=UTF-8', `preview` = 'https:\/\/umn.zoom.us\/w_p\/97052352091\/fd632736-9997-4ac6-b1c9-03d2d11f2fa6.jpg', `preview-height` = 161, `preview-width` = 896, `description` = 'This event will be co-sponsored by the Permanent Mission of the Islamic Republic of Afghanistan to the United Nations in Geneva, the Permanent Mission of of Norway to the United Nations in Geneva, Afghanistan\u2019s Independent Human Rights Commission, an\u2026', `author-url` = NULL, `author-name` = NULL, `author-image` = NULL, `publisher-url` = NULL, `publisher-name` = 'Zoom Video Communications', `publisher-image` = NULL"} - {"file":"Database.php","line":765,"function":"e","uid":"2b4935","process_id":2756}
```

More information here: https://friendica.hubup.pro/display/174591b4-1260-e474-18f1-bda142090998
### Platform Info

Friendica Version: 2021.07 

Friendica Source: 

PHP version: 7.3

SQL version: 15.1 Distrib 10.3.29-MariaDB

**Comment by foss-** [comment] 2021-07-10 11:00
Dupe of https://github.com/friendica/friendica/issues/10453

**Comment by AlfredSK** [comment] 2021-07-10 11:10
~~No. That's not a duplicate.~~ it could be related, but I don't think it's a duplicate.

**Comment by AndyHee** [comment] 2023-01-23 15:35
The problem seems to have disappeared.

**Closed as completed** 2023-01-23 15:35 UTC
Labels: Bug
