### ISSUE TITLE
WordPress pterotype activitypub feed not federating to friendica

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#6161] opened 2018-11-18 07:57 UTC
I'm currently trying out the [pterotype plugin for WordPress](https://github.com/pterotype-project/pterotype) that adds activitypub support.

I subscribed to the blog feed URL with my friendica account:

https://blog.cwiwie.org/wp-json/pterotype/v1/actor/-blog

However, blog posts are not being federated. Is this currently not supported?

As far as I can see, the author is testing the plugin with Mastodon.

**Comment by annando** [comment] 2018-11-18 12:49
I need to have test cases to check where the problem is.

**Comment by wiwie** [comment] 2018-11-18 12:53
How can/should I provide these test cases?

**Comment by wiwie** [comment] 2018-11-18 14:40
P.S.: I posted the link to my blog, you could use that as a test case?

**Comment by annando** [comment] 2018-11-18 20:19
I will see.

**Comment by wiwie** [comment] 2018-12-11 20:44
any news? more test data needed?

**Comment by annando** [comment] 2018-12-11 21:59
I still have to have a look, I totally forgot about this.

**Comment by poVoq** [comment] 2019-03-12 16:45
https://wedistribute.org/
Seems to implement it and you can subscribe to `blog@wedistribute.org` via Mastodon.
But in Friendica is gives a bunch of warnings and then shows the profile, but never actually adds it.

**Comment by annando** [comment] 2019-03-12 17:36
Thanks for the reminder.

**Comment by annando** [comment] 2019-03-15 04:37
I had been able to follow that account without any problems.

**Comment by poVoq** [comment] 2019-03-15 05:03
Odd, adding it again now seems to have resulted in no errors. Maybe there was an issue on the other side?

**Comment by tobiasd** [comment] 2019-03-15 05:50
I remember them talking about planed work (it was somewhere in the stream of Deadsuperhero I just don't find) on this issue from their end, so maybe there was an update in pterotype in the meantime.

**Comment by annando** [comment] 2019-03-15 06:15
Can we close this issue then?

**Comment by poVoq** [comment] 2019-03-15 07:21
I haven't actually received any posts though it yet. Only the connection itself seems to work.
Just a matter of waiting for their next blog post I hope though.

**Comment by MrPetovan** [comment] 2019-03-15 13:17
Closing in the meantime, please reopen it if it fails again.

**Closed by MrPetovan** 2019-03-15 13:17 UTC
Labels: Bug, Federation

**Comment by annando** [comment] 2019-03-17 21:26
I just received a first post from https://wedistribute.org/, it works fine.
