### ISSUE TITLE
click certain diaspora contact name --> white screen of death

### ISSUE THREAD

**Issue by haheute** [friendica/friendica#13378] opened 2023-08-24 19:15 UTC
### Bug Description

When I try to open the conversations page of a certain diaspora contact, I get a WSOD. 
Other contact links seem to work fine.

Actual Result:

`ERROR: app`

    Uncaught Exception TypeError: "Friendica\Util\Network::isLocalLink(): Argument #1 ($url) must be of type string, null given, called in /var/www/localhost/friendica/src/Object/Post.php on line 287" at /var/www/localhost/friendica/src/Util/Network.php line 645
        
more info:

    TypeError: Friendica\Util\Network::isLocalLink(): Argument #1 ($url) must be of type string, null given, called in /var/www/localhost/friendica/src/Object/Post.php on line 287 and defined in /var/www/localhost/friendica/src/Util/Network.php:645
    Stack trace:
    #0 /var/www/localhost/friendica/src/Object/Post.php(287): Friendica\Util\Network::isLocalLink()
    #1 /var/www/localhost/friendica/src/Object/Thread.php(208): Friendica\Object\Post->getTemplateData()
    #2 /var/www/localhost/friendica/src/Content/Conversation.php(670): Friendica\Object\Thread->getTemplateData()
    #3 /var/www/localhost/friendica/src/Content/Conversation.php(568): Friendica\Content\Conversation->getThreadList()
    #4 /var/www/localhost/friendica/src/Model/Contact.php(1634): Friendica\Content\Conversation->render()
    #5 /var/www/localhost/friendica/src/Module/Contact/Conversations.php(116): Friendica\Model\Contact::getPostsFromId()
    #6 /var/www/localhost/friendica/src/BaseModule.php(244): Friendica\Module\Contact\Conversations->content()
    #7 /var/www/localhost/friendica/src/App.php(707): Friendica\BaseModule->run()
    #8 /var/www/localhost/friendica/index.php(55): Friendica\App->runFrontend()
    #9 {main}

### Platform Info

Friendica Version:

Diese Friendica-Instanz verwendet die Version 2023.09-dev, sie ist unter der folgenden Adresse im Web zu finden https://boerdica.de. Die Datenbankversion ist 1528/1528 und die Post-Update-Version 1507/1507.

PHP 8.1.22 (cli) (built: Aug  3 2023 19:18:42) (NTS)

mysql  Ver 15.1 Distrib 10.11.4-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by MrPetovan** [comment] 2023-08-24 23:19
Duplicate of #13367, will be fixed by #13368

**Closed as completed by MrPetovan** 2023-08-24 23:19 UTC
Labels: Bug
